// Canonical IRS Form 1040 Schedule C line mapping for default expense categories.
// Generated from a verified 3-expert tax panel + reconciliation (see
// docs/plans). Keyed by exact category name. line = Schedule C line code
// shown in the UI; label = human description; deductible = business-deductible.
export interface ScheduleCEntry { line: string; label: string; deductible: boolean }
export const SCHEDULE_C_BY_CATEGORY: Record<string, ScheduleCEntry> = {
  'Office Supplies': { line: 'Line 22', label: 'Supplies', deductible: true },
  'Postage & Shipping': { line: 'Line 18', label: 'Office expense', deductible: true },
  'Printing & Copying': { line: 'Line 18', label: 'Office expense', deductible: true },
  'Software Subscriptions': { line: 'Line 18', label: 'Office expense', deductible: true },
  'Computer Equipment': { line: 'Line 13', label: 'Depreciation/§179', deductible: true },
  'Office Furniture': { line: 'Line 13', label: 'Depreciation/§179', deductible: true },
  'Phone & Internet': { line: 'Line 25', label: 'Utilities', deductible: true },
  'Web Hosting': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Cloud Services': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'IT Support': { line: 'Line 17', label: 'Legal and professional services', deductible: true },
  'Airfare': { line: 'Line 24a', label: 'Travel', deductible: true },
  'Hotel & Lodging': { line: 'Line 24a', label: 'Travel', deductible: true },
  'Car Rental': { line: 'Line 24a', label: 'Travel', deductible: true },
  'Mileage & Fuel': { line: 'Line 9', label: 'Car and truck', deductible: true },
  'Parking & Tolls': { line: 'Line 9', label: 'Car and truck', deductible: true },
  'Meals & Entertainment (Travel)': { line: 'Line 24b', label: 'Deductible meals', deductible: true },
  'Public Transit': { line: 'Line 24a', label: 'Travel', deductible: true },
  'Rideshare & Taxi': { line: 'Line 24a', label: 'Travel', deductible: true },
  'Advertising': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Social Media Ads': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Print Materials': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Trade Shows & Events': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Sponsorships': { line: 'Line 8', label: 'Advertising', deductible: true },
  'PR & Communications': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Market Research': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Photography & Video': { line: 'Line 8', label: 'Advertising', deductible: true },
  'Accounting & Bookkeeping': { line: 'Line 17', label: 'Legal and professional services', deductible: true },
  'Legal Fees': { line: 'Line 17', label: 'Legal and professional services', deductible: true },
  'Consulting': { line: 'Line 17', label: 'Legal and professional services', deductible: true },
  'Recruiting & HR': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Training & Education': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Certification & Licensing': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'Rent & Lease': { line: 'Line 20b', label: 'Rent/lease (other property)', deductible: true },
  'Utilities (Electric)': { line: 'Line 25', label: 'Utilities', deductible: true },
  'Utilities (Gas)': { line: 'Line 25', label: 'Utilities', deductible: true },
  'Utilities (Water)': { line: 'Line 25', label: 'Utilities', deductible: true },
  'Janitorial & Cleaning': { line: 'Line 21', label: 'Repairs and maintenance', deductible: true },
  'Repairs & Maintenance': { line: 'Line 21', label: 'Repairs and maintenance', deductible: true },
  'Security': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Property Insurance': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Salaries & Wages': { line: 'Line 26', label: 'Wages', deductible: true },
  'Contract Labor': { line: 'Line 11', label: 'Contract labor', deductible: true },
  'Employee Benefits': { line: 'Line 14', label: 'Employee benefit programs', deductible: true },
  'Health Insurance': { line: 'Schedule 1 Line 17', label: 'Self-employed health insurance', deductible: true },
  'Retirement Contributions': { line: 'Line 19', label: 'Pension/profit-sharing', deductible: true },
  'Payroll Taxes': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'Workers Compensation': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Bank Fees': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Credit Card Fees': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Loan Interest': { line: 'Line 16b', label: 'Interest (other)', deductible: true },
  'Late Fees': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Wire Transfer Fees': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Currency Exchange': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Inventory Purchases': { line: 'Part III (COGS)', label: 'Purchases (COGS)', deductible: true },
  'Raw Materials': { line: 'Part III (COGS)', label: 'Materials and supplies (COGS)', deductible: true },
  'Packaging Materials': { line: 'Part III (COGS)', label: 'Materials and supplies (COGS)', deductible: true },
  'Freight & Delivery': { line: 'Part III (COGS)', label: 'Cost of labor/freight-in (COGS)', deductible: true },
  'Customs & Duties': { line: 'Part III (COGS)', label: 'Materials and supplies (COGS)', deductible: true },
  'General Liability': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Professional Liability (E&O)': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Commercial Auto': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Directors & Officers': { line: 'Line 15', label: 'Insurance (other than health)', deductible: true },
  'Business Licenses': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'State Taxes': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'Local Taxes': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'Sales Tax Paid': { line: 'Line 23', label: 'Taxes and licenses', deductible: true },
  'Import Duties': { line: 'Part III (COGS)', label: 'Materials and supplies (COGS)', deductible: true },
  'Meals & Entertainment': { line: 'Line 24b', label: 'Deductible meals', deductible: true },
  'Subscriptions & Dues': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Charitable Donations': { line: 'Not deductible on Sch C', label: 'Charitable donations (Schedule A)', deductible: false },
  'Depreciation Expense': { line: 'Line 13', label: 'Depreciation/§179', deductible: true },
  'Amortization': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Bad Debt Expense': { line: 'Line 27a', label: 'Other expenses', deductible: true },
  'Miscellaneous Expense': { line: 'Line 27a', label: 'Other expenses', deductible: true },
};
