import { Router } from 'express';
import path from 'path';
import { db } from '../db';

export const portalRouter = Router();

portalRouter.get('/:token/data', (req, res) => {
  const row = db.prepare(
    `SELECT invoice_id, company_id, expires_at FROM invoice_tokens WHERE token = ?`
  ).get(req.params.token) as any;

  if (!row) return res.status(404).json({ error: 'Invoice not found' });
  if (row.expires_at < Math.floor(Date.now() / 1000)) {
    return res.status(410).json({ error: 'Link expired' });
  }

  const invoice = db.prepare(`SELECT * FROM invoices WHERE id = ?`).get(row.invoice_id) as any;
  if (!invoice) return res.status(404).json({ error: 'Invoice not found in replica' });

  const lineItems = db.prepare(
    `SELECT * FROM invoice_line_items WHERE invoice_id = ?`
  ).all(row.invoice_id);

  const company = db.prepare(`SELECT * FROM companies WHERE id = ?`).get(row.company_id);

  res.json({ invoice, lineItems, company });
});

portalRouter.get('/:token/receipt', (req, res) => {
  const row = db.prepare(
    `SELECT invoice_id, company_id, expires_at FROM invoice_tokens WHERE token = ?`
  ).get(req.params.token) as any;

  if (!row) return res.status(404).json({ error: 'Invoice not found' });

  const invoice = db.prepare(`SELECT * FROM invoices WHERE id = ?`).get(row.invoice_id) as any;
  if (!invoice) return res.status(404).json({ error: 'Invoice not found' });

  const company = db.prepare(`SELECT * FROM companies WHERE id = ?`).get(row.company_id) as any;
  const payments = db.prepare(
    `SELECT * FROM payments WHERE invoice_id = ? ORDER BY date DESC`
  ).all(row.invoice_id);

  const fmt = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n || 0);
  const companyName = company?.name || 'Company';
  const companyAddr = [company?.address_line1, company?.city, company?.state, company?.zip].filter(Boolean).join(', ');

  const paymentRows = (payments as any[]).map((p: any) =>
    `<tr><td style="padding:8px 12px;border:1px solid #ddd;">${p.date || ''}</td>
     <td style="padding:8px 12px;border:1px solid #ddd;text-align:right;font-family:monospace;">${fmt(p.amount)}</td>
     <td style="padding:8px 12px;border:1px solid #ddd;">${p.payment_method || ''}</td>
     <td style="padding:8px 12px;border:1px solid #ddd;font-family:monospace;">${p.reference || '—'}</td></tr>`
  ).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: system-ui, sans-serif; max-width: 600px; margin: 40px auto; padding: 0 20px; color: #111; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .meta { font-size: 13px; color: #555; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #f0f0f0; padding: 8px 12px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; border: 1px solid #ddd; }
    .total { margin-top: 20px; text-align: right; font-size: 16px; font-weight: 700; }
    .badge { display: inline-block; padding: 3px 10px; font-size: 11px; font-weight: 700; text-transform: uppercase; border-radius: 3px; }
    .paid { background: #dcfce7; color: #166534; }
    .partial { background: #f3e8ff; color: #6b21a8; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #777; text-align: center; }
  </style></head><body>
    <h1>Payment Receipt</h1>
    <div class="meta">
      ${companyName}<br>${companyAddr || ''}<br>
      Invoice #${invoice.invoice_number} &middot;
      <span class="badge ${invoice.status === 'paid' ? 'paid' : 'partial'}">${invoice.status === 'paid' ? 'Paid in Full' : 'Partial Payment'}</span>
    </div>
    <table>
      <thead><tr><th>Date</th><th style="text-align:right">Amount</th><th>Method</th><th>Reference</th></tr></thead>
      <tbody>${paymentRows || '<tr><td colspan="4" style="padding:12px;text-align:center;color:#999;">No payments recorded</td></tr>'}</tbody>
    </table>
    <div class="total">Total Paid: ${fmt(invoice.amount_paid)} of ${fmt(invoice.total)}</div>
    ${invoice.status === 'paid' ? '<p style="color:#166534;font-weight:600;margin-top:12px;text-align:right;">This invoice has been paid in full. Thank you.</p>' : `<p style="color:#6b21a8;margin-top:12px;text-align:right;">Remaining balance: ${fmt(invoice.total - invoice.amount_paid)}</p>`}
    <div class="footer">Receipt generated by ${companyName} &middot; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </body></html>`;

  res.setHeader('Content-Type', 'text/html');
  res.send(html);
});

portalRouter.get('/:token', (_req, res) => {
  res.sendFile('index.html', {
    root: path.join(__dirname, '..', '..', 'portal', 'dist')
  });
});
