import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (group: Display) =====
  { id: 'accounts-default-view-mode', section: 'accounts', group: 'Display', label: 'Default account view', description: 'How the chart of accounts opens by default.', type: 'select', default: 'tree', options: [{ value: 'tree', label: 'Tree (hierarchical)' }, { value: 'flat', label: 'Flat list' }, { value: 'grouped', label: 'Grouped by type' }] },
  { id: 'accounts-show-inactive', section: 'accounts', group: 'Display', label: 'Show inactive accounts', description: 'Include deactivated accounts in the list.', type: 'toggle', default: false },
  { id: 'accounts-show-zero-balance', section: 'accounts', group: 'Display', label: 'Show zero-balance accounts', description: 'Display accounts that currently have no balance.', type: 'toggle', default: true },
  { id: 'accounts-rows-per-page', section: 'accounts', group: 'Display', label: 'Accounts per page', description: 'Number of accounts shown before pagination.', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'accounts-compact-rows', section: 'accounts', group: 'Display', label: 'Compact row height', description: 'Use tighter spacing between account rows.', type: 'toggle', default: false },
  { id: 'accounts-show-account-icons', section: 'accounts', group: 'Display', label: 'Account type icons', description: 'Show an icon indicating each account type.', type: 'toggle', default: true },
  { id: 'accounts-expand-tree-depth', section: 'accounts', group: 'Display', label: 'Default tree expansion depth', description: 'How many sub-account levels expand on load.', type: 'number', default: 2, min: 0, max: 8, step: 1 },
  { id: 'accounts-show-balance-inline', section: 'accounts', group: 'Display', label: 'Inline running balance', description: 'Show running balance beside each ledger line.', type: 'toggle', default: true },
  { id: 'accounts-sticky-header', section: 'accounts', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible while scrolling.', type: 'toggle', default: true },
  { id: 'accounts-show-account-path', section: 'accounts', group: 'Display', label: 'Show full account path', description: 'Display parent path (e.g. Assets:Bank:Checking).', type: 'toggle', default: false },
  { id: 'accounts-ledger-density', section: 'accounts', group: 'Display', label: 'Ledger density', description: 'Information density of the general ledger.', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'accounts-show-subtotal-rows', section: 'accounts', group: 'Display', label: 'Show subtotal rows', description: 'Insert subtotal rows per account group.', type: 'toggle', default: true },
  { id: 'accounts-highlight-current-row', section: 'accounts', group: 'Display', label: 'Highlight hovered row', description: 'Highlight the ledger row under the cursor.', type: 'toggle', default: true },
  { id: 'accounts-show-empty-state-tips', section: 'accounts', group: 'Display', label: 'Empty-state tips', description: 'Show helpful tips when no accounts exist.', type: 'toggle', default: true },
  { id: 'accounts-default-fiscal-year-display', section: 'accounts', group: 'Display', label: 'Fiscal year label format', description: 'How fiscal years appear in headers.', type: 'select', default: 'fy-end', options: [{ value: 'fy-start', label: 'FY start year' }, { value: 'fy-end', label: 'FY end year' }, { value: 'range', label: 'Start–End range' }] },
  { id: 'accounts-show-archived-banner', section: 'accounts', group: 'Display', label: 'Archived period banner', description: 'Show a banner when viewing a closed period.', type: 'toggle', default: true },

  // ===== Columns (group: Columns) =====
  { id: 'accounts-col-number', section: 'accounts', group: 'Columns', label: 'Show account number', description: 'Display the account number column.', type: 'toggle', default: true },
  { id: 'accounts-col-name', section: 'accounts', group: 'Columns', label: 'Show account name', description: 'Display the account name column.', type: 'toggle', default: true },
  { id: 'accounts-col-type', section: 'accounts', group: 'Columns', label: 'Show account type', description: 'Display the account type column.', type: 'toggle', default: true },
  { id: 'accounts-col-subtype', section: 'accounts', group: 'Columns', label: 'Show account subtype', description: 'Display the account subtype/detail column.', type: 'toggle', default: false },
  { id: 'accounts-col-balance', section: 'accounts', group: 'Columns', label: 'Show balance', description: 'Display the current balance column.', type: 'toggle', default: true },
  { id: 'accounts-col-debit', section: 'accounts', group: 'Columns', label: 'Show debit column', description: 'Display the debit amount column in the ledger.', type: 'toggle', default: true },
  { id: 'accounts-col-credit', section: 'accounts', group: 'Columns', label: 'Show credit column', description: 'Display the credit amount column in the ledger.', type: 'toggle', default: true },
  { id: 'accounts-col-description', section: 'accounts', group: 'Columns', label: 'Show description', description: 'Display the line description column.', type: 'toggle', default: true },
  { id: 'accounts-col-memo', section: 'accounts', group: 'Columns', label: 'Show memo', description: 'Display the memo/notes column.', type: 'toggle', default: false },
  { id: 'accounts-col-reference', section: 'accounts', group: 'Columns', label: 'Show reference number', description: 'Display the reference/document number column.', type: 'toggle', default: true },
  { id: 'accounts-col-date', section: 'accounts', group: 'Columns', label: 'Show date column', description: 'Display the transaction date column.', type: 'toggle', default: true },
  { id: 'accounts-col-posting-date', section: 'accounts', group: 'Columns', label: 'Show posting date', description: 'Display the posting date separately from transaction date.', type: 'toggle', default: false },
  { id: 'accounts-col-reconciled', section: 'accounts', group: 'Columns', label: 'Show reconciled flag', description: 'Display whether a line is reconciled.', type: 'toggle', default: true },
  { id: 'accounts-col-source', section: 'accounts', group: 'Columns', label: 'Show source module', description: 'Display which module created the entry.', type: 'toggle', default: false },
  { id: 'accounts-col-currency', section: 'accounts', group: 'Columns', label: 'Show currency code', description: 'Display the currency for multi-currency accounts.', type: 'toggle', default: false },
  { id: 'accounts-col-fx-rate', section: 'accounts', group: 'Columns', label: 'Show FX rate', description: 'Display the exchange rate used on each line.', type: 'toggle', default: false },
  { id: 'accounts-col-running-balance', section: 'accounts', group: 'Columns', label: 'Show running balance column', description: 'Display the cumulative running balance column.', type: 'toggle', default: true },
  { id: 'accounts-col-created-by', section: 'accounts', group: 'Columns', label: 'Show created-by user', description: 'Display the user who entered the line.', type: 'toggle', default: false },
  { id: 'accounts-col-class', section: 'accounts', group: 'Columns', label: 'Show class/department', description: 'Display the class or department tag column.', type: 'toggle', default: false },
  { id: 'accounts-col-project', section: 'accounts', group: 'Columns', label: 'Show project column', description: 'Display the project/job tracking column.', type: 'toggle', default: false },
  { id: 'accounts-col-tax-code', section: 'accounts', group: 'Columns', label: 'Show tax code', description: 'Display the tax code applied to the line.', type: 'toggle', default: false },
  { id: 'accounts-frozen-columns', section: 'accounts', group: 'Columns', label: 'Frozen leading columns', description: 'Number of left columns that stay fixed when scrolling.', type: 'number', default: 2, min: 0, max: 5, step: 1 },

  // ===== Formatting (group: Formatting) =====
  { id: 'accounts-currency-symbol', section: 'accounts', group: 'Formatting', label: 'Currency symbol', description: 'Symbol shown before amounts.', type: 'text', default: '$' },
  { id: 'accounts-decimal-places', section: 'accounts', group: 'Formatting', label: 'Decimal places', description: 'Number of decimals shown for amounts.', type: 'number', default: 2, min: 0, max: 6, step: 1 },
  { id: 'accounts-thousands-separator', section: 'accounts', group: 'Formatting', label: 'Thousands separator', description: 'Group digits with separators (e.g. 1,000).', type: 'toggle', default: true },
  { id: 'accounts-negative-format', section: 'accounts', group: 'Formatting', label: 'Negative number format', description: 'How negative balances are displayed.', type: 'select', default: 'parentheses', options: [{ value: 'minus', label: '-1,000.00' }, { value: 'parentheses', label: '(1,000.00)' }, { value: 'red', label: 'Red text' }] },
  { id: 'accounts-date-format', section: 'accounts', group: 'Formatting', label: 'Date format', description: 'Format used for ledger dates.', type: 'select', default: 'mm-dd-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }] },
  { id: 'accounts-zero-display', section: 'accounts', group: 'Formatting', label: 'Zero amount display', description: 'How zero amounts render.', type: 'select', default: 'dash', options: [{ value: 'zero', label: '0.00' }, { value: 'dash', label: '—' }, { value: 'blank', label: 'Blank' }] },
  { id: 'accounts-currency-position', section: 'accounts', group: 'Formatting', label: 'Currency symbol position', description: 'Place the symbol before or after the amount.', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($100)' }, { value: 'after', label: 'After (100$)' }] },
  { id: 'accounts-account-number-mask', section: 'accounts', group: 'Formatting', label: 'Account number format', description: 'Template for displaying account numbers.', type: 'text', default: '####-###' },
  { id: 'accounts-show-currency-code', section: 'accounts', group: 'Formatting', label: 'Append ISO currency code', description: 'Append the 3-letter code (e.g. 100.00 USD).', type: 'toggle', default: false },
  { id: 'accounts-round-display', section: 'accounts', group: 'Formatting', label: 'Round display to whole units', description: 'Hide cents in list summaries.', type: 'toggle', default: false },
  { id: 'accounts-abbreviate-large', section: 'accounts', group: 'Formatting', label: 'Abbreviate large numbers', description: 'Show 1.2M instead of 1,200,000 in summaries.', type: 'toggle', default: false },
  { id: 'accounts-percent-decimal-places', section: 'accounts', group: 'Formatting', label: 'Percentage decimal places', description: 'Decimals shown for ratios and percentages.', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'accounts-debit-credit-style', section: 'accounts', group: 'Formatting', label: 'Debit/Credit presentation', description: 'How debits and credits are shown.', type: 'select', default: 'two-column', options: [{ value: 'two-column', label: 'Separate Dr/Cr columns' }, { value: 'signed', label: 'Single signed column' }] },
  { id: 'accounts-balance-sign-convention', section: 'accounts', group: 'Formatting', label: 'Balance sign convention', description: 'Show balances by natural sign or always positive.', type: 'select', default: 'natural', options: [{ value: 'natural', label: 'Natural (Dr+/Cr-)' }, { value: 'absolute', label: 'Always positive' }] },
  { id: 'accounts-monospace-amounts', section: 'accounts', group: 'Formatting', label: 'Monospace amount font', description: 'Use a fixed-width font so digits align.', type: 'toggle', default: true },

  // ===== Defaults (group: Defaults) =====
  { id: 'accounts-default-account-type', section: 'accounts', group: 'Defaults', label: 'Default new account type', description: 'Pre-selected type when creating an account.', type: 'select', default: 'expense', options: [{ value: 'asset', label: 'Asset' }, { value: 'liability', label: 'Liability' }, { value: 'equity', label: 'Equity' }, { value: 'income', label: 'Income' }, { value: 'expense', label: 'Expense' }] },
  { id: 'accounts-auto-number-new', section: 'accounts', group: 'Defaults', label: 'Auto-assign account numbers', description: 'Generate the next number automatically.', type: 'toggle', default: true },
  { id: 'accounts-number-increment', section: 'accounts', group: 'Defaults', label: 'Account number increment', description: 'Step between auto-generated numbers.', type: 'number', default: 10, min: 1, max: 1000, step: 1 },
  { id: 'accounts-default-currency', section: 'accounts', group: 'Defaults', label: 'Default account currency', description: 'Currency assigned to new accounts.', type: 'text', default: 'USD' },
  { id: 'accounts-default-journal-date', section: 'accounts', group: 'Defaults', label: 'Default journal entry date', description: 'Date pre-filled on new journal entries.', type: 'select', default: 'today', options: [{ value: 'today', label: 'Today' }, { value: 'last-used', label: 'Last used date' }, { value: 'period-end', label: 'Current period end' }] },
  { id: 'accounts-default-reference-prefix', section: 'accounts', group: 'Defaults', label: 'Journal reference prefix', description: 'Prefix added to new journal entry references.', type: 'text', default: 'JE-' },
  { id: 'accounts-default-new-account-active', section: 'accounts', group: 'Defaults', label: 'New accounts active by default', description: 'Mark newly created accounts as active.', type: 'toggle', default: true },
  { id: 'accounts-default-opening-balance', section: 'accounts', group: 'Defaults', label: 'Default opening balance', description: 'Opening balance prefilled for new accounts.', type: 'number', default: 0, min: -1000000, max: 1000000, step: 0.01 },
  { id: 'accounts-fiscal-year-start-month', section: 'accounts', group: 'Defaults', label: 'Fiscal year start month', description: 'Month the fiscal year begins.', type: 'select', default: 'january', options: [{ value: 'january', label: 'January' }, { value: 'april', label: 'April' }, { value: 'july', label: 'July' }, { value: 'october', label: 'October' }] },
  { id: 'accounts-default-tax-code', section: 'accounts', group: 'Defaults', label: 'Default tax code', description: 'Tax code applied to new ledger lines.', type: 'text', default: 'NONE' },
  { id: 'accounts-default-je-lines', section: 'accounts', group: 'Defaults', label: 'Default journal lines', description: 'Number of empty lines on a new journal entry.', type: 'number', default: 2, min: 2, max: 20, step: 1 },
  { id: 'accounts-default-rounding-account', section: 'accounts', group: 'Defaults', label: 'Default rounding account', description: 'Account used to absorb rounding differences.', type: 'text', default: 'Rounding Adjustments' },
  { id: 'accounts-copy-last-memo', section: 'accounts', group: 'Defaults', label: 'Carry forward last memo', description: 'Pre-fill memo from the previous entry.', type: 'toggle', default: false },
  { id: 'accounts-default-balance-as-of', section: 'accounts', group: 'Defaults', label: 'Default balance as-of', description: 'Reference point for displayed balances.', type: 'select', default: 'today', options: [{ value: 'today', label: 'Today' }, { value: 'period-end', label: 'Period end' }, { value: 'year-end', label: 'Year end' }] },

  // ===== Sorting & Filtering (group: Sorting & Filtering) =====
  { id: 'accounts-default-sort', section: 'accounts', group: 'Sorting & Filtering', label: 'Default account sort', description: 'How accounts are ordered.', type: 'select', default: 'number', options: [{ value: 'number', label: 'Account number' }, { value: 'name', label: 'Name' }, { value: 'type', label: 'Type' }, { value: 'balance', label: 'Balance' }] },
  { id: 'accounts-sort-direction', section: 'accounts', group: 'Sorting & Filtering', label: 'Default sort direction', description: 'Ascending or descending order.', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'accounts-ledger-sort', section: 'accounts', group: 'Sorting & Filtering', label: 'Ledger line sort', description: 'How ledger lines are ordered.', type: 'select', default: 'date-asc', options: [{ value: 'date-asc', label: 'Date (oldest first)' }, { value: 'date-desc', label: 'Date (newest first)' }, { value: 'reference', label: 'Reference number' }] },
  { id: 'accounts-default-type-filter', section: 'accounts', group: 'Sorting & Filtering', label: 'Default type filter', description: 'Account type shown by default.', type: 'select', default: 'all', options: [{ value: 'all', label: 'All types' }, { value: 'balance-sheet', label: 'Balance sheet only' }, { value: 'pnl', label: 'P&L only' }] },
  { id: 'accounts-remember-filters', section: 'accounts', group: 'Sorting & Filtering', label: 'Remember last filters', description: 'Restore filters when reopening the module.', type: 'toggle', default: true },
  { id: 'accounts-default-date-range', section: 'accounts', group: 'Sorting & Filtering', label: 'Default ledger date range', description: 'Period of transactions loaded initially.', type: 'select', default: 'current-month', options: [{ value: 'current-month', label: 'Current month' }, { value: 'current-quarter', label: 'Current quarter' }, { value: 'ytd', label: 'Year to date' }, { value: 'all', label: 'All time' }] },
  { id: 'accounts-search-includes-memo', section: 'accounts', group: 'Sorting & Filtering', label: 'Search includes memos', description: 'Match the search box against memo text.', type: 'toggle', default: true },
  { id: 'accounts-search-includes-numbers', section: 'accounts', group: 'Sorting & Filtering', label: 'Search includes account numbers', description: 'Match search against account numbers.', type: 'toggle', default: true },
  { id: 'accounts-filter-min-amount', section: 'accounts', group: 'Sorting & Filtering', label: 'Hide lines below amount', description: 'Suppress ledger lines under this absolute value.', type: 'number', default: 0, min: 0, max: 100000, step: 1 },
  { id: 'accounts-group-by-default', section: 'accounts', group: 'Sorting & Filtering', label: 'Default grouping', description: 'How ledger lines group together.', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'month', label: 'By month' }, { value: 'reference', label: 'By reference' }, { value: 'source', label: 'By source module' }] },
  { id: 'accounts-show-unreconciled-first', section: 'accounts', group: 'Sorting & Filtering', label: 'Unreconciled lines first', description: 'Float unreconciled lines to the top.', type: 'toggle', default: false },
  { id: 'accounts-quickfilter-favorites', section: 'accounts', group: 'Sorting & Filtering', label: 'Show favorites quick filter', description: 'Display a one-click filter for starred accounts.', type: 'toggle', default: true },

  // ===== Behavior (group: Behavior) =====
  { id: 'accounts-confirm-deactivate', section: 'accounts', group: 'Behavior', label: 'Confirm before deactivating', description: 'Ask for confirmation when deactivating an account.', type: 'toggle', default: true },
  { id: 'accounts-prevent-delete-with-activity', section: 'accounts', group: 'Behavior', label: 'Block deleting used accounts', description: 'Prevent deletion of accounts with transactions.', type: 'toggle', default: true },
  { id: 'accounts-autobalance-je', section: 'accounts', group: 'Behavior', label: 'Auto-balance journal entries', description: 'Auto-fill the last line to balance debits and credits.', type: 'toggle', default: false },
  { id: 'accounts-warn-unbalanced', section: 'accounts', group: 'Behavior', label: 'Warn on unbalanced entry', description: 'Show a warning if Dr does not equal Cr.', type: 'toggle', default: true },
  { id: 'accounts-allow-future-dates', section: 'accounts', group: 'Behavior', label: 'Allow future-dated entries', description: 'Permit posting to future dates.', type: 'toggle', default: false },
  { id: 'accounts-allow-backdating', section: 'accounts', group: 'Behavior', label: 'Allow backdated entries', description: 'Permit posting to closed or prior periods.', type: 'toggle', default: false },
  { id: 'accounts-lock-after-reconcile', section: 'accounts', group: 'Behavior', label: 'Lock reconciled lines', description: 'Prevent editing lines once reconciled.', type: 'toggle', default: true },
  { id: 'accounts-autosave-draft-je', section: 'accounts', group: 'Behavior', label: 'Auto-save journal drafts', description: 'Periodically save unfinished journal entries.', type: 'toggle', default: true },
  { id: 'accounts-autosave-interval', section: 'accounts', group: 'Behavior', label: 'Draft auto-save interval (sec)', description: 'How often drafts are saved.', type: 'number', default: 30, min: 5, max: 600, step: 5 },
  { id: 'accounts-enter-moves-down', section: 'accounts', group: 'Behavior', label: 'Enter adds next line', description: 'Pressing Enter creates a new journal line.', type: 'toggle', default: true },
  { id: 'accounts-duplicate-detection', section: 'accounts', group: 'Behavior', label: 'Detect duplicate entries', description: 'Warn when an identical entry already exists.', type: 'toggle', default: true },
  { id: 'accounts-auto-collapse-saved', section: 'accounts', group: 'Behavior', label: 'Collapse after save', description: 'Collapse the entry form after a successful save.', type: 'toggle', default: false },
  { id: 'accounts-require-memo', section: 'accounts', group: 'Behavior', label: 'Require memo on entries', description: 'Make the memo field mandatory.', type: 'toggle', default: false },
  { id: 'accounts-require-reference', section: 'accounts', group: 'Behavior', label: 'Require reference number', description: 'Make the reference field mandatory.', type: 'toggle', default: false },
  { id: 'accounts-default-action-on-save', section: 'accounts', group: 'Behavior', label: 'Action after save', description: 'What happens after saving an entry.', type: 'select', default: 'new', options: [{ value: 'new', label: 'Start new entry' }, { value: 'close', label: 'Return to ledger' }, { value: 'stay', label: 'Stay on entry' }] },
  { id: 'accounts-inline-edit', section: 'accounts', group: 'Behavior', label: 'Inline ledger editing', description: 'Edit ledger lines directly in the table.', type: 'toggle', default: false },
  { id: 'accounts-confirm-period-close', section: 'accounts', group: 'Behavior', label: 'Confirm period close', description: 'Require confirmation before closing a period.', type: 'toggle', default: true },
  { id: 'accounts-auto-suggest-offset', section: 'accounts', group: 'Behavior', label: 'Suggest offsetting account', description: 'Recommend a contra account based on history.', type: 'toggle', default: true },

  // ===== Notifications (group: Notifications) =====
  { id: 'accounts-notify-unbalanced', section: 'accounts', group: 'Notifications', label: 'Alert on unbalanced trial balance', description: 'Notify when the trial balance does not net to zero.', type: 'toggle', default: true },
  { id: 'accounts-notify-negative-balance', section: 'accounts', group: 'Notifications', label: 'Alert on unexpected negative balance', description: 'Notify when an account goes negative against its nature.', type: 'toggle', default: true },
  { id: 'accounts-notify-period-close-due', section: 'accounts', group: 'Notifications', label: 'Period close reminder', description: 'Remind to close the books at period end.', type: 'toggle', default: true },
  { id: 'accounts-notify-unreconciled-count', section: 'accounts', group: 'Notifications', label: 'Unreconciled item alert', description: 'Notify when unreconciled items exceed a threshold.', type: 'toggle', default: false },
  { id: 'accounts-unreconciled-threshold', section: 'accounts', group: 'Notifications', label: 'Unreconciled alert threshold', description: 'Number of unreconciled items that triggers an alert.', type: 'number', default: 25, min: 1, max: 1000, step: 1 },
  { id: 'accounts-notify-large-entry', section: 'accounts', group: 'Notifications', label: 'Large entry alert', description: 'Notify when an entry exceeds a value threshold.', type: 'toggle', default: false },
  { id: 'accounts-large-entry-threshold', section: 'accounts', group: 'Notifications', label: 'Large entry threshold', description: 'Amount above which an entry triggers an alert.', type: 'number', default: 10000, min: 100, max: 10000000, step: 100 },
  { id: 'accounts-notify-budget-overrun', section: 'accounts', group: 'Notifications', label: 'Budget overrun alert', description: 'Notify when an expense account exceeds budget.', type: 'toggle', default: false },
  { id: 'accounts-notify-on-post', section: 'accounts', group: 'Notifications', label: 'Toast on successful post', description: 'Show a confirmation toast after posting.', type: 'toggle', default: true },
  { id: 'accounts-notify-duplicate-number', section: 'accounts', group: 'Notifications', label: 'Duplicate account number alert', description: 'Warn when a number collides with an existing account.', type: 'toggle', default: true },
  { id: 'accounts-notify-channel', section: 'accounts', group: 'Notifications', label: 'Notification channel', description: 'Where ledger alerts are delivered.', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app only' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'In-app and email' }] },
  { id: 'accounts-notify-recurring-due', section: 'accounts', group: 'Notifications', label: 'Recurring entry reminder', description: 'Remind when a recurring journal entry is due.', type: 'toggle', default: true },

  // ===== Export (group: Export) =====
  { id: 'accounts-export-format', section: 'accounts', group: 'Export', label: 'Default export format', description: 'File format used when exporting ledgers.', type: 'select', default: 'xlsx', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel (XLSX)' }, { value: 'pdf', label: 'PDF' }, { value: 'qbo', label: 'QuickBooks (QBO)' }] },
  { id: 'accounts-export-include-headers', section: 'accounts', group: 'Export', label: 'Include column headers', description: 'Write a header row in exports.', type: 'toggle', default: true },
  { id: 'accounts-export-include-subtotals', section: 'accounts', group: 'Export', label: 'Include subtotals', description: 'Include group subtotal rows in exports.', type: 'toggle', default: true },
  { id: 'accounts-export-include-inactive', section: 'accounts', group: 'Export', label: 'Include inactive accounts', description: 'Export deactivated accounts too.', type: 'toggle', default: false },
  { id: 'accounts-export-date-range', section: 'accounts', group: 'Export', label: 'Export date range', description: 'Default period included in exports.', type: 'select', default: 'current-view', options: [{ value: 'current-view', label: 'Current view' }, { value: 'ytd', label: 'Year to date' }, { value: 'all', label: 'All time' }] },
  { id: 'accounts-export-csv-delimiter', section: 'accounts', group: 'Export', label: 'CSV delimiter', description: 'Character separating CSV fields.', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'accounts-export-encoding', section: 'accounts', group: 'Export', label: 'Export file encoding', description: 'Character encoding for exported files.', type: 'select', default: 'utf-8', options: [{ value: 'utf-8', label: 'UTF-8' }, { value: 'utf-8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'accounts-export-filename-template', section: 'accounts', group: 'Export', label: 'Export filename template', description: 'Naming template for exported files.', type: 'text', default: 'GL_{account}_{date}' },
  { id: 'accounts-export-include-running-balance', section: 'accounts', group: 'Export', label: 'Include running balance', description: 'Add the running balance column to exports.', type: 'toggle', default: true },
  { id: 'accounts-export-pdf-orientation', section: 'accounts', group: 'Export', label: 'PDF page orientation', description: 'Orientation for PDF exports.', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'accounts-export-include-logo', section: 'accounts', group: 'Export', label: 'Include company logo on PDF', description: 'Add the company logo to PDF exports.', type: 'toggle', default: true },
  { id: 'accounts-export-open-after', section: 'accounts', group: 'Export', label: 'Open file after export', description: 'Automatically open exported files.', type: 'toggle', default: true },
  { id: 'accounts-export-split-by-account', section: 'accounts', group: 'Export', label: 'One file per account', description: 'Export each account to its own file.', type: 'toggle', default: false },

  // ===== Colors & Theme (group: Colors & Theme) =====
  { id: 'accounts-color-asset', section: 'accounts', group: 'Colors & Theme', label: 'Asset accent color', description: 'Color used for asset accounts.', type: 'color', default: '#3b82f6' },
  { id: 'accounts-color-liability', section: 'accounts', group: 'Colors & Theme', label: 'Liability accent color', description: 'Color used for liability accounts.', type: 'color', default: '#f59e0b' },
  { id: 'accounts-color-equity', section: 'accounts', group: 'Colors & Theme', label: 'Equity accent color', description: 'Color used for equity accounts.', type: 'color', default: '#8b5cf6' },
  { id: 'accounts-color-income', section: 'accounts', group: 'Colors & Theme', label: 'Income accent color', description: 'Color used for income accounts.', type: 'color', default: '#10b981' },
  { id: 'accounts-color-expense', section: 'accounts', group: 'Colors & Theme', label: 'Expense accent color', description: 'Color used for expense accounts.', type: 'color', default: '#ef4444' },
  { id: 'accounts-color-debit', section: 'accounts', group: 'Colors & Theme', label: 'Debit text color', description: 'Color of debit amounts.', type: 'color', default: '#111827' },
  { id: 'accounts-color-credit', section: 'accounts', group: 'Colors & Theme', label: 'Credit text color', description: 'Color of credit amounts.', type: 'color', default: '#111827' },
  { id: 'accounts-color-negative', section: 'accounts', group: 'Colors & Theme', label: 'Negative amount color', description: 'Color applied to negative balances.', type: 'color', default: '#dc2626' },
  { id: 'accounts-color-reconciled', section: 'accounts', group: 'Colors & Theme', label: 'Reconciled highlight color', description: 'Background tint for reconciled lines.', type: 'color', default: '#ecfdf5' },
  { id: 'accounts-color-subtotal-bg', section: 'accounts', group: 'Colors & Theme', label: 'Subtotal row background', description: 'Background color of subtotal rows.', type: 'color', default: '#f3f4f6' },
  { id: 'accounts-color-row-stripe', section: 'accounts', group: 'Colors & Theme', label: 'Zebra stripe color', description: 'Alternate row background tint.', type: 'color', default: '#fafafa' },
  { id: 'accounts-color-current-period', section: 'accounts', group: 'Colors & Theme', label: 'Current period highlight', description: 'Highlight color for the active period.', type: 'color', default: '#dbeafe' },
  { id: 'accounts-zebra-striping', section: 'accounts', group: 'Colors & Theme', label: 'Zebra striping', description: 'Alternate row shading in the ledger.', type: 'toggle', default: true },
  { id: 'accounts-color-coded-types', section: 'accounts', group: 'Colors & Theme', label: 'Color-code account types', description: 'Apply type colors to rows and badges.', type: 'toggle', default: true },

  // ===== Accessibility (group: Accessibility) =====
  { id: 'accounts-font-size', section: 'accounts', group: 'Accessibility', label: 'Ledger font size (px)', description: 'Base font size for the ledger table.', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'accounts-high-contrast', section: 'accounts', group: 'Accessibility', label: 'High-contrast mode', description: 'Increase contrast for readability.', type: 'toggle', default: false },
  { id: 'accounts-colorblind-safe', section: 'accounts', group: 'Accessibility', label: 'Color-blind safe palette', description: 'Use patterns and shapes alongside color.', type: 'toggle', default: false },
  { id: 'accounts-reduce-motion', section: 'accounts', group: 'Accessibility', label: 'Reduce motion', description: 'Minimize animations and transitions.', type: 'toggle', default: false },
  { id: 'accounts-focus-outline', section: 'accounts', group: 'Accessibility', label: 'Strong focus outline', description: 'Show a prominent outline on focused cells.', type: 'toggle', default: true },
  { id: 'accounts-screenreader-summaries', section: 'accounts', group: 'Accessibility', label: 'Screen-reader summaries', description: 'Announce row totals to assistive tech.', type: 'toggle', default: true },
  { id: 'accounts-keyboard-nav-cells', section: 'accounts', group: 'Accessibility', label: 'Cell keyboard navigation', description: 'Move between ledger cells with arrow keys.', type: 'toggle', default: true },
  { id: 'accounts-line-height', section: 'accounts', group: 'Accessibility', label: 'Row line height', description: 'Vertical spacing multiplier for rows.', type: 'number', default: 1.4, min: 1, max: 2.5, step: 0.1 },
  { id: 'accounts-bold-totals', section: 'accounts', group: 'Accessibility', label: 'Bold total amounts', description: 'Render totals in bold for emphasis.', type: 'toggle', default: true },
  { id: 'accounts-underline-links', section: 'accounts', group: 'Accessibility', label: 'Underline drill-down links', description: 'Underline clickable references and accounts.', type: 'toggle', default: false },

  // ===== Shortcuts (group: Shortcuts) =====
  { id: 'accounts-shortcut-new-je', section: 'accounts', group: 'Shortcuts', label: 'New journal entry shortcut', description: 'Keyboard shortcut to open a new journal entry.', type: 'text', default: 'Ctrl+J' },
  { id: 'accounts-shortcut-new-account', section: 'accounts', group: 'Shortcuts', label: 'New account shortcut', description: 'Keyboard shortcut to create an account.', type: 'text', default: 'Ctrl+Shift+A' },
  { id: 'accounts-shortcut-save', section: 'accounts', group: 'Shortcuts', label: 'Save entry shortcut', description: 'Keyboard shortcut to save the current entry.', type: 'text', default: 'Ctrl+S' },
  { id: 'accounts-shortcut-add-line', section: 'accounts', group: 'Shortcuts', label: 'Add line shortcut', description: 'Keyboard shortcut to add a journal line.', type: 'text', default: 'Ctrl+Enter' },
  { id: 'accounts-shortcut-search', section: 'accounts', group: 'Shortcuts', label: 'Focus search shortcut', description: 'Keyboard shortcut to focus the search box.', type: 'text', default: 'Ctrl+F' },
  { id: 'accounts-shortcut-toggle-balance', section: 'accounts', group: 'Shortcuts', label: 'Toggle balance column shortcut', description: 'Keyboard shortcut to show/hide running balance.', type: 'text', default: 'Ctrl+B' },
  { id: 'accounts-shortcut-reconcile', section: 'accounts', group: 'Shortcuts', label: 'Reconcile line shortcut', description: 'Keyboard shortcut to mark a line reconciled.', type: 'text', default: 'Ctrl+R' },
  { id: 'accounts-shortcut-duplicate', section: 'accounts', group: 'Shortcuts', label: 'Duplicate entry shortcut', description: 'Keyboard shortcut to duplicate an entry.', type: 'text', default: 'Ctrl+D' },
  { id: 'accounts-shortcut-export', section: 'accounts', group: 'Shortcuts', label: 'Export shortcut', description: 'Keyboard shortcut to export the ledger.', type: 'text', default: 'Ctrl+E' },
  { id: 'accounts-shortcuts-enabled', section: 'accounts', group: 'Shortcuts', label: 'Enable keyboard shortcuts', description: 'Master toggle for ledger shortcuts.', type: 'toggle', default: true },
  { id: 'accounts-shortcut-next-account', section: 'accounts', group: 'Shortcuts', label: 'Next account shortcut', description: 'Keyboard shortcut to jump to the next account.', type: 'text', default: 'Alt+Down' },
  { id: 'accounts-shortcut-prev-account', section: 'accounts', group: 'Shortcuts', label: 'Previous account shortcut', description: 'Keyboard shortcut to jump to the previous account.', type: 'text', default: 'Alt+Up' },

  // ===== Privacy (group: Privacy) =====
  { id: 'accounts-mask-balances', section: 'accounts', group: 'Privacy', label: 'Mask balances by default', description: 'Blur account balances until revealed.', type: 'toggle', default: false },
  { id: 'accounts-mask-on-screenshare', section: 'accounts', group: 'Privacy', label: 'Hide amounts during screen share', description: 'Automatically mask figures when sharing.', type: 'toggle', default: false },
  { id: 'accounts-require-pin-sensitive', section: 'accounts', group: 'Privacy', label: 'Require PIN for sensitive accounts', description: 'Prompt for a PIN to view flagged accounts.', type: 'toggle', default: false },
  { id: 'accounts-audit-log-views', section: 'accounts', group: 'Privacy', label: 'Log account views', description: 'Record who viewed each account ledger.', type: 'toggle', default: false },
  { id: 'accounts-redact-exports', section: 'accounts', group: 'Privacy', label: 'Redact memos in exports', description: 'Strip memo text from exported files.', type: 'toggle', default: false },
  { id: 'accounts-auto-lock-minutes', section: 'accounts', group: 'Privacy', label: 'Auto-lock after idle (min)', description: 'Lock the ledger after inactivity.', type: 'number', default: 15, min: 1, max: 120, step: 1 },
  { id: 'accounts-hide-user-names', section: 'accounts', group: 'Privacy', label: 'Hide created-by names', description: 'Replace user names with initials in shared views.', type: 'toggle', default: false },
  { id: 'accounts-watermark-prints', section: 'accounts', group: 'Privacy', label: 'Watermark printed ledgers', description: 'Add a confidential watermark to printouts.', type: 'toggle', default: false },
  { id: 'accounts-watermark-text', section: 'accounts', group: 'Privacy', label: 'Watermark text', description: 'Text used for the confidential watermark.', type: 'text', default: 'CONFIDENTIAL' },

  // ===== Reconciliation (group: Reconciliation) =====
  { id: 'accounts-recon-auto-match', section: 'accounts', group: 'Reconciliation', label: 'Auto-match cleared items', description: 'Automatically match items during reconciliation.', type: 'toggle', default: true },
  { id: 'accounts-recon-tolerance', section: 'accounts', group: 'Reconciliation', label: 'Match tolerance', description: 'Allowed difference when auto-matching.', type: 'number', default: 0.02, min: 0, max: 10, step: 0.01 },
  { id: 'accounts-recon-date-window', section: 'accounts', group: 'Reconciliation', label: 'Match date window (days)', description: 'Days within which items can auto-match.', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'accounts-recon-show-difference', section: 'accounts', group: 'Reconciliation', label: 'Show running difference', description: 'Display the reconciliation difference live.', type: 'toggle', default: true },
  { id: 'accounts-recon-lock-on-finish', section: 'accounts', group: 'Reconciliation', label: 'Lock account after reconcile', description: 'Lock the account once reconciliation completes.', type: 'toggle', default: true },
  { id: 'accounts-recon-default-account', section: 'accounts', group: 'Reconciliation', label: 'Default reconcile account', description: 'Account pre-selected for reconciliation.', type: 'text', default: 'Checking' },
  { id: 'accounts-recon-carry-uncleared', section: 'accounts', group: 'Reconciliation', label: 'Carry uncleared forward', description: 'Roll uncleared items into the next reconciliation.', type: 'toggle', default: true },
  { id: 'accounts-recon-highlight-stale', section: 'accounts', group: 'Reconciliation', label: 'Highlight stale items', description: 'Flag items uncleared beyond a threshold.', type: 'toggle', default: true },
  { id: 'accounts-recon-stale-days', section: 'accounts', group: 'Reconciliation', label: 'Stale item threshold (days)', description: 'Age at which an item is considered stale.', type: 'number', default: 60, min: 1, max: 365, step: 1 },
  { id: 'accounts-recon-statement-prompt', section: 'accounts', group: 'Reconciliation', label: 'Prompt for statement balance', description: 'Ask for the statement balance at start.', type: 'toggle', default: true },

  // ===== Chart of Accounts (group: Chart of Accounts) =====
  { id: 'accounts-coa-numbering-scheme', section: 'accounts', group: 'Chart of Accounts', label: 'Numbering scheme', description: 'Standard used for account numbers.', type: 'select', default: '4-digit', options: [{ value: '3-digit', label: '3-digit' }, { value: '4-digit', label: '4-digit' }, { value: '5-digit', label: '5-digit' }, { value: 'custom', label: 'Custom' }] },
  { id: 'accounts-coa-allow-subaccounts', section: 'accounts', group: 'Chart of Accounts', label: 'Allow sub-accounts', description: 'Permit nesting accounts under parents.', type: 'toggle', default: true },
  { id: 'accounts-coa-max-depth', section: 'accounts', group: 'Chart of Accounts', label: 'Maximum nesting depth', description: 'Deepest level of sub-accounts allowed.', type: 'number', default: 4, min: 1, max: 10, step: 1 },
  { id: 'accounts-coa-enforce-ranges', section: 'accounts', group: 'Chart of Accounts', label: 'Enforce type number ranges', description: 'Require numbers fall in the type range (e.g. assets 1000-1999).', type: 'toggle', default: true },
  { id: 'accounts-coa-template', section: 'accounts', group: 'Chart of Accounts', label: 'Starter chart template', description: 'Template used to seed new charts.', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard business' }, { value: 'nonprofit', label: 'Nonprofit' }, { value: 'retail', label: 'Retail' }, { value: 'service', label: 'Service' }, { value: 'blank', label: 'Blank' }] },
  { id: 'accounts-coa-show-account-count', section: 'accounts', group: 'Chart of Accounts', label: 'Show account counts', description: 'Display the number of accounts per group.', type: 'toggle', default: true },
  { id: 'accounts-coa-merge-confirm', section: 'accounts', group: 'Chart of Accounts', label: 'Confirm account merges', description: 'Require confirmation when merging accounts.', type: 'toggle', default: true },
  { id: 'accounts-coa-allow-rename-used', section: 'accounts', group: 'Chart of Accounts', label: 'Allow renaming used accounts', description: 'Permit renaming accounts that have activity.', type: 'toggle', default: true },
  { id: 'accounts-coa-default-detail-type', section: 'accounts', group: 'Chart of Accounts', label: 'Require detail type', description: 'Mandate a detail/subtype on each account.', type: 'toggle', default: false },
  { id: 'accounts-coa-bank-feed-link', section: 'accounts', group: 'Chart of Accounts', label: 'Show bank feed link status', description: 'Indicate which accounts are linked to bank feeds.', type: 'toggle', default: true },
  { id: 'accounts-coa-favorite-pinning', section: 'accounts', group: 'Chart of Accounts', label: 'Allow pinning favorites', description: 'Let users star frequently used accounts.', type: 'toggle', default: true },

  // ===== Multi-Currency (group: Multi-Currency) =====
  { id: 'accounts-mc-enabled', section: 'accounts', group: 'Multi-Currency', label: 'Enable multi-currency', description: 'Allow accounts in foreign currencies.', type: 'toggle', default: false },
  { id: 'accounts-mc-base-currency', section: 'accounts', group: 'Multi-Currency', label: 'Base reporting currency', description: 'Currency used for consolidated reports.', type: 'text', default: 'USD' },
  { id: 'accounts-mc-rate-source', section: 'accounts', group: 'Multi-Currency', label: 'Exchange rate source', description: 'Where FX rates are pulled from.', type: 'select', default: 'manual', options: [{ value: 'manual', label: 'Manual entry' }, { value: 'ecb', label: 'European Central Bank' }, { value: 'openexchange', label: 'Open Exchange Rates' }] },
  { id: 'accounts-mc-show-both-amounts', section: 'accounts', group: 'Multi-Currency', label: 'Show foreign and base amounts', description: 'Display both currency amounts on each line.', type: 'toggle', default: true },
  { id: 'accounts-mc-auto-revalue', section: 'accounts', group: 'Multi-Currency', label: 'Auto-revalue at period end', description: 'Post unrealized FX gains/losses automatically.', type: 'toggle', default: false },
  { id: 'accounts-mc-gain-loss-account', section: 'accounts', group: 'Multi-Currency', label: 'FX gain/loss account', description: 'Account used for realized FX differences.', type: 'text', default: 'Currency Gain/Loss' },
  { id: 'accounts-mc-rate-decimal-places', section: 'accounts', group: 'Multi-Currency', label: 'Exchange rate decimals', description: 'Decimal precision for FX rates.', type: 'number', default: 6, min: 2, max: 10, step: 1 },
  { id: 'accounts-mc-lock-rate-on-post', section: 'accounts', group: 'Multi-Currency', label: 'Lock rate on posting', description: 'Freeze the FX rate once an entry is posted.', type: 'toggle', default: true },

  // ===== Audit & Compliance (group: Audit & Compliance) =====
  { id: 'accounts-audit-trail-enabled', section: 'accounts', group: 'Audit & Compliance', label: 'Enable audit trail', description: 'Record all changes to ledger entries.', type: 'toggle', default: true },
  { id: 'accounts-audit-immutable-posted', section: 'accounts', group: 'Audit & Compliance', label: 'Immutable posted entries', description: 'Require reversal instead of editing posted entries.', type: 'toggle', default: true },
  { id: 'accounts-audit-require-reason', section: 'accounts', group: 'Audit & Compliance', label: 'Require change reason', description: 'Prompt for a reason when editing entries.', type: 'toggle', default: false },
  { id: 'accounts-audit-retention-years', section: 'accounts', group: 'Audit & Compliance', label: 'Audit retention (years)', description: 'How long audit records are kept.', type: 'number', default: 7, min: 1, max: 30, step: 1 },
  { id: 'accounts-audit-show-revision-history', section: 'accounts', group: 'Audit & Compliance', label: 'Show revision history', description: 'Display the change history on each entry.', type: 'toggle', default: true },
  { id: 'accounts-audit-segregation-warn', section: 'accounts', group: 'Audit & Compliance', label: 'Warn on segregation of duties', description: 'Flag when one user both creates and approves.', type: 'toggle', default: false },
  { id: 'accounts-audit-require-approval', section: 'accounts', group: 'Audit & Compliance', label: 'Require approval to post', description: 'Route entries through an approval step.', type: 'toggle', default: false },
  { id: 'accounts-audit-approval-threshold', section: 'accounts', group: 'Audit & Compliance', label: 'Approval threshold amount', description: 'Entries above this amount need approval.', type: 'number', default: 5000, min: 0, max: 1000000, step: 100 },
  { id: 'accounts-audit-lock-closed-periods', section: 'accounts', group: 'Audit & Compliance', label: 'Hard-lock closed periods', description: 'Fully prevent any posting to closed periods.', type: 'toggle', default: true },

  // ===== Budgeting (group: Budgeting) =====
  { id: 'accounts-budget-show-vs-actual', section: 'accounts', group: 'Budgeting', label: 'Show budget vs actual', description: 'Display a budget comparison column.', type: 'toggle', default: false },
  { id: 'accounts-budget-variance-format', section: 'accounts', group: 'Budgeting', label: 'Variance display', description: 'How budget variance is shown.', type: 'select', default: 'amount-percent', options: [{ value: 'amount', label: 'Amount only' }, { value: 'percent', label: 'Percent only' }, { value: 'amount-percent', label: 'Amount and percent' }] },
  { id: 'accounts-budget-period', section: 'accounts', group: 'Budgeting', label: 'Budget period granularity', description: 'Time granularity for budget figures.', type: 'select', default: 'monthly', options: [{ value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }] },
  { id: 'accounts-budget-highlight-overrun', section: 'accounts', group: 'Budgeting', label: 'Highlight over-budget', description: 'Color accounts that exceed their budget.', type: 'toggle', default: true },
  { id: 'accounts-budget-overrun-color', section: 'accounts', group: 'Budgeting', label: 'Over-budget color', description: 'Color used for over-budget figures.', type: 'color', default: '#dc2626' },
  { id: 'accounts-budget-rollover', section: 'accounts', group: 'Budgeting', label: 'Roll over unused budget', description: 'Carry remaining budget into the next period.', type: 'toggle', default: false },
  { id: 'accounts-budget-warn-percent', section: 'accounts', group: 'Budgeting', label: 'Budget warning threshold (%)', description: 'Warn when spend reaches this percent of budget.', type: 'number', default: 90, min: 50, max: 100, step: 5 },

  // ===== Recurring Entries (group: Recurring Entries) =====
  { id: 'accounts-recurring-enabled', section: 'accounts', group: 'Recurring Entries', label: 'Enable recurring entries', description: 'Allow scheduling repeating journal entries.', type: 'toggle', default: true },
  { id: 'accounts-recurring-auto-post', section: 'accounts', group: 'Recurring Entries', label: 'Auto-post recurring entries', description: 'Post recurring entries without review.', type: 'toggle', default: false },
  { id: 'accounts-recurring-default-frequency', section: 'accounts', group: 'Recurring Entries', label: 'Default frequency', description: 'Default repeat interval for new schedules.', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }] },
  { id: 'accounts-recurring-lead-days', section: 'accounts', group: 'Recurring Entries', label: 'Create lead time (days)', description: 'Days ahead to generate the draft entry.', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'accounts-recurring-skip-weekends', section: 'accounts', group: 'Recurring Entries', label: 'Shift off weekends', description: 'Move recurring postings off weekend dates.', type: 'toggle', default: true },
  { id: 'accounts-recurring-end-behavior', section: 'accounts', group: 'Recurring Entries', label: 'End-of-schedule behavior', description: 'What happens when a schedule completes.', type: 'select', default: 'notify', options: [{ value: 'notify', label: 'Notify and stop' }, { value: 'silent', label: 'Stop silently' }, { value: 'archive', label: 'Archive schedule' }] },

  // ===== Dashboard & Summary (group: Dashboard) =====
  { id: 'accounts-dash-show-trial-balance', section: 'accounts', group: 'Dashboard', label: 'Show trial balance tile', description: 'Display a trial balance summary tile.', type: 'toggle', default: true },
  { id: 'accounts-dash-show-account-mix', section: 'accounts', group: 'Dashboard', label: 'Show account mix chart', description: 'Display a chart of balances by type.', type: 'toggle', default: true },
  { id: 'accounts-dash-chart-type', section: 'accounts', group: 'Dashboard', label: 'Summary chart type', description: 'Chart used for the account summary.', type: 'select', default: 'donut', options: [{ value: 'donut', label: 'Donut' }, { value: 'bar', label: 'Bar' }, { value: 'treemap', label: 'Treemap' }] },
  { id: 'accounts-dash-top-accounts-count', section: 'accounts', group: 'Dashboard', label: 'Top accounts shown', description: 'Number of largest accounts on the dashboard.', type: 'number', default: 5, min: 1, max: 25, step: 1 },
  { id: 'accounts-dash-show-recent-entries', section: 'accounts', group: 'Dashboard', label: 'Show recent entries feed', description: 'Display the latest journal entries.', type: 'toggle', default: true },
  { id: 'accounts-dash-recent-count', section: 'accounts', group: 'Dashboard', label: 'Recent entries count', description: 'How many recent entries to list.', type: 'number', default: 10, min: 1, max: 50, step: 1 },
  { id: 'accounts-dash-show-unbalanced-warning', section: 'accounts', group: 'Dashboard', label: 'Show out-of-balance warning', description: 'Flag if the books are out of balance.', type: 'toggle', default: true },
  { id: 'accounts-dash-comparison-period', section: 'accounts', group: 'Dashboard', label: 'Comparison period', description: 'Period compared against on the dashboard.', type: 'select', default: 'prior-month', options: [{ value: 'prior-month', label: 'Prior month' }, { value: 'prior-quarter', label: 'Prior quarter' }, { value: 'prior-year', label: 'Prior year' }] },
  { id: 'accounts-dash-refresh-interval', section: 'accounts', group: 'Dashboard', label: 'Auto-refresh interval (min)', description: 'How often dashboard tiles refresh.', type: 'number', default: 5, min: 0, max: 120, step: 1 },

  // ===== Printing (group: Printing) =====
  { id: 'accounts-print-header-text', section: 'accounts', group: 'Printing', label: 'Print header text', description: 'Custom header line on printed ledgers.', type: 'text', default: 'General Ledger' },
  { id: 'accounts-print-include-footer', section: 'accounts', group: 'Printing', label: 'Include page footer', description: 'Print a footer with page numbers and date.', type: 'toggle', default: true },
  { id: 'accounts-print-paper-size', section: 'accounts', group: 'Printing', label: 'Paper size', description: 'Default paper size for printing.', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'legal', label: 'Legal' }, { value: 'a4', label: 'A4' }] },
  { id: 'accounts-print-grayscale', section: 'accounts', group: 'Printing', label: 'Print in grayscale', description: 'Strip colors when printing.', type: 'toggle', default: false },
  { id: 'accounts-print-repeat-headers', section: 'accounts', group: 'Printing', label: 'Repeat headers per page', description: 'Reprint column headers on each page.', type: 'toggle', default: true },
  { id: 'accounts-print-page-break-account', section: 'accounts', group: 'Printing', label: 'Page break per account', description: 'Start each account on a new page.', type: 'toggle', default: false },
  { id: 'accounts-print-margin-mm', section: 'accounts', group: 'Printing', label: 'Page margin (mm)', description: 'Margin applied to printed pages.', type: 'number', default: 15, min: 0, max: 50, step: 1 },

  // ===== Integration (group: Integration) =====
  { id: 'accounts-int-sync-bank-feeds', section: 'accounts', group: 'Integration', label: 'Sync bank feeds to GL', description: 'Pull bank feed transactions into the ledger.', type: 'toggle', default: true },
  { id: 'accounts-int-auto-categorize', section: 'accounts', group: 'Integration', label: 'Auto-categorize fed transactions', description: 'Suggest accounts for imported transactions.', type: 'toggle', default: true },
  { id: 'accounts-int-quickbooks-mapping', section: 'accounts', group: 'Integration', label: 'QuickBooks account mapping', description: 'Default mapping mode for QuickBooks imports.', type: 'select', default: 'by-number', options: [{ value: 'by-number', label: 'By account number' }, { value: 'by-name', label: 'By name' }, { value: 'manual', label: 'Manual each time' }] },
  { id: 'accounts-int-post-from-ar', section: 'accounts', group: 'Integration', label: 'Auto-post from AR', description: 'Create GL entries from accounts receivable.', type: 'toggle', default: true },
  { id: 'accounts-int-post-from-ap', section: 'accounts', group: 'Integration', label: 'Auto-post from AP', description: 'Create GL entries from accounts payable.', type: 'toggle', default: true },
  { id: 'accounts-int-post-from-payroll', section: 'accounts', group: 'Integration', label: 'Auto-post from payroll', description: 'Create GL entries from payroll runs.', type: 'toggle', default: true },
  { id: 'accounts-int-sync-frequency', section: 'accounts', group: 'Integration', label: 'Integration sync frequency', description: 'How often integrated sources post to the GL.', type: 'select', default: 'realtime', options: [{ value: 'realtime', label: 'Real-time' }, { value: 'hourly', label: 'Hourly' }, { value: 'daily', label: 'Daily' }, { value: 'manual', label: 'Manual' }] },

  // ===== Period Close (group: Period Close) =====
  { id: 'accounts-close-auto-rollforward', section: 'accounts', group: 'Period Close', label: 'Auto roll-forward balances', description: 'Carry balance-sheet balances into the new period.', type: 'toggle', default: true },
  { id: 'accounts-close-retained-earnings-account', section: 'accounts', group: 'Period Close', label: 'Retained earnings account', description: 'Account income/expense closes into at year end.', type: 'text', default: 'Retained Earnings' },
  { id: 'accounts-close-require-recon', section: 'accounts', group: 'Period Close', label: 'Require reconciliation to close', description: 'Block closing until key accounts are reconciled.', type: 'toggle', default: true },
  { id: 'accounts-close-checklist', section: 'accounts', group: 'Period Close', label: 'Show close checklist', description: 'Display a period-close task checklist.', type: 'toggle', default: true },
  { id: 'accounts-close-soft-vs-hard', section: 'accounts', group: 'Period Close', label: 'Close type', description: 'Whether closing is reversible or final.', type: 'select', default: 'soft', options: [{ value: 'soft', label: 'Soft (reopenable)' }, { value: 'hard', label: 'Hard (locked)' }] },
  { id: 'accounts-close-auto-accruals', section: 'accounts', group: 'Period Close', label: 'Auto-reverse accruals', description: 'Reverse accrual entries on the first of next period.', type: 'toggle', default: true },
  { id: 'accounts-close-notify-stakeholders', section: 'accounts', group: 'Period Close', label: 'Notify on close', description: 'Email stakeholders when a period closes.', type: 'toggle', default: false },
];
