import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-20) =====
  { id: 'show-running-balance', section: 'bank-recon', group: 'Display', label: 'Show running balance column', description: 'Display a running ledger balance next to each transaction.', type: 'toggle', default: true },
  { id: 'split-cleared-uncleared', section: 'bank-recon', group: 'Display', label: 'Split cleared and uncleared panes', description: 'Show cleared and uncleared transactions in separate side-by-side panes.', type: 'toggle', default: true },
  { id: 'statement-summary-position', section: 'bank-recon', group: 'Display', label: 'Statement summary position', type: 'select', default: 'top', options: [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }, { value: 'right', label: 'Right sidebar' }, { value: 'hidden', label: 'Hidden' }] },
  { id: 'rows-per-page', section: 'bank-recon', group: 'Display', label: 'Transactions per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'density', section: 'bank-recon', group: 'Display', label: 'Row density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'show-difference-banner', section: 'bank-recon', group: 'Display', label: 'Show difference banner', description: 'Persistent banner showing the remaining difference to reconcile.', type: 'toggle', default: true },
  { id: 'highlight-matched-rows', section: 'bank-recon', group: 'Display', label: 'Highlight matched rows', type: 'toggle', default: true },
  { id: 'show-account-nickname', section: 'bank-recon', group: 'Display', label: 'Show account nickname', description: 'Use the friendly account nickname instead of the full account number.', type: 'toggle', default: true },
  { id: 'mask-account-number', section: 'bank-recon', group: 'Display', label: 'Mask account number', description: 'Show only the last four digits of the bank account number.', type: 'toggle', default: true },
  { id: 'show-bank-logo', section: 'bank-recon', group: 'Display', label: 'Show bank logo', type: 'toggle', default: true },
  { id: 'show-progress-meter', section: 'bank-recon', group: 'Display', label: 'Show reconciliation progress meter', type: 'toggle', default: true },
  { id: 'sticky-header', section: 'bank-recon', group: 'Display', label: 'Sticky table header', description: 'Keep the column header visible while scrolling.', type: 'toggle', default: true },
  { id: 'show-memo-line', section: 'bank-recon', group: 'Display', label: 'Show memo on a second line', type: 'toggle', default: false },
  { id: 'show-deposit-withdrawal-icons', section: 'bank-recon', group: 'Display', label: 'Show deposit/withdrawal icons', type: 'toggle', default: true },
  { id: 'collapse-reconciled-by-default', section: 'bank-recon', group: 'Display', label: 'Collapse reconciled transactions by default', type: 'toggle', default: false },
  { id: 'show-statement-image-thumb', section: 'bank-recon', group: 'Display', label: 'Show statement image thumbnail', type: 'toggle', default: false },
  { id: 'panel-layout', section: 'bank-recon', group: 'Display', label: 'Panel layout', type: 'select', default: 'two-column', options: [{ value: 'single', label: 'Single list' }, { value: 'two-column', label: 'Two column' }, { value: 'three-pane', label: 'Three pane' }] },
  { id: 'show-empty-state-hint', section: 'bank-recon', group: 'Display', label: 'Show empty-state hints', type: 'toggle', default: true },
  { id: 'zebra-striping', section: 'bank-recon', group: 'Display', label: 'Zebra-stripe rows', type: 'toggle', default: true },
  { id: 'show-count-badges', section: 'bank-recon', group: 'Display', label: 'Show transaction count badges', type: 'toggle', default: true },

  // ===== Columns (21-42) =====
  { id: 'col-date', section: 'bank-recon', group: 'Columns', label: 'Show date column', type: 'toggle', default: true },
  { id: 'col-cleared-date', section: 'bank-recon', group: 'Columns', label: 'Show cleared-date column', type: 'toggle', default: false },
  { id: 'col-check-number', section: 'bank-recon', group: 'Columns', label: 'Show check number column', type: 'toggle', default: true },
  { id: 'col-reference', section: 'bank-recon', group: 'Columns', label: 'Show reference/ID column', type: 'toggle', default: true },
  { id: 'col-payee', section: 'bank-recon', group: 'Columns', label: 'Show payee column', type: 'toggle', default: true },
  { id: 'col-description', section: 'bank-recon', group: 'Columns', label: 'Show description column', type: 'toggle', default: true },
  { id: 'col-category', section: 'bank-recon', group: 'Columns', label: 'Show category column', type: 'toggle', default: true },
  { id: 'col-deposit', section: 'bank-recon', group: 'Columns', label: 'Show deposit column', type: 'toggle', default: true },
  { id: 'col-withdrawal', section: 'bank-recon', group: 'Columns', label: 'Show withdrawal column', type: 'toggle', default: true },
  { id: 'col-amount-single', section: 'bank-recon', group: 'Columns', label: 'Single signed amount column', description: 'Combine deposit and withdrawal into one signed amount column.', type: 'toggle', default: false },
  { id: 'col-balance', section: 'bank-recon', group: 'Columns', label: 'Show balance column', type: 'toggle', default: true },
  { id: 'col-source', section: 'bank-recon', group: 'Columns', label: 'Show source (feed/manual) column', type: 'toggle', default: false },
  { id: 'col-match-confidence', section: 'bank-recon', group: 'Columns', label: 'Show match confidence column', type: 'toggle', default: false },
  { id: 'col-reconciled-by', section: 'bank-recon', group: 'Columns', label: 'Show reconciled-by user column', type: 'toggle', default: false },
  { id: 'col-attachments', section: 'bank-recon', group: 'Columns', label: 'Show attachments column', type: 'toggle', default: false },
  { id: 'col-tags', section: 'bank-recon', group: 'Columns', label: 'Show tags column', type: 'toggle', default: false },
  { id: 'col-fx-amount', section: 'bank-recon', group: 'Columns', label: 'Show foreign-currency amount column', type: 'toggle', default: false },
  { id: 'col-cleared-checkbox', section: 'bank-recon', group: 'Columns', label: 'Show cleared checkbox column', type: 'toggle', default: true },
  { id: 'frozen-columns', section: 'bank-recon', group: 'Columns', label: 'Frozen leading columns', description: 'Number of leftmost columns to freeze during horizontal scroll.', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'col-order-amount-first', section: 'bank-recon', group: 'Columns', label: 'Put amount columns first', type: 'toggle', default: false },
  { id: 'description-max-chars', section: 'bank-recon', group: 'Columns', label: 'Description truncation length', type: 'number', default: 60, min: 20, max: 200, step: 5 },
  { id: 'col-statement-line', section: 'bank-recon', group: 'Columns', label: 'Show original statement line column', type: 'toggle', default: false },

  // ===== Formatting (43-62) =====
  { id: 'date-format', section: 'bank-recon', group: 'Formatting', label: 'Date format', type: 'select', default: 'MM/DD/YYYY', options: [{ value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' }, { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' }, { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' }, { value: 'MMM D, YYYY', label: 'MMM D, YYYY' }] },
  { id: 'currency-symbol-position', section: 'bank-recon', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($1.00)' }, { value: 'after', label: 'After (1.00$)' }, { value: 'none', label: 'No symbol' }] },
  { id: 'thousands-separator', section: 'bank-recon', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'period', label: 'Period' }, { value: 'space', label: 'Space' }, { value: 'none', label: 'None' }] },
  { id: 'decimal-places', section: 'bank-recon', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'negative-style', section: 'bank-recon', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-1.00' }, { value: 'parens', label: '(1.00)' }, { value: 'red', label: 'Red text' }, { value: 'parens-red', label: 'Red parentheses' }] },
  { id: 'zero-display', section: 'bank-recon', group: 'Formatting', label: 'Zero amount display', type: 'select', default: 'zero', options: [{ value: 'zero', label: '0.00' }, { value: 'dash', label: '—' }, { value: 'blank', label: 'Blank' }] },
  { id: 'currency-code', section: 'bank-recon', group: 'Formatting', label: 'Show currency code', description: 'Append the ISO code (e.g. USD) to amounts.', type: 'toggle', default: false },
  { id: 'date-relative', section: 'bank-recon', group: 'Formatting', label: 'Show relative dates', description: 'Display "Yesterday", "3 days ago" for recent transactions.', type: 'toggle', default: false },
  { id: 'uppercase-payees', section: 'bank-recon', group: 'Formatting', label: 'Uppercase payee names', type: 'toggle', default: false },
  { id: 'trim-bank-prefixes', section: 'bank-recon', group: 'Formatting', label: 'Trim bank descriptor prefixes', description: 'Strip noise like "POS DEBIT" from imported descriptions.', type: 'toggle', default: true },
  { id: 'amount-alignment', section: 'bank-recon', group: 'Formatting', label: 'Amount column alignment', type: 'select', default: 'right', options: [{ value: 'right', label: 'Right' }, { value: 'left', label: 'Left' }, { value: 'decimal', label: 'Decimal-aligned' }] },
  { id: 'check-number-padding', section: 'bank-recon', group: 'Formatting', label: 'Check number zero-padding width', type: 'number', default: 0, min: 0, max: 10, step: 1 },
  { id: 'thousands-in-summary', section: 'bank-recon', group: 'Formatting', label: 'Abbreviate large summary totals', description: 'Show 1.2K / 3.4M in summary tiles.', type: 'toggle', default: false },
  { id: 'fx-rate-precision', section: 'bank-recon', group: 'Formatting', label: 'FX rate precision', type: 'number', default: 6, min: 2, max: 10, step: 1 },
  { id: 'description-case', section: 'bank-recon', group: 'Formatting', label: 'Description text case', type: 'select', default: 'original', options: [{ value: 'original', label: 'Original' }, { value: 'title', label: 'Title Case' }, { value: 'sentence', label: 'Sentence case' }] },
  { id: 'show-day-of-week', section: 'bank-recon', group: 'Formatting', label: 'Show day of week with dates', type: 'toggle', default: false },
  { id: 'symbol-override', section: 'bank-recon', group: 'Formatting', label: 'Custom currency symbol', description: 'Override the displayed currency symbol.', type: 'text', default: '$' },
  { id: 'group-date-headers', section: 'bank-recon', group: 'Formatting', label: 'Insert date group headers', description: 'Add subheaders between transactions of different days.', type: 'toggle', default: false },
  { id: 'reference-format', section: 'bank-recon', group: 'Formatting', label: 'Reference number prefix', type: 'text', default: '' },
  { id: 'pad-amounts-to-width', section: 'bank-recon', group: 'Formatting', label: 'Pad amounts to fixed width', type: 'toggle', default: true },

  // ===== Defaults (63-82) =====
  { id: 'default-account', section: 'bank-recon', group: 'Defaults', label: 'Default account to reconcile', type: 'text', default: '' },
  { id: 'default-statement-day', section: 'bank-recon', group: 'Defaults', label: 'Default statement closing day', type: 'number', default: 30, min: 1, max: 31, step: 1 },
  { id: 'default-opening-from-prior', section: 'bank-recon', group: 'Defaults', label: 'Prefill opening balance from prior reconciliation', type: 'toggle', default: true },
  { id: 'default-date-range', section: 'bank-recon', group: 'Defaults', label: 'Default date range', type: 'select', default: 'statement-period', options: [{ value: 'statement-period', label: 'Statement period' }, { value: 'last-30', label: 'Last 30 days' }, { value: 'this-month', label: 'This month' }, { value: 'all', label: 'All unreconciled' }] },
  { id: 'default-tolerance', section: 'bank-recon', group: 'Defaults', label: 'Default reconciliation tolerance', description: 'Difference within this amount is treated as reconciled.', type: 'number', default: 0, min: 0, max: 100, step: 0.01 },
  { id: 'default-currency', section: 'bank-recon', group: 'Defaults', label: 'Default reconciliation currency', type: 'text', default: 'USD' },
  { id: 'default-clear-on-import', section: 'bank-recon', group: 'Defaults', label: 'Mark imported feed items cleared by default', type: 'toggle', default: false },
  { id: 'default-statement-format', section: 'bank-recon', group: 'Defaults', label: 'Default statement import format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'ofx', label: 'OFX' }, { value: 'qfx', label: 'QFX' }, { value: 'qbo', label: 'QBO' }, { value: 'pdf', label: 'PDF' }] },
  { id: 'default-adjustment-category', section: 'bank-recon', group: 'Defaults', label: 'Default adjustment category', type: 'text', default: 'Bank Adjustments' },
  { id: 'default-bank-fee-category', section: 'bank-recon', group: 'Defaults', label: 'Default bank fee category', type: 'text', default: 'Bank Fees' },
  { id: 'default-interest-category', section: 'bank-recon', group: 'Defaults', label: 'Default interest income category', type: 'text', default: 'Interest Income' },
  { id: 'default-new-txn-cleared', section: 'bank-recon', group: 'Defaults', label: 'New manual transactions cleared by default', type: 'toggle', default: false },
  { id: 'default-statement-end-time', section: 'bank-recon', group: 'Defaults', label: 'Statement period offset (days back)', type: 'number', default: 0, min: 0, max: 31, step: 1 },
  { id: 'default-reconcile-frequency', section: 'bank-recon', group: 'Defaults', label: 'Reconciliation frequency', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'default-rounding-account', section: 'bank-recon', group: 'Defaults', label: 'Default rounding difference account', type: 'text', default: 'Rounding' },
  { id: 'default-show-only-uncleared', section: 'bank-recon', group: 'Defaults', label: 'Start with only uncleared shown', type: 'toggle', default: false },
  { id: 'default-include-pending', section: 'bank-recon', group: 'Defaults', label: 'Include pending transactions by default', type: 'toggle', default: false },
  { id: 'default-fee-amount', section: 'bank-recon', group: 'Defaults', label: 'Default monthly service fee', type: 'number', default: 0, min: 0, max: 1000, step: 0.5 },
  { id: 'default-auto-create-adjustment', section: 'bank-recon', group: 'Defaults', label: 'Auto-create adjustment entry on finish', type: 'toggle', default: false },
  { id: 'default-statement-balance-required', section: 'bank-recon', group: 'Defaults', label: 'Require ending statement balance entry', type: 'toggle', default: true },

  // ===== Matching (83-104) =====
  { id: 'auto-match-enabled', section: 'bank-recon', group: 'Matching', label: 'Enable automatic matching', type: 'toggle', default: true },
  { id: 'match-amount-tolerance', section: 'bank-recon', group: 'Matching', label: 'Amount match tolerance', type: 'number', default: 0, min: 0, max: 10, step: 0.01 },
  { id: 'match-date-window', section: 'bank-recon', group: 'Matching', label: 'Date match window (days)', type: 'number', default: 5, min: 0, max: 30, step: 1 },
  { id: 'match-on-check-number', section: 'bank-recon', group: 'Matching', label: 'Match on check number', type: 'toggle', default: true },
  { id: 'match-on-reference', section: 'bank-recon', group: 'Matching', label: 'Match on reference/ID', type: 'toggle', default: true },
  { id: 'match-fuzzy-payee', section: 'bank-recon', group: 'Matching', label: 'Fuzzy payee matching', type: 'toggle', default: true },
  { id: 'match-min-confidence', section: 'bank-recon', group: 'Matching', label: 'Minimum auto-match confidence (%)', type: 'number', default: 85, min: 50, max: 100, step: 5 },
  { id: 'match-auto-accept-threshold', section: 'bank-recon', group: 'Matching', label: 'Auto-accept confidence threshold (%)', type: 'number', default: 95, min: 70, max: 100, step: 1 },
  { id: 'match-allow-many-to-one', section: 'bank-recon', group: 'Matching', label: 'Allow many-to-one matches', description: 'Match multiple book entries to a single statement line.', type: 'toggle', default: true },
  { id: 'match-allow-one-to-many', section: 'bank-recon', group: 'Matching', label: 'Allow one-to-many matches', type: 'toggle', default: true },
  { id: 'match-suggest-split', section: 'bank-recon', group: 'Matching', label: 'Suggest split matches', type: 'toggle', default: true },
  { id: 'match-ignore-sign', section: 'bank-recon', group: 'Matching', label: 'Ignore sign when matching', type: 'toggle', default: false },
  { id: 'match-learn-rules', section: 'bank-recon', group: 'Matching', label: 'Learn matching rules from confirmations', type: 'toggle', default: true },
  { id: 'match-strategy', section: 'bank-recon', group: 'Matching', label: 'Primary match strategy', type: 'select', default: 'balanced', options: [{ value: 'strict', label: 'Strict (exact)' }, { value: 'balanced', label: 'Balanced' }, { value: 'aggressive', label: 'Aggressive (fuzzy)' }] },
  { id: 'match-confirm-each', section: 'bank-recon', group: 'Matching', label: 'Require confirmation for each match', type: 'toggle', default: false },
  { id: 'match-on-amount-only', section: 'bank-recon', group: 'Matching', label: 'Allow amount-only matches', type: 'toggle', default: false },
  { id: 'match-payee-min-similarity', section: 'bank-recon', group: 'Matching', label: 'Payee similarity threshold (%)', type: 'number', default: 70, min: 40, max: 100, step: 5 },
  { id: 'match-highlight-suggestions', section: 'bank-recon', group: 'Matching', label: 'Highlight suggested matches', type: 'toggle', default: true },
  { id: 'match-auto-unmatch-on-edit', section: 'bank-recon', group: 'Matching', label: 'Auto-unmatch when a matched item is edited', type: 'toggle', default: true },
  { id: 'match-prefer-recent', section: 'bank-recon', group: 'Matching', label: 'Prefer most recent candidate on tie', type: 'toggle', default: true },
  { id: 'match-rule-priority', section: 'bank-recon', group: 'Matching', label: 'Rule application order', type: 'select', default: 'specific-first', options: [{ value: 'specific-first', label: 'Most specific first' }, { value: 'newest-first', label: 'Newest rules first' }, { value: 'manual', label: 'Manual order' }] },
  { id: 'match-cross-account', section: 'bank-recon', group: 'Matching', label: 'Detect cross-account transfers', type: 'toggle', default: true },

  // ===== Sorting & Filtering (105-122) =====
  { id: 'default-sort-field', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'date', options: [{ value: 'date', label: 'Date' }, { value: 'amount', label: 'Amount' }, { value: 'payee', label: 'Payee' }, { value: 'check', label: 'Check number' }, { value: 'status', label: 'Cleared status' }] },
  { id: 'default-sort-direction', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'group-by', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Group transactions by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'date', label: 'Date' }, { value: 'type', label: 'Deposit/Withdrawal' }, { value: 'category', label: 'Category' }, { value: 'status', label: 'Status' }] },
  { id: 'filter-hide-cleared', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Hide already-cleared by default', type: 'toggle', default: false },
  { id: 'filter-hide-reconciled', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Hide reconciled by default', type: 'toggle', default: true },
  { id: 'filter-min-amount', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Default minimum amount filter', type: 'number', default: 0, min: 0, max: 100000, step: 1 },
  { id: 'filter-remember-last', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Remember last filter set', type: 'toggle', default: true },
  { id: 'quick-filter-bar', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Show quick filter chips', type: 'toggle', default: true },
  { id: 'filter-default-type', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Default transaction type filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'deposits', label: 'Deposits only' }, { value: 'withdrawals', label: 'Withdrawals only' }] },
  { id: 'search-includes-memo', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Search includes memo field', type: 'toggle', default: true },
  { id: 'search-includes-category', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Search includes category', type: 'toggle', default: true },
  { id: 'secondary-sort', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'amount', options: [{ value: 'amount', label: 'Amount' }, { value: 'payee', label: 'Payee' }, { value: 'check', label: 'Check number' }, { value: 'none', label: 'None' }] },
  { id: 'filter-only-feed-items', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Show only bank feed items by default', type: 'toggle', default: false },
  { id: 'filter-flagged-first', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Float flagged items to top', type: 'toggle', default: true },
  { id: 'sort-uncleared-first', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Sort uncleared items first', type: 'toggle', default: true },
  { id: 'filter-saved-views', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Enable saved filter views', type: 'toggle', default: true },
  { id: 'filter-case-sensitive', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'search-debounce-ms', section: 'bank-recon', group: 'Sorting & Filtering', label: 'Search debounce (ms)', type: 'number', default: 250, min: 0, max: 2000, step: 50 },

  // ===== Behavior (123-144) =====
  { id: 'auto-clear-on-check', section: 'bank-recon', group: 'Behavior', label: 'Single-click to clear a transaction', type: 'toggle', default: true },
  { id: 'confirm-before-finish', section: 'bank-recon', group: 'Behavior', label: 'Confirm before finishing reconciliation', type: 'toggle', default: true },
  { id: 'allow-finish-with-difference', section: 'bank-recon', group: 'Behavior', label: 'Allow finishing with non-zero difference', type: 'toggle', default: false },
  { id: 'auto-save-progress', section: 'bank-recon', group: 'Behavior', label: 'Auto-save reconciliation progress', type: 'toggle', default: true },
  { id: 'auto-save-interval', section: 'bank-recon', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 600, step: 5 },
  { id: 'lock-after-finish', section: 'bank-recon', group: 'Behavior', label: 'Lock reconciled period after finishing', type: 'toggle', default: true },
  { id: 'warn-unlock-period', section: 'bank-recon', group: 'Behavior', label: 'Warn when unlocking a reconciled period', type: 'toggle', default: true },
  { id: 'keep-running-after-finish', section: 'bank-recon', group: 'Behavior', label: 'Stay on screen after finishing', type: 'toggle', default: false },
  { id: 'auto-detect-duplicates', section: 'bank-recon', group: 'Behavior', label: 'Auto-detect duplicate transactions', type: 'toggle', default: true },
  { id: 'auto-create-missing-from-feed', section: 'bank-recon', group: 'Behavior', label: 'Auto-create book entries for unmatched feed items', type: 'toggle', default: false },
  { id: 'prompt-create-fee', section: 'bank-recon', group: 'Behavior', label: 'Prompt to record service charge', type: 'toggle', default: true },
  { id: 'prompt-create-interest', section: 'bank-recon', group: 'Behavior', label: 'Prompt to record interest earned', type: 'toggle', default: true },
  { id: 'scroll-to-next-after-clear', section: 'bank-recon', group: 'Behavior', label: 'Scroll to next item after clearing', type: 'toggle', default: true },
  { id: 'undo-stack-size', section: 'bank-recon', group: 'Behavior', label: 'Undo history depth', type: 'number', default: 50, min: 0, max: 500, step: 10 },
  { id: 'block-future-dated', section: 'bank-recon', group: 'Behavior', label: 'Block clearing future-dated items', type: 'toggle', default: false },
  { id: 'warn-stale-uncleared', section: 'bank-recon', group: 'Behavior', label: 'Warn on stale uncleared items', description: 'Flag uncleared items older than the threshold.', type: 'toggle', default: true },
  { id: 'stale-threshold-days', section: 'bank-recon', group: 'Behavior', label: 'Stale uncleared threshold (days)', type: 'number', default: 90, min: 7, max: 730, step: 1 },
  { id: 'auto-reconcile-feed', section: 'bank-recon', group: 'Behavior', label: 'Auto-reconcile high-confidence feed matches', type: 'toggle', default: false },
  { id: 'recompute-balance-live', section: 'bank-recon', group: 'Behavior', label: 'Recompute difference live while clearing', type: 'toggle', default: true },
  { id: 'confirm-bulk-clear', section: 'bank-recon', group: 'Behavior', label: 'Confirm before bulk-clearing', type: 'toggle', default: true },
  { id: 'keep-selection-on-refresh', section: 'bank-recon', group: 'Behavior', label: 'Keep selection after list refresh', type: 'toggle', default: true },
  { id: 'auto-backup-on-finish', section: 'bank-recon', group: 'Behavior', label: 'Trigger backup after finishing', type: 'toggle', default: true },

  // ===== Notifications (145-160) =====
  { id: 'notify-recon-complete', section: 'bank-recon', group: 'Notifications', label: 'Notify when reconciliation completes', type: 'toggle', default: true },
  { id: 'notify-difference-remains', section: 'bank-recon', group: 'Notifications', label: 'Alert when a difference remains at session end', type: 'toggle', default: true },
  { id: 'notify-new-feed-items', section: 'bank-recon', group: 'Notifications', label: 'Notify on new bank feed items', type: 'toggle', default: true },
  { id: 'notify-feed-disconnected', section: 'bank-recon', group: 'Notifications', label: 'Alert when bank feed disconnects', type: 'toggle', default: true },
  { id: 'notify-overdue-recon', section: 'bank-recon', group: 'Notifications', label: 'Remind when reconciliation is overdue', type: 'toggle', default: true },
  { id: 'overdue-grace-days', section: 'bank-recon', group: 'Notifications', label: 'Overdue grace period (days)', type: 'number', default: 5, min: 0, max: 60, step: 1 },
  { id: 'notify-duplicate-detected', section: 'bank-recon', group: 'Notifications', label: 'Alert on possible duplicates', type: 'toggle', default: true },
  { id: 'notify-large-uncleared', section: 'bank-recon', group: 'Notifications', label: 'Alert on large uncleared amounts', type: 'toggle', default: false },
  { id: 'large-uncleared-threshold', section: 'bank-recon', group: 'Notifications', label: 'Large uncleared alert threshold', type: 'number', default: 5000, min: 0, max: 1000000, step: 100 },
  { id: 'notify-channel', section: 'bank-recon', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app only' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'In-app and email' }, { value: 'none', label: 'None' }] },
  { id: 'notify-summary-email', section: 'bank-recon', group: 'Notifications', label: 'Send reconciliation summary email', type: 'toggle', default: false },
  { id: 'notify-stale-items', section: 'bank-recon', group: 'Notifications', label: 'Notify about stale uncleared items', type: 'toggle', default: true },
  { id: 'notify-negative-balance', section: 'bank-recon', group: 'Notifications', label: 'Alert if cleared balance goes negative', type: 'toggle', default: true },
  { id: 'notify-sound', section: 'bank-recon', group: 'Notifications', label: 'Play sound on completion', type: 'toggle', default: false },
  { id: 'notify-digest-frequency', section: 'bank-recon', group: 'Notifications', label: 'Reminder digest frequency', type: 'select', default: 'weekly', options: [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'off', label: 'Off' }] },
  { id: 'notify-recipient', section: 'bank-recon', group: 'Notifications', label: 'Notification recipient email', type: 'text', default: '' },

  // ===== Export (161-178) =====
  { id: 'export-format', section: 'bank-recon', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [{ value: 'pdf', label: 'PDF' }, { value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'json', label: 'JSON' }] },
  { id: 'export-include-cleared', section: 'bank-recon', group: 'Export', label: 'Include cleared items in export', type: 'toggle', default: true },
  { id: 'export-include-uncleared', section: 'bank-recon', group: 'Export', label: 'Include uncleared items in export', type: 'toggle', default: true },
  { id: 'export-include-summary', section: 'bank-recon', group: 'Export', label: 'Include reconciliation summary page', type: 'toggle', default: true },
  { id: 'export-include-signoff', section: 'bank-recon', group: 'Export', label: 'Include sign-off / approval block', type: 'toggle', default: true },
  { id: 'export-company-header', section: 'bank-recon', group: 'Export', label: 'Include company header/logo', type: 'toggle', default: true },
  { id: 'export-page-orientation', section: 'bank-recon', group: 'Export', label: 'PDF page orientation', type: 'select', default: 'portrait', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'export-paper-size', section: 'bank-recon', group: 'Export', label: 'PDF paper size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'export-filename-pattern', section: 'bank-recon', group: 'Export', label: 'Export filename pattern', description: 'Tokens: {account} {period} {date}.', type: 'text', default: 'Recon_{account}_{period}' },
  { id: 'export-include-attachments', section: 'bank-recon', group: 'Export', label: 'Bundle attachments into export', type: 'toggle', default: false },
  { id: 'export-csv-delimiter', section: 'bank-recon', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }, { value: 'pipe', label: 'Pipe' }] },
  { id: 'export-date-format', section: 'bank-recon', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'YYYY-MM-DD' }, { value: 'us', label: 'MM/DD/YYYY' }, { value: 'eu', label: 'DD/MM/YYYY' }] },
  { id: 'export-open-after', section: 'bank-recon', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'export-include-running-balance', section: 'bank-recon', group: 'Export', label: 'Include running balance column in export', type: 'toggle', default: false },
  { id: 'export-default-folder', section: 'bank-recon', group: 'Export', label: 'Default export folder', type: 'text', default: '' },
  { id: 'export-watermark-draft', section: 'bank-recon', group: 'Export', label: 'Watermark drafts as "DRAFT"', type: 'toggle', default: true },
  { id: 'export-include-difference-detail', section: 'bank-recon', group: 'Export', label: 'Include difference breakdown', type: 'toggle', default: true },
  { id: 'export-fit-to-page', section: 'bank-recon', group: 'Export', label: 'Fit table to page width', type: 'toggle', default: true },

  // ===== Colors & Theme (179-188) =====
  { id: 'color-cleared', section: 'bank-recon', group: 'Colors & Theme', label: 'Cleared item color', type: 'color', default: '#22c55e' },
  { id: 'color-uncleared', section: 'bank-recon', group: 'Colors & Theme', label: 'Uncleared item color', type: 'color', default: '#f59e0b' },
  { id: 'color-matched', section: 'bank-recon', group: 'Colors & Theme', label: 'Matched row highlight', type: 'color', default: '#3b82f6' },
  { id: 'color-difference', section: 'bank-recon', group: 'Colors & Theme', label: 'Difference banner color', type: 'color', default: '#ef4444' },
  { id: 'color-difference-zero', section: 'bank-recon', group: 'Colors & Theme', label: 'Balanced (zero difference) color', type: 'color', default: '#10b981' },
  { id: 'color-deposit', section: 'bank-recon', group: 'Colors & Theme', label: 'Deposit amount color', type: 'color', default: '#16a34a' },
  { id: 'color-withdrawal', section: 'bank-recon', group: 'Colors & Theme', label: 'Withdrawal amount color', type: 'color', default: '#dc2626' },
  { id: 'color-flagged', section: 'bank-recon', group: 'Colors & Theme', label: 'Flagged item color', type: 'color', default: '#a855f7' },
  { id: 'color-duplicate', section: 'bank-recon', group: 'Colors & Theme', label: 'Duplicate warning color', type: 'color', default: '#eab308' },
  { id: 'color-stale', section: 'bank-recon', group: 'Colors & Theme', label: 'Stale uncleared color', type: 'color', default: '#f97316' },

  // ===== Accessibility (189-195) =====
  { id: 'a11y-high-contrast', section: 'bank-recon', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'a11y-color-blind-safe', section: 'bank-recon', group: 'Accessibility', label: 'Color-blind safe palette', type: 'toggle', default: false },
  { id: 'a11y-status-icons-not-color', section: 'bank-recon', group: 'Accessibility', label: 'Use icons (not just color) for status', type: 'toggle', default: true },
  { id: 'a11y-font-scale', section: 'bank-recon', group: 'Accessibility', label: 'Font scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'a11y-reduce-motion', section: 'bank-recon', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'a11y-focus-ring', section: 'bank-recon', group: 'Accessibility', label: 'Always show keyboard focus ring', type: 'toggle', default: true },
  { id: 'a11y-screen-reader-summaries', section: 'bank-recon', group: 'Accessibility', label: 'Announce difference changes to screen readers', type: 'toggle', default: true },

  // ===== Shortcuts (196-200) =====
  { id: 'shortcut-clear-key', section: 'bank-recon', group: 'Shortcuts', label: 'Clear/uncheck transaction key', type: 'text', default: 'Space' },
  { id: 'shortcut-next-key', section: 'bank-recon', group: 'Shortcuts', label: 'Move to next transaction key', type: 'text', default: 'ArrowDown' },
  { id: 'shortcut-finish-key', section: 'bank-recon', group: 'Shortcuts', label: 'Finish reconciliation shortcut', type: 'text', default: 'Ctrl+Enter' },
  { id: 'shortcut-enable-keyboard-nav', section: 'bank-recon', group: 'Shortcuts', label: 'Enable keyboard navigation', type: 'toggle', default: true },
  { id: 'shortcut-vim-mode', section: 'bank-recon', group: 'Shortcuts', label: 'Vim-style j/k navigation', type: 'toggle', default: false },
];
