import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-22) =====
  { id: 'bills-default-view', section: 'bills', group: 'Display', label: 'Default view', description: 'How bills open by default', type: 'select', default: 'list', options: [{ value: 'list', label: 'List' }, { value: 'cards', label: 'Cards' }, { value: 'calendar', label: 'Calendar' }, { value: 'kanban', label: 'Kanban by status' }] },
  { id: 'bills-rows-per-page', section: 'bills', group: 'Display', label: 'Rows per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'bills-compact-rows', section: 'bills', group: 'Display', label: 'Compact row height', description: 'Tighter spacing in the bills table', type: 'toggle', default: false },
  { id: 'bills-show-vendor-logos', section: 'bills', group: 'Display', label: 'Show vendor logos', type: 'toggle', default: true },
  { id: 'bills-zebra-striping', section: 'bills', group: 'Display', label: 'Alternating row shading', type: 'toggle', default: true },
  { id: 'bills-show-running-total', section: 'bills', group: 'Display', label: 'Show running total footer', type: 'toggle', default: true },
  { id: 'bills-sticky-header', section: 'bills', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'bills-group-by', section: 'bills', group: 'Display', label: 'Group bills by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'vendor', label: 'Vendor' }, { value: 'status', label: 'Status' }, { value: 'due_date', label: 'Due date' }, { value: 'category', label: 'Category' }] },
  { id: 'bills-show-aging-bar', section: 'bills', group: 'Display', label: 'Show AP aging summary bar', type: 'toggle', default: true },
  { id: 'bills-overdue-highlight', section: 'bills', group: 'Display', label: 'Highlight overdue rows', type: 'toggle', default: true },
  { id: 'bills-density', section: 'bills', group: 'Display', label: 'Information density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'bills-show-attachment-icon', section: 'bills', group: 'Display', label: 'Show attachment indicator', type: 'toggle', default: true },
  { id: 'bills-show-notes-preview', section: 'bills', group: 'Display', label: 'Show notes preview on hover', type: 'toggle', default: false },
  { id: 'bills-show-balance-due', section: 'bills', group: 'Display', label: 'Show remaining balance column', type: 'toggle', default: true },
  { id: 'bills-truncate-vendor', section: 'bills', group: 'Display', label: 'Truncate long vendor names', type: 'toggle', default: true },
  { id: 'bills-vendor-name-max', section: 'bills', group: 'Display', label: 'Vendor name max characters', type: 'number', default: 28, min: 10, max: 80, step: 1 },
  { id: 'bills-show-empty-state-tips', section: 'bills', group: 'Display', label: 'Show tips on empty list', type: 'toggle', default: true },
  { id: 'bills-show-quick-stats', section: 'bills', group: 'Display', label: 'Show quick stat tiles above table', type: 'toggle', default: true },
  { id: 'bills-calendar-week-start', section: 'bills', group: 'Display', label: 'Calendar week starts on', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },
  { id: 'bills-show-line-item-count', section: 'bills', group: 'Display', label: 'Show line-item count badge', type: 'toggle', default: false },
  { id: 'bills-show-approval-avatars', section: 'bills', group: 'Display', label: 'Show approver avatars', type: 'toggle', default: true },
  { id: 'bills-row-click-action', section: 'bills', group: 'Display', label: 'Row click opens', type: 'select', default: 'detail', options: [{ value: 'detail', label: 'Detail panel' }, { value: 'edit', label: 'Edit form' }, { value: 'preview', label: 'Quick preview' }] },

  // ===== Columns (23-44) =====
  { id: 'bills-col-bill-number', section: 'bills', group: 'Columns', label: 'Show Bill # column', type: 'toggle', default: true },
  { id: 'bills-col-vendor', section: 'bills', group: 'Columns', label: 'Show Vendor column', type: 'toggle', default: true },
  { id: 'bills-col-bill-date', section: 'bills', group: 'Columns', label: 'Show Bill Date column', type: 'toggle', default: true },
  { id: 'bills-col-due-date', section: 'bills', group: 'Columns', label: 'Show Due Date column', type: 'toggle', default: true },
  { id: 'bills-col-amount', section: 'bills', group: 'Columns', label: 'Show Amount column', type: 'toggle', default: true },
  { id: 'bills-col-status', section: 'bills', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'bills-col-category', section: 'bills', group: 'Columns', label: 'Show Category column', type: 'toggle', default: true },
  { id: 'bills-col-terms', section: 'bills', group: 'Columns', label: 'Show Payment Terms column', type: 'toggle', default: false },
  { id: 'bills-col-po-number', section: 'bills', group: 'Columns', label: 'Show PO Number column', type: 'toggle', default: false },
  { id: 'bills-col-approval', section: 'bills', group: 'Columns', label: 'Show Approval column', type: 'toggle', default: true },
  { id: 'bills-col-paid-amount', section: 'bills', group: 'Columns', label: 'Show Paid Amount column', type: 'toggle', default: false },
  { id: 'bills-col-balance', section: 'bills', group: 'Columns', label: 'Show Balance column', type: 'toggle', default: true },
  { id: 'bills-col-days-until-due', section: 'bills', group: 'Columns', label: 'Show Days Until Due column', type: 'toggle', default: true },
  { id: 'bills-col-account', section: 'bills', group: 'Columns', label: 'Show GL Account column', type: 'toggle', default: false },
  { id: 'bills-col-memo', section: 'bills', group: 'Columns', label: 'Show Memo column', type: 'toggle', default: false },
  { id: 'bills-col-created-by', section: 'bills', group: 'Columns', label: 'Show Created By column', type: 'toggle', default: false },
  { id: 'bills-col-currency', section: 'bills', group: 'Columns', label: 'Show Currency column', type: 'toggle', default: false },
  { id: 'bills-col-tax', section: 'bills', group: 'Columns', label: 'Show Tax column', type: 'toggle', default: false },
  { id: 'bills-col-discount', section: 'bills', group: 'Columns', label: 'Show Early-Pay Discount column', type: 'toggle', default: false },
  { id: 'bills-col-reference', section: 'bills', group: 'Columns', label: 'Show Vendor Reference column', type: 'toggle', default: false },
  { id: 'bills-frozen-columns', section: 'bills', group: 'Columns', label: 'Number of frozen left columns', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'bills-col-order', section: 'bills', group: 'Columns', label: 'Custom column order (CSV)', description: 'Comma-separated column keys', type: 'text', default: 'number,vendor,date,due,amount,status' },

  // ===== Formatting (45-66) =====
  { id: 'bills-currency-symbol', section: 'bills', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'bills-currency-position', section: 'bills', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'bills-decimal-places', section: 'bills', group: 'Formatting', label: 'Amount decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'bills-thousands-separator', section: 'bills', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'period', label: 'Period' }, { value: 'space', label: 'Space' }, { value: 'none', label: 'None' }] },
  { id: 'bills-negative-style', section: 'bills', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-100.00' }, { value: 'parens', label: '(100.00)' }, { value: 'red', label: 'Red text' }] },
  { id: 'bills-date-format', section: 'bills', group: 'Formatting', label: 'Date format', type: 'select', default: 'mm-dd-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }, { value: 'medium', label: 'Mon DD, YYYY' }] },
  { id: 'bills-relative-dates', section: 'bills', group: 'Formatting', label: 'Show relative due dates', description: 'e.g. "in 3 days"', type: 'toggle', default: true },
  { id: 'bills-zero-amount-dash', section: 'bills', group: 'Formatting', label: 'Show zero amounts as dash', type: 'toggle', default: false },
  { id: 'bills-round-display', section: 'bills', group: 'Formatting', label: 'Round displayed amounts to whole', type: 'toggle', default: false },
  { id: 'bills-default-currency', section: 'bills', group: 'Formatting', label: 'Default currency code', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' }] },
  { id: 'bills-number-prefix', section: 'bills', group: 'Formatting', label: 'Bill number prefix', type: 'text', default: 'BILL-' },
  { id: 'bills-number-padding', section: 'bills', group: 'Formatting', label: 'Bill number digit padding', type: 'number', default: 5, min: 1, max: 10, step: 1 },
  { id: 'bills-uppercase-vendor', section: 'bills', group: 'Formatting', label: 'Display vendor names uppercase', type: 'toggle', default: false },
  { id: 'bills-amount-color-coding', section: 'bills', group: 'Formatting', label: 'Color-code amounts by size', type: 'toggle', default: false },
  { id: 'bills-percent-decimals', section: 'bills', group: 'Formatting', label: 'Discount percent decimals', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'bills-show-currency-code', section: 'bills', group: 'Formatting', label: 'Append currency code to amounts', type: 'toggle', default: false },
  { id: 'bills-status-label-style', section: 'bills', group: 'Formatting', label: 'Status label style', type: 'select', default: 'badge', options: [{ value: 'badge', label: 'Colored badge' }, { value: 'text', label: 'Plain text' }, { value: 'dot', label: 'Dot + text' }] },
  { id: 'bills-due-soon-threshold', section: 'bills', group: 'Formatting', label: 'Due soon threshold (days)', type: 'number', default: 7, min: 1, max: 60, step: 1 },
  { id: 'bills-time-display', section: 'bills', group: 'Formatting', label: 'Time format', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'bills-memo-line-template', section: 'bills', group: 'Formatting', label: 'Default memo template', type: 'text', default: 'Bill from {vendor}' },
  { id: 'bills-fiscal-year-start', section: 'bills', group: 'Formatting', label: 'Fiscal year start month', type: 'number', default: 1, min: 1, max: 12, step: 1 },

  // ===== Defaults (67-88) =====
  { id: 'bills-default-terms', section: 'bills', group: 'Defaults', label: 'Default payment terms', type: 'select', default: 'net30', options: [{ value: 'due_on_receipt', label: 'Due on receipt' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net45', label: 'Net 45' }, { value: 'net60', label: 'Net 60' }] },
  { id: 'bills-default-category', section: 'bills', group: 'Defaults', label: 'Default expense category', type: 'text', default: 'Uncategorized' },
  { id: 'bills-default-account', section: 'bills', group: 'Defaults', label: 'Default AP GL account', type: 'text', default: '2000 Accounts Payable' },
  { id: 'bills-default-tax-rate', section: 'bills', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 30, step: 0.25 },
  { id: 'bills-default-status', section: 'bills', group: 'Defaults', label: 'Default status for new bills', type: 'select', default: 'draft', options: [{ value: 'draft', label: 'Draft' }, { value: 'pending', label: 'Pending approval' }, { value: 'open', label: 'Open' }] },
  { id: 'bills-prefill-bill-date-today', section: 'bills', group: 'Defaults', label: 'Prefill bill date with today', type: 'toggle', default: true },
  { id: 'bills-auto-bill-number', section: 'bills', group: 'Defaults', label: 'Auto-generate bill numbers', type: 'toggle', default: true },
  { id: 'bills-default-currency-from-vendor', section: 'bills', group: 'Defaults', label: 'Inherit currency from vendor', type: 'toggle', default: true },
  { id: 'bills-default-due-from-terms', section: 'bills', group: 'Defaults', label: 'Calculate due date from terms', type: 'toggle', default: true },
  { id: 'bills-default-line-count', section: 'bills', group: 'Defaults', label: 'Default blank line items', type: 'number', default: 1, min: 0, max: 10, step: 1 },
  { id: 'bills-copy-vendor-defaults', section: 'bills', group: 'Defaults', label: 'Copy vendor default terms/category', type: 'toggle', default: true },
  { id: 'bills-default-tax-inclusive', section: 'bills', group: 'Defaults', label: 'Amounts tax-inclusive by default', type: 'toggle', default: false },
  { id: 'bills-default-approval-required', section: 'bills', group: 'Defaults', label: 'Require approval by default', type: 'toggle', default: false },
  { id: 'bills-approval-threshold', section: 'bills', group: 'Defaults', label: 'Approval required above amount', type: 'number', default: 1000, min: 0, max: 1000000, step: 100 },
  { id: 'bills-default-memo', section: 'bills', group: 'Defaults', label: 'Default memo text', type: 'text', default: '' },
  { id: 'bills-default-attachment-required', section: 'bills', group: 'Defaults', label: 'Require attachment by default', type: 'toggle', default: false },
  { id: 'bills-default-recurring', section: 'bills', group: 'Defaults', label: 'Mark new bills recurring by default', type: 'toggle', default: false },
  { id: 'bills-default-recurring-interval', section: 'bills', group: 'Defaults', label: 'Default recurring interval', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annually', label: 'Annually' }] },
  { id: 'bills-default-payment-method', section: 'bills', group: 'Defaults', label: 'Default payment method', type: 'select', default: 'ach', options: [{ value: 'ach', label: 'ACH' }, { value: 'check', label: 'Check' }, { value: 'wire', label: 'Wire' }, { value: 'card', label: 'Card' }, { value: 'cash', label: 'Cash' }] },
  { id: 'bills-default-bank-account', section: 'bills', group: 'Defaults', label: 'Default pay-from bank account', type: 'text', default: 'Operating Checking' },
  { id: 'bills-default-discount-days', section: 'bills', group: 'Defaults', label: 'Default early-pay discount days', type: 'number', default: 10, min: 0, max: 60, step: 1 },
  { id: 'bills-default-discount-pct', section: 'bills', group: 'Defaults', label: 'Default early-pay discount (%)', type: 'number', default: 2, min: 0, max: 20, step: 0.5 },

  // ===== Sorting & Filtering (89-108) =====
  { id: 'bills-default-sort', section: 'bills', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'due_date', options: [{ value: 'due_date', label: 'Due date' }, { value: 'bill_date', label: 'Bill date' }, { value: 'amount', label: 'Amount' }, { value: 'vendor', label: 'Vendor' }, { value: 'status', label: 'Status' }] },
  { id: 'bills-default-sort-dir', section: 'bills', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'bills-default-status-filter', section: 'bills', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'open', options: [{ value: 'all', label: 'All' }, { value: 'open', label: 'Open' }, { value: 'overdue', label: 'Overdue' }, { value: 'paid', label: 'Paid' }, { value: 'draft', label: 'Draft' }] },
  { id: 'bills-hide-paid', section: 'bills', group: 'Sorting & Filtering', label: 'Hide paid bills by default', type: 'toggle', default: false },
  { id: 'bills-hide-void', section: 'bills', group: 'Sorting & Filtering', label: 'Hide void bills by default', type: 'toggle', default: true },
  { id: 'bills-remember-filters', section: 'bills', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'bills-default-date-range', section: 'bills', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'this_quarter', options: [{ value: 'this_month', label: 'This month' }, { value: 'this_quarter', label: 'This quarter' }, { value: 'this_year', label: 'This year' }, { value: 'all', label: 'All time' }] },
  { id: 'bills-quick-search-fields', section: 'bills', group: 'Sorting & Filtering', label: 'Search includes memo text', type: 'toggle', default: true },
  { id: 'bills-search-min-chars', section: 'bills', group: 'Sorting & Filtering', label: 'Minimum search characters', type: 'number', default: 2, min: 1, max: 5, step: 1 },
  { id: 'bills-secondary-sort', section: 'bills', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'vendor', options: [{ value: 'vendor', label: 'Vendor' }, { value: 'amount', label: 'Amount' }, { value: 'bill_number', label: 'Bill number' }, { value: 'none', label: 'None' }] },
  { id: 'bills-amount-filter-min', section: 'bills', group: 'Sorting & Filtering', label: 'Default minimum amount filter', type: 'number', default: 0, min: 0, max: 1000000, step: 50 },
  { id: 'bills-amount-filter-max', section: 'bills', group: 'Sorting & Filtering', label: 'Default maximum amount filter', type: 'number', default: 0, min: 0, max: 10000000, step: 100 },
  { id: 'bills-filter-by-vendor-default', section: 'bills', group: 'Sorting & Filtering', label: 'Default vendor filter', type: 'text', default: '' },
  { id: 'bills-show-filter-chips', section: 'bills', group: 'Sorting & Filtering', label: 'Show active filter chips', type: 'toggle', default: true },
  { id: 'bills-sort-overdue-first', section: 'bills', group: 'Sorting & Filtering', label: 'Always sort overdue first', type: 'toggle', default: false },
  { id: 'bills-filter-my-approvals', section: 'bills', group: 'Sorting & Filtering', label: 'Default to my pending approvals', type: 'toggle', default: false },
  { id: 'bills-saved-filter-name', section: 'bills', group: 'Sorting & Filtering', label: 'Default saved filter name', type: 'text', default: '' },
  { id: 'bills-case-sensitive-search', section: 'bills', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'bills-filter-recurring-only', section: 'bills', group: 'Sorting & Filtering', label: 'Default to recurring bills only', type: 'toggle', default: false },
  { id: 'bills-fuzzy-vendor-match', section: 'bills', group: 'Sorting & Filtering', label: 'Fuzzy vendor name matching', type: 'toggle', default: true },

  // ===== Behavior (109-130) =====
  { id: 'bills-confirm-delete', section: 'bills', group: 'Behavior', label: 'Confirm before deleting', type: 'toggle', default: true },
  { id: 'bills-confirm-void', section: 'bills', group: 'Behavior', label: 'Confirm before voiding', type: 'toggle', default: true },
  { id: 'bills-autosave-draft', section: 'bills', group: 'Behavior', label: 'Auto-save drafts while editing', type: 'toggle', default: true },
  { id: 'bills-autosave-interval', section: 'bills', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'bills-stay-after-save', section: 'bills', group: 'Behavior', label: 'Stay on form after saving', type: 'toggle', default: false },
  { id: 'bills-duplicate-detection', section: 'bills', group: 'Behavior', label: 'Warn on duplicate bill numbers', type: 'toggle', default: true },
  { id: 'bills-duplicate-amount-warn', section: 'bills', group: 'Behavior', label: 'Warn on duplicate vendor+amount', type: 'toggle', default: true },
  { id: 'bills-auto-match-po', section: 'bills', group: 'Behavior', label: 'Auto-match to purchase orders', type: 'toggle', default: false },
  { id: 'bills-three-way-match', section: 'bills', group: 'Behavior', label: 'Require 3-way PO match', type: 'toggle', default: false },
  { id: 'bills-tab-key-adds-line', section: 'bills', group: 'Behavior', label: 'Tab on last cell adds line item', type: 'toggle', default: true },
  { id: 'bills-keep-recent-vendors', section: 'bills', group: 'Behavior', label: 'Show recent vendors first', type: 'toggle', default: true },
  { id: 'bills-recent-vendor-count', section: 'bills', group: 'Behavior', label: 'Recent vendors to remember', type: 'number', default: 8, min: 0, max: 30, step: 1 },
  { id: 'bills-auto-create-vendor', section: 'bills', group: 'Behavior', label: 'Auto-create unknown vendors', type: 'toggle', default: false },
  { id: 'bills-lock-after-payment', section: 'bills', group: 'Behavior', label: 'Lock editing after payment', type: 'toggle', default: true },
  { id: 'bills-lock-closed-period', section: 'bills', group: 'Behavior', label: 'Block edits in closed periods', type: 'toggle', default: true },
  { id: 'bills-recurring-auto-create', section: 'bills', group: 'Behavior', label: 'Auto-create recurring bills', type: 'toggle', default: true },
  { id: 'bills-recurring-lead-days', section: 'bills', group: 'Behavior', label: 'Create recurring bills N days early', type: 'number', default: 5, min: 0, max: 30, step: 1 },
  { id: 'bills-ocr-on-attach', section: 'bills', group: 'Behavior', label: 'Run OCR on attachments', type: 'toggle', default: true },
  { id: 'bills-ocr-autofill', section: 'bills', group: 'Behavior', label: 'Auto-fill fields from OCR', type: 'toggle', default: true },
  { id: 'bills-round-line-totals', section: 'bills', group: 'Behavior', label: 'Round line totals on entry', type: 'toggle', default: false },
  { id: 'bills-enter-saves', section: 'bills', group: 'Behavior', label: 'Enter key saves the bill', type: 'toggle', default: false },
  { id: 'bills-undo-window', section: 'bills', group: 'Behavior', label: 'Undo window after delete (seconds)', type: 'number', default: 10, min: 0, max: 60, step: 1 },

  // ===== Notifications (131-150) =====
  { id: 'bills-notify-due-soon', section: 'bills', group: 'Notifications', label: 'Notify when bills are due soon', type: 'toggle', default: true },
  { id: 'bills-notify-due-lead', section: 'bills', group: 'Notifications', label: 'Due-soon reminder lead (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'bills-notify-overdue', section: 'bills', group: 'Notifications', label: 'Notify on overdue bills', type: 'toggle', default: true },
  { id: 'bills-notify-overdue-repeat', section: 'bills', group: 'Notifications', label: 'Repeat overdue reminders', type: 'toggle', default: false },
  { id: 'bills-notify-approval-needed', section: 'bills', group: 'Notifications', label: 'Notify when approval needed', type: 'toggle', default: true },
  { id: 'bills-notify-approved', section: 'bills', group: 'Notifications', label: 'Notify when my bill is approved', type: 'toggle', default: true },
  { id: 'bills-notify-rejected', section: 'bills', group: 'Notifications', label: 'Notify when my bill is rejected', type: 'toggle', default: true },
  { id: 'bills-notify-payment-sent', section: 'bills', group: 'Notifications', label: 'Notify when payment is sent', type: 'toggle', default: true },
  { id: 'bills-notify-discount-expiring', section: 'bills', group: 'Notifications', label: 'Notify when early-pay discount expiring', type: 'toggle', default: true },
  { id: 'bills-notify-discount-lead', section: 'bills', group: 'Notifications', label: 'Discount-expiry lead (days)', type: 'number', default: 2, min: 0, max: 15, step: 1 },
  { id: 'bills-notify-channel', section: 'bills', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in_app', options: [{ value: 'in_app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }, { value: 'none', label: 'None' }] },
  { id: 'bills-notify-digest', section: 'bills', group: 'Notifications', label: 'Send daily AP digest', type: 'toggle', default: false },
  { id: 'bills-notify-digest-time', section: 'bills', group: 'Notifications', label: 'Digest send time', type: 'text', default: '08:00' },
  { id: 'bills-notify-recurring-created', section: 'bills', group: 'Notifications', label: 'Notify when recurring bill created', type: 'toggle', default: true },
  { id: 'bills-notify-ocr-done', section: 'bills', group: 'Notifications', label: 'Notify when OCR finishes', type: 'toggle', default: false },
  { id: 'bills-notify-large-amount', section: 'bills', group: 'Notifications', label: 'Alert on large bill entry', type: 'toggle', default: true },
  { id: 'bills-notify-large-threshold', section: 'bills', group: 'Notifications', label: 'Large bill alert threshold', type: 'number', default: 10000, min: 0, max: 1000000, step: 500 },
  { id: 'bills-notify-cash-shortfall', section: 'bills', group: 'Notifications', label: 'Alert on projected cash shortfall', type: 'toggle', default: true },
  { id: 'bills-notify-sound', section: 'bills', group: 'Notifications', label: 'Play sound on notifications', type: 'toggle', default: false },
  { id: 'bills-notify-duplicate', section: 'bills', group: 'Notifications', label: 'Notify on possible duplicate', type: 'toggle', default: true },

  // ===== Export (151-168) =====
  { id: 'bills-export-format', section: 'bills', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'bills-export-include-headers', section: 'bills', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'bills-export-visible-only', section: 'bills', group: 'Export', label: 'Export visible columns only', type: 'toggle', default: false },
  { id: 'bills-export-filtered-only', section: 'bills', group: 'Export', label: 'Export filtered rows only', type: 'toggle', default: true },
  { id: 'bills-export-line-items', section: 'bills', group: 'Export', label: 'Include line-item detail', type: 'toggle', default: false },
  { id: 'bills-export-date-format', section: 'bills', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'YYYY-MM-DD' }, { value: 'us', label: 'MM/DD/YYYY' }, { value: 'eu', label: 'DD/MM/YYYY' }] },
  { id: 'bills-export-delimiter', section: 'bills', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }, { value: 'pipe', label: 'Pipe' }] },
  { id: 'bills-export-encoding', section: 'bills', group: 'Export', label: 'File encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'bills-export-filename', section: 'bills', group: 'Export', label: 'Export filename template', type: 'text', default: 'bills_{date}' },
  { id: 'bills-export-include-totals', section: 'bills', group: 'Export', label: 'Append totals row', type: 'toggle', default: true },
  { id: 'bills-export-currency-raw', section: 'bills', group: 'Export', label: 'Export amounts unformatted', type: 'toggle', default: true },
  { id: 'bills-export-attachments', section: 'bills', group: 'Export', label: 'Include attachments in PDF export', type: 'toggle', default: false },
  { id: 'bills-export-page-size', section: 'bills', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'bills-export-orientation', section: 'bills', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'bills-export-company-header', section: 'bills', group: 'Export', label: 'Include company header on PDF', type: 'toggle', default: true },
  { id: 'bills-export-quickbooks', section: 'bills', group: 'Export', label: 'QuickBooks IIF compatibility', type: 'toggle', default: false },
  { id: 'bills-export-open-after', section: 'bills', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'bills-export-max-rows', section: 'bills', group: 'Export', label: 'Max rows per export', type: 'number', default: 10000, min: 100, max: 100000, step: 100 },

  // ===== Colors & Theme (169-182) =====
  { id: 'bills-color-overdue', section: 'bills', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#ef4444' },
  { id: 'bills-color-due-soon', section: 'bills', group: 'Colors & Theme', label: 'Due-soon highlight color', type: 'color', default: '#f59e0b' },
  { id: 'bills-color-paid', section: 'bills', group: 'Colors & Theme', label: 'Paid status color', type: 'color', default: '#22c55e' },
  { id: 'bills-color-open', section: 'bills', group: 'Colors & Theme', label: 'Open status color', type: 'color', default: '#3b82f6' },
  { id: 'bills-color-draft', section: 'bills', group: 'Colors & Theme', label: 'Draft status color', type: 'color', default: '#6b7280' },
  { id: 'bills-color-pending', section: 'bills', group: 'Colors & Theme', label: 'Pending approval color', type: 'color', default: '#a855f7' },
  { id: 'bills-color-void', section: 'bills', group: 'Colors & Theme', label: 'Void status color', type: 'color', default: '#9ca3af' },
  { id: 'bills-color-row-hover', section: 'bills', group: 'Colors & Theme', label: 'Row hover color', type: 'color', default: '#1e293b' },
  { id: 'bills-color-header-bg', section: 'bills', group: 'Colors & Theme', label: 'Table header background', type: 'color', default: '#0f172a' },
  { id: 'bills-color-accent', section: 'bills', group: 'Colors & Theme', label: 'Accent / primary action color', type: 'color', default: '#3b82f6' },
  { id: 'bills-color-aging-bar', section: 'bills', group: 'Colors & Theme', label: 'Aging bar fill color', type: 'color', default: '#0ea5e9' },
  { id: 'bills-status-icon-set', section: 'bills', group: 'Colors & Theme', label: 'Status icon set', type: 'select', default: 'solid', options: [{ value: 'solid', label: 'Solid' }, { value: 'outline', label: 'Outline' }, { value: 'minimal', label: 'Minimal' }] },
  { id: 'bills-color-discount', section: 'bills', group: 'Colors & Theme', label: 'Early-pay discount highlight', type: 'color', default: '#10b981' },
  { id: 'bills-theme-rounded', section: 'bills', group: 'Colors & Theme', label: 'Use rounded corners on cards', type: 'toggle', default: true },

  // ===== Accessibility (183-191) =====
  { id: 'bills-a11y-high-contrast', section: 'bills', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'bills-a11y-font-size', section: 'bills', group: 'Accessibility', label: 'Table font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'bills-a11y-status-text', section: 'bills', group: 'Accessibility', label: 'Always show status as text (not color only)', type: 'toggle', default: true },
  { id: 'bills-a11y-reduce-motion', section: 'bills', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'bills-a11y-focus-ring', section: 'bills', group: 'Accessibility', label: 'Show bold focus outlines', type: 'toggle', default: true },
  { id: 'bills-a11y-screen-reader-totals', section: 'bills', group: 'Accessibility', label: 'Announce totals to screen reader', type: 'toggle', default: true },
  { id: 'bills-a11y-underline-links', section: 'bills', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: false },
  { id: 'bills-a11y-cursor-size', section: 'bills', group: 'Accessibility', label: 'Cell cursor thickness', type: 'select', default: 'normal', options: [{ value: 'thin', label: 'Thin' }, { value: 'normal', label: 'Normal' }, { value: 'thick', label: 'Thick' }] },
  { id: 'bills-a11y-tooltips-delay', section: 'bills', group: 'Accessibility', label: 'Tooltip show delay (ms)', type: 'number', default: 400, min: 0, max: 2000, step: 50 },

  // ===== Shortcuts (192-196) =====
  { id: 'bills-shortcut-new-bill', section: 'bills', group: 'Shortcuts', label: 'New bill shortcut', type: 'text', default: 'mod+n' },
  { id: 'bills-shortcut-pay', section: 'bills', group: 'Shortcuts', label: 'Pay selected shortcut', type: 'text', default: 'mod+p' },
  { id: 'bills-shortcut-approve', section: 'bills', group: 'Shortcuts', label: 'Approve shortcut', type: 'text', default: 'mod+enter' },
  { id: 'bills-shortcut-search', section: 'bills', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'bills-shortcuts-enabled', section: 'bills', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },

  // ===== Privacy (197-200) =====
  { id: 'bills-privacy-mask-amounts', section: 'bills', group: 'Privacy', label: 'Mask amounts until hover', type: 'toggle', default: false },
  { id: 'bills-privacy-hide-vendor-bank', section: 'bills', group: 'Privacy', label: 'Hide vendor bank details', type: 'toggle', default: true },
  { id: 'bills-privacy-audit-log', section: 'bills', group: 'Privacy', label: 'Log all bill edits to audit trail', type: 'toggle', default: true },
  { id: 'bills-privacy-blur-on-idle', section: 'bills', group: 'Privacy', label: 'Blur screen after idle (minutes)', type: 'number', default: 0, min: 0, max: 60, step: 1 },
];
