// src/renderer/customization/sections/budgets.ts
//
// Customization options for the Budgets section. 200 genuine, varied
// preferences a user managing budgets in this accounting app would expect.

import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ── Display (1-22) ──────────────────────────────────────────────
  { id: 'show-budget-summary-banner', section: 'budgets', group: 'Display', label: 'Show summary banner', description: 'Display the total budgeted vs actual banner at the top of the page.', type: 'toggle', default: true },
  { id: 'default-view', section: 'budgets', group: 'Display', label: 'Default view', description: 'Initial layout when opening Budgets.', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'chart', label: 'Chart' }, { value: 'kanban', label: 'Kanban' }] },
  { id: 'rows-per-page', section: 'budgets', group: 'Display', label: 'Budgets per page', description: 'Number of budget lines shown before pagination.', type: 'number', default: 25, min: 5, max: 200, step: 5 },
  { id: 'compact-rows', section: 'budgets', group: 'Display', label: 'Compact row height', description: 'Use denser rows to fit more budgets on screen.', type: 'toggle', default: false },
  { id: 'show-category-icons', section: 'budgets', group: 'Display', label: 'Show category icons', type: 'toggle', default: true },
  { id: 'show-progress-bars', section: 'budgets', group: 'Display', label: 'Show spend progress bars', description: 'Inline bar showing percent of budget consumed.', type: 'toggle', default: true },
  { id: 'progress-bar-style', section: 'budgets', group: 'Display', label: 'Progress bar style', type: 'select', default: 'gradient', options: [{ value: 'flat', label: 'Flat' }, { value: 'gradient', label: 'Gradient' }, { value: 'striped', label: 'Striped' }] },
  { id: 'show-remaining-amount', section: 'budgets', group: 'Display', label: 'Show remaining amount', description: 'Display dollars left rather than only percent used.', type: 'toggle', default: true },
  { id: 'show-period-label', section: 'budgets', group: 'Display', label: 'Show period label on rows', type: 'toggle', default: true },
  { id: 'default-period-view', section: 'budgets', group: 'Display', label: 'Default period grouping', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }] },
  { id: 'collapse-zero-budgets', section: 'budgets', group: 'Display', label: 'Collapse zero-amount budgets', type: 'toggle', default: false },
  { id: 'show-empty-categories', section: 'budgets', group: 'Display', label: 'Show categories with no budget', type: 'toggle', default: false },
  { id: 'sticky-header', section: 'budgets', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'sticky-totals-row', section: 'budgets', group: 'Display', label: 'Pin totals row to bottom', type: 'toggle', default: true },
  { id: 'show-variance-inline', section: 'budgets', group: 'Display', label: 'Show variance inline', description: 'Budget minus actual shown directly in each row.', type: 'toggle', default: true },
  { id: 'variance-display-mode', section: 'budgets', group: 'Display', label: 'Variance display mode', type: 'select', default: 'both', options: [{ value: 'amount', label: 'Amount only' }, { value: 'percent', label: 'Percent only' }, { value: 'both', label: 'Amount & percent' }] },
  { id: 'show-forecast-column', section: 'budgets', group: 'Display', label: 'Show forecast column', description: 'Projected end-of-period spend based on run rate.', type: 'toggle', default: false },
  { id: 'show-budget-owner', section: 'budgets', group: 'Display', label: 'Show budget owner avatar', type: 'toggle', default: false },
  { id: 'tile-size', section: 'budgets', group: 'Display', label: 'Card tile size', type: 'select', default: 'medium', options: [{ value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large' }] },
  { id: 'show-last-edited', section: 'budgets', group: 'Display', label: 'Show last edited timestamp', type: 'toggle', default: false },
  { id: 'show-budget-notes-preview', section: 'budgets', group: 'Display', label: 'Show notes preview', description: 'First line of the budget note under the name.', type: 'toggle', default: false },
  { id: 'header-density', section: 'budgets', group: 'Display', label: 'Header density', type: 'select', default: 'normal', options: [{ value: 'tight', label: 'Tight' }, { value: 'normal', label: 'Normal' }, { value: 'spacious', label: 'Spacious' }] },

  // ── Columns (23-44) ─────────────────────────────────────────────
  { id: 'col-category', section: 'budgets', group: 'Columns', label: 'Show Category column', type: 'toggle', default: true },
  { id: 'col-budgeted', section: 'budgets', group: 'Columns', label: 'Show Budgeted column', type: 'toggle', default: true },
  { id: 'col-actual', section: 'budgets', group: 'Columns', label: 'Show Actual column', type: 'toggle', default: true },
  { id: 'col-variance', section: 'budgets', group: 'Columns', label: 'Show Variance column', type: 'toggle', default: true },
  { id: 'col-percent-used', section: 'budgets', group: 'Columns', label: 'Show % Used column', type: 'toggle', default: true },
  { id: 'col-remaining', section: 'budgets', group: 'Columns', label: 'Show Remaining column', type: 'toggle', default: true },
  { id: 'col-period', section: 'budgets', group: 'Columns', label: 'Show Period column', type: 'toggle', default: true },
  { id: 'col-forecast', section: 'budgets', group: 'Columns', label: 'Show Forecast column', type: 'toggle', default: false },
  { id: 'col-prior-period', section: 'budgets', group: 'Columns', label: 'Show Prior Period column', type: 'toggle', default: false },
  { id: 'col-ytd-actual', section: 'budgets', group: 'Columns', label: 'Show YTD Actual column', type: 'toggle', default: false },
  { id: 'col-owner', section: 'budgets', group: 'Columns', label: 'Show Owner column', type: 'toggle', default: false },
  { id: 'col-department', section: 'budgets', group: 'Columns', label: 'Show Department column', type: 'toggle', default: false },
  { id: 'col-rollover', section: 'budgets', group: 'Columns', label: 'Show Rollover column', type: 'toggle', default: false },
  { id: 'col-notes', section: 'budgets', group: 'Columns', label: 'Show Notes column', type: 'toggle', default: false },
  { id: 'col-status', section: 'budgets', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'col-tags', section: 'budgets', group: 'Columns', label: 'Show Tags column', type: 'toggle', default: false },
  { id: 'col-committed', section: 'budgets', group: 'Columns', label: 'Show Committed column', description: 'Approved POs/commitments not yet spent.', type: 'toggle', default: false },
  { id: 'col-available', section: 'budgets', group: 'Columns', label: 'Show Available column', description: 'Budget minus actual minus committed.', type: 'toggle', default: false },
  { id: 'frozen-first-column', section: 'budgets', group: 'Columns', label: 'Freeze first column', type: 'toggle', default: true },
  { id: 'category-column-width', section: 'budgets', group: 'Columns', label: 'Category column width (px)', type: 'number', default: 220, min: 100, max: 500, step: 10 },
  { id: 'amount-column-align', section: 'budgets', group: 'Columns', label: 'Amount column alignment', type: 'select', default: 'right', options: [{ value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' }] },
  { id: 'remember-column-order', section: 'budgets', group: 'Columns', label: 'Remember column order', description: 'Persist drag-reordered columns across sessions.', type: 'toggle', default: true },

  // ── Formatting (45-66) ──────────────────────────────────────────
  { id: 'currency-symbol', section: 'budgets', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'currency-code', section: 'budgets', group: 'Formatting', label: 'Currency code', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' }] },
  { id: 'decimal-places', section: 'budgets', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'thousands-separator', section: 'budgets', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'negative-format', section: 'budgets', group: 'Formatting', label: 'Negative number format', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-$100' }, { value: 'parens', label: '($100)' }, { value: 'red', label: 'Red text' }] },
  { id: 'abbreviate-large-amounts', section: 'budgets', group: 'Formatting', label: 'Abbreviate large amounts', description: 'Show 12.5K / 1.2M instead of full figures.', type: 'toggle', default: false },
  { id: 'symbol-position', section: 'budgets', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($100)' }, { value: 'after', label: 'After (100$)' }] },
  { id: 'percent-decimal-places', section: 'budgets', group: 'Formatting', label: 'Percent decimal places', type: 'number', default: 1, min: 0, max: 2, step: 1 },
  { id: 'date-format', section: 'budgets', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }] },
  { id: 'round-display-amounts', section: 'budgets', group: 'Formatting', label: 'Round displayed amounts to whole', type: 'toggle', default: false },
  { id: 'show-cents-on-totals', section: 'budgets', group: 'Formatting', label: 'Show cents on totals', type: 'toggle', default: true },
  { id: 'period-label-format', section: 'budgets', group: 'Formatting', label: 'Period label format', type: 'select', default: 'monthyear', options: [{ value: 'monthyear', label: 'Jan 2026' }, { value: 'numeric', label: '2026-01' }, { value: 'quarter', label: 'Q1 2026' }] },
  { id: 'fiscal-year-start-month', section: 'budgets', group: 'Formatting', label: 'Fiscal year start month', type: 'number', default: 1, min: 1, max: 12, step: 1 },
  { id: 'show-currency-code-suffix', section: 'budgets', group: 'Formatting', label: 'Append currency code', description: 'Show 100.00 USD on figures.', type: 'toggle', default: false },
  { id: 'variance-sign-convention', section: 'budgets', group: 'Formatting', label: 'Variance sign convention', description: 'Whether overspend shows as positive or negative.', type: 'select', default: 'overspend-negative', options: [{ value: 'overspend-negative', label: 'Overspend negative' }, { value: 'overspend-positive', label: 'Overspend positive' }] },
  { id: 'percent-bar-cap', section: 'budgets', group: 'Formatting', label: 'Cap progress bar at 100%', type: 'toggle', default: false },
  { id: 'zero-display', section: 'budgets', group: 'Formatting', label: 'Zero amount display', type: 'select', default: 'dash', options: [{ value: 'zero', label: '$0.00' }, { value: 'dash', label: '—' }, { value: 'blank', label: 'Blank' }] },
  { id: 'amount-font', section: 'budgets', group: 'Formatting', label: 'Amount font style', type: 'select', default: 'tabular', options: [{ value: 'tabular', label: 'Tabular (monospace digits)' }, { value: 'proportional', label: 'Proportional' }] },
  { id: 'thousands-grouping-india', section: 'budgets', group: 'Formatting', label: 'Use lakh/crore grouping', type: 'toggle', default: false },
  { id: 'rounding-mode', section: 'budgets', group: 'Formatting', label: 'Rounding mode', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Half up' }, { value: 'half-even', label: 'Banker\'s' }, { value: 'down', label: 'Truncate' }] },
  { id: 'period-week-start', section: 'budgets', group: 'Formatting', label: 'Week starts on', type: 'select', default: 'monday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },
  { id: 'percent-symbol-spacing', section: 'budgets', group: 'Formatting', label: 'Space before % symbol', type: 'toggle', default: false },

  // ── Defaults (67-88) ────────────────────────────────────────────
  { id: 'default-budget-period', section: 'budgets', group: 'Defaults', label: 'Default new budget period', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }] },
  { id: 'default-budget-amount', section: 'budgets', group: 'Defaults', label: 'Default budget amount', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'default-rollover-enabled', section: 'budgets', group: 'Defaults', label: 'Enable rollover by default', description: 'Unspent funds carry into next period.', type: 'toggle', default: false },
  { id: 'default-budget-type', section: 'budgets', group: 'Defaults', label: 'Default budget type', type: 'select', default: 'expense', options: [{ value: 'expense', label: 'Expense' }, { value: 'income', label: 'Income' }, { value: 'savings', label: 'Savings goal' }] },
  { id: 'default-allocation-method', section: 'budgets', group: 'Defaults', label: 'Default allocation method', type: 'select', default: 'even', options: [{ value: 'even', label: 'Even split' }, { value: 'prior-actual', label: 'Based on prior actuals' }, { value: 'manual', label: 'Manual' }] },
  { id: 'auto-name-budget', section: 'budgets', group: 'Defaults', label: 'Auto-generate budget name', description: 'Name from category + period.', type: 'toggle', default: true },
  { id: 'budget-name-template', section: 'budgets', group: 'Defaults', label: 'Budget name template', type: 'text', default: '{category} – {period}' },
  { id: 'default-owner', section: 'budgets', group: 'Defaults', label: 'Default owner', type: 'text', default: '' },
  { id: 'default-department', section: 'budgets', group: 'Defaults', label: 'Default department', type: 'text', default: '' },
  { id: 'copy-from-prior-period', section: 'budgets', group: 'Defaults', label: 'Copy amounts from prior period', description: 'Pre-fill new budgets with last period\'s figures.', type: 'toggle', default: true },
  { id: 'prior-period-uplift-percent', section: 'budgets', group: 'Defaults', label: 'Prior-period uplift %', description: 'Apply this increase when copying forward.', type: 'number', default: 0, min: -50, max: 100, step: 0.5 },
  { id: 'default-start-day', section: 'budgets', group: 'Defaults', label: 'Default period start day', type: 'number', default: 1, min: 1, max: 28, step: 1 },
  { id: 'auto-create-next-period', section: 'budgets', group: 'Defaults', label: 'Auto-create next period budget', type: 'toggle', default: false },
  { id: 'default-currency-new', section: 'budgets', group: 'Defaults', label: 'Default currency for new budgets', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }] },
  { id: 'default-include-tax', section: 'budgets', group: 'Defaults', label: 'Include tax in budget amounts', type: 'toggle', default: false },
  { id: 'default-status-new', section: 'budgets', group: 'Defaults', label: 'Default status for new budgets', type: 'select', default: 'active', options: [{ value: 'draft', label: 'Draft' }, { value: 'active', label: 'Active' }, { value: 'locked', label: 'Locked' }] },
  { id: 'default-tags', section: 'budgets', group: 'Defaults', label: 'Default tags', type: 'text', default: '' },
  { id: 'apply-template-on-create', section: 'budgets', group: 'Defaults', label: 'Apply template on create', type: 'toggle', default: false },
  { id: 'default-template-name', section: 'budgets', group: 'Defaults', label: 'Default template name', type: 'text', default: '' },
  { id: 'default-overspend-action', section: 'budgets', group: 'Defaults', label: 'Default overspend action', type: 'select', default: 'warn', options: [{ value: 'allow', label: 'Allow' }, { value: 'warn', label: 'Warn' }, { value: 'block', label: 'Block' }] },
  { id: 'default-contingency-percent', section: 'budgets', group: 'Defaults', label: 'Default contingency buffer %', type: 'number', default: 0, min: 0, max: 50, step: 1 },
  { id: 'link-to-categories-default', section: 'budgets', group: 'Defaults', label: 'Auto-link to spending categories', type: 'toggle', default: true },

  // ── Sorting & Filtering (89-108) ────────────────────────────────
  { id: 'default-sort-field', section: 'budgets', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'category', options: [{ value: 'category', label: 'Category' }, { value: 'budgeted', label: 'Budgeted' }, { value: 'actual', label: 'Actual' }, { value: 'variance', label: 'Variance' }, { value: 'percent-used', label: '% Used' }] },
  { id: 'default-sort-direction', section: 'budgets', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'remember-last-filters', section: 'budgets', group: 'Sorting & Filtering', label: 'Remember last filters', type: 'toggle', default: true },
  { id: 'default-period-filter', section: 'budgets', group: 'Sorting & Filtering', label: 'Default period filter', type: 'select', default: 'current', options: [{ value: 'current', label: 'Current period' }, { value: 'all', label: 'All periods' }, { value: 'ytd', label: 'Year to date' }] },
  { id: 'hide-inactive', section: 'budgets', group: 'Sorting & Filtering', label: 'Hide inactive budgets', type: 'toggle', default: true },
  { id: 'hide-locked', section: 'budgets', group: 'Sorting & Filtering', label: 'Hide locked budgets', type: 'toggle', default: false },
  { id: 'show-only-overspent', section: 'budgets', group: 'Sorting & Filtering', label: 'Show only overspent', type: 'toggle', default: false },
  { id: 'show-only-near-limit', section: 'budgets', group: 'Sorting & Filtering', label: 'Show only near-limit budgets', type: 'toggle', default: false },
  { id: 'near-limit-threshold', section: 'budgets', group: 'Sorting & Filtering', label: 'Near-limit threshold %', type: 'number', default: 85, min: 50, max: 100, step: 1 },
  { id: 'default-department-filter', section: 'budgets', group: 'Sorting & Filtering', label: 'Default department filter', type: 'text', default: '' },
  { id: 'default-owner-filter', section: 'budgets', group: 'Sorting & Filtering', label: 'Default owner filter', type: 'text', default: '' },
  { id: 'group-by', section: 'budgets', group: 'Sorting & Filtering', label: 'Group budgets by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'department', label: 'Department' }, { value: 'owner', label: 'Owner' }, { value: 'type', label: 'Type' }, { value: 'category-group', label: 'Category group' }] },
  { id: 'secondary-sort-field', section: 'budgets', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'budgeted', options: [{ value: 'category', label: 'Category' }, { value: 'budgeted', label: 'Budgeted' }, { value: 'actual', label: 'Actual' }, { value: 'name', label: 'Name' }] },
  { id: 'search-includes-notes', section: 'budgets', group: 'Sorting & Filtering', label: 'Search includes notes', type: 'toggle', default: true },
  { id: 'search-includes-tags', section: 'budgets', group: 'Sorting & Filtering', label: 'Search includes tags', type: 'toggle', default: true },
  { id: 'sort-totals-respect-filter', section: 'budgets', group: 'Sorting & Filtering', label: 'Totals reflect active filters', type: 'toggle', default: true },
  { id: 'pin-favorites-top', section: 'budgets', group: 'Sorting & Filtering', label: 'Pin favorite budgets to top', type: 'toggle', default: true },
  { id: 'filter-amount-min', section: 'budgets', group: 'Sorting & Filtering', label: 'Default min amount filter', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'case-sensitive-search', section: 'budgets', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'show-archived-toggle', section: 'budgets', group: 'Sorting & Filtering', label: 'Show archived budgets toggle', type: 'toggle', default: false },

  // ── Behavior (109-130) ──────────────────────────────────────────
  { id: 'confirm-before-delete', section: 'budgets', group: 'Behavior', label: 'Confirm before deleting budget', type: 'toggle', default: true },
  { id: 'autosave', section: 'budgets', group: 'Behavior', label: 'Auto-save edits', type: 'toggle', default: true },
  { id: 'autosave-delay-ms', section: 'budgets', group: 'Behavior', label: 'Auto-save delay (ms)', type: 'number', default: 800, min: 100, max: 5000, step: 100 },
  { id: 'inline-edit-amounts', section: 'budgets', group: 'Behavior', label: 'Edit amounts inline in table', type: 'toggle', default: true },
  { id: 'enter-moves-down', section: 'budgets', group: 'Behavior', label: 'Enter moves to next budget', description: 'During inline editing, Enter advances down.', type: 'toggle', default: true },
  { id: 'block-overspend-entry', section: 'budgets', group: 'Behavior', label: 'Block saving over-limit budgets', type: 'toggle', default: false },
  { id: 'auto-recalc-on-transaction', section: 'budgets', group: 'Behavior', label: 'Recalculate actuals live', description: 'Update actuals immediately as transactions post.', type: 'toggle', default: true },
  { id: 'rollover-on-period-close', section: 'budgets', group: 'Behavior', label: 'Roll over unspent on period close', type: 'toggle', default: false },
  { id: 'lock-past-periods', section: 'budgets', group: 'Behavior', label: 'Lock past-period budgets', type: 'toggle', default: true },
  { id: 'require-note-on-overspend', section: 'budgets', group: 'Behavior', label: 'Require note when overspending', type: 'toggle', default: false },
  { id: 'duplicate-on-copy', section: 'budgets', group: 'Behavior', label: 'Duplicate includes notes & tags', type: 'toggle', default: true },
  { id: 'undo-window-seconds', section: 'budgets', group: 'Behavior', label: 'Undo window (seconds)', type: 'number', default: 10, min: 0, max: 60, step: 1 },
  { id: 'open-detail-on-click', section: 'budgets', group: 'Behavior', label: 'Open detail panel on row click', type: 'toggle', default: true },
  { id: 'detail-panel-position', section: 'budgets', group: 'Behavior', label: 'Detail panel position', type: 'select', default: 'right', options: [{ value: 'right', label: 'Right drawer' }, { value: 'bottom', label: 'Bottom sheet' }, { value: 'modal', label: 'Modal' }] },
  { id: 'auto-link-transactions', section: 'budgets', group: 'Behavior', label: 'Auto-link matching transactions', type: 'toggle', default: true },
  { id: 'warn-unsaved-changes', section: 'budgets', group: 'Behavior', label: 'Warn on unsaved changes', type: 'toggle', default: true },
  { id: 'remember-expanded-groups', section: 'budgets', group: 'Behavior', label: 'Remember expanded groups', type: 'toggle', default: true },
  { id: 'auto-archive-old-budgets', section: 'budgets', group: 'Behavior', label: 'Auto-archive budgets older than', type: 'select', default: 'never', options: [{ value: 'never', label: 'Never' }, { value: '1y', label: '1 year' }, { value: '2y', label: '2 years' }, { value: '3y', label: '3 years' }] },
  { id: 'recalc-forecast-method', section: 'budgets', group: 'Behavior', label: 'Forecast method', type: 'select', default: 'runrate', options: [{ value: 'runrate', label: 'Run rate' }, { value: 'linear', label: 'Linear to date' }, { value: 'prior', label: 'Same as prior period' }] },
  { id: 'tab-key-skips-readonly', section: 'budgets', group: 'Behavior', label: 'Tab skips read-only cells', type: 'toggle', default: true },
  { id: 'double-click-to-edit', section: 'budgets', group: 'Behavior', label: 'Double-click to edit cell', type: 'toggle', default: false },
  { id: 'budget-approval-required', section: 'budgets', group: 'Behavior', label: 'Require approval before activation', type: 'toggle', default: false },

  // ── Notifications (131-152) ─────────────────────────────────────
  { id: 'notify-overspend', section: 'budgets', group: 'Notifications', label: 'Notify on overspend', type: 'toggle', default: true },
  { id: 'notify-threshold-percent', section: 'budgets', group: 'Notifications', label: 'Alert threshold %', description: 'Warn when spend reaches this percent of budget.', type: 'number', default: 90, min: 50, max: 100, step: 1 },
  { id: 'notify-near-limit', section: 'budgets', group: 'Notifications', label: 'Notify when near limit', type: 'toggle', default: true },
  { id: 'notify-period-end', section: 'budgets', group: 'Notifications', label: 'Notify before period ends', type: 'toggle', default: true },
  { id: 'period-end-lead-days', section: 'budgets', group: 'Notifications', label: 'Period-end reminder lead (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'notify-underspend', section: 'budgets', group: 'Notifications', label: 'Notify on significant underspend', type: 'toggle', default: false },
  { id: 'underspend-threshold-percent', section: 'budgets', group: 'Notifications', label: 'Underspend threshold %', type: 'number', default: 40, min: 0, max: 90, step: 5 },
  { id: 'notify-channel', section: 'budgets', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'notify-email-address', section: 'budgets', group: 'Notifications', label: 'Notification email address', type: 'text', default: '' },
  { id: 'daily-digest', section: 'budgets', group: 'Notifications', label: 'Send daily budget digest', type: 'toggle', default: false },
  { id: 'weekly-digest', section: 'budgets', group: 'Notifications', label: 'Send weekly budget digest', type: 'toggle', default: true },
  { id: 'digest-day', section: 'budgets', group: 'Notifications', label: 'Weekly digest day', type: 'select', default: 'monday', options: [{ value: 'monday', label: 'Monday' }, { value: 'friday', label: 'Friday' }, { value: 'sunday', label: 'Sunday' }] },
  { id: 'digest-hour', section: 'budgets', group: 'Notifications', label: 'Digest send hour (24h)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'notify-owner-only', section: 'budgets', group: 'Notifications', label: 'Notify budget owner only', type: 'toggle', default: false },
  { id: 'notify-on-new-budget', section: 'budgets', group: 'Notifications', label: 'Notify when budget created', type: 'toggle', default: false },
  { id: 'notify-on-approval-needed', section: 'budgets', group: 'Notifications', label: 'Notify when approval needed', type: 'toggle', default: true },
  { id: 'mute-weekend-alerts', section: 'budgets', group: 'Notifications', label: 'Mute weekend alerts', type: 'toggle', default: false },
  { id: 'notify-rollover-applied', section: 'budgets', group: 'Notifications', label: 'Notify when rollover applied', type: 'toggle', default: true },
  { id: 'snooze-default-hours', section: 'budgets', group: 'Notifications', label: 'Default snooze duration (hours)', type: 'number', default: 24, min: 1, max: 168, step: 1 },
  { id: 'group-similar-alerts', section: 'budgets', group: 'Notifications', label: 'Group similar alerts', type: 'toggle', default: true },
  { id: 'alert-sound', section: 'budgets', group: 'Notifications', label: 'Play sound on critical alert', type: 'toggle', default: false },
  { id: 'forecast-overrun-alert', section: 'budgets', group: 'Notifications', label: 'Alert on forecast overrun', description: 'Warn when projected spend exceeds budget.', type: 'toggle', default: true },

  // ── Export (153-170) ────────────────────────────────────────────
  { id: 'default-export-format', section: 'budgets', group: 'Export', label: 'Default export format', type: 'select', default: 'xlsx', options: [{ value: 'xlsx', label: 'Excel (.xlsx)' }, { value: 'csv', label: 'CSV' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'export-include-actuals', section: 'budgets', group: 'Export', label: 'Include actuals in export', type: 'toggle', default: true },
  { id: 'export-include-variance', section: 'budgets', group: 'Export', label: 'Include variance in export', type: 'toggle', default: true },
  { id: 'export-include-notes', section: 'budgets', group: 'Export', label: 'Include notes in export', type: 'toggle', default: false },
  { id: 'export-include-charts', section: 'budgets', group: 'Export', label: 'Include charts in PDF export', type: 'toggle', default: true },
  { id: 'export-respect-filters', section: 'budgets', group: 'Export', label: 'Export only filtered rows', type: 'toggle', default: true },
  { id: 'export-include-totals-row', section: 'budgets', group: 'Export', label: 'Include totals row', type: 'toggle', default: true },
  { id: 'export-date-stamp', section: 'budgets', group: 'Export', label: 'Stamp export with date', type: 'toggle', default: true },
  { id: 'export-filename-template', section: 'budgets', group: 'Export', label: 'Export filename template', type: 'text', default: 'budgets-{period}-{date}' },
  { id: 'pdf-orientation', section: 'budgets', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'pdf-paper-size', section: 'budgets', group: 'Export', label: 'PDF paper size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'csv-delimiter', section: 'budgets', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'export-company-logo', section: 'budgets', group: 'Export', label: 'Include company logo in PDF', type: 'toggle', default: true },
  { id: 'export-currency-code-cols', section: 'budgets', group: 'Export', label: 'Add currency code column', type: 'toggle', default: false },
  { id: 'export-hidden-columns', section: 'budgets', group: 'Export', label: 'Export hidden columns too', type: 'toggle', default: false },
  { id: 'export-group-subtotals', section: 'budgets', group: 'Export', label: 'Include group subtotals', type: 'toggle', default: true },
  { id: 'export-open-after-save', section: 'budgets', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'export-precision', section: 'budgets', group: 'Export', label: 'Export decimal precision', type: 'number', default: 2, min: 0, max: 6, step: 1 },

  // ── Colors & Theme (171-186) ────────────────────────────────────
  { id: 'over-budget-color', section: 'budgets', group: 'Colors & Theme', label: 'Over-budget color', type: 'color', default: '#ef4444' },
  { id: 'under-budget-color', section: 'budgets', group: 'Colors & Theme', label: 'Under-budget color', type: 'color', default: '#22c55e' },
  { id: 'near-limit-color', section: 'budgets', group: 'Colors & Theme', label: 'Near-limit color', type: 'color', default: '#f59e0b' },
  { id: 'progress-bar-color', section: 'budgets', group: 'Colors & Theme', label: 'Progress bar base color', type: 'color', default: '#3b82f6' },
  { id: 'chart-budgeted-color', section: 'budgets', group: 'Colors & Theme', label: 'Chart: budgeted series color', type: 'color', default: '#6366f1' },
  { id: 'chart-actual-color', section: 'budgets', group: 'Colors & Theme', label: 'Chart: actual series color', type: 'color', default: '#14b8a6' },
  { id: 'chart-forecast-color', section: 'budgets', group: 'Colors & Theme', label: 'Chart: forecast series color', type: 'color', default: '#a855f7' },
  { id: 'totals-row-bg', section: 'budgets', group: 'Colors & Theme', label: 'Totals row background', type: 'color', default: '#1e293b' },
  { id: 'color-code-by-status', section: 'budgets', group: 'Colors & Theme', label: 'Color-code rows by status', type: 'toggle', default: true },
  { id: 'use-heatmap-shading', section: 'budgets', group: 'Colors & Theme', label: 'Heatmap shading on % used', type: 'toggle', default: false },
  { id: 'chart-type', section: 'budgets', group: 'Colors & Theme', label: 'Default chart type', type: 'select', default: 'bar', options: [{ value: 'bar', label: 'Bar' }, { value: 'line', label: 'Line' }, { value: 'donut', label: 'Donut' }, { value: 'area', label: 'Area' }] },
  { id: 'highlight-favorite-color', section: 'budgets', group: 'Colors & Theme', label: 'Favorite highlight color', type: 'color', default: '#fbbf24' },
  { id: 'grid-line-color', section: 'budgets', group: 'Colors & Theme', label: 'Grid line color', type: 'color', default: '#334155' },
  { id: 'use-category-colors', section: 'budgets', group: 'Colors & Theme', label: 'Use category colors in rows', type: 'toggle', default: true },
  { id: 'show-chart-gridlines', section: 'budgets', group: 'Colors & Theme', label: 'Show chart gridlines', type: 'toggle', default: true },
  { id: 'chart-legend-position', section: 'budgets', group: 'Colors & Theme', label: 'Chart legend position', type: 'select', default: 'bottom', options: [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }, { value: 'right', label: 'Right' }, { value: 'hidden', label: 'Hidden' }] },

  // ── Accessibility (187-194) ─────────────────────────────────────
  { id: 'high-contrast-mode', section: 'budgets', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'colorblind-safe-palette', section: 'budgets', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'toggle', default: false },
  { id: 'use-patterns-not-color', section: 'budgets', group: 'Accessibility', label: 'Use patterns alongside color', description: 'Add icons/patterns so status isn\'t color-only.', type: 'toggle', default: false },
  { id: 'larger-text', section: 'budgets', group: 'Accessibility', label: 'Larger text size', type: 'toggle', default: false },
  { id: 'text-scale', section: 'budgets', group: 'Accessibility', label: 'Text scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'reduce-motion', section: 'budgets', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'screen-reader-summaries', section: 'budgets', group: 'Accessibility', label: 'Verbose screen-reader summaries', type: 'toggle', default: true },
  { id: 'focus-ring-visible', section: 'budgets', group: 'Accessibility', label: 'Always show focus outline', type: 'toggle', default: false },

  // ── Shortcuts (195-198) ─────────────────────────────────────────
  { id: 'enable-keyboard-shortcuts', section: 'budgets', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'shortcut-new-budget', section: 'budgets', group: 'Shortcuts', label: 'New budget shortcut', type: 'text', default: 'n' },
  { id: 'shortcut-export', section: 'budgets', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'mod+e' },
  { id: 'shortcut-focus-search', section: 'budgets', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },

  // ── Privacy (199-200) ───────────────────────────────────────────
  { id: 'mask-amounts', section: 'budgets', group: 'Privacy', label: 'Mask amounts until hover', description: 'Hide figures with dots until you hover.', type: 'toggle', default: false },
  { id: 'hide-from-screenshare', section: 'budgets', group: 'Privacy', label: 'Blur amounts during screen share', type: 'toggle', default: false },
];
