import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-22) =====
  { id: 'clients-default-view', section: 'clients', group: 'Display', label: 'Default client view', description: 'Layout used when opening the Clients module', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'kanban', label: 'Kanban' }, { value: 'compact', label: 'Compact list' }] },
  { id: 'clients-rows-per-page', section: 'clients', group: 'Display', label: 'Rows per page', description: 'Number of clients shown per page', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'clients-show-avatars', section: 'clients', group: 'Display', label: 'Show client avatars', description: 'Display logo or initials avatar next to each client', type: 'toggle', default: true },
  { id: 'clients-avatar-style', section: 'clients', group: 'Display', label: 'Avatar style', type: 'select', default: 'initials', options: [{ value: 'initials', label: 'Initials' }, { value: 'logo', label: 'Company logo' }, { value: 'gravatar', label: 'Gravatar' }, { value: 'none', label: 'None' }] },
  { id: 'clients-row-density', section: 'clients', group: 'Display', label: 'Row density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'clients-show-row-numbers', section: 'clients', group: 'Display', label: 'Show row numbers', type: 'toggle', default: false },
  { id: 'clients-zebra-striping', section: 'clients', group: 'Display', label: 'Zebra row striping', description: 'Alternate background shading on rows', type: 'toggle', default: true },
  { id: 'clients-sticky-header', section: 'clients', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'clients-show-quick-stats', section: 'clients', group: 'Display', label: 'Show quick stats bar', description: 'Totals and counts above the client list', type: 'toggle', default: true },
  { id: 'clients-show-inactive', section: 'clients', group: 'Display', label: 'Show inactive clients', type: 'toggle', default: false },
  { id: 'clients-inactive-style', section: 'clients', group: 'Display', label: 'Inactive client styling', type: 'select', default: 'dimmed', options: [{ value: 'dimmed', label: 'Dimmed' }, { value: 'strikethrough', label: 'Strikethrough' }, { value: 'badge', label: 'Badge only' }] },
  { id: 'clients-show-archived', section: 'clients', group: 'Display', label: 'Show archived clients', type: 'toggle', default: false },
  { id: 'clients-card-size', section: 'clients', group: 'Display', label: 'Card size', type: 'select', default: 'medium', options: [{ value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large' }] },
  { id: 'clients-cards-per-row', section: 'clients', group: 'Display', label: 'Cards per row', type: 'number', default: 3, min: 1, max: 6, step: 1 },
  { id: 'clients-show-tags-inline', section: 'clients', group: 'Display', label: 'Show tags inline', description: 'Display client tags directly in the list', type: 'toggle', default: true },
  { id: 'clients-max-inline-tags', section: 'clients', group: 'Display', label: 'Max inline tags', type: 'number', default: 3, min: 0, max: 10, step: 1 },
  { id: 'clients-show-favorites-first', section: 'clients', group: 'Display', label: 'Pin favorites to top', type: 'toggle', default: true },
  { id: 'clients-truncate-long-names', section: 'clients', group: 'Display', label: 'Truncate long names', type: 'toggle', default: true },
  { id: 'clients-name-max-length', section: 'clients', group: 'Display', label: 'Name truncation length', type: 'number', default: 40, min: 10, max: 120, step: 5 },
  { id: 'clients-show-empty-state-tips', section: 'clients', group: 'Display', label: 'Show empty-state tips', type: 'toggle', default: true },
  { id: 'clients-highlight-overdue', section: 'clients', group: 'Display', label: 'Highlight clients with overdue balances', type: 'toggle', default: true },
  { id: 'clients-show-relationship-since', section: 'clients', group: 'Display', label: 'Show "client since" date', type: 'toggle', default: false },

  // ===== Columns (23-46) =====
  { id: 'clients-col-name', section: 'clients', group: 'Columns', label: 'Show Name column', type: 'toggle', default: true },
  { id: 'clients-col-company', section: 'clients', group: 'Columns', label: 'Show Company column', type: 'toggle', default: true },
  { id: 'clients-col-email', section: 'clients', group: 'Columns', label: 'Show Email column', type: 'toggle', default: true },
  { id: 'clients-col-phone', section: 'clients', group: 'Columns', label: 'Show Phone column', type: 'toggle', default: true },
  { id: 'clients-col-balance', section: 'clients', group: 'Columns', label: 'Show Outstanding Balance column', type: 'toggle', default: true },
  { id: 'clients-col-total-billed', section: 'clients', group: 'Columns', label: 'Show Total Billed column', type: 'toggle', default: false },
  { id: 'clients-col-last-invoice', section: 'clients', group: 'Columns', label: 'Show Last Invoice column', type: 'toggle', default: false },
  { id: 'clients-col-last-payment', section: 'clients', group: 'Columns', label: 'Show Last Payment column', type: 'toggle', default: false },
  { id: 'clients-col-status', section: 'clients', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'clients-col-tags', section: 'clients', group: 'Columns', label: 'Show Tags column', type: 'toggle', default: false },
  { id: 'clients-col-payment-terms', section: 'clients', group: 'Columns', label: 'Show Payment Terms column', type: 'toggle', default: false },
  { id: 'clients-col-currency', section: 'clients', group: 'Columns', label: 'Show Currency column', type: 'toggle', default: false },
  { id: 'clients-col-tax-id', section: 'clients', group: 'Columns', label: 'Show Tax ID column', type: 'toggle', default: false },
  { id: 'clients-col-city', section: 'clients', group: 'Columns', label: 'Show City column', type: 'toggle', default: false },
  { id: 'clients-col-country', section: 'clients', group: 'Columns', label: 'Show Country column', type: 'toggle', default: false },
  { id: 'clients-col-assigned-rep', section: 'clients', group: 'Columns', label: 'Show Assigned Rep column', type: 'toggle', default: false },
  { id: 'clients-col-created-date', section: 'clients', group: 'Columns', label: 'Show Created Date column', type: 'toggle', default: false },
  { id: 'clients-col-open-invoices', section: 'clients', group: 'Columns', label: 'Show Open Invoices count column', type: 'toggle', default: false },
  { id: 'clients-col-avg-days-to-pay', section: 'clients', group: 'Columns', label: 'Show Avg Days to Pay column', type: 'toggle', default: false },
  { id: 'clients-col-credit-limit', section: 'clients', group: 'Columns', label: 'Show Credit Limit column', type: 'toggle', default: false },
  { id: 'clients-col-order', section: 'clients', group: 'Columns', label: 'Column order preset', type: 'select', default: 'default', options: [{ value: 'default', label: 'Default' }, { value: 'finance-first', label: 'Finance first' }, { value: 'contact-first', label: 'Contact first' }] },
  { id: 'clients-freeze-first-column', section: 'clients', group: 'Columns', label: 'Freeze first column', type: 'toggle', default: false },
  { id: 'clients-resizable-columns', section: 'clients', group: 'Columns', label: 'Allow column resizing', type: 'toggle', default: true },
  { id: 'clients-name-column-width', section: 'clients', group: 'Columns', label: 'Name column width (px)', type: 'number', default: 220, min: 100, max: 500, step: 10 },

  // ===== Formatting (47-68) =====
  { id: 'clients-name-format', section: 'clients', group: 'Formatting', label: 'Name display format', type: 'select', default: 'first-last', options: [{ value: 'first-last', label: 'First Last' }, { value: 'last-first', label: 'Last, First' }, { value: 'company-only', label: 'Company only' }] },
  { id: 'clients-currency-symbol', section: 'clients', group: 'Formatting', label: 'Default currency symbol', type: 'select', default: 'usd', options: [{ value: 'usd', label: '$ USD' }, { value: 'eur', label: '€ EUR' }, { value: 'gbp', label: '£ GBP' }, { value: 'cad', label: '$ CAD' }, { value: 'aud', label: '$ AUD' }] },
  { id: 'clients-currency-position', section: 'clients', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'clients-decimal-places', section: 'clients', group: 'Formatting', label: 'Decimal places for amounts', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'clients-thousands-separator', section: 'clients', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'clients-date-format', section: 'clients', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Mon DD, YYYY' }] },
  { id: 'clients-phone-format', section: 'clients', group: 'Formatting', label: 'Phone number format', type: 'select', default: 'national', options: [{ value: 'national', label: 'National (555) 123-4567' }, { value: 'international', label: 'International +1 555 123 4567' }, { value: 'raw', label: 'Raw digits' }] },
  { id: 'clients-negative-balance-style', section: 'clients', group: 'Formatting', label: 'Negative balance style', type: 'select', default: 'parentheses', options: [{ value: 'parentheses', label: '(100.00)' }, { value: 'minus', label: '-100.00' }, { value: 'red', label: 'Red text' }] },
  { id: 'clients-zero-balance-display', section: 'clients', group: 'Formatting', label: 'Zero balance display', type: 'select', default: 'dash', options: [{ value: 'dash', label: 'Dash (—)' }, { value: 'zero', label: '0.00' }, { value: 'blank', label: 'Blank' }] },
  { id: 'clients-capitalize-names', section: 'clients', group: 'Formatting', label: 'Auto-capitalize client names', type: 'toggle', default: true },
  { id: 'clients-uppercase-tax-id', section: 'clients', group: 'Formatting', label: 'Uppercase tax IDs', type: 'toggle', default: true },
  { id: 'clients-email-lowercase', section: 'clients', group: 'Formatting', label: 'Force lowercase emails', type: 'toggle', default: true },
  { id: 'clients-relative-dates', section: 'clients', group: 'Formatting', label: 'Use relative dates', description: 'Show "3 days ago" instead of exact date', type: 'toggle', default: false },
  { id: 'clients-address-format', section: 'clients', group: 'Formatting', label: 'Address display format', type: 'select', default: 'single-line', options: [{ value: 'single-line', label: 'Single line' }, { value: 'multi-line', label: 'Multi-line' }, { value: 'postal', label: 'Postal block' }] },
  { id: 'clients-tag-case', section: 'clients', group: 'Formatting', label: 'Tag text case', type: 'select', default: 'as-entered', options: [{ value: 'as-entered', label: 'As entered' }, { value: 'lower', label: 'lowercase' }, { value: 'title', label: 'Title Case' }] },
  { id: 'clients-balance-rounding', section: 'clients', group: 'Formatting', label: 'Round displayed balances', type: 'toggle', default: false },
  { id: 'clients-show-currency-code', section: 'clients', group: 'Formatting', label: 'Show currency code (USD)', type: 'toggle', default: false },
  { id: 'clients-percent-format', section: 'clients', group: 'Formatting', label: 'Discount percent format', type: 'select', default: 'whole', options: [{ value: 'whole', label: '10%' }, { value: 'one-dp', label: '10.0%' }, { value: 'two-dp', label: '10.00%' }] },
  { id: 'clients-time-format', section: 'clients', group: 'Formatting', label: 'Time format', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'clients-id-prefix', section: 'clients', group: 'Formatting', label: 'Client ID prefix', type: 'text', default: 'CL-' },
  { id: 'clients-id-pad-length', section: 'clients', group: 'Formatting', label: 'Client ID number padding', type: 'number', default: 4, min: 0, max: 8, step: 1 },
  { id: 'clients-mask-tax-id', section: 'clients', group: 'Formatting', label: 'Mask tax IDs in list', description: 'Show only last 4 digits', type: 'toggle', default: false },

  // ===== Defaults (69-90) =====
  { id: 'clients-default-payment-terms', section: 'clients', group: 'Defaults', label: 'Default payment terms', type: 'select', default: 'net30', options: [{ value: 'due-on-receipt', label: 'Due on receipt' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net45', label: 'Net 45' }, { value: 'net60', label: 'Net 60' }] },
  { id: 'clients-default-currency', section: 'clients', group: 'Defaults', label: 'Default currency for new clients', type: 'select', default: 'usd', options: [{ value: 'usd', label: 'USD' }, { value: 'eur', label: 'EUR' }, { value: 'gbp', label: 'GBP' }, { value: 'cad', label: 'CAD' }] },
  { id: 'clients-default-country', section: 'clients', group: 'Defaults', label: 'Default country', type: 'text', default: 'United States' },
  { id: 'clients-default-tax-rate', section: 'clients', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 30, step: 0.25 },
  { id: 'clients-default-status', section: 'clients', group: 'Defaults', label: 'Default status for new clients', type: 'select', default: 'active', options: [{ value: 'active', label: 'Active' }, { value: 'prospect', label: 'Prospect' }, { value: 'lead', label: 'Lead' }] },
  { id: 'clients-default-credit-limit', section: 'clients', group: 'Defaults', label: 'Default credit limit', type: 'number', default: 0, min: 0, max: 1000000, step: 500 },
  { id: 'clients-default-discount', section: 'clients', group: 'Defaults', label: 'Default discount (%)', type: 'number', default: 0, min: 0, max: 100, step: 1 },
  { id: 'clients-default-invoice-delivery', section: 'clients', group: 'Defaults', label: 'Default invoice delivery method', type: 'select', default: 'email', options: [{ value: 'email', label: 'Email' }, { value: 'print', label: 'Print/mail' }, { value: 'portal', label: 'Client portal' }] },
  { id: 'clients-default-language', section: 'clients', group: 'Defaults', label: 'Default communication language', type: 'select', default: 'en', options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }] },
  { id: 'clients-auto-generate-id', section: 'clients', group: 'Defaults', label: 'Auto-generate client ID', type: 'toggle', default: true },
  { id: 'clients-default-assigned-rep', section: 'clients', group: 'Defaults', label: 'Default assigned rep', type: 'text', default: '' },
  { id: 'clients-require-email', section: 'clients', group: 'Defaults', label: 'Require email on new client', type: 'toggle', default: false },
  { id: 'clients-require-phone', section: 'clients', group: 'Defaults', label: 'Require phone on new client', type: 'toggle', default: false },
  { id: 'clients-require-billing-address', section: 'clients', group: 'Defaults', label: 'Require billing address', type: 'toggle', default: false },
  { id: 'clients-copy-billing-to-shipping', section: 'clients', group: 'Defaults', label: 'Copy billing to shipping by default', type: 'toggle', default: true },
  { id: 'clients-default-late-fee', section: 'clients', group: 'Defaults', label: 'Default late fee (%)', type: 'number', default: 0, min: 0, max: 25, step: 0.5 },
  { id: 'clients-default-tax-exempt', section: 'clients', group: 'Defaults', label: 'New clients tax-exempt by default', type: 'toggle', default: false },
  { id: 'clients-default-statement-frequency', section: 'clients', group: 'Defaults', label: 'Default statement frequency', type: 'select', default: 'monthly', options: [{ value: 'never', label: 'Never' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'clients-default-portal-access', section: 'clients', group: 'Defaults', label: 'Enable portal access by default', type: 'toggle', default: false },
  { id: 'clients-default-notes-template', section: 'clients', group: 'Defaults', label: 'Default client notes template', type: 'text', default: '' },
  { id: 'clients-default-payment-method', section: 'clients', group: 'Defaults', label: 'Default preferred payment method', type: 'select', default: 'bank-transfer', options: [{ value: 'bank-transfer', label: 'Bank transfer' }, { value: 'card', label: 'Card' }, { value: 'check', label: 'Check' }, { value: 'cash', label: 'Cash' }] },
  { id: 'clients-default-reminder-days', section: 'clients', group: 'Defaults', label: 'Default payment reminder lead (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },

  // ===== Sorting & Filtering (91-110) =====
  { id: 'clients-default-sort-field', section: 'clients', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'name', options: [{ value: 'name', label: 'Name' }, { value: 'balance', label: 'Balance' }, { value: 'created', label: 'Created date' }, { value: 'last-activity', label: 'Last activity' }, { value: 'total-billed', label: 'Total billed' }] },
  { id: 'clients-default-sort-direction', section: 'clients', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'clients-remember-last-filter', section: 'clients', group: 'Sorting & Filtering', label: 'Remember last used filter', type: 'toggle', default: true },
  { id: 'clients-default-status-filter', section: 'clients', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active only' }, { value: 'with-balance', label: 'With balance' }, { value: 'overdue', label: 'Overdue' }] },
  { id: 'clients-search-fields', section: 'clients', group: 'Sorting & Filtering', label: 'Search scope', type: 'select', default: 'all', options: [{ value: 'name', label: 'Name only' }, { value: 'name-email', label: 'Name & email' }, { value: 'all', label: 'All fields' }] },
  { id: 'clients-fuzzy-search', section: 'clients', group: 'Sorting & Filtering', label: 'Enable fuzzy search', type: 'toggle', default: true },
  { id: 'clients-search-debounce', section: 'clients', group: 'Sorting & Filtering', label: 'Search debounce (ms)', type: 'number', default: 250, min: 0, max: 1000, step: 50 },
  { id: 'clients-show-filter-chips', section: 'clients', group: 'Sorting & Filtering', label: 'Show active filter chips', type: 'toggle', default: true },
  { id: 'clients-quick-filter-favorites', section: 'clients', group: 'Sorting & Filtering', label: 'Show "Favorites" quick filter', type: 'toggle', default: true },
  { id: 'clients-quick-filter-overdue', section: 'clients', group: 'Sorting & Filtering', label: 'Show "Overdue" quick filter', type: 'toggle', default: true },
  { id: 'clients-quick-filter-new', section: 'clients', group: 'Sorting & Filtering', label: 'Show "New this month" quick filter', type: 'toggle', default: false },
  { id: 'clients-secondary-sort', section: 'clients', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'name', label: 'Name' }, { value: 'created', label: 'Created' }, { value: 'balance', label: 'Balance' }] },
  { id: 'clients-case-insensitive-sort', section: 'clients', group: 'Sorting & Filtering', label: 'Case-insensitive sorting', type: 'toggle', default: true },
  { id: 'clients-numeric-name-sort', section: 'clients', group: 'Sorting & Filtering', label: 'Natural numeric sort in names', type: 'toggle', default: true },
  { id: 'clients-save-filter-presets', section: 'clients', group: 'Sorting & Filtering', label: 'Allow saving filter presets', type: 'toggle', default: true },
  { id: 'clients-default-tag-filter', section: 'clients', group: 'Sorting & Filtering', label: 'Default tag filter', type: 'text', default: '' },
  { id: 'clients-filter-by-rep', section: 'clients', group: 'Sorting & Filtering', label: 'Filter by my clients only', type: 'toggle', default: false },
  { id: 'clients-balance-filter-threshold', section: 'clients', group: 'Sorting & Filtering', label: 'Min balance filter threshold', type: 'number', default: 0, min: 0, max: 100000, step: 100 },
  { id: 'clients-show-result-count', section: 'clients', group: 'Sorting & Filtering', label: 'Show filtered result count', type: 'toggle', default: true },
  { id: 'clients-clear-filters-on-exit', section: 'clients', group: 'Sorting & Filtering', label: 'Clear filters when leaving module', type: 'toggle', default: false },

  // ===== Behavior (111-132) =====
  { id: 'clients-confirm-delete', section: 'clients', group: 'Behavior', label: 'Confirm before deleting a client', type: 'toggle', default: true },
  { id: 'clients-soft-delete', section: 'clients', group: 'Behavior', label: 'Archive instead of permanent delete', type: 'toggle', default: true },
  { id: 'clients-row-click-action', section: 'clients', group: 'Behavior', label: 'Row click action', type: 'select', default: 'open-detail', options: [{ value: 'open-detail', label: 'Open detail' }, { value: 'select', label: 'Select row' }, { value: 'quick-preview', label: 'Quick preview' }] },
  { id: 'clients-detail-open-mode', section: 'clients', group: 'Behavior', label: 'Detail open mode', type: 'select', default: 'panel', options: [{ value: 'panel', label: 'Side panel' }, { value: 'modal', label: 'Modal' }, { value: 'full-page', label: 'Full page' }] },
  { id: 'clients-autosave-edits', section: 'clients', group: 'Behavior', label: 'Auto-save client edits', type: 'toggle', default: false },
  { id: 'clients-autosave-delay', section: 'clients', group: 'Behavior', label: 'Auto-save delay (seconds)', type: 'number', default: 5, min: 1, max: 60, step: 1 },
  { id: 'clients-warn-unsaved', section: 'clients', group: 'Behavior', label: 'Warn on unsaved changes', type: 'toggle', default: true },
  { id: 'clients-duplicate-detection', section: 'clients', group: 'Behavior', label: 'Detect duplicate clients on create', type: 'toggle', default: true },
  { id: 'clients-duplicate-match-field', section: 'clients', group: 'Behavior', label: 'Duplicate match field', type: 'select', default: 'email', options: [{ value: 'email', label: 'Email' }, { value: 'name', label: 'Name' }, { value: 'phone', label: 'Phone' }, { value: 'tax-id', label: 'Tax ID' }] },
  { id: 'clients-prevent-delete-with-balance', section: 'clients', group: 'Behavior', label: 'Prevent deleting clients with balance', type: 'toggle', default: true },
  { id: 'clients-auto-archive-inactive', section: 'clients', group: 'Behavior', label: 'Auto-archive after inactivity', type: 'toggle', default: false },
  { id: 'clients-inactive-threshold-days', section: 'clients', group: 'Behavior', label: 'Inactivity threshold (days)', type: 'number', default: 365, min: 30, max: 1095, step: 30 },
  { id: 'clients-keep-detail-open', section: 'clients', group: 'Behavior', label: 'Keep detail open after save', type: 'toggle', default: true },
  { id: 'clients-open-new-after-save', section: 'clients', group: 'Behavior', label: 'Open blank form after saving new client', type: 'toggle', default: false },
  { id: 'clients-inline-editing', section: 'clients', group: 'Behavior', label: 'Enable inline cell editing', type: 'toggle', default: false },
  { id: 'clients-bulk-actions', section: 'clients', group: 'Behavior', label: 'Enable bulk actions', type: 'toggle', default: true },
  { id: 'clients-multi-select', section: 'clients', group: 'Behavior', label: 'Enable multi-row selection', type: 'toggle', default: true },
  { id: 'clients-validate-email-format', section: 'clients', group: 'Behavior', label: 'Validate email format', type: 'toggle', default: true },
  { id: 'clients-validate-tax-id', section: 'clients', group: 'Behavior', label: 'Validate tax ID format', type: 'toggle', default: false },
  { id: 'clients-auto-link-invoices', section: 'clients', group: 'Behavior', label: 'Auto-link invoices to client record', type: 'toggle', default: true },
  { id: 'clients-merge-allowed', section: 'clients', group: 'Behavior', label: 'Allow merging clients', type: 'toggle', default: true },
  { id: 'clients-geocode-addresses', section: 'clients', group: 'Behavior', label: 'Geocode addresses on save', type: 'toggle', default: false },

  // ===== Notifications (133-150) =====
  { id: 'clients-notify-new-client', section: 'clients', group: 'Notifications', label: 'Notify when a client is added', type: 'toggle', default: false },
  { id: 'clients-notify-overdue', section: 'clients', group: 'Notifications', label: 'Notify on overdue balances', type: 'toggle', default: true },
  { id: 'clients-overdue-notify-threshold', section: 'clients', group: 'Notifications', label: 'Overdue notify threshold (days)', type: 'number', default: 7, min: 1, max: 90, step: 1 },
  { id: 'clients-notify-credit-limit', section: 'clients', group: 'Notifications', label: 'Notify when credit limit exceeded', type: 'toggle', default: true },
  { id: 'clients-notify-birthday', section: 'clients', group: 'Notifications', label: 'Notify on client contact birthdays', type: 'toggle', default: false },
  { id: 'clients-notify-anniversary', section: 'clients', group: 'Notifications', label: 'Notify on client anniversaries', type: 'toggle', default: false },
  { id: 'clients-notify-large-payment', section: 'clients', group: 'Notifications', label: 'Notify on large payments received', type: 'toggle', default: true },
  { id: 'clients-large-payment-amount', section: 'clients', group: 'Notifications', label: 'Large payment threshold', type: 'number', default: 5000, min: 100, max: 1000000, step: 100 },
  { id: 'clients-notify-no-activity', section: 'clients', group: 'Notifications', label: 'Notify on dormant clients', type: 'toggle', default: false },
  { id: 'clients-notification-channel', section: 'clients', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'clients-digest-frequency', section: 'clients', group: 'Notifications', label: 'Client activity digest frequency', type: 'select', default: 'weekly', options: [{ value: 'never', label: 'Never' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }] },
  { id: 'clients-notify-merge', section: 'clients', group: 'Notifications', label: 'Notify when clients are merged', type: 'toggle', default: true },
  { id: 'clients-notify-portal-signup', section: 'clients', group: 'Notifications', label: 'Notify on portal sign-up', type: 'toggle', default: true },
  { id: 'clients-notify-bounced-email', section: 'clients', group: 'Notifications', label: 'Notify on bounced client email', type: 'toggle', default: true },
  { id: 'clients-notify-disputed-invoice', section: 'clients', group: 'Notifications', label: 'Notify on disputed invoices', type: 'toggle', default: true },
  { id: 'clients-notify-sound', section: 'clients', group: 'Notifications', label: 'Play notification sound', type: 'toggle', default: false },
  { id: 'clients-notify-quiet-start', section: 'clients', group: 'Notifications', label: 'Quiet hours start', type: 'text', default: '20:00' },
  { id: 'clients-notify-quiet-end', section: 'clients', group: 'Notifications', label: 'Quiet hours end', type: 'text', default: '08:00' },

  // ===== Export (151-168) =====
  { id: 'clients-export-format', section: 'clients', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'clients-export-include-balances', section: 'clients', group: 'Export', label: 'Include balances in export', type: 'toggle', default: true },
  { id: 'clients-export-include-contacts', section: 'clients', group: 'Export', label: 'Include contact details in export', type: 'toggle', default: true },
  { id: 'clients-export-include-notes', section: 'clients', group: 'Export', label: 'Include notes in export', type: 'toggle', default: false },
  { id: 'clients-export-include-tags', section: 'clients', group: 'Export', label: 'Include tags in export', type: 'toggle', default: true },
  { id: 'clients-export-respect-filters', section: 'clients', group: 'Export', label: 'Export only filtered rows', type: 'toggle', default: true },
  { id: 'clients-export-selected-only', section: 'clients', group: 'Export', label: 'Export selected rows only', type: 'toggle', default: false },
  { id: 'clients-export-mask-tax-id', section: 'clients', group: 'Export', label: 'Mask tax IDs in export', type: 'toggle', default: true },
  { id: 'clients-export-date-stamp', section: 'clients', group: 'Export', label: 'Add date stamp to filename', type: 'toggle', default: true },
  { id: 'clients-export-filename-prefix', section: 'clients', group: 'Export', label: 'Export filename prefix', type: 'text', default: 'clients' },
  { id: 'clients-export-delimiter', section: 'clients', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'clients-export-encoding', section: 'clients', group: 'Export', label: 'Export file encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'clients-export-header-row', section: 'clients', group: 'Export', label: 'Include header row', type: 'toggle', default: true },
  { id: 'clients-pdf-orientation', section: 'clients', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'clients-pdf-include-logo', section: 'clients', group: 'Export', label: 'Include company logo in PDF', type: 'toggle', default: true },
  { id: 'clients-export-max-rows', section: 'clients', group: 'Export', label: 'Max rows per export', type: 'number', default: 10000, min: 100, max: 100000, step: 100 },
  { id: 'clients-export-open-after', section: 'clients', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'clients-export-include-statement', section: 'clients', group: 'Export', label: 'Attach account statement per client', type: 'toggle', default: false },

  // ===== Colors & Theme (169-180) =====
  { id: 'clients-active-status-color', section: 'clients', group: 'Colors & Theme', label: 'Active status color', type: 'color', default: '#22c55e' },
  { id: 'clients-inactive-status-color', section: 'clients', group: 'Colors & Theme', label: 'Inactive status color', type: 'color', default: '#94a3b8' },
  { id: 'clients-prospect-status-color', section: 'clients', group: 'Colors & Theme', label: 'Prospect status color', type: 'color', default: '#3b82f6' },
  { id: 'clients-overdue-highlight-color', section: 'clients', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#ef4444' },
  { id: 'clients-favorite-icon-color', section: 'clients', group: 'Colors & Theme', label: 'Favorite star color', type: 'color', default: '#facc15' },
  { id: 'clients-balance-positive-color', section: 'clients', group: 'Colors & Theme', label: 'Positive balance color', type: 'color', default: '#16a34a' },
  { id: 'clients-balance-negative-color', section: 'clients', group: 'Colors & Theme', label: 'Negative balance color', type: 'color', default: '#dc2626' },
  { id: 'clients-tag-default-color', section: 'clients', group: 'Colors & Theme', label: 'Default tag color', type: 'color', default: '#6366f1' },
  { id: 'clients-avatar-bg-color', section: 'clients', group: 'Colors & Theme', label: 'Avatar background color', type: 'color', default: '#1e293b' },
  { id: 'clients-row-hover-color', section: 'clients', group: 'Colors & Theme', label: 'Row hover highlight color', type: 'color', default: '#334155' },
  { id: 'clients-selected-row-color', section: 'clients', group: 'Colors & Theme', label: 'Selected row color', type: 'color', default: '#2563eb' },
  { id: 'clients-credit-warning-color', section: 'clients', group: 'Colors & Theme', label: 'Credit limit warning color', type: 'color', default: '#f59e0b' },

  // ===== Accessibility (181-190) =====
  { id: 'clients-high-contrast', section: 'clients', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'clients-font-size', section: 'clients', group: 'Accessibility', label: 'Table font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'clients-reduce-motion', section: 'clients', group: 'Accessibility', label: 'Reduce motion/animations', type: 'toggle', default: false },
  { id: 'clients-status-icons', section: 'clients', group: 'Accessibility', label: 'Use icons in addition to status colors', type: 'toggle', default: true },
  { id: 'clients-screen-reader-labels', section: 'clients', group: 'Accessibility', label: 'Verbose screen reader labels', type: 'toggle', default: true },
  { id: 'clients-focus-outline', section: 'clients', group: 'Accessibility', label: 'Visible keyboard focus outline', type: 'toggle', default: true },
  { id: 'clients-colorblind-mode', section: 'clients', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' }] },
  { id: 'clients-underline-links', section: 'clients', group: 'Accessibility', label: 'Underline email/phone links', type: 'toggle', default: true },
  { id: 'clients-min-touch-target', section: 'clients', group: 'Accessibility', label: 'Minimum touch target (px)', type: 'number', default: 40, min: 24, max: 64, step: 2 },
  { id: 'clients-tooltip-delay', section: 'clients', group: 'Accessibility', label: 'Tooltip show delay (ms)', type: 'number', default: 400, min: 0, max: 2000, step: 50 },

  // ===== Shortcuts (191-196) =====
  { id: 'clients-shortcut-new', section: 'clients', group: 'Shortcuts', label: 'New client shortcut', type: 'text', default: 'n' },
  { id: 'clients-shortcut-search', section: 'clients', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'clients-shortcut-export', section: 'clients', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'mod+e' },
  { id: 'clients-enable-shortcuts', section: 'clients', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'clients-shortcut-delete', section: 'clients', group: 'Shortcuts', label: 'Delete selected shortcut', type: 'text', default: 'mod+backspace' },
  { id: 'clients-vim-navigation', section: 'clients', group: 'Shortcuts', label: 'Enable j/k row navigation', type: 'toggle', default: false },

  // ===== Privacy (197-200) =====
  { id: 'clients-mask-balances', section: 'clients', group: 'Privacy', label: 'Mask balances until hover', type: 'toggle', default: false },
  { id: 'clients-hide-contact-info', section: 'clients', group: 'Privacy', label: 'Hide contact info from non-owners', type: 'toggle', default: false },
  { id: 'clients-audit-log-views', section: 'clients', group: 'Privacy', label: 'Log who views client records', type: 'toggle', default: false },
  { id: 'clients-redact-on-screenshare', section: 'clients', group: 'Privacy', label: 'Redact sensitive fields during screen share', type: 'toggle', default: false },
];
