// src/renderer/customization/sections/dashboard.ts
//
// Customization options for the Dashboard section. Data-only: a generic
// Customization Center renders these and persists values keyed by
// `dashboard.${id}`.

import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ───────────────────────── Layout ─────────────────────────
  { id: 'layout-density', section: 'dashboard', group: 'Layout', label: 'Layout density', description: 'Spacing between dashboard tiles.', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'grid-columns', section: 'dashboard', group: 'Layout', label: 'Grid columns', description: 'Number of tile columns on wide screens.', type: 'number', default: 3, min: 1, max: 6, step: 1 },
  { id: 'tile-gap', section: 'dashboard', group: 'Layout', label: 'Tile gap (px)', type: 'number', default: 16, min: 0, max: 48, step: 2 },
  { id: 'tile-corner-radius', section: 'dashboard', group: 'Layout', label: 'Tile corner radius (px)', type: 'number', default: 6, min: 0, max: 24, step: 1 },
  { id: 'allow-drag-reorder', section: 'dashboard', group: 'Layout', label: 'Drag to reorder tiles', type: 'toggle', default: true },
  { id: 'allow-tile-resize', section: 'dashboard', group: 'Layout', label: 'Allow tile resizing', type: 'toggle', default: true },
  { id: 'snap-to-grid', section: 'dashboard', group: 'Layout', label: 'Snap tiles to grid', type: 'toggle', default: true },
  { id: 'sticky-header', section: 'dashboard', group: 'Layout', label: 'Sticky dashboard header', type: 'toggle', default: true },
  { id: 'full-width-content', section: 'dashboard', group: 'Layout', label: 'Use full window width', type: 'toggle', default: false },
  { id: 'max-content-width', section: 'dashboard', group: 'Layout', label: 'Max content width (px)', type: 'number', default: 1440, min: 800, max: 2560, step: 80 },
  { id: 'sidebar-collapsed-default', section: 'dashboard', group: 'Layout', label: 'Collapse sidebar by default', type: 'toggle', default: false },
  { id: 'tile-shadow', section: 'dashboard', group: 'Layout', label: 'Tile drop shadow', type: 'toggle', default: true },
  { id: 'section-dividers', section: 'dashboard', group: 'Layout', label: 'Show section dividers', type: 'toggle', default: true },
  { id: 'default-layout-preset', section: 'dashboard', group: 'Layout', label: 'Default layout preset', type: 'select', default: 'balanced', options: [{ value: 'balanced', label: 'Balanced' }, { value: 'kpi-focus', label: 'KPI Focus' }, { value: 'charts-first', label: 'Charts First' }, { value: 'minimal', label: 'Minimal' }] },

  // ───────────────────────── Widgets ─────────────────────────
  { id: 'widget-cash-balance', section: 'dashboard', group: 'Widgets', label: 'Show cash balance widget', type: 'toggle', default: true },
  { id: 'widget-revenue', section: 'dashboard', group: 'Widgets', label: 'Show revenue widget', type: 'toggle', default: true },
  { id: 'widget-expenses', section: 'dashboard', group: 'Widgets', label: 'Show expenses widget', type: 'toggle', default: true },
  { id: 'widget-net-profit', section: 'dashboard', group: 'Widgets', label: 'Show net profit widget', type: 'toggle', default: true },
  { id: 'widget-ar-aging', section: 'dashboard', group: 'Widgets', label: 'Show A/R aging widget', type: 'toggle', default: true },
  { id: 'widget-ap-aging', section: 'dashboard', group: 'Widgets', label: 'Show A/P aging widget', type: 'toggle', default: true },
  { id: 'widget-overdue-invoices', section: 'dashboard', group: 'Widgets', label: 'Show overdue invoices widget', type: 'toggle', default: true },
  { id: 'widget-upcoming-bills', section: 'dashboard', group: 'Widgets', label: 'Show upcoming bills widget', type: 'toggle', default: true },
  { id: 'widget-bank-accounts', section: 'dashboard', group: 'Widgets', label: 'Show bank accounts widget', type: 'toggle', default: true },
  { id: 'widget-recent-transactions', section: 'dashboard', group: 'Widgets', label: 'Show recent transactions widget', type: 'toggle', default: true },
  { id: 'widget-top-customers', section: 'dashboard', group: 'Widgets', label: 'Show top customers widget', type: 'toggle', default: false },
  { id: 'widget-top-vendors', section: 'dashboard', group: 'Widgets', label: 'Show top vendors widget', type: 'toggle', default: false },
  { id: 'widget-tax-liability', section: 'dashboard', group: 'Widgets', label: 'Show tax liability widget', type: 'toggle', default: true },
  { id: 'widget-payroll-summary', section: 'dashboard', group: 'Widgets', label: 'Show payroll summary widget', type: 'toggle', default: false },
  { id: 'widget-loan-balances', section: 'dashboard', group: 'Widgets', label: 'Show loan balances widget', type: 'toggle', default: false },
  { id: 'widget-cash-flow-forecast', section: 'dashboard', group: 'Widgets', label: 'Show cash flow forecast widget', type: 'toggle', default: true },
  { id: 'widget-budget-vs-actual', section: 'dashboard', group: 'Widgets', label: 'Show budget vs actual widget', type: 'toggle', default: false },
  { id: 'widget-profit-margin', section: 'dashboard', group: 'Widgets', label: 'Show profit margin widget', type: 'toggle', default: false },
  { id: 'widget-burn-rate', section: 'dashboard', group: 'Widgets', label: 'Show burn rate widget', type: 'toggle', default: false },
  { id: 'widget-runway', section: 'dashboard', group: 'Widgets', label: 'Show cash runway widget', type: 'toggle', default: false },
  { id: 'widget-uncategorized', section: 'dashboard', group: 'Widgets', label: 'Show uncategorized transactions widget', type: 'toggle', default: true },
  { id: 'widget-reconciliation-status', section: 'dashboard', group: 'Widgets', label: 'Show reconciliation status widget', type: 'toggle', default: false },
  { id: 'widget-quick-actions', section: 'dashboard', group: 'Widgets', label: 'Show quick actions widget', type: 'toggle', default: true },
  { id: 'max-recent-transactions', section: 'dashboard', group: 'Widgets', label: 'Recent transactions to show', type: 'number', default: 10, min: 3, max: 50, step: 1 },
  { id: 'top-customers-count', section: 'dashboard', group: 'Widgets', label: 'Top customers to show', type: 'number', default: 5, min: 3, max: 25, step: 1 },

  // ───────────────────────── KPIs ─────────────────────────
  { id: 'kpi-primary-metric', section: 'dashboard', group: 'KPIs', label: 'Primary headline metric', type: 'select', default: 'net-profit', options: [{ value: 'revenue', label: 'Revenue' }, { value: 'net-profit', label: 'Net Profit' }, { value: 'cash-balance', label: 'Cash Balance' }, { value: 'gross-margin', label: 'Gross Margin' }] },
  { id: 'kpi-show-sparklines', section: 'dashboard', group: 'KPIs', label: 'Show sparklines on KPI cards', type: 'toggle', default: true },
  { id: 'kpi-show-trend-arrows', section: 'dashboard', group: 'KPIs', label: 'Show trend arrows', type: 'toggle', default: true },
  { id: 'kpi-show-pct-change', section: 'dashboard', group: 'KPIs', label: 'Show percent change', type: 'toggle', default: true },
  { id: 'kpi-comparison-period', section: 'dashboard', group: 'KPIs', label: 'KPI comparison period', type: 'select', default: 'prior-period', options: [{ value: 'prior-period', label: 'Prior Period' }, { value: 'prior-year', label: 'Prior Year' }, { value: 'budget', label: 'Budget' }, { value: 'none', label: 'None' }] },
  { id: 'kpi-card-size', section: 'dashboard', group: 'KPIs', label: 'KPI card size', type: 'select', default: 'medium', options: [{ value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large' }] },
  { id: 'kpi-decimal-places', section: 'dashboard', group: 'KPIs', label: 'KPI decimal places', type: 'number', default: 0, min: 0, max: 4, step: 1 },
  { id: 'kpi-abbreviate-large', section: 'dashboard', group: 'KPIs', label: 'Abbreviate large numbers (1.2M)', type: 'toggle', default: true },
  { id: 'kpi-show-target-bar', section: 'dashboard', group: 'KPIs', label: 'Show target progress bar', type: 'toggle', default: false },
  { id: 'kpi-color-positive', section: 'dashboard', group: 'KPIs', label: 'Positive trend color', type: 'color', default: '#22c55e' },
  { id: 'kpi-color-negative', section: 'dashboard', group: 'KPIs', label: 'Negative trend color', type: 'color', default: '#ef4444' },
  { id: 'kpi-color-neutral', section: 'dashboard', group: 'KPIs', label: 'Neutral trend color', type: 'color', default: '#94a3b8' },
  { id: 'kpi-invert-expense-colors', section: 'dashboard', group: 'KPIs', label: 'Invert colors for expense KPIs', description: 'Lower expenses shown green.', type: 'toggle', default: true },
  { id: 'kpi-animate-count', section: 'dashboard', group: 'KPIs', label: 'Animate number count-up', type: 'toggle', default: true },
  { id: 'kpi-revenue-target', section: 'dashboard', group: 'KPIs', label: 'Monthly revenue target', type: 'number', default: 0, min: 0, max: 100000000, step: 1000 },
  { id: 'kpi-profit-margin-target', section: 'dashboard', group: 'KPIs', label: 'Target profit margin (%)', type: 'number', default: 20, min: 0, max: 100, step: 1 },

  // ───────────────────────── Charts ─────────────────────────
  { id: 'chart-revenue-type', section: 'dashboard', group: 'Charts', label: 'Revenue chart type', type: 'select', default: 'bar', options: [{ value: 'bar', label: 'Bar' }, { value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }] },
  { id: 'chart-expense-breakdown-type', section: 'dashboard', group: 'Charts', label: 'Expense breakdown chart', type: 'select', default: 'donut', options: [{ value: 'pie', label: 'Pie' }, { value: 'donut', label: 'Donut' }, { value: 'bar', label: 'Bar' }, { value: 'treemap', label: 'Treemap' }] },
  { id: 'chart-cashflow-type', section: 'dashboard', group: 'Charts', label: 'Cash flow chart type', type: 'select', default: 'area', options: [{ value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }, { value: 'bar', label: 'Bar' }] },
  { id: 'chart-show-gridlines', section: 'dashboard', group: 'Charts', label: 'Show chart gridlines', type: 'toggle', default: true },
  { id: 'chart-show-data-labels', section: 'dashboard', group: 'Charts', label: 'Show data labels on points', type: 'toggle', default: false },
  { id: 'chart-show-legend', section: 'dashboard', group: 'Charts', label: 'Show chart legend', type: 'toggle', default: true },
  { id: 'chart-legend-position', section: 'dashboard', group: 'Charts', label: 'Legend position', type: 'select', default: 'bottom', options: [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }, { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }] },
  { id: 'chart-smooth-lines', section: 'dashboard', group: 'Charts', label: 'Smooth (curved) lines', type: 'toggle', default: true },
  { id: 'chart-fill-opacity', section: 'dashboard', group: 'Charts', label: 'Area fill opacity (%)', type: 'number', default: 30, min: 0, max: 100, step: 5 },
  { id: 'chart-animation', section: 'dashboard', group: 'Charts', label: 'Animate charts on load', type: 'toggle', default: true },
  { id: 'chart-animation-duration', section: 'dashboard', group: 'Charts', label: 'Chart animation duration (ms)', type: 'number', default: 600, min: 0, max: 2000, step: 50 },
  { id: 'chart-tooltip-mode', section: 'dashboard', group: 'Charts', label: 'Tooltip mode', type: 'select', default: 'nearest', options: [{ value: 'nearest', label: 'Nearest point' }, { value: 'index', label: 'All series at index' }, { value: 'off', label: 'Off' }] },
  { id: 'chart-stacked-expenses', section: 'dashboard', group: 'Charts', label: 'Stack expense categories', type: 'toggle', default: false },
  { id: 'chart-show-zero-baseline', section: 'dashboard', group: 'Charts', label: 'Always include zero baseline', type: 'toggle', default: true },
  { id: 'chart-max-categories', section: 'dashboard', group: 'Charts', label: 'Max categories before "Other"', type: 'number', default: 8, min: 3, max: 20, step: 1 },
  { id: 'chart-color-scheme', section: 'dashboard', group: 'Charts', label: 'Chart color scheme', type: 'select', default: 'default', options: [{ value: 'default', label: 'Default' }, { value: 'vibrant', label: 'Vibrant' }, { value: 'pastel', label: 'Pastel' }, { value: 'monochrome', label: 'Monochrome' }, { value: 'colorblind', label: 'Colorblind-safe' }] },

  // ───────────────────────── Date & Period ─────────────────────────
  { id: 'default-date-range', section: 'dashboard', group: 'Date & Period', label: 'Default date range', type: 'select', default: 'this-month', options: [{ value: 'today', label: 'Today' }, { value: 'this-week', label: 'This Week' }, { value: 'this-month', label: 'This Month' }, { value: 'this-quarter', label: 'This Quarter' }, { value: 'this-year', label: 'This Year' }, { value: 'custom', label: 'Custom' }] },
  { id: 'fiscal-year-start-month', section: 'dashboard', group: 'Date & Period', label: 'Fiscal year start month', type: 'select', default: 'january', options: [{ value: 'january', label: 'January' }, { value: 'april', label: 'April' }, { value: 'july', label: 'July' }, { value: 'october', label: 'October' }] },
  { id: 'week-start-day', section: 'dashboard', group: 'Date & Period', label: 'Week starts on', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },
  { id: 'compare-to-prior-period', section: 'dashboard', group: 'Date & Period', label: 'Compare to prior period by default', type: 'toggle', default: true },
  { id: 'remember-last-range', section: 'dashboard', group: 'Date & Period', label: 'Remember last selected range', type: 'toggle', default: true },
  { id: 'forecast-horizon-months', section: 'dashboard', group: 'Date & Period', label: 'Cash flow forecast horizon (months)', type: 'number', default: 6, min: 1, max: 24, step: 1 },
  { id: 'trend-period-count', section: 'dashboard', group: 'Date & Period', label: 'Trend chart periods shown', type: 'number', default: 12, min: 3, max: 36, step: 1 },
  { id: 'trend-granularity', section: 'dashboard', group: 'Date & Period', label: 'Trend granularity', type: 'select', default: 'monthly', options: [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },

  // ───────────────────────── Formatting ─────────────────────────
  { id: 'currency-code', section: 'dashboard', group: 'Formatting', label: 'Display currency', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD ($)' }, { value: 'EUR', label: 'EUR (€)' }, { value: 'GBP', label: 'GBP (£)' }, { value: 'CAD', label: 'CAD ($)' }, { value: 'AUD', label: 'AUD ($)' }] },
  { id: 'currency-symbol-position', section: 'dashboard', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($100)' }, { value: 'after', label: 'After (100$)' }] },
  { id: 'thousands-separator', section: 'dashboard', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'decimal-separator', section: 'dashboard', group: 'Formatting', label: 'Decimal separator', type: 'select', default: 'period', options: [{ value: 'period', label: 'Period (1.50)' }, { value: 'comma', label: 'Comma (1,50)' }] },
  { id: 'currency-decimals', section: 'dashboard', group: 'Formatting', label: 'Currency decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'negative-format', section: 'dashboard', group: 'Formatting', label: 'Negative number format', type: 'select', default: 'parentheses', options: [{ value: 'minus', label: 'Minus (-100)' }, { value: 'parentheses', label: 'Parentheses (100)' }, { value: 'red', label: 'Red text' }] },
  { id: 'date-format', section: 'dashboard', group: 'Formatting', label: 'Date format', type: 'select', default: 'MM/DD/YYYY', options: [{ value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' }, { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' }, { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' }, { value: 'DD MMM YYYY', label: 'DD MMM YYYY' }] },
  { id: 'show-currency-code', section: 'dashboard', group: 'Formatting', label: 'Show currency code (USD)', type: 'toggle', default: false },
  { id: 'percent-decimals', section: 'dashboard', group: 'Formatting', label: 'Percentage decimal places', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'round-to-whole', section: 'dashboard', group: 'Formatting', label: 'Round amounts to whole numbers', type: 'toggle', default: false },
  { id: 'relative-dates', section: 'dashboard', group: 'Formatting', label: 'Use relative dates ("2 days ago")', type: 'toggle', default: true },

  // ───────────────────────── Colors & Theme ─────────────────────────
  { id: 'theme-mode', section: 'dashboard', group: 'Colors & Theme', label: 'Theme mode', type: 'select', default: 'dark', options: [{ value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }, { value: 'system', label: 'System' }] },
  { id: 'accent-color', section: 'dashboard', group: 'Colors & Theme', label: 'Accent color', type: 'color', default: '#3b82f6' },
  { id: 'revenue-color', section: 'dashboard', group: 'Colors & Theme', label: 'Revenue series color', type: 'color', default: '#22c55e' },
  { id: 'expense-color', section: 'dashboard', group: 'Colors & Theme', label: 'Expense series color', type: 'color', default: '#ef4444' },
  { id: 'profit-color', section: 'dashboard', group: 'Colors & Theme', label: 'Profit series color', type: 'color', default: '#3b82f6' },
  { id: 'cash-color', section: 'dashboard', group: 'Colors & Theme', label: 'Cash series color', type: 'color', default: '#06b6d4' },
  { id: 'tile-background-color', section: 'dashboard', group: 'Colors & Theme', label: 'Tile background color', type: 'color', default: '#111827' },
  { id: 'dashboard-background-color', section: 'dashboard', group: 'Colors & Theme', label: 'Dashboard background color', type: 'color', default: '#0b1120' },
  { id: 'grid-line-color', section: 'dashboard', group: 'Colors & Theme', label: 'Chart gridline color', type: 'color', default: '#1f2937' },
  { id: 'overdue-highlight-color', section: 'dashboard', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#f59e0b' },
  { id: 'use-category-colors', section: 'dashboard', group: 'Colors & Theme', label: 'Use per-category colors', type: 'toggle', default: true },
  { id: 'high-contrast-tiles', section: 'dashboard', group: 'Colors & Theme', label: 'High-contrast tile borders', type: 'toggle', default: false },
  { id: 'glass-effect', section: 'dashboard', group: 'Colors & Theme', label: 'Glass blur effect on tiles', type: 'toggle', default: true },

  // ───────────────────────── Behavior ─────────────────────────
  { id: 'auto-refresh', section: 'dashboard', group: 'Behavior', label: 'Auto-refresh data', type: 'toggle', default: true },
  { id: 'auto-refresh-interval', section: 'dashboard', group: 'Behavior', label: 'Auto-refresh interval (seconds)', type: 'number', default: 60, min: 10, max: 3600, step: 10 },
  { id: 'confirm-before-leaving', section: 'dashboard', group: 'Behavior', label: 'Confirm before leaving with unsaved layout', type: 'toggle', default: true },
  { id: 'open-drilldown-in-modal', section: 'dashboard', group: 'Behavior', label: 'Open drill-downs in modal', type: 'toggle', default: true },
  { id: 'click-tile-to-expand', section: 'dashboard', group: 'Behavior', label: 'Click tile title to expand', type: 'toggle', default: true },
  { id: 'remember-collapsed-tiles', section: 'dashboard', group: 'Behavior', label: 'Remember collapsed tiles', type: 'toggle', default: true },
  { id: 'lazy-load-tiles', section: 'dashboard', group: 'Behavior', label: 'Lazy-load below-fold tiles', type: 'toggle', default: true },
  { id: 'show-loading-skeletons', section: 'dashboard', group: 'Behavior', label: 'Show loading skeletons', type: 'toggle', default: true },
  { id: 'tooltip-delay', section: 'dashboard', group: 'Behavior', label: 'Tooltip hover delay (ms)', type: 'number', default: 300, min: 0, max: 1500, step: 50 },
  { id: 'landing-module', section: 'dashboard', group: 'Behavior', label: 'Landing module on launch', type: 'select', default: 'dashboard', options: [{ value: 'dashboard', label: 'Dashboard' }, { value: 'invoices', label: 'Invoices' }, { value: 'banking', label: 'Banking' }, { value: 'reports', label: 'Reports' }] },
  { id: 'animate-tile-transitions', section: 'dashboard', group: 'Behavior', label: 'Animate tile transitions', type: 'toggle', default: true },
  { id: 'pin-favorite-tiles-top', section: 'dashboard', group: 'Behavior', label: 'Pin favorite tiles to top', type: 'toggle', default: false },

  // ───────────────────────── Alerts & Thresholds ─────────────────────────
  { id: 'low-cash-alert-enabled', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Low cash balance alert', type: 'toggle', default: true },
  { id: 'low-cash-threshold', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Low cash threshold', type: 'number', default: 5000, min: 0, max: 10000000, step: 500 },
  { id: 'overdue-alert-enabled', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Overdue invoice alert', type: 'toggle', default: true },
  { id: 'overdue-alert-days', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Flag invoices overdue after (days)', type: 'number', default: 30, min: 1, max: 180, step: 1 },
  { id: 'expense-spike-alert', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Expense spike alert', type: 'toggle', default: false },
  { id: 'expense-spike-pct', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Expense spike threshold (%)', type: 'number', default: 25, min: 5, max: 200, step: 5 },
  { id: 'low-margin-alert', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Low profit margin alert', type: 'toggle', default: false },
  { id: 'low-margin-threshold', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Low margin threshold (%)', type: 'number', default: 10, min: 0, max: 100, step: 1 },
  { id: 'tax-due-reminder', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Tax filing due reminder', type: 'toggle', default: true },
  { id: 'tax-due-lead-days', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Tax reminder lead time (days)', type: 'number', default: 14, min: 1, max: 90, step: 1 },
  { id: 'uncategorized-alert', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Uncategorized transactions alert', type: 'toggle', default: true },
  { id: 'uncategorized-threshold', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Alert when uncategorized exceeds', type: 'number', default: 10, min: 1, max: 500, step: 1 },
  { id: 'runway-alert-enabled', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Short runway alert', type: 'toggle', default: false },
  { id: 'runway-alert-months', section: 'dashboard', group: 'Alerts & Thresholds', label: 'Alert when runway under (months)', type: 'number', default: 3, min: 1, max: 24, step: 1 },

  // ───────────────────────── Notifications ─────────────────────────
  { id: 'notify-in-app', section: 'dashboard', group: 'Notifications', label: 'In-app notifications', type: 'toggle', default: true },
  { id: 'notify-desktop', section: 'dashboard', group: 'Notifications', label: 'Desktop notifications', type: 'toggle', default: false },
  { id: 'notify-sound', section: 'dashboard', group: 'Notifications', label: 'Play notification sound', type: 'toggle', default: false },
  { id: 'notify-daily-summary', section: 'dashboard', group: 'Notifications', label: 'Daily summary notification', type: 'toggle', default: false },
  { id: 'notify-summary-time', section: 'dashboard', group: 'Notifications', label: 'Daily summary time', type: 'text', default: '08:00' },
  { id: 'notify-weekly-digest', section: 'dashboard', group: 'Notifications', label: 'Weekly digest email', type: 'toggle', default: false },
  { id: 'notify-digest-day', section: 'dashboard', group: 'Notifications', label: 'Weekly digest day', type: 'select', default: 'monday', options: [{ value: 'monday', label: 'Monday' }, { value: 'friday', label: 'Friday' }, { value: 'sunday', label: 'Sunday' }] },
  { id: 'notify-overdue', section: 'dashboard', group: 'Notifications', label: 'Notify on new overdue invoice', type: 'toggle', default: true },
  { id: 'notify-large-transaction', section: 'dashboard', group: 'Notifications', label: 'Notify on large transaction', type: 'toggle', default: false },
  { id: 'notify-large-amount', section: 'dashboard', group: 'Notifications', label: 'Large transaction amount', type: 'number', default: 10000, min: 100, max: 10000000, step: 500 },
  { id: 'notify-backup', section: 'dashboard', group: 'Notifications', label: 'Notify on backup completion', type: 'toggle', default: false },

  // ───────────────────────── Export ─────────────────────────
  { id: 'export-default-format', section: 'dashboard', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [{ value: 'pdf', label: 'PDF' }, { value: 'png', label: 'PNG' }, { value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }] },
  { id: 'export-include-charts', section: 'dashboard', group: 'Export', label: 'Include charts in export', type: 'toggle', default: true },
  { id: 'export-include-logo', section: 'dashboard', group: 'Export', label: 'Include company logo', type: 'toggle', default: true },
  { id: 'export-include-timestamp', section: 'dashboard', group: 'Export', label: 'Include generated timestamp', type: 'toggle', default: true },
  { id: 'export-page-orientation', section: 'dashboard', group: 'Export', label: 'PDF page orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'export-page-size', section: 'dashboard', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'export-filename-prefix', section: 'dashboard', group: 'Export', label: 'Export filename prefix', type: 'text', default: 'dashboard' },
  { id: 'export-csv-delimiter', section: 'dashboard', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'export-open-after', section: 'dashboard', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'export-default-folder', section: 'dashboard', group: 'Export', label: 'Default export folder', type: 'text', default: '~/Downloads' },

  // ───────────────────────── Accessibility ─────────────────────────
  { id: 'reduce-motion', section: 'dashboard', group: 'Accessibility', label: 'Reduce motion / animations', type: 'toggle', default: false },
  { id: 'font-scale', section: 'dashboard', group: 'Accessibility', label: 'Font scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'high-contrast-mode', section: 'dashboard', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'colorblind-mode', section: 'dashboard', group: 'Accessibility', label: 'Colorblind-friendly palette', type: 'toggle', default: false },
  { id: 'use-patterns-in-charts', section: 'dashboard', group: 'Accessibility', label: 'Use patterns (not just color) in charts', type: 'toggle', default: false },
  { id: 'focus-ring-visible', section: 'dashboard', group: 'Accessibility', label: 'Always show keyboard focus ring', type: 'toggle', default: true },
  { id: 'larger-click-targets', section: 'dashboard', group: 'Accessibility', label: 'Larger click targets', type: 'toggle', default: false },
  { id: 'screen-reader-summaries', section: 'dashboard', group: 'Accessibility', label: 'Screen reader chart summaries', type: 'toggle', default: true },

  // ───────────────────────── Shortcuts ─────────────────────────
  { id: 'enable-shortcuts', section: 'dashboard', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'shortcut-refresh', section: 'dashboard', group: 'Shortcuts', label: 'Refresh shortcut', type: 'text', default: 'R' },
  { id: 'shortcut-new-invoice', section: 'dashboard', group: 'Shortcuts', label: 'New invoice shortcut', type: 'text', default: 'I' },
  { id: 'shortcut-new-expense', section: 'dashboard', group: 'Shortcuts', label: 'New expense shortcut', type: 'text', default: 'E' },
  { id: 'shortcut-search', section: 'dashboard', group: 'Shortcuts', label: 'Global search shortcut', type: 'text', default: 'Cmd+K' },
  { id: 'shortcut-toggle-sidebar', section: 'dashboard', group: 'Shortcuts', label: 'Toggle sidebar shortcut', type: 'text', default: 'Cmd+B' },
  { id: 'shortcut-export', section: 'dashboard', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'Cmd+E' },
  { id: 'shortcut-next-period', section: 'dashboard', group: 'Shortcuts', label: 'Next period shortcut', type: 'text', default: ']' },
  { id: 'shortcut-prev-period', section: 'dashboard', group: 'Shortcuts', label: 'Previous period shortcut', type: 'text', default: '[' },

  // ───────────────────────── Data & Sources ─────────────────────────
  { id: 'include-draft-invoices', section: 'dashboard', group: 'Data & Sources', label: 'Include draft invoices in totals', type: 'toggle', default: false },
  { id: 'include-pending-payments', section: 'dashboard', group: 'Data & Sources', label: 'Include pending payments', type: 'toggle', default: true },
  { id: 'cash-vs-accrual', section: 'dashboard', group: 'Data & Sources', label: 'Accounting basis', type: 'select', default: 'accrual', options: [{ value: 'cash', label: 'Cash' }, { value: 'accrual', label: 'Accrual' }] },
  { id: 'include-transfers', section: 'dashboard', group: 'Data & Sources', label: 'Include internal transfers', type: 'toggle', default: false },
  { id: 'exclude-zero-amounts', section: 'dashboard', group: 'Data & Sources', label: 'Exclude zero-amount entries', type: 'toggle', default: true },
  { id: 'multi-company-rollup', section: 'dashboard', group: 'Data & Sources', label: 'Roll up all companies', type: 'toggle', default: false },
  { id: 'default-bank-account', section: 'dashboard', group: 'Data & Sources', label: 'Primary bank account for cash tile', type: 'text', default: '' },
  { id: 'cache-data', section: 'dashboard', group: 'Data & Sources', label: 'Cache dashboard data locally', type: 'toggle', default: true },
  { id: 'show-data-freshness', section: 'dashboard', group: 'Data & Sources', label: 'Show "last updated" timestamp', type: 'toggle', default: true },
  { id: 'rounding-mode', section: 'dashboard', group: 'Data & Sources', label: 'Rounding mode', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Half up' }, { value: 'half-even', label: 'Half even (banker)' }, { value: 'truncate', label: 'Truncate' }] },

  // ───────────────────────── Privacy ─────────────────────────
  { id: 'blur-amounts', section: 'dashboard', group: 'Privacy', label: 'Blur amounts until hover', type: 'toggle', default: false },
  { id: 'hide-amounts-on-idle', section: 'dashboard', group: 'Privacy', label: 'Hide amounts when idle', type: 'toggle', default: false },
  { id: 'idle-hide-delay', section: 'dashboard', group: 'Privacy', label: 'Idle hide delay (seconds)', type: 'number', default: 120, min: 15, max: 1800, step: 15 },
  { id: 'mask-account-numbers', section: 'dashboard', group: 'Privacy', label: 'Mask bank account numbers', type: 'toggle', default: true },
  { id: 'presentation-mode', section: 'dashboard', group: 'Privacy', label: 'Presentation mode (hide sensitive tiles)', type: 'toggle', default: false },
  { id: 'require-pin-on-open', section: 'dashboard', group: 'Privacy', label: 'Require PIN to view dashboard', type: 'toggle', default: false },

  // ───────────────────────── Quick Actions ─────────────────────────
  { id: 'qa-show-new-invoice', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: New invoice', type: 'toggle', default: true },
  { id: 'qa-show-new-expense', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: New expense', type: 'toggle', default: true },
  { id: 'qa-show-record-payment', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: Record payment', type: 'toggle', default: true },
  { id: 'qa-show-new-bill', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: New bill', type: 'toggle', default: false },
  { id: 'qa-show-reconcile', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: Reconcile', type: 'toggle', default: false },
  { id: 'qa-show-run-report', section: 'dashboard', group: 'Quick Actions', label: 'Quick action: Run report', type: 'toggle', default: true },
  { id: 'qa-button-style', section: 'dashboard', group: 'Quick Actions', label: 'Quick action button style', type: 'select', default: 'icon-text', options: [{ value: 'icon', label: 'Icon only' }, { value: 'text', label: 'Text only' }, { value: 'icon-text', label: 'Icon + Text' }] },
  { id: 'qa-max-buttons', section: 'dashboard', group: 'Quick Actions', label: 'Max quick action buttons', type: 'number', default: 6, min: 2, max: 12, step: 1 },
  { id: 'qa-position', section: 'dashboard', group: 'Quick Actions', label: 'Quick actions position', type: 'select', default: 'top', options: [{ value: 'top', label: 'Top bar' }, { value: 'floating', label: 'Floating button' }, { value: 'tile', label: 'As tile' }] },

  // ───────────────────────── Tables ─────────────────────────
  { id: 'table-row-density', section: 'dashboard', group: 'Tables', label: 'Table row density', type: 'select', default: 'normal', options: [{ value: 'compact', label: 'Compact' }, { value: 'normal', label: 'Normal' }, { value: 'relaxed', label: 'Relaxed' }] },
  { id: 'table-zebra-striping', section: 'dashboard', group: 'Tables', label: 'Zebra striping', type: 'toggle', default: true },
  { id: 'table-show-row-hover', section: 'dashboard', group: 'Tables', label: 'Highlight row on hover', type: 'toggle', default: true },
  { id: 'table-sticky-header', section: 'dashboard', group: 'Tables', label: 'Sticky table headers', type: 'toggle', default: true },
  { id: 'table-default-sort', section: 'dashboard', group: 'Tables', label: 'Default sort for lists', type: 'select', default: 'date-desc', options: [{ value: 'date-desc', label: 'Date (newest)' }, { value: 'date-asc', label: 'Date (oldest)' }, { value: 'amount-desc', label: 'Amount (high to low)' }, { value: 'amount-asc', label: 'Amount (low to high)' }] },
  { id: 'table-show-running-total', section: 'dashboard', group: 'Tables', label: 'Show running total column', type: 'toggle', default: false },
  { id: 'table-column-count', section: 'dashboard', group: 'Tables', label: 'Recent transactions columns', type: 'number', default: 4, min: 2, max: 8, step: 1 },
  { id: 'table-show-status-pills', section: 'dashboard', group: 'Tables', label: 'Show status pills', type: 'toggle', default: true },
];
