import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-18) =====
  { id: 'dc-display-default-view', section: 'debt-collection', group: 'Display', label: 'Default view', description: 'Initial layout when opening Debt Collection', type: 'select', default: 'list', options: [{ value: 'list', label: 'List' }, { value: 'kanban', label: 'Kanban board' }, { value: 'calendar', label: 'Calendar' }, { value: 'cards', label: 'Cards' }] },
  { id: 'dc-display-density', section: 'debt-collection', group: 'Display', label: 'Row density', description: 'Vertical spacing of account rows', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'dc-display-rows-per-page', section: 'debt-collection', group: 'Display', label: 'Accounts per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'dc-display-show-avatars', section: 'debt-collection', group: 'Display', label: 'Show debtor avatars', type: 'toggle', default: true },
  { id: 'dc-display-show-aging-bars', section: 'debt-collection', group: 'Display', label: 'Show aging progress bars', description: 'Visual bar indicating days overdue', type: 'toggle', default: true },
  { id: 'dc-display-show-collector-column', section: 'debt-collection', group: 'Display', label: 'Show assigned collector', type: 'toggle', default: true },
  { id: 'dc-display-sticky-header', section: 'debt-collection', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'dc-display-highlight-promise', section: 'debt-collection', group: 'Display', label: 'Highlight promise-to-pay accounts', type: 'toggle', default: true },
  { id: 'dc-display-show-priority-flag', section: 'debt-collection', group: 'Display', label: 'Show priority flag icons', type: 'toggle', default: true },
  { id: 'dc-display-balance-emphasis', section: 'debt-collection', group: 'Display', label: 'Emphasize balance amount', description: 'Bold/larger balance text', type: 'toggle', default: true },
  { id: 'dc-display-show-last-contact', section: 'debt-collection', group: 'Display', label: 'Show last contact date', type: 'toggle', default: true },
  { id: 'dc-display-show-next-action', section: 'debt-collection', group: 'Display', label: 'Show next scheduled action', type: 'toggle', default: true },
  { id: 'dc-display-summary-banner', section: 'debt-collection', group: 'Display', label: 'Show summary banner', description: 'Totals and counts above the list', type: 'toggle', default: true },
  { id: 'dc-display-show-thumbnails', section: 'debt-collection', group: 'Display', label: 'Show document thumbnails', type: 'toggle', default: false },
  { id: 'dc-display-collapse-resolved', section: 'debt-collection', group: 'Display', label: 'Collapse resolved accounts', type: 'toggle', default: true },
  { id: 'dc-display-zebra-striping', section: 'debt-collection', group: 'Display', label: 'Zebra-stripe rows', type: 'toggle', default: false },
  { id: 'dc-display-show-account-age-tooltip', section: 'debt-collection', group: 'Display', label: 'Show account age tooltip on hover', type: 'toggle', default: true },
  { id: 'dc-display-pinned-accounts', section: 'debt-collection', group: 'Display', label: 'Pin flagged accounts to top', type: 'toggle', default: true },

  // ===== Columns (19-40) =====
  { id: 'dc-col-account-number', section: 'debt-collection', group: 'Columns', label: 'Account number column', type: 'toggle', default: true },
  { id: 'dc-col-debtor-name', section: 'debt-collection', group: 'Columns', label: 'Debtor name column', type: 'toggle', default: true },
  { id: 'dc-col-original-balance', section: 'debt-collection', group: 'Columns', label: 'Original balance column', type: 'toggle', default: false },
  { id: 'dc-col-current-balance', section: 'debt-collection', group: 'Columns', label: 'Current balance column', type: 'toggle', default: true },
  { id: 'dc-col-days-overdue', section: 'debt-collection', group: 'Columns', label: 'Days overdue column', type: 'toggle', default: true },
  { id: 'dc-col-aging-bucket', section: 'debt-collection', group: 'Columns', label: 'Aging bucket column', type: 'toggle', default: true },
  { id: 'dc-col-status', section: 'debt-collection', group: 'Columns', label: 'Status column', type: 'toggle', default: true },
  { id: 'dc-col-collector', section: 'debt-collection', group: 'Columns', label: 'Assigned collector column', type: 'toggle', default: true },
  { id: 'dc-col-phone', section: 'debt-collection', group: 'Columns', label: 'Phone number column', type: 'toggle', default: false },
  { id: 'dc-col-email', section: 'debt-collection', group: 'Columns', label: 'Email column', type: 'toggle', default: false },
  { id: 'dc-col-last-payment-date', section: 'debt-collection', group: 'Columns', label: 'Last payment date column', type: 'toggle', default: true },
  { id: 'dc-col-last-payment-amount', section: 'debt-collection', group: 'Columns', label: 'Last payment amount column', type: 'toggle', default: false },
  { id: 'dc-col-promise-date', section: 'debt-collection', group: 'Columns', label: 'Promise-to-pay date column', type: 'toggle', default: true },
  { id: 'dc-col-attempts', section: 'debt-collection', group: 'Columns', label: 'Contact attempts count column', type: 'toggle', default: true },
  { id: 'dc-col-dispute-flag', section: 'debt-collection', group: 'Columns', label: 'Dispute flag column', type: 'toggle', default: true },
  { id: 'dc-col-recovery-rate', section: 'debt-collection', group: 'Columns', label: 'Recovery rate column', type: 'toggle', default: false },
  { id: 'dc-col-original-invoice', section: 'debt-collection', group: 'Columns', label: 'Original invoice reference column', type: 'toggle', default: false },
  { id: 'dc-col-agency', section: 'debt-collection', group: 'Columns', label: 'Collection agency column', type: 'toggle', default: false },
  { id: 'dc-col-priority-score', section: 'debt-collection', group: 'Columns', label: 'Priority score column', type: 'toggle', default: false },
  { id: 'dc-col-next-action-date', section: 'debt-collection', group: 'Columns', label: 'Next action date column', type: 'toggle', default: true },
  { id: 'dc-col-fees', section: 'debt-collection', group: 'Columns', label: 'Late fees / interest column', type: 'toggle', default: false },
  { id: 'dc-col-order', section: 'debt-collection', group: 'Columns', label: 'Custom column order', description: 'Comma-separated column keys', type: 'text', default: 'account,name,balance,overdue,status' },

  // ===== Formatting (41-58) =====
  { id: 'dc-fmt-currency-symbol', section: 'debt-collection', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'dc-fmt-currency-position', section: 'debt-collection', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'dc-fmt-decimal-places', section: 'debt-collection', group: 'Formatting', label: 'Decimal places for amounts', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'dc-fmt-thousands-separator', section: 'debt-collection', group: 'Formatting', label: 'Use thousands separator', type: 'toggle', default: true },
  { id: 'dc-fmt-negative-style', section: 'debt-collection', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'parentheses', options: [{ value: 'minus', label: 'Minus sign' }, { value: 'parentheses', label: 'Parentheses' }, { value: 'red', label: 'Red text' }] },
  { id: 'dc-fmt-date-format', section: 'debt-collection', group: 'Formatting', label: 'Date format', type: 'select', default: 'mm-dd-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }] },
  { id: 'dc-fmt-relative-dates', section: 'debt-collection', group: 'Formatting', label: 'Show relative dates', description: 'e.g. "3 days ago"', type: 'toggle', default: true },
  { id: 'dc-fmt-overdue-unit', section: 'debt-collection', group: 'Formatting', label: 'Overdue duration unit', type: 'select', default: 'days', options: [{ value: 'days', label: 'Days' }, { value: 'weeks', label: 'Weeks' }, { value: 'months', label: 'Months' }] },
  { id: 'dc-fmt-phone-format', section: 'debt-collection', group: 'Formatting', label: 'Phone number format', type: 'select', default: 'national', options: [{ value: 'national', label: '(555) 123-4567' }, { value: 'international', label: '+1 555 123 4567' }, { value: 'raw', label: 'Unformatted' }] },
  { id: 'dc-fmt-percent-decimals', section: 'debt-collection', group: 'Formatting', label: 'Percentage decimal places', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'dc-fmt-name-order', section: 'debt-collection', group: 'Formatting', label: 'Debtor name order', type: 'select', default: 'first-last', options: [{ value: 'first-last', label: 'First Last' }, { value: 'last-first', label: 'Last, First' }] },
  { id: 'dc-fmt-account-mask', section: 'debt-collection', group: 'Formatting', label: 'Mask account numbers', description: 'Show only last 4 digits', type: 'toggle', default: false },
  { id: 'dc-fmt-rounding', section: 'debt-collection', group: 'Formatting', label: 'Round balances to whole', type: 'toggle', default: false },
  { id: 'dc-fmt-time-format', section: 'debt-collection', group: 'Formatting', label: 'Time format', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'dc-fmt-bucket-labels', section: 'debt-collection', group: 'Formatting', label: 'Aging bucket label style', type: 'select', default: 'ranges', options: [{ value: 'ranges', label: '31-60 days' }, { value: 'short', label: '60d' }, { value: 'words', label: 'Two months' }] },
  { id: 'dc-fmt-zero-balance-text', section: 'debt-collection', group: 'Formatting', label: 'Zero balance display text', type: 'text', default: 'Paid' },
  { id: 'dc-fmt-locale', section: 'debt-collection', group: 'Formatting', label: 'Number locale', type: 'text', default: 'en-US' },
  { id: 'dc-fmt-truncate-notes', section: 'debt-collection', group: 'Formatting', label: 'Truncate note preview length', type: 'number', default: 80, min: 20, max: 300, step: 10 },

  // ===== Defaults (59-78) =====
  { id: 'dc-def-overdue-threshold', section: 'debt-collection', group: 'Defaults', label: 'Days overdue to enter collection', type: 'number', default: 30, min: 1, max: 180, step: 1 },
  { id: 'dc-def-status', section: 'debt-collection', group: 'Defaults', label: 'Default new account status', type: 'select', default: 'new', options: [{ value: 'new', label: 'New' }, { value: 'in-progress', label: 'In progress' }, { value: 'pending', label: 'Pending review' }] },
  { id: 'dc-def-collector', section: 'debt-collection', group: 'Defaults', label: 'Default assigned collector', type: 'text', default: '' },
  { id: 'dc-def-priority', section: 'debt-collection', group: 'Defaults', label: 'Default priority', type: 'select', default: 'medium', options: [{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'urgent', label: 'Urgent' }] },
  { id: 'dc-def-late-fee-percent', section: 'debt-collection', group: 'Defaults', label: 'Default late fee percent', type: 'number', default: 1.5, min: 0, max: 25, step: 0.5 },
  { id: 'dc-def-interest-rate', section: 'debt-collection', group: 'Defaults', label: 'Default monthly interest rate', type: 'number', default: 1.5, min: 0, max: 10, step: 0.25 },
  { id: 'dc-def-grace-period', section: 'debt-collection', group: 'Defaults', label: 'Grace period days before fees', type: 'number', default: 10, min: 0, max: 60, step: 1 },
  { id: 'dc-def-promise-window', section: 'debt-collection', group: 'Defaults', label: 'Default promise-to-pay window days', type: 'number', default: 14, min: 1, max: 90, step: 1 },
  { id: 'dc-def-contact-method', section: 'debt-collection', group: 'Defaults', label: 'Default first contact method', type: 'select', default: 'email', options: [{ value: 'email', label: 'Email' }, { value: 'phone', label: 'Phone' }, { value: 'letter', label: 'Letter' }, { value: 'sms', label: 'SMS' }] },
  { id: 'dc-def-followup-interval', section: 'debt-collection', group: 'Defaults', label: 'Default follow-up interval days', type: 'number', default: 7, min: 1, max: 60, step: 1 },
  { id: 'dc-def-max-attempts', section: 'debt-collection', group: 'Defaults', label: 'Max contact attempts before escalation', type: 'number', default: 5, min: 1, max: 20, step: 1 },
  { id: 'dc-def-writeoff-days', section: 'debt-collection', group: 'Defaults', label: 'Days overdue to suggest write-off', type: 'number', default: 180, min: 60, max: 730, step: 30 },
  { id: 'dc-def-settlement-floor', section: 'debt-collection', group: 'Defaults', label: 'Minimum settlement percent of balance', type: 'number', default: 60, min: 10, max: 100, step: 5 },
  { id: 'dc-def-currency', section: 'debt-collection', group: 'Defaults', label: 'Default currency code', type: 'text', default: 'USD' },
  { id: 'dc-def-payment-plan-installments', section: 'debt-collection', group: 'Defaults', label: 'Default payment plan installments', type: 'number', default: 3, min: 1, max: 36, step: 1 },
  { id: 'dc-def-auto-assign', section: 'debt-collection', group: 'Defaults', label: 'Auto-assign new accounts', description: 'Round-robin among collectors', type: 'toggle', default: true },
  { id: 'dc-def-template-letter', section: 'debt-collection', group: 'Defaults', label: 'Default dunning letter template', type: 'text', default: 'standard-reminder' },
  { id: 'dc-def-escalation-stage', section: 'debt-collection', group: 'Defaults', label: 'Default escalation stage', type: 'select', default: 'reminder', options: [{ value: 'reminder', label: 'Reminder' }, { value: 'demand', label: 'Demand' }, { value: 'final-notice', label: 'Final notice' }, { value: 'agency', label: 'Agency referral' }] },
  { id: 'dc-def-tax-on-fees', section: 'debt-collection', group: 'Defaults', label: 'Apply tax to late fees', type: 'toggle', default: false },
  { id: 'dc-def-auto-close-paid', section: 'debt-collection', group: 'Defaults', label: 'Auto-close accounts when paid in full', type: 'toggle', default: true },

  // ===== Sorting & Filtering (79-96) =====
  { id: 'dc-sort-default-field', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'days-overdue', options: [{ value: 'days-overdue', label: 'Days overdue' }, { value: 'balance', label: 'Balance' }, { value: 'name', label: 'Debtor name' }, { value: 'priority', label: 'Priority' }, { value: 'next-action', label: 'Next action date' }] },
  { id: 'dc-sort-direction', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'dc-sort-secondary-field', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'balance', options: [{ value: 'balance', label: 'Balance' }, { value: 'name', label: 'Name' }, { value: 'priority', label: 'Priority' }, { value: 'none', label: 'None' }] },
  { id: 'dc-filter-default-status', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active only' }, { value: 'overdue', label: 'Overdue only' }, { value: 'disputed', label: 'Disputed only' }] },
  { id: 'dc-filter-hide-disputed', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Hide disputed accounts by default', type: 'toggle', default: false },
  { id: 'dc-filter-hide-paid', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Hide paid accounts by default', type: 'toggle', default: true },
  { id: 'dc-filter-hide-promised', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Hide promise-to-pay accounts', type: 'toggle', default: false },
  { id: 'dc-filter-min-balance', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Minimum balance filter', type: 'number', default: 0, min: 0, max: 100000, step: 50 },
  { id: 'dc-filter-aging-bucket', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default aging bucket filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All buckets' }, { value: '1-30', label: '1-30 days' }, { value: '31-60', label: '31-60 days' }, { value: '61-90', label: '61-90 days' }, { value: '90plus', label: '90+ days' }] },
  { id: 'dc-filter-my-accounts-only', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Show only my assigned accounts', type: 'toggle', default: false },
  { id: 'dc-filter-remember-last', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Remember last filter set', type: 'toggle', default: true },
  { id: 'dc-filter-saved-default', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default saved filter name', type: 'text', default: '' },
  { id: 'dc-filter-search-fields', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Search scope', type: 'select', default: 'all', options: [{ value: 'all', label: 'All fields' }, { value: 'name', label: 'Name only' }, { value: 'account', label: 'Account number only' }, { value: 'name-account', label: 'Name & account' }] },
  { id: 'dc-filter-fuzzy-search', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Enable fuzzy search', type: 'toggle', default: true },
  { id: 'dc-filter-date-range-default', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'all-time', options: [{ value: 'all-time', label: 'All time' }, { value: 'this-month', label: 'This month' }, { value: 'this-quarter', label: 'This quarter' }, { value: 'this-year', label: 'This year' }] },
  { id: 'dc-filter-priority-min', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Minimum priority shown', type: 'select', default: 'low', options: [{ value: 'low', label: 'Low+' }, { value: 'medium', label: 'Medium+' }, { value: 'high', label: 'High+' }, { value: 'urgent', label: 'Urgent only' }] },
  { id: 'dc-filter-group-by', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Group accounts by', type: 'select', default: 'none', options: [{ value: 'none', label: 'No grouping' }, { value: 'collector', label: 'Collector' }, { value: 'aging', label: 'Aging bucket' }, { value: 'status', label: 'Status' }, { value: 'priority', label: 'Priority' }] },
  { id: 'dc-filter-exclude-agency', section: 'debt-collection', group: 'Sorting & Filtering', label: 'Exclude agency-referred accounts', type: 'toggle', default: false },

  // ===== Behavior (97-118) =====
  { id: 'dc-beh-confirm-writeoff', section: 'debt-collection', group: 'Behavior', label: 'Confirm before write-off', type: 'toggle', default: true },
  { id: 'dc-beh-confirm-agency-referral', section: 'debt-collection', group: 'Behavior', label: 'Confirm before agency referral', type: 'toggle', default: true },
  { id: 'dc-beh-auto-log-contact', section: 'debt-collection', group: 'Behavior', label: 'Auto-log contact on email/call', type: 'toggle', default: true },
  { id: 'dc-beh-auto-advance-stage', section: 'debt-collection', group: 'Behavior', label: 'Auto-advance escalation stage', description: 'Move stage forward after each cycle', type: 'toggle', default: true },
  { id: 'dc-beh-broken-promise-action', section: 'debt-collection', group: 'Behavior', label: 'On broken promise-to-pay', type: 'select', default: 'flag', options: [{ value: 'flag', label: 'Flag account' }, { value: 'escalate', label: 'Auto-escalate' }, { value: 'notify', label: 'Notify collector' }, { value: 'nothing', label: 'Do nothing' }] },
  { id: 'dc-beh-default-action-on-open', section: 'debt-collection', group: 'Behavior', label: 'Action when opening account', type: 'select', default: 'detail', options: [{ value: 'detail', label: 'Open detail panel' }, { value: 'edit', label: 'Open edit form' }, { value: 'history', label: 'Open contact history' }] },
  { id: 'dc-beh-keep-panel-open', section: 'debt-collection', group: 'Behavior', label: 'Keep detail panel open after save', type: 'toggle', default: false },
  { id: 'dc-beh-autosave-notes', section: 'debt-collection', group: 'Behavior', label: 'Auto-save notes draft', type: 'toggle', default: true },
  { id: 'dc-beh-require-note-on-status', section: 'debt-collection', group: 'Behavior', label: 'Require note on status change', type: 'toggle', default: true },
  { id: 'dc-beh-recalc-fees-daily', section: 'debt-collection', group: 'Behavior', label: 'Recalculate fees/interest daily', type: 'toggle', default: true },
  { id: 'dc-beh-auto-apply-payments', section: 'debt-collection', group: 'Behavior', label: 'Auto-apply received payments to balance', type: 'toggle', default: true },
  { id: 'dc-beh-payment-allocation', section: 'debt-collection', group: 'Behavior', label: 'Payment allocation order', type: 'select', default: 'fees-first', options: [{ value: 'fees-first', label: 'Fees, then principal' }, { value: 'principal-first', label: 'Principal, then fees' }, { value: 'oldest-first', label: 'Oldest charges first' }] },
  { id: 'dc-beh-debounce-search', section: 'debt-collection', group: 'Behavior', label: 'Search debounce (ms)', type: 'number', default: 300, min: 0, max: 1500, step: 50 },
  { id: 'dc-beh-bulk-actions', section: 'debt-collection', group: 'Behavior', label: 'Enable bulk actions', type: 'toggle', default: true },
  { id: 'dc-beh-bulk-limit', section: 'debt-collection', group: 'Behavior', label: 'Max accounts per bulk action', type: 'number', default: 100, min: 5, max: 1000, step: 5 },
  { id: 'dc-beh-undo-window', section: 'debt-collection', group: 'Behavior', label: 'Undo window (seconds)', type: 'number', default: 8, min: 0, max: 60, step: 1 },
  { id: 'dc-beh-respect-no-contact', section: 'debt-collection', group: 'Behavior', label: 'Honor do-not-contact flags', type: 'toggle', default: true },
  { id: 'dc-beh-quiet-hours-start', section: 'debt-collection', group: 'Behavior', label: 'Contact quiet hours start (hour)', type: 'number', default: 21, min: 0, max: 23, step: 1 },
  { id: 'dc-beh-quiet-hours-end', section: 'debt-collection', group: 'Behavior', label: 'Contact quiet hours end (hour)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'dc-beh-auto-snooze', section: 'debt-collection', group: 'Behavior', label: 'Auto-snooze after contact (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'dc-beh-double-click-action', section: 'debt-collection', group: 'Behavior', label: 'Double-click row action', type: 'select', default: 'open', options: [{ value: 'open', label: 'Open detail' }, { value: 'log-contact', label: 'Log contact' }, { value: 'edit', label: 'Edit' }] },
  { id: 'dc-beh-stale-after-days', section: 'debt-collection', group: 'Behavior', label: 'Mark account stale after no activity (days)', type: 'number', default: 14, min: 1, max: 120, step: 1 },

  // ===== Notifications (119-138) =====
  { id: 'dc-notif-promise-due', section: 'debt-collection', group: 'Notifications', label: 'Notify on promise-to-pay due', type: 'toggle', default: true },
  { id: 'dc-notif-promise-lead', section: 'debt-collection', group: 'Notifications', label: 'Promise reminder lead time (days)', type: 'number', default: 1, min: 0, max: 14, step: 1 },
  { id: 'dc-notif-broken-promise', section: 'debt-collection', group: 'Notifications', label: 'Notify on broken promise', type: 'toggle', default: true },
  { id: 'dc-notif-new-assignment', section: 'debt-collection', group: 'Notifications', label: 'Notify on new account assignment', type: 'toggle', default: true },
  { id: 'dc-notif-payment-received', section: 'debt-collection', group: 'Notifications', label: 'Notify on payment received', type: 'toggle', default: true },
  { id: 'dc-notif-dispute-filed', section: 'debt-collection', group: 'Notifications', label: 'Notify when dispute is filed', type: 'toggle', default: true },
  { id: 'dc-notif-escalation', section: 'debt-collection', group: 'Notifications', label: 'Notify on escalation stage change', type: 'toggle', default: true },
  { id: 'dc-notif-followup-due', section: 'debt-collection', group: 'Notifications', label: 'Notify on follow-up due', type: 'toggle', default: true },
  { id: 'dc-notif-large-balance-threshold', section: 'debt-collection', group: 'Notifications', label: 'Alert for balances above', type: 'number', default: 10000, min: 0, max: 1000000, step: 500 },
  { id: 'dc-notif-channel', section: 'debt-collection', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'In-app & email' }, { value: 'none', label: 'None' }] },
  { id: 'dc-notif-digest', section: 'debt-collection', group: 'Notifications', label: 'Daily digest of overdue accounts', type: 'toggle', default: true },
  { id: 'dc-notif-digest-time', section: 'debt-collection', group: 'Notifications', label: 'Digest delivery hour', type: 'number', default: 9, min: 0, max: 23, step: 1 },
  { id: 'dc-notif-writeoff-approval', section: 'debt-collection', group: 'Notifications', label: 'Notify manager on write-off request', type: 'toggle', default: true },
  { id: 'dc-notif-settlement-offer', section: 'debt-collection', group: 'Notifications', label: 'Notify on settlement offer', type: 'toggle', default: true },
  { id: 'dc-notif-sound', section: 'debt-collection', group: 'Notifications', label: 'Play sound for alerts', type: 'toggle', default: false },
  { id: 'dc-notif-stale-account', section: 'debt-collection', group: 'Notifications', label: 'Notify on stale accounts', type: 'toggle', default: true },
  { id: 'dc-notif-quota-warning', section: 'debt-collection', group: 'Notifications', label: 'Warn when collection quota at risk', type: 'toggle', default: false },
  { id: 'dc-notif-legal-deadline', section: 'debt-collection', group: 'Notifications', label: 'Notify on statute-of-limitations deadline', type: 'toggle', default: true },
  { id: 'dc-notif-deadline-lead', section: 'debt-collection', group: 'Notifications', label: 'SOL deadline lead time (days)', type: 'number', default: 30, min: 1, max: 180, step: 1 },
  { id: 'dc-notif-batch-complete', section: 'debt-collection', group: 'Notifications', label: 'Notify when bulk action completes', type: 'toggle', default: true },

  // ===== Export (139-156) =====
  { id: 'dc-exp-default-format', section: 'debt-collection', group: 'Export', label: 'Default export format', type: 'select', default: 'xlsx', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'dc-exp-include-notes', section: 'debt-collection', group: 'Export', label: 'Include collection notes in export', type: 'toggle', default: false },
  { id: 'dc-exp-include-contact-history', section: 'debt-collection', group: 'Export', label: 'Include contact history', type: 'toggle', default: false },
  { id: 'dc-exp-mask-pii', section: 'debt-collection', group: 'Export', label: 'Mask PII in exports', type: 'toggle', default: true },
  { id: 'dc-exp-respect-filters', section: 'debt-collection', group: 'Export', label: 'Export respects active filters', type: 'toggle', default: true },
  { id: 'dc-exp-include-headers', section: 'debt-collection', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'dc-exp-date-format', section: 'debt-collection', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'ISO 8601' }, { value: 'us', label: 'US (MM/DD/YYYY)' }, { value: 'eu', label: 'EU (DD/MM/YYYY)' }] },
  { id: 'dc-exp-csv-delimiter', section: 'debt-collection', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'dc-exp-filename-template', section: 'debt-collection', group: 'Export', label: 'Export filename template', type: 'text', default: 'collections_{date}' },
  { id: 'dc-exp-include-summary', section: 'debt-collection', group: 'Export', label: 'Include summary totals row', type: 'toggle', default: true },
  { id: 'dc-exp-pdf-orientation', section: 'debt-collection', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'dc-exp-pdf-logo', section: 'debt-collection', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'dc-exp-encoding', section: 'debt-collection', group: 'Export', label: 'CSV text encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'dc-exp-aging-report', section: 'debt-collection', group: 'Export', label: 'Auto-generate aging report on export', type: 'toggle', default: false },
  { id: 'dc-exp-agency-format', section: 'debt-collection', group: 'Export', label: 'Use agency placement file format', type: 'toggle', default: false },
  { id: 'dc-exp-include-fees-breakdown', section: 'debt-collection', group: 'Export', label: 'Include fees/interest breakdown', type: 'toggle', default: true },
  { id: 'dc-exp-max-rows', section: 'debt-collection', group: 'Export', label: 'Max rows per export file', type: 'number', default: 5000, min: 100, max: 100000, step: 100 },
  { id: 'dc-exp-email-recipient', section: 'debt-collection', group: 'Export', label: 'Default export email recipient', type: 'text', default: '' },

  // ===== Colors & Theme (157-174) =====
  { id: 'dc-color-current-bucket', section: 'debt-collection', group: 'Colors & Theme', label: 'Current (0-30 days) color', type: 'color', default: '#22c55e' },
  { id: 'dc-color-bucket-30', section: 'debt-collection', group: 'Colors & Theme', label: '31-60 days color', type: 'color', default: '#eab308' },
  { id: 'dc-color-bucket-60', section: 'debt-collection', group: 'Colors & Theme', label: '61-90 days color', type: 'color', default: '#f97316' },
  { id: 'dc-color-bucket-90', section: 'debt-collection', group: 'Colors & Theme', label: '90+ days color', type: 'color', default: '#ef4444' },
  { id: 'dc-color-disputed', section: 'debt-collection', group: 'Colors & Theme', label: 'Disputed account color', type: 'color', default: '#a855f7' },
  { id: 'dc-color-promise', section: 'debt-collection', group: 'Colors & Theme', label: 'Promise-to-pay color', type: 'color', default: '#3b82f6' },
  { id: 'dc-color-paid', section: 'debt-collection', group: 'Colors & Theme', label: 'Paid/resolved color', type: 'color', default: '#10b981' },
  { id: 'dc-color-writeoff', section: 'debt-collection', group: 'Colors & Theme', label: 'Write-off color', type: 'color', default: '#6b7280' },
  { id: 'dc-color-urgent-priority', section: 'debt-collection', group: 'Colors & Theme', label: 'Urgent priority color', type: 'color', default: '#dc2626' },
  { id: 'dc-color-high-priority', section: 'debt-collection', group: 'Colors & Theme', label: 'High priority color', type: 'color', default: '#f59e0b' },
  { id: 'dc-color-balance-positive', section: 'debt-collection', group: 'Colors & Theme', label: 'Outstanding balance text color', type: 'color', default: '#ef4444' },
  { id: 'dc-color-row-highlight', section: 'debt-collection', group: 'Colors & Theme', label: 'Selected row highlight color', type: 'color', default: '#1e293b' },
  { id: 'dc-color-aging-bar-bg', section: 'debt-collection', group: 'Colors & Theme', label: 'Aging bar background color', type: 'color', default: '#334155' },
  { id: 'dc-color-agency', section: 'debt-collection', group: 'Colors & Theme', label: 'Agency-referred badge color', type: 'color', default: '#0ea5e9' },
  { id: 'dc-color-theme-mode', section: 'debt-collection', group: 'Colors & Theme', label: 'Color coding mode', type: 'select', default: 'aging', options: [{ value: 'aging', label: 'By aging bucket' }, { value: 'priority', label: 'By priority' }, { value: 'status', label: 'By status' }, { value: 'none', label: 'No color coding' }] },
  { id: 'dc-color-heatmap', section: 'debt-collection', group: 'Colors & Theme', label: 'Use balance heatmap shading', type: 'toggle', default: false },
  { id: 'dc-color-badge-style', section: 'debt-collection', group: 'Colors & Theme', label: 'Status badge style', type: 'select', default: 'filled', options: [{ value: 'filled', label: 'Filled' }, { value: 'outline', label: 'Outline' }, { value: 'dot', label: 'Dot + text' }] },
  { id: 'dc-color-broken-promise', section: 'debt-collection', group: 'Colors & Theme', label: 'Broken promise color', type: 'color', default: '#be123c' },

  // ===== Accessibility (175-186) =====
  { id: 'dc-a11y-high-contrast', section: 'debt-collection', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'dc-a11y-colorblind-safe', section: 'debt-collection', group: 'Accessibility', label: 'Color-blind safe palette', type: 'toggle', default: false },
  { id: 'dc-a11y-status-icons', section: 'debt-collection', group: 'Accessibility', label: 'Show status icons (not color only)', type: 'toggle', default: true },
  { id: 'dc-a11y-font-scale', section: 'debt-collection', group: 'Accessibility', label: 'Font size scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'dc-a11y-reduce-motion', section: 'debt-collection', group: 'Accessibility', label: 'Reduce motion/animations', type: 'toggle', default: false },
  { id: 'dc-a11y-focus-outline', section: 'debt-collection', group: 'Accessibility', label: 'Show strong focus outlines', type: 'toggle', default: true },
  { id: 'dc-a11y-screenreader-summaries', section: 'debt-collection', group: 'Accessibility', label: 'Announce row summaries to screen reader', type: 'toggle', default: true },
  { id: 'dc-a11y-keyboard-nav', section: 'debt-collection', group: 'Accessibility', label: 'Enable full keyboard navigation', type: 'toggle', default: true },
  { id: 'dc-a11y-tooltip-delay', section: 'debt-collection', group: 'Accessibility', label: 'Tooltip show delay (ms)', type: 'number', default: 500, min: 0, max: 2000, step: 100 },
  { id: 'dc-a11y-underline-links', section: 'debt-collection', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },
  { id: 'dc-a11y-min-touch-target', section: 'debt-collection', group: 'Accessibility', label: 'Minimum touch target size (px)', type: 'number', default: 44, min: 24, max: 64, step: 2 },
  { id: 'dc-a11y-pattern-fills', section: 'debt-collection', group: 'Accessibility', label: 'Use pattern fills on charts', type: 'toggle', default: false },

  // ===== Shortcuts (187-194) =====
  { id: 'dc-sc-log-contact', section: 'debt-collection', group: 'Shortcuts', label: 'Log contact shortcut', type: 'text', default: 'c' },
  { id: 'dc-sc-new-promise', section: 'debt-collection', group: 'Shortcuts', label: 'New promise-to-pay shortcut', type: 'text', default: 'p' },
  { id: 'dc-sc-record-payment', section: 'debt-collection', group: 'Shortcuts', label: 'Record payment shortcut', type: 'text', default: 'r' },
  { id: 'dc-sc-escalate', section: 'debt-collection', group: 'Shortcuts', label: 'Escalate account shortcut', type: 'text', default: 'e' },
  { id: 'dc-sc-next-account', section: 'debt-collection', group: 'Shortcuts', label: 'Next account shortcut', type: 'text', default: 'j' },
  { id: 'dc-sc-prev-account', section: 'debt-collection', group: 'Shortcuts', label: 'Previous account shortcut', type: 'text', default: 'k' },
  { id: 'dc-sc-enable-shortcuts', section: 'debt-collection', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'dc-sc-search-focus', section: 'debt-collection', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },

  // ===== Privacy (195-200) =====
  { id: 'dc-priv-mask-balances', section: 'debt-collection', group: 'Privacy', label: 'Mask balances until hover', type: 'toggle', default: false },
  { id: 'dc-priv-hide-ssn', section: 'debt-collection', group: 'Privacy', label: 'Hide SSN/tax ID fields', type: 'toggle', default: true },
  { id: 'dc-priv-audit-log', section: 'debt-collection', group: 'Privacy', label: 'Log all account views to audit trail', type: 'toggle', default: true },
  { id: 'dc-priv-redact-exports', section: 'debt-collection', group: 'Privacy', label: 'Redact sensitive fields in exports', type: 'toggle', default: true },
  { id: 'dc-priv-auto-lock', section: 'debt-collection', group: 'Privacy', label: 'Auto-lock panel after idle (minutes)', type: 'number', default: 10, min: 0, max: 60, step: 1 },
  { id: 'dc-priv-restrict-cross-collector', section: 'debt-collection', group: 'Privacy', label: 'Restrict viewing other collectors accounts', type: 'toggle', default: false },
];
