import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (group) =====
  { id: 'expenses-default-view', section: 'expenses', group: 'Display', label: 'Default view', description: 'Layout used when opening Expenses', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'kanban', label: 'Kanban by status' }, { value: 'calendar', label: 'Calendar' }] },
  { id: 'expenses-rows-per-page', section: 'expenses', group: 'Display', label: 'Rows per page', description: 'Number of expenses shown per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'expenses-density', section: 'expenses', group: 'Display', label: 'Row density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'expenses-show-running-total', section: 'expenses', group: 'Display', label: 'Show running total row', type: 'toggle', default: true },
  { id: 'expenses-sticky-header', section: 'expenses', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible while scrolling', type: 'toggle', default: true },
  { id: 'expenses-zebra-striping', section: 'expenses', group: 'Display', label: 'Zebra row striping', type: 'toggle', default: true },
  { id: 'expenses-show-thumbnails', section: 'expenses', group: 'Display', label: 'Show receipt thumbnails', type: 'toggle', default: false },
  { id: 'expenses-thumbnail-size', section: 'expenses', group: 'Display', label: 'Receipt thumbnail size (px)', type: 'number', default: 48, min: 24, max: 128, step: 8 },
  { id: 'expenses-show-vendor-logo', section: 'expenses', group: 'Display', label: 'Show vendor logos', type: 'toggle', default: false },
  { id: 'expenses-highlight-overbudget', section: 'expenses', group: 'Display', label: 'Highlight over-budget rows', type: 'toggle', default: true },
  { id: 'expenses-highlight-unreconciled', section: 'expenses', group: 'Display', label: 'Highlight unreconciled rows', type: 'toggle', default: true },
  { id: 'expenses-show-quick-add-bar', section: 'expenses', group: 'Display', label: 'Show quick-add bar', description: 'Inline row for fast expense entry', type: 'toggle', default: true },
  { id: 'expenses-collapse-sidebar', section: 'expenses', group: 'Display', label: 'Collapse filters sidebar by default', type: 'toggle', default: false },
  { id: 'expenses-show-summary-cards', section: 'expenses', group: 'Display', label: 'Show summary cards header', description: 'Total, this month, pending tiles', type: 'toggle', default: true },
  { id: 'expenses-empty-state-tips', section: 'expenses', group: 'Display', label: 'Show tips on empty list', type: 'toggle', default: true },
  { id: 'expenses-show-attachment-icon', section: 'expenses', group: 'Display', label: 'Show attachment indicator icon', type: 'toggle', default: true },
  { id: 'expenses-show-recurring-badge', section: 'expenses', group: 'Display', label: 'Show recurring badge', type: 'toggle', default: true },

  // ===== Columns (group) =====
  { id: 'expenses-col-date', section: 'expenses', group: 'Columns', label: 'Show Date column', type: 'toggle', default: true },
  { id: 'expenses-col-vendor', section: 'expenses', group: 'Columns', label: 'Show Vendor column', type: 'toggle', default: true },
  { id: 'expenses-col-category', section: 'expenses', group: 'Columns', label: 'Show Category column', type: 'toggle', default: true },
  { id: 'expenses-col-amount', section: 'expenses', group: 'Columns', label: 'Show Amount column', type: 'toggle', default: true },
  { id: 'expenses-col-tax', section: 'expenses', group: 'Columns', label: 'Show Tax column', type: 'toggle', default: false },
  { id: 'expenses-col-payment-method', section: 'expenses', group: 'Columns', label: 'Show Payment Method column', type: 'toggle', default: true },
  { id: 'expenses-col-account', section: 'expenses', group: 'Columns', label: 'Show Account column', type: 'toggle', default: false },
  { id: 'expenses-col-status', section: 'expenses', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'expenses-col-reference', section: 'expenses', group: 'Columns', label: 'Show Reference/Memo column', type: 'toggle', default: false },
  { id: 'expenses-col-billable', section: 'expenses', group: 'Columns', label: 'Show Billable column', type: 'toggle', default: false },
  { id: 'expenses-col-project', section: 'expenses', group: 'Columns', label: 'Show Project/Job column', type: 'toggle', default: false },
  { id: 'expenses-col-receipt', section: 'expenses', group: 'Columns', label: 'Show Receipt column', type: 'toggle', default: true },
  { id: 'expenses-col-reconciled', section: 'expenses', group: 'Columns', label: 'Show Reconciled column', type: 'toggle', default: false },
  { id: 'expenses-col-created-by', section: 'expenses', group: 'Columns', label: 'Show Created By column', type: 'toggle', default: false },
  { id: 'expenses-col-tags', section: 'expenses', group: 'Columns', label: 'Show Tags column', type: 'toggle', default: false },
  { id: 'expenses-col-notes', section: 'expenses', group: 'Columns', label: 'Show Notes column', type: 'toggle', default: false },
  { id: 'expenses-col-currency', section: 'expenses', group: 'Columns', label: 'Show Currency column', type: 'toggle', default: false },
  { id: 'expenses-col-order-vendor', section: 'expenses', group: 'Columns', label: 'Vendor column position', type: 'number', default: 2, min: 1, max: 15, step: 1 },
  { id: 'expenses-col-order-amount', section: 'expenses', group: 'Columns', label: 'Amount column position', type: 'number', default: 4, min: 1, max: 15, step: 1 },
  { id: 'expenses-col-amount-width', section: 'expenses', group: 'Columns', label: 'Amount column width (px)', type: 'number', default: 120, min: 60, max: 300, step: 10 },
  { id: 'expenses-col-vendor-width', section: 'expenses', group: 'Columns', label: 'Vendor column width (px)', type: 'number', default: 180, min: 80, max: 400, step: 10 },
  { id: 'expenses-freeze-first-column', section: 'expenses', group: 'Columns', label: 'Freeze first column', type: 'toggle', default: false },
  { id: 'expenses-wrap-long-text', section: 'expenses', group: 'Columns', label: 'Wrap long text in cells', type: 'toggle', default: false },

  // ===== Formatting (group) =====
  { id: 'expenses-currency-symbol', section: 'expenses', group: 'Formatting', label: 'Currency symbol', type: 'select', default: 'usd', options: [{ value: 'usd', label: '$ USD' }, { value: 'eur', label: '€ EUR' }, { value: 'gbp', label: '£ GBP' }, { value: 'cad', label: '$ CAD' }, { value: 'aud', label: '$ AUD' }, { value: 'jpy', label: '¥ JPY' }] },
  { id: 'expenses-decimal-places', section: 'expenses', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'expenses-thousands-separator', section: 'expenses', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'expenses-negative-style', section: 'expenses', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-$50.00' }, { value: 'parens', label: '($50.00)' }, { value: 'red', label: 'Red text' }] },
  { id: 'expenses-symbol-position', section: 'expenses', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($50)' }, { value: 'after', label: 'After (50$)' }] },
  { id: 'expenses-date-format', section: 'expenses', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Mon DD, YYYY' }] },
  { id: 'expenses-relative-dates', section: 'expenses', group: 'Formatting', label: 'Use relative dates', description: 'Show "Yesterday", "2 days ago"', type: 'toggle', default: false },
  { id: 'expenses-uppercase-vendor', section: 'expenses', group: 'Formatting', label: 'Uppercase vendor names', type: 'toggle', default: false },
  { id: 'expenses-truncate-memo', section: 'expenses', group: 'Formatting', label: 'Truncate memo length (chars)', type: 'number', default: 40, min: 10, max: 200, step: 5 },
  { id: 'expenses-show-cents', section: 'expenses', group: 'Formatting', label: 'Always show cents', type: 'toggle', default: true },
  { id: 'expenses-round-display', section: 'expenses', group: 'Formatting', label: 'Round amounts to nearest dollar in display', type: 'toggle', default: false },
  { id: 'expenses-percent-of-total', section: 'expenses', group: 'Formatting', label: 'Show amount as % of total', type: 'toggle', default: false },
  { id: 'expenses-time-format', section: 'expenses', group: 'Formatting', label: 'Time format', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'expenses-category-color-dots', section: 'expenses', group: 'Formatting', label: 'Show category color dots', type: 'toggle', default: true },
  { id: 'expenses-abbreviate-large', section: 'expenses', group: 'Formatting', label: 'Abbreviate large amounts (1.2K)', type: 'toggle', default: false },

  // ===== Defaults (group) =====
  { id: 'expenses-default-category', section: 'expenses', group: 'Defaults', label: 'Default category', type: 'text', default: 'Uncategorized' },
  { id: 'expenses-default-payment-method', section: 'expenses', group: 'Defaults', label: 'Default payment method', type: 'select', default: 'card', options: [{ value: 'card', label: 'Credit/Debit Card' }, { value: 'cash', label: 'Cash' }, { value: 'check', label: 'Check' }, { value: 'transfer', label: 'Bank Transfer' }, { value: 'ach', label: 'ACH' }] },
  { id: 'expenses-default-account', section: 'expenses', group: 'Defaults', label: 'Default account', type: 'text', default: 'Operating Checking' },
  { id: 'expenses-default-date', section: 'expenses', group: 'Defaults', label: 'Default date for new expense', type: 'select', default: 'today', options: [{ value: 'today', label: 'Today' }, { value: 'lastused', label: 'Last used' }, { value: 'blank', label: 'Blank' }] },
  { id: 'expenses-default-billable', section: 'expenses', group: 'Defaults', label: 'New expenses billable by default', type: 'toggle', default: false },
  { id: 'expenses-default-tax-rate', section: 'expenses', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 30, step: 0.5 },
  { id: 'expenses-default-currency', section: 'expenses', group: 'Defaults', label: 'Default currency', type: 'select', default: 'usd', options: [{ value: 'usd', label: 'USD' }, { value: 'eur', label: 'EUR' }, { value: 'gbp', label: 'GBP' }, { value: 'cad', label: 'CAD' }] },
  { id: 'expenses-default-tax-inclusive', section: 'expenses', group: 'Defaults', label: 'Amounts tax-inclusive by default', type: 'toggle', default: false },
  { id: 'expenses-default-status', section: 'expenses', group: 'Defaults', label: 'Default status', type: 'select', default: 'pending', options: [{ value: 'pending', label: 'Pending' }, { value: 'approved', label: 'Approved' }, { value: 'paid', label: 'Paid' }] },
  { id: 'expenses-default-project', section: 'expenses', group: 'Defaults', label: 'Default project/job', type: 'text', default: '' },
  { id: 'expenses-default-vendor', section: 'expenses', group: 'Defaults', label: 'Default vendor', type: 'text', default: '' },
  { id: 'expenses-remember-last-vendor', section: 'expenses', group: 'Defaults', label: 'Remember last used vendor', type: 'toggle', default: true },
  { id: 'expenses-default-tag', section: 'expenses', group: 'Defaults', label: 'Default tag applied', type: 'text', default: '' },
  { id: 'expenses-default-reimbursable', section: 'expenses', group: 'Defaults', label: 'New expenses reimbursable by default', type: 'toggle', default: false },
  { id: 'expenses-quick-amount-1', section: 'expenses', group: 'Defaults', label: 'Quick amount button 1', type: 'number', default: 10, min: 1, max: 10000, step: 1 },
  { id: 'expenses-quick-amount-2', section: 'expenses', group: 'Defaults', label: 'Quick amount button 2', type: 'number', default: 25, min: 1, max: 10000, step: 1 },
  { id: 'expenses-quick-amount-3', section: 'expenses', group: 'Defaults', label: 'Quick amount button 3', type: 'number', default: 100, min: 1, max: 10000, step: 1 },

  // ===== Sorting & Filtering (group) =====
  { id: 'expenses-default-sort-field', section: 'expenses', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'date', options: [{ value: 'date', label: 'Date' }, { value: 'amount', label: 'Amount' }, { value: 'vendor', label: 'Vendor' }, { value: 'category', label: 'Category' }, { value: 'status', label: 'Status' }] },
  { id: 'expenses-default-sort-direction', section: 'expenses', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'expenses-default-date-range', section: 'expenses', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'this-month', options: [{ value: 'today', label: 'Today' }, { value: 'this-week', label: 'This week' }, { value: 'this-month', label: 'This month' }, { value: 'this-quarter', label: 'This quarter' }, { value: 'this-year', label: 'This year' }, { value: 'all', label: 'All time' }] },
  { id: 'expenses-remember-filters', section: 'expenses', group: 'Sorting & Filtering', label: 'Remember filters between sessions', type: 'toggle', default: true },
  { id: 'expenses-hide-paid', section: 'expenses', group: 'Sorting & Filtering', label: 'Hide paid expenses by default', type: 'toggle', default: false },
  { id: 'expenses-hide-reconciled', section: 'expenses', group: 'Sorting & Filtering', label: 'Hide reconciled expenses by default', type: 'toggle', default: false },
  { id: 'expenses-min-amount-filter', section: 'expenses', group: 'Sorting & Filtering', label: 'Default minimum amount filter', type: 'number', default: 0, min: 0, max: 100000, step: 10 },
  { id: 'expenses-secondary-sort', section: 'expenses', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'vendor', options: [{ value: 'none', label: 'None' }, { value: 'vendor', label: 'Vendor' }, { value: 'amount', label: 'Amount' }, { value: 'category', label: 'Category' }] },
  { id: 'expenses-group-by', section: 'expenses', group: 'Sorting & Filtering', label: 'Group expenses by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'category', label: 'Category' }, { value: 'vendor', label: 'Vendor' }, { value: 'month', label: 'Month' }, { value: 'project', label: 'Project' }] },
  { id: 'expenses-show-filter-chips', section: 'expenses', group: 'Sorting & Filtering', label: 'Show active filter chips', type: 'toggle', default: true },
  { id: 'expenses-saved-filter-default', section: 'expenses', group: 'Sorting & Filtering', label: 'Default saved filter name', type: 'text', default: '' },
  { id: 'expenses-search-fields', section: 'expenses', group: 'Sorting & Filtering', label: 'Search scope', type: 'select', default: 'all', options: [{ value: 'all', label: 'All fields' }, { value: 'vendor', label: 'Vendor only' }, { value: 'memo', label: 'Memo only' }, { value: 'amount', label: 'Amount only' }] },
  { id: 'expenses-fuzzy-search', section: 'expenses', group: 'Sorting & Filtering', label: 'Enable fuzzy search', type: 'toggle', default: true },
  { id: 'expenses-quick-filter-buttons', section: 'expenses', group: 'Sorting & Filtering', label: 'Show quick filter buttons', type: 'toggle', default: true },

  // ===== Behavior (group) =====
  { id: 'expenses-confirm-delete', section: 'expenses', group: 'Behavior', label: 'Confirm before deleting', type: 'toggle', default: true },
  { id: 'expenses-autosave-draft', section: 'expenses', group: 'Behavior', label: 'Auto-save drafts', type: 'toggle', default: true },
  { id: 'expenses-keep-form-open', section: 'expenses', group: 'Behavior', label: 'Keep form open after saving', description: 'For rapid sequential entry', type: 'toggle', default: false },
  { id: 'expenses-duplicate-warning', section: 'expenses', group: 'Behavior', label: 'Warn on possible duplicate', type: 'toggle', default: true },
  { id: 'expenses-duplicate-window-days', section: 'expenses', group: 'Behavior', label: 'Duplicate detection window (days)', type: 'number', default: 7, min: 1, max: 90, step: 1 },
  { id: 'expenses-auto-categorize', section: 'expenses', group: 'Behavior', label: 'Auto-categorize from vendor', type: 'toggle', default: true },
  { id: 'expenses-require-receipt-over', section: 'expenses', group: 'Behavior', label: 'Require receipt over amount', type: 'number', default: 75, min: 0, max: 5000, step: 5 },
  { id: 'expenses-require-category', section: 'expenses', group: 'Behavior', label: 'Require category on save', type: 'toggle', default: true },
  { id: 'expenses-require-memo', section: 'expenses', group: 'Behavior', label: 'Require memo on save', type: 'toggle', default: false },
  { id: 'expenses-inline-edit', section: 'expenses', group: 'Behavior', label: 'Allow inline editing', type: 'toggle', default: true },
  { id: 'expenses-double-click-action', section: 'expenses', group: 'Behavior', label: 'Double-click row action', type: 'select', default: 'edit', options: [{ value: 'edit', label: 'Edit' }, { value: 'view', label: 'View details' }, { value: 'receipt', label: 'Open receipt' }] },
  { id: 'expenses-auto-match-bank', section: 'expenses', group: 'Behavior', label: 'Auto-match to bank transactions', type: 'toggle', default: true },
  { id: 'expenses-undo-window-seconds', section: 'expenses', group: 'Behavior', label: 'Undo window after action (sec)', type: 'number', default: 5, min: 0, max: 30, step: 1 },
  { id: 'expenses-bulk-edit-enabled', section: 'expenses', group: 'Behavior', label: 'Enable bulk edit', type: 'toggle', default: true },
  { id: 'expenses-ocr-receipts', section: 'expenses', group: 'Behavior', label: 'Run OCR on uploaded receipts', type: 'toggle', default: true },
  { id: 'expenses-ocr-auto-fill', section: 'expenses', group: 'Behavior', label: 'Auto-fill fields from OCR', type: 'toggle', default: true },
  { id: 'expenses-approval-required', section: 'expenses', group: 'Behavior', label: 'Require approval workflow', type: 'toggle', default: false },
  { id: 'expenses-approval-threshold', section: 'expenses', group: 'Behavior', label: 'Approval required over amount', type: 'number', default: 500, min: 0, max: 50000, step: 50 },
  { id: 'expenses-lock-after-reconcile', section: 'expenses', group: 'Behavior', label: 'Lock expenses after reconciliation', type: 'toggle', default: true },
  { id: 'expenses-tab-on-enter', section: 'expenses', group: 'Behavior', label: 'Enter key moves to next field', type: 'toggle', default: true },

  // ===== Notifications (group) =====
  { id: 'expenses-notify-receipt-missing', section: 'expenses', group: 'Notifications', label: 'Notify on missing receipts', type: 'toggle', default: true },
  { id: 'expenses-notify-over-budget', section: 'expenses', group: 'Notifications', label: 'Notify when category over budget', type: 'toggle', default: true },
  { id: 'expenses-notify-approval-pending', section: 'expenses', group: 'Notifications', label: 'Notify on pending approvals', type: 'toggle', default: true },
  { id: 'expenses-notify-recurring-due', section: 'expenses', group: 'Notifications', label: 'Notify when recurring expense is due', type: 'toggle', default: true },
  { id: 'expenses-notify-recurring-lead-days', section: 'expenses', group: 'Notifications', label: 'Recurring reminder lead time (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'expenses-notify-large-amount', section: 'expenses', group: 'Notifications', label: 'Alert on large expense', type: 'toggle', default: true },
  { id: 'expenses-large-amount-threshold', section: 'expenses', group: 'Notifications', label: 'Large expense threshold', type: 'number', default: 1000, min: 100, max: 100000, step: 100 },
  { id: 'expenses-notify-duplicate', section: 'expenses', group: 'Notifications', label: 'Notify on detected duplicates', type: 'toggle', default: true },
  { id: 'expenses-notify-uncategorized', section: 'expenses', group: 'Notifications', label: 'Weekly uncategorized digest', type: 'toggle', default: false },
  { id: 'expenses-notify-channel', section: 'expenses', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'inapp', options: [{ value: 'inapp', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }, { value: 'none', label: 'None' }] },
  { id: 'expenses-notify-failed-sync', section: 'expenses', group: 'Notifications', label: 'Notify on sync failure', type: 'toggle', default: true },
  { id: 'expenses-notify-tax-deadline', section: 'expenses', group: 'Notifications', label: 'Notify on tax deduction deadlines', type: 'toggle', default: false },
  { id: 'expenses-notify-sound', section: 'expenses', group: 'Notifications', label: 'Play sound on notification', type: 'toggle', default: false },
  { id: 'expenses-notify-mileage-reminder', section: 'expenses', group: 'Notifications', label: 'Remind to log mileage', type: 'toggle', default: false },

  // ===== Export (group) =====
  { id: 'expenses-export-format', section: 'expenses', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'qbo', label: 'QuickBooks (QBO)' }, { value: 'json', label: 'JSON' }] },
  { id: 'expenses-export-include-receipts', section: 'expenses', group: 'Export', label: 'Include receipt images in export', type: 'toggle', default: false },
  { id: 'expenses-export-include-headers', section: 'expenses', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'expenses-export-date-format', section: 'expenses', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'YYYY-MM-DD' }, { value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }] },
  { id: 'expenses-export-only-filtered', section: 'expenses', group: 'Export', label: 'Export only filtered rows', type: 'toggle', default: true },
  { id: 'expenses-export-currency-symbol', section: 'expenses', group: 'Export', label: 'Include currency symbol in export', type: 'toggle', default: false },
  { id: 'expenses-export-filename-pattern', section: 'expenses', group: 'Export', label: 'Export filename pattern', type: 'text', default: 'expenses_{date}' },
  { id: 'expenses-export-group-by-category', section: 'expenses', group: 'Export', label: 'Group export by category', type: 'toggle', default: false },
  { id: 'expenses-export-include-totals', section: 'expenses', group: 'Export', label: 'Include totals row in export', type: 'toggle', default: true },
  { id: 'expenses-export-delimiter', section: 'expenses', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'expenses-export-encoding', section: 'expenses', group: 'Export', label: 'File encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'expenses-export-split-tax', section: 'expenses', group: 'Export', label: 'Split tax into separate column', type: 'toggle', default: true },
  { id: 'expenses-pdf-orientation', section: 'expenses', group: 'Export', label: 'PDF page orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'expenses-export-include-notes', section: 'expenses', group: 'Export', label: 'Include notes column in export', type: 'toggle', default: true },

  // ===== Colors & Theme (group) =====
  { id: 'expenses-color-overbudget', section: 'expenses', group: 'Colors & Theme', label: 'Over-budget highlight color', type: 'color', default: '#ef4444' },
  { id: 'expenses-color-pending', section: 'expenses', group: 'Colors & Theme', label: 'Pending status color', type: 'color', default: '#f59e0b' },
  { id: 'expenses-color-approved', section: 'expenses', group: 'Colors & Theme', label: 'Approved status color', type: 'color', default: '#3b82f6' },
  { id: 'expenses-color-paid', section: 'expenses', group: 'Colors & Theme', label: 'Paid status color', type: 'color', default: '#22c55e' },
  { id: 'expenses-color-reconciled', section: 'expenses', group: 'Colors & Theme', label: 'Reconciled indicator color', type: 'color', default: '#10b981' },
  { id: 'expenses-color-negative', section: 'expenses', group: 'Colors & Theme', label: 'Negative amount color', type: 'color', default: '#dc2626' },
  { id: 'expenses-color-billable', section: 'expenses', group: 'Colors & Theme', label: 'Billable badge color', type: 'color', default: '#8b5cf6' },
  { id: 'expenses-color-row-hover', section: 'expenses', group: 'Colors & Theme', label: 'Row hover color', type: 'color', default: '#1e293b' },
  { id: 'expenses-color-selected-row', section: 'expenses', group: 'Colors & Theme', label: 'Selected row color', type: 'color', default: '#334155' },
  { id: 'expenses-color-recurring-badge', section: 'expenses', group: 'Colors & Theme', label: 'Recurring badge color', type: 'color', default: '#06b6d4' },
  { id: 'expenses-color-missing-receipt', section: 'expenses', group: 'Colors & Theme', label: 'Missing receipt flag color', type: 'color', default: '#f97316' },
  { id: 'expenses-color-chart-accent', section: 'expenses', group: 'Colors & Theme', label: 'Summary chart accent color', type: 'color', default: '#6366f1' },
  { id: 'expenses-use-category-colors', section: 'expenses', group: 'Colors & Theme', label: 'Use category colors throughout', type: 'toggle', default: true },
  { id: 'expenses-theme-mode', section: 'expenses', group: 'Colors & Theme', label: 'Theme mode', type: 'select', default: 'system', options: [{ value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }, { value: 'system', label: 'System' }] },
  { id: 'expenses-color-tax-deductible', section: 'expenses', group: 'Colors & Theme', label: 'Tax-deductible highlight color', type: 'color', default: '#14b8a6' },

  // ===== Accessibility (group) =====
  { id: 'expenses-high-contrast', section: 'expenses', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'expenses-font-size', section: 'expenses', group: 'Accessibility', label: 'Table font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'expenses-reduce-motion', section: 'expenses', group: 'Accessibility', label: 'Reduce motion/animations', type: 'toggle', default: false },
  { id: 'expenses-focus-outline', section: 'expenses', group: 'Accessibility', label: 'Show strong focus outlines', type: 'toggle', default: true },
  { id: 'expenses-status-icons-not-color', section: 'expenses', group: 'Accessibility', label: 'Use icons not color for status', description: 'For color-blind users', type: 'toggle', default: false },
  { id: 'expenses-screen-reader-totals', section: 'expenses', group: 'Accessibility', label: 'Announce totals to screen readers', type: 'toggle', default: true },
  { id: 'expenses-keyboard-nav', section: 'expenses', group: 'Accessibility', label: 'Full keyboard navigation', type: 'toggle', default: true },
  { id: 'expenses-bold-amounts', section: 'expenses', group: 'Accessibility', label: 'Bold amount text', type: 'toggle', default: false },
  { id: 'expenses-min-row-height', section: 'expenses', group: 'Accessibility', label: 'Minimum row height (px)', type: 'number', default: 36, min: 24, max: 72, step: 2 },
  { id: 'expenses-underline-links', section: 'expenses', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },
  { id: 'expenses-cursor-size', section: 'expenses', group: 'Accessibility', label: 'Larger interactive targets', type: 'toggle', default: false },
  { id: 'expenses-tooltips-delay', section: 'expenses', group: 'Accessibility', label: 'Tooltip show delay (ms)', type: 'number', default: 500, min: 0, max: 2000, step: 100 },

  // ===== Shortcuts (group) =====
  { id: 'expenses-shortcut-new', section: 'expenses', group: 'Shortcuts', label: 'New expense shortcut', type: 'text', default: 'n' },
  { id: 'expenses-shortcut-search', section: 'expenses', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'expenses-shortcut-save', section: 'expenses', group: 'Shortcuts', label: 'Save expense shortcut', type: 'text', default: 'mod+s' },
  { id: 'expenses-shortcut-delete', section: 'expenses', group: 'Shortcuts', label: 'Delete expense shortcut', type: 'text', default: 'del' },
  { id: 'expenses-shortcut-duplicate', section: 'expenses', group: 'Shortcuts', label: 'Duplicate expense shortcut', type: 'text', default: 'mod+d' },
  { id: 'expenses-shortcut-export', section: 'expenses', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'mod+e' },
  { id: 'expenses-shortcut-receipt', section: 'expenses', group: 'Shortcuts', label: 'Attach receipt shortcut', type: 'text', default: 'mod+u' },
  { id: 'expenses-shortcut-approve', section: 'expenses', group: 'Shortcuts', label: 'Approve expense shortcut', type: 'text', default: 'a' },
  { id: 'expenses-shortcut-next-row', section: 'expenses', group: 'Shortcuts', label: 'Next row shortcut', type: 'text', default: 'j' },
  { id: 'expenses-shortcut-prev-row', section: 'expenses', group: 'Shortcuts', label: 'Previous row shortcut', type: 'text', default: 'k' },
  { id: 'expenses-shortcuts-enabled', section: 'expenses', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'expenses-shortcut-toggle-filters', section: 'expenses', group: 'Shortcuts', label: 'Toggle filters shortcut', type: 'text', default: 'f' },
  { id: 'expenses-shortcut-select-all', section: 'expenses', group: 'Shortcuts', label: 'Select all shortcut', type: 'text', default: 'mod+a' },
  { id: 'expenses-shortcut-bulk-edit', section: 'expenses', group: 'Shortcuts', label: 'Bulk edit shortcut', type: 'text', default: 'mod+b' },

  // ===== Privacy (group) =====
  { id: 'expenses-mask-amounts', section: 'expenses', group: 'Privacy', label: 'Mask amounts by default', description: 'Hide values until hover/click', type: 'toggle', default: false },
  { id: 'expenses-mask-account-numbers', section: 'expenses', group: 'Privacy', label: 'Mask account numbers', type: 'toggle', default: true },
  { id: 'expenses-hide-on-blur', section: 'expenses', group: 'Privacy', label: 'Blur amounts when window unfocused', type: 'toggle', default: false },
  { id: 'expenses-redact-export', section: 'expenses', group: 'Privacy', label: 'Redact account numbers in export', type: 'toggle', default: true },
  { id: 'expenses-audit-log', section: 'expenses', group: 'Privacy', label: 'Keep edit audit log', type: 'toggle', default: true },
  { id: 'expenses-require-pin-delete', section: 'expenses', group: 'Privacy', label: 'Require PIN to delete', type: 'toggle', default: false },
  { id: 'expenses-share-vendor-anon', section: 'expenses', group: 'Privacy', label: 'Anonymize vendors in shared reports', type: 'toggle', default: false },
  { id: 'expenses-receipt-retention-days', section: 'expenses', group: 'Privacy', label: 'Receipt retention period (days)', type: 'number', default: 2555, min: 30, max: 3650, step: 30 },
  { id: 'expenses-auto-lock-minutes', section: 'expenses', group: 'Privacy', label: 'Auto-lock view after idle (min)', type: 'number', default: 0, min: 0, max: 120, step: 5 },
  { id: 'expenses-watermark-exports', section: 'expenses', group: 'Privacy', label: 'Watermark PDF exports', type: 'toggle', default: false },
  { id: 'expenses-hide-creator', section: 'expenses', group: 'Privacy', label: 'Hide creator from other users', type: 'toggle', default: false },

  // ===== Recurring (group) =====
  { id: 'expenses-recurring-auto-create', section: 'expenses', group: 'Recurring', label: 'Auto-create recurring expenses', type: 'toggle', default: true },
  { id: 'expenses-recurring-default-frequency', section: 'expenses', group: 'Recurring', label: 'Default recurrence frequency', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'yearly', label: 'Yearly' }] },
  { id: 'expenses-recurring-confirm-before-post', section: 'expenses', group: 'Recurring', label: 'Confirm before posting recurring', type: 'toggle', default: false },
  { id: 'expenses-recurring-skip-weekends', section: 'expenses', group: 'Recurring', label: 'Skip weekends for recurring dates', type: 'toggle', default: false },
  { id: 'expenses-recurring-end-after', section: 'expenses', group: 'Recurring', label: 'Default end after N occurrences', type: 'number', default: 0, min: 0, max: 120, step: 1 },
  { id: 'expenses-recurring-show-upcoming', section: 'expenses', group: 'Recurring', label: 'Show upcoming recurring preview', type: 'toggle', default: true },
  { id: 'expenses-recurring-copy-receipt', section: 'expenses', group: 'Recurring', label: 'Copy receipt to each occurrence', type: 'toggle', default: false },

  // ===== Mileage & Travel (group) =====
  { id: 'expenses-mileage-rate', section: 'expenses', group: 'Mileage & Travel', label: 'Mileage rate per mile', type: 'number', default: 0.67, min: 0, max: 5, step: 0.01 },
  { id: 'expenses-mileage-unit', section: 'expenses', group: 'Mileage & Travel', label: 'Distance unit', type: 'select', default: 'miles', options: [{ value: 'miles', label: 'Miles' }, { value: 'km', label: 'Kilometers' }] },
  { id: 'expenses-per-diem-rate', section: 'expenses', group: 'Mileage & Travel', label: 'Default per diem rate', type: 'number', default: 75, min: 0, max: 500, step: 5 },
  { id: 'expenses-track-gps', section: 'expenses', group: 'Mileage & Travel', label: 'Track trips via GPS', type: 'toggle', default: false },
  { id: 'expenses-mileage-auto-calc', section: 'expenses', group: 'Mileage & Travel', label: 'Auto-calculate mileage amount', type: 'toggle', default: true },
  { id: 'expenses-travel-category', section: 'expenses', group: 'Mileage & Travel', label: 'Default travel category', type: 'text', default: 'Travel' },
  { id: 'expenses-mileage-round-trip', section: 'expenses', group: 'Mileage & Travel', label: 'Assume round trip by default', type: 'toggle', default: false },

  // ===== Tax & Compliance (group) =====
  { id: 'expenses-default-deductible', section: 'expenses', group: 'Tax & Compliance', label: 'Mark new expenses tax-deductible', type: 'toggle', default: true },
  { id: 'expenses-tax-category-map', section: 'expenses', group: 'Tax & Compliance', label: 'Auto-map to tax schedule', type: 'toggle', default: true },
  { id: 'expenses-meals-deduction-pct', section: 'expenses', group: 'Tax & Compliance', label: 'Meals deduction percentage', type: 'number', default: 50, min: 0, max: 100, step: 5 },
  { id: 'expenses-vat-tracking', section: 'expenses', group: 'Tax & Compliance', label: 'Track VAT/GST separately', type: 'toggle', default: false },
  { id: 'expenses-require-tax-id-over', section: 'expenses', group: 'Tax & Compliance', label: 'Require vendor tax ID over amount', type: 'number', default: 600, min: 0, max: 10000, step: 50 },
  { id: 'expenses-show-deductible-total', section: 'expenses', group: 'Tax & Compliance', label: 'Show deductible total in summary', type: 'toggle', default: true },
  { id: 'expenses-1099-flag', section: 'expenses', group: 'Tax & Compliance', label: 'Flag 1099-reportable vendors', type: 'toggle', default: true },
  { id: 'expenses-fiscal-year-start', section: 'expenses', group: 'Tax & Compliance', label: 'Fiscal year start month', type: 'select', default: 'january', options: [{ value: 'january', label: 'January' }, { value: 'april', label: 'April' }, { value: 'july', label: 'July' }, { value: 'october', label: 'October' }] },

  // ===== Receipts & Attachments (group) =====
  { id: 'expenses-max-receipt-size-mb', section: 'expenses', group: 'Receipts & Attachments', label: 'Max receipt file size (MB)', type: 'number', default: 10, min: 1, max: 100, step: 1 },
  { id: 'expenses-receipt-formats', section: 'expenses', group: 'Receipts & Attachments', label: 'Allowed receipt formats', type: 'select', default: 'all', options: [{ value: 'all', label: 'All (image + PDF)' }, { value: 'image', label: 'Images only' }, { value: 'pdf', label: 'PDF only' }] },
  { id: 'expenses-compress-receipts', section: 'expenses', group: 'Receipts & Attachments', label: 'Compress uploaded receipts', type: 'toggle', default: true },
  { id: 'expenses-auto-attach-email', section: 'expenses', group: 'Receipts & Attachments', label: 'Auto-import receipts from email', type: 'toggle', default: false },
  { id: 'expenses-receipt-email-address', section: 'expenses', group: 'Receipts & Attachments', label: 'Receipt forwarding email', type: 'text', default: '' },
  { id: 'expenses-multi-receipt', section: 'expenses', group: 'Receipts & Attachments', label: 'Allow multiple receipts per expense', type: 'toggle', default: true },
  { id: 'expenses-receipt-preview-pane', section: 'expenses', group: 'Receipts & Attachments', label: 'Show receipt preview pane', type: 'toggle', default: true },
  { id: 'expenses-store-original', section: 'expenses', group: 'Receipts & Attachments', label: 'Keep original receipt file', type: 'toggle', default: true },

  // ===== Budgets (group) =====
  { id: 'expenses-show-budget-progress', section: 'expenses', group: 'Budgets', label: 'Show budget progress bars', type: 'toggle', default: true },
  { id: 'expenses-budget-warn-pct', section: 'expenses', group: 'Budgets', label: 'Budget warning threshold (%)', type: 'number', default: 80, min: 50, max: 100, step: 5 },
  { id: 'expenses-budget-period', section: 'expenses', group: 'Budgets', label: 'Budget period', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }] },
  { id: 'expenses-budget-rollover', section: 'expenses', group: 'Budgets', label: 'Roll over unused budget', type: 'toggle', default: false },
  { id: 'expenses-block-over-budget', section: 'expenses', group: 'Budgets', label: 'Block saving when over budget', type: 'toggle', default: false },
  { id: 'expenses-budget-include-pending', section: 'expenses', group: 'Budgets', label: 'Count pending toward budget', type: 'toggle', default: true },
  { id: 'expenses-show-budget-remaining', section: 'expenses', group: 'Budgets', label: 'Show remaining budget per category', type: 'toggle', default: true },
];
