import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-20) =====
  { id: 'display-default-view', section: 'fixed-assets', group: 'Display', label: 'Default asset view', description: 'How the asset register opens by default.', type: 'select', default: 'table', options: [ { value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'grouped', label: 'Grouped by category' }, { value: 'timeline', label: 'Timeline' } ] },
  { id: 'display-rows-per-page', section: 'fixed-assets', group: 'Display', label: 'Assets per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'display-show-thumbnails', section: 'fixed-assets', group: 'Display', label: 'Show asset photo thumbnails', type: 'toggle', default: true },
  { id: 'display-compact-rows', section: 'fixed-assets', group: 'Display', label: 'Compact row height', type: 'toggle', default: false },
  { id: 'display-show-disposed', section: 'fixed-assets', group: 'Display', label: 'Show disposed assets in register', type: 'toggle', default: false },
  { id: 'display-show-fully-depreciated', section: 'fixed-assets', group: 'Display', label: 'Show fully depreciated assets', type: 'toggle', default: true },
  { id: 'display-highlight-near-eol', section: 'fixed-assets', group: 'Display', label: 'Highlight assets near end of life', type: 'toggle', default: true },
  { id: 'display-eol-threshold-months', section: 'fixed-assets', group: 'Display', label: 'End-of-life warning threshold (months)', type: 'number', default: 6, min: 1, max: 36, step: 1 },
  { id: 'display-zebra-striping', section: 'fixed-assets', group: 'Display', label: 'Alternating row striping', type: 'toggle', default: true },
  { id: 'display-sticky-header', section: 'fixed-assets', group: 'Display', label: 'Sticky table header on scroll', type: 'toggle', default: true },
  { id: 'display-group-by', section: 'fixed-assets', group: 'Display', label: 'Group register by', type: 'select', default: 'none', options: [ { value: 'none', label: 'None' }, { value: 'category', label: 'Category' }, { value: 'location', label: 'Location' }, { value: 'department', label: 'Department' }, { value: 'status', label: 'Status' } ] },
  { id: 'display-show-running-total', section: 'fixed-assets', group: 'Display', label: 'Show running book value total', type: 'toggle', default: true },
  { id: 'display-show-category-icons', section: 'fixed-assets', group: 'Display', label: 'Show category icons', type: 'toggle', default: true },
  { id: 'display-default-status-filter', section: 'fixed-assets', group: 'Display', label: 'Default status filter', type: 'select', default: 'active', options: [ { value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'in-service', label: 'In service' }, { value: 'idle', label: 'Idle' } ] },
  { id: 'display-show-net-book-badge', section: 'fixed-assets', group: 'Display', label: 'Show net book value badge', type: 'toggle', default: true },
  { id: 'display-density', section: 'fixed-assets', group: 'Display', label: 'Table density', type: 'select', default: 'comfortable', options: [ { value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' } ] },
  { id: 'display-show-asset-tag-prefix', section: 'fixed-assets', group: 'Display', label: 'Show asset tag prefix', type: 'toggle', default: true },
  { id: 'display-expand-subassets', section: 'fixed-assets', group: 'Display', label: 'Expand component sub-assets by default', type: 'toggle', default: false },
  { id: 'display-show-warranty-status', section: 'fixed-assets', group: 'Display', label: 'Show warranty status indicator', type: 'toggle', default: true },
  { id: 'display-default-sort-direction', section: 'fixed-assets', group: 'Display', label: 'Default sort direction', type: 'select', default: 'desc', options: [ { value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' } ] },

  // ===== Columns (21-44) =====
  { id: 'col-asset-tag', section: 'fixed-assets', group: 'Columns', label: 'Show Asset Tag column', type: 'toggle', default: true },
  { id: 'col-description', section: 'fixed-assets', group: 'Columns', label: 'Show Description column', type: 'toggle', default: true },
  { id: 'col-category', section: 'fixed-assets', group: 'Columns', label: 'Show Category column', type: 'toggle', default: true },
  { id: 'col-acquisition-date', section: 'fixed-assets', group: 'Columns', label: 'Show Acquisition Date column', type: 'toggle', default: true },
  { id: 'col-acquisition-cost', section: 'fixed-assets', group: 'Columns', label: 'Show Acquisition Cost column', type: 'toggle', default: true },
  { id: 'col-accumulated-depreciation', section: 'fixed-assets', group: 'Columns', label: 'Show Accumulated Depreciation column', type: 'toggle', default: true },
  { id: 'col-net-book-value', section: 'fixed-assets', group: 'Columns', label: 'Show Net Book Value column', type: 'toggle', default: true },
  { id: 'col-salvage-value', section: 'fixed-assets', group: 'Columns', label: 'Show Salvage Value column', type: 'toggle', default: false },
  { id: 'col-useful-life', section: 'fixed-assets', group: 'Columns', label: 'Show Useful Life column', type: 'toggle', default: true },
  { id: 'col-depreciation-method', section: 'fixed-assets', group: 'Columns', label: 'Show Depreciation Method column', type: 'toggle', default: true },
  { id: 'col-location', section: 'fixed-assets', group: 'Columns', label: 'Show Location column', type: 'toggle', default: true },
  { id: 'col-department', section: 'fixed-assets', group: 'Columns', label: 'Show Department column', type: 'toggle', default: false },
  { id: 'col-custodian', section: 'fixed-assets', group: 'Columns', label: 'Show Custodian column', type: 'toggle', default: false },
  { id: 'col-serial-number', section: 'fixed-assets', group: 'Columns', label: 'Show Serial Number column', type: 'toggle', default: false },
  { id: 'col-vendor', section: 'fixed-assets', group: 'Columns', label: 'Show Vendor column', type: 'toggle', default: false },
  { id: 'col-status', section: 'fixed-assets', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'col-gl-account', section: 'fixed-assets', group: 'Columns', label: 'Show GL Account column', type: 'toggle', default: false },
  { id: 'col-warranty-expiry', section: 'fixed-assets', group: 'Columns', label: 'Show Warranty Expiry column', type: 'toggle', default: false },
  { id: 'col-disposal-date', section: 'fixed-assets', group: 'Columns', label: 'Show Disposal Date column', type: 'toggle', default: false },
  { id: 'col-disposal-proceeds', section: 'fixed-assets', group: 'Columns', label: 'Show Disposal Proceeds column', type: 'toggle', default: false },
  { id: 'col-monthly-depreciation', section: 'fixed-assets', group: 'Columns', label: 'Show Monthly Depreciation column', type: 'toggle', default: false },
  { id: 'col-remaining-life', section: 'fixed-assets', group: 'Columns', label: 'Show Remaining Life column', type: 'toggle', default: true },
  { id: 'col-cost-center', section: 'fixed-assets', group: 'Columns', label: 'Show Cost Center column', type: 'toggle', default: false },
  { id: 'col-tax-book-value', section: 'fixed-assets', group: 'Columns', label: 'Show Tax Book Value column', type: 'toggle', default: false },

  // ===== Formatting (45-64) =====
  { id: 'fmt-currency-symbol', section: 'fixed-assets', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'fmt-decimal-places', section: 'fixed-assets', group: 'Formatting', label: 'Decimal places for amounts', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'fmt-thousands-separator', section: 'fixed-assets', group: 'Formatting', label: 'Use thousands separator', type: 'toggle', default: true },
  { id: 'fmt-negative-style', section: 'fixed-assets', group: 'Formatting', label: 'Negative number style', type: 'select', default: 'parentheses', options: [ { value: 'minus', label: 'Minus sign' }, { value: 'parentheses', label: 'Parentheses' }, { value: 'red', label: 'Red text' } ] },
  { id: 'fmt-date-format', section: 'fixed-assets', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [ { value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' } ] },
  { id: 'fmt-useful-life-unit', section: 'fixed-assets', group: 'Formatting', label: 'Useful life unit', type: 'select', default: 'years', options: [ { value: 'years', label: 'Years' }, { value: 'months', label: 'Months' } ] },
  { id: 'fmt-zero-as-dash', section: 'fixed-assets', group: 'Formatting', label: 'Show zero values as dash', type: 'toggle', default: true },
  { id: 'fmt-round-depreciation', section: 'fixed-assets', group: 'Formatting', label: 'Round depreciation to whole units', type: 'toggle', default: false },
  { id: 'fmt-percent-decimals', section: 'fixed-assets', group: 'Formatting', label: 'Decimal places for percentages', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'fmt-asset-tag-pattern', section: 'fixed-assets', group: 'Formatting', label: 'Asset tag display pattern', type: 'text', default: 'FA-{0000}' },
  { id: 'fmt-currency-position', section: 'fixed-assets', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [ { value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' } ] },
  { id: 'fmt-life-display', section: 'fixed-assets', group: 'Formatting', label: 'Remaining life display', type: 'select', default: 'years-months', options: [ { value: 'years', label: 'Years' }, { value: 'months', label: 'Months' }, { value: 'years-months', label: 'Years & months' } ] },
  { id: 'fmt-truncate-description', section: 'fixed-assets', group: 'Formatting', label: 'Truncate long descriptions', type: 'toggle', default: true },
  { id: 'fmt-description-max-chars', section: 'fixed-assets', group: 'Formatting', label: 'Description truncation length', type: 'number', default: 60, min: 20, max: 200, step: 5 },
  { id: 'fmt-show-currency-code', section: 'fixed-assets', group: 'Formatting', label: 'Show ISO currency code', type: 'toggle', default: false },
  { id: 'fmt-abbreviate-large', section: 'fixed-assets', group: 'Formatting', label: 'Abbreviate large amounts (K/M)', type: 'toggle', default: false },
  { id: 'fmt-relative-dates', section: 'fixed-assets', group: 'Formatting', label: 'Show relative dates (e.g. "2y ago")', type: 'toggle', default: false },
  { id: 'fmt-category-case', section: 'fixed-assets', group: 'Formatting', label: 'Category text case', type: 'select', default: 'title', options: [ { value: 'title', label: 'Title Case' }, { value: 'upper', label: 'UPPERCASE' }, { value: 'sentence', label: 'Sentence case' } ] },
  { id: 'fmt-fiscal-year-start', section: 'fixed-assets', group: 'Formatting', label: 'Fiscal year start month', type: 'number', default: 1, min: 1, max: 12, step: 1 },
  { id: 'fmt-depreciation-sign', section: 'fixed-assets', group: 'Formatting', label: 'Show accumulated depreciation as negative', type: 'toggle', default: true },

  // ===== Defaults (65-88) =====
  { id: 'def-depreciation-method', section: 'fixed-assets', group: 'Defaults', label: 'Default depreciation method', type: 'select', default: 'straight-line', options: [ { value: 'straight-line', label: 'Straight-line' }, { value: 'declining-balance', label: 'Declining balance' }, { value: 'double-declining', label: 'Double declining' }, { value: 'sum-of-years', label: 'Sum of years digits' }, { value: 'units-of-production', label: 'Units of production' } ] },
  { id: 'def-useful-life-years', section: 'fixed-assets', group: 'Defaults', label: 'Default useful life (years)', type: 'number', default: 5, min: 1, max: 50, step: 1 },
  { id: 'def-salvage-percent', section: 'fixed-assets', group: 'Defaults', label: 'Default salvage value (% of cost)', type: 'number', default: 0, min: 0, max: 50, step: 1 },
  { id: 'def-convention', section: 'fixed-assets', group: 'Defaults', label: 'Default depreciation convention', type: 'select', default: 'half-year', options: [ { value: 'half-year', label: 'Half-year' }, { value: 'mid-month', label: 'Mid-month' }, { value: 'mid-quarter', label: 'Mid-quarter' }, { value: 'full-month', label: 'Full month' } ] },
  { id: 'def-declining-rate', section: 'fixed-assets', group: 'Defaults', label: 'Default declining balance rate (%)', type: 'number', default: 150, min: 100, max: 300, step: 25 },
  { id: 'def-asset-account', section: 'fixed-assets', group: 'Defaults', label: 'Default asset GL account', type: 'text', default: '1500' },
  { id: 'def-accumdep-account', section: 'fixed-assets', group: 'Defaults', label: 'Default accumulated depreciation account', type: 'text', default: '1590' },
  { id: 'def-depexpense-account', section: 'fixed-assets', group: 'Defaults', label: 'Default depreciation expense account', type: 'text', default: '6500' },
  { id: 'def-disposal-gain-account', section: 'fixed-assets', group: 'Defaults', label: 'Default gain/loss on disposal account', type: 'text', default: '7200' },
  { id: 'def-tag-prefix', section: 'fixed-assets', group: 'Defaults', label: 'Default asset tag prefix', type: 'text', default: 'FA-' },
  { id: 'def-capitalization-threshold', section: 'fixed-assets', group: 'Defaults', label: 'Capitalization threshold amount', type: 'number', default: 2500, min: 0, max: 100000, step: 100 },
  { id: 'def-start-depreciation', section: 'fixed-assets', group: 'Defaults', label: 'Start depreciation on', type: 'select', default: 'in-service', options: [ { value: 'acquisition', label: 'Acquisition date' }, { value: 'in-service', label: 'In-service date' }, { value: 'next-period', label: 'Next period start' } ] },
  { id: 'def-category', section: 'fixed-assets', group: 'Defaults', label: 'Default asset category', type: 'select', default: 'equipment', options: [ { value: 'equipment', label: 'Equipment' }, { value: 'vehicles', label: 'Vehicles' }, { value: 'furniture', label: 'Furniture & Fixtures' }, { value: 'buildings', label: 'Buildings' }, { value: 'computers', label: 'Computers' } ] },
  { id: 'def-location', section: 'fixed-assets', group: 'Defaults', label: 'Default location', type: 'text', default: 'Head Office' },
  { id: 'def-currency', section: 'fixed-assets', group: 'Defaults', label: 'Default currency', type: 'text', default: 'USD' },
  { id: 'def-acquisition-date-today', section: 'fixed-assets', group: 'Defaults', label: 'Default acquisition date to today', type: 'toggle', default: true },
  { id: 'def-auto-generate-tag', section: 'fixed-assets', group: 'Defaults', label: 'Auto-generate asset tag', type: 'toggle', default: true },
  { id: 'def-tag-next-number', section: 'fixed-assets', group: 'Defaults', label: 'Next asset tag number', type: 'number', default: 1001, min: 1, max: 9999999, step: 1 },
  { id: 'def-tax-method', section: 'fixed-assets', group: 'Defaults', label: 'Default tax depreciation method', type: 'select', default: 'macrs', options: [ { value: 'macrs', label: 'MACRS' }, { value: 'straight-line', label: 'Straight-line' }, { value: 'section-179', label: 'Section 179' }, { value: 'bonus', label: 'Bonus depreciation' } ] },
  { id: 'def-bonus-percent', section: 'fixed-assets', group: 'Defaults', label: 'Default bonus depreciation (%)', type: 'number', default: 0, min: 0, max: 100, step: 10 },
  { id: 'def-depreciation-frequency', section: 'fixed-assets', group: 'Defaults', label: 'Default depreciation run frequency', type: 'select', default: 'monthly', options: [ { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annually', label: 'Annually' } ] },
  { id: 'def-require-photo', section: 'fixed-assets', group: 'Defaults', label: 'Require photo on new asset', type: 'toggle', default: false },
  { id: 'def-require-serial', section: 'fixed-assets', group: 'Defaults', label: 'Require serial number on new asset', type: 'toggle', default: false },
  { id: 'def-require-custodian', section: 'fixed-assets', group: 'Defaults', label: 'Require custodian assignment', type: 'toggle', default: false },

  // ===== Sorting & Filtering (89-104) =====
  { id: 'sort-default-column', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default sort column', type: 'select', default: 'acquisition-date', options: [ { value: 'asset-tag', label: 'Asset Tag' }, { value: 'description', label: 'Description' }, { value: 'acquisition-date', label: 'Acquisition Date' }, { value: 'net-book-value', label: 'Net Book Value' }, { value: 'category', label: 'Category' } ] },
  { id: 'sort-disposed-last', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Always sort disposed assets last', type: 'toggle', default: true },
  { id: 'filter-remember-last', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'filter-default-category', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default category filter', type: 'select', default: 'all', options: [ { value: 'all', label: 'All categories' }, { value: 'equipment', label: 'Equipment' }, { value: 'vehicles', label: 'Vehicles' }, { value: 'computers', label: 'Computers' } ] },
  { id: 'filter-default-location', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default location filter', type: 'text', default: '' },
  { id: 'filter-date-range', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default acquisition date range', type: 'select', default: 'all', options: [ { value: 'all', label: 'All time' }, { value: 'this-year', label: 'This year' }, { value: 'last-year', label: 'Last year' }, { value: 'this-quarter', label: 'This quarter' } ] },
  { id: 'filter-min-value', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default minimum book value filter', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'filter-show-search-bar', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Show quick search bar', type: 'toggle', default: true },
  { id: 'filter-search-scope', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Quick search scope', type: 'select', default: 'all', options: [ { value: 'all', label: 'All fields' }, { value: 'tag-desc', label: 'Tag & description' }, { value: 'serial', label: 'Serial number' } ] },
  { id: 'filter-fuzzy-search', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Enable fuzzy search matching', type: 'toggle', default: false },
  { id: 'filter-default-status', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Default status filter on load', type: 'select', default: 'active', options: [ { value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'disposed', label: 'Disposed' }, { value: 'idle', label: 'Idle' } ] },
  { id: 'filter-saved-views-enabled', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Enable saved filter views', type: 'toggle', default: true },
  { id: 'filter-secondary-sort', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Secondary sort column', type: 'select', default: 'asset-tag', options: [ { value: 'asset-tag', label: 'Asset Tag' }, { value: 'description', label: 'Description' }, { value: 'category', label: 'Category' } ] },
  { id: 'filter-case-sensitive', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'filter-max-saved-views', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Maximum saved views', type: 'number', default: 10, min: 1, max: 50, step: 1 },
  { id: 'filter-clear-on-navigate', section: 'fixed-assets', group: 'Sorting & Filtering', label: 'Clear filters when leaving module', type: 'toggle', default: false },

  // ===== Behavior (105-128) =====
  { id: 'beh-confirm-disposal', section: 'fixed-assets', group: 'Behavior', label: 'Confirm before disposing an asset', type: 'toggle', default: true },
  { id: 'beh-confirm-delete', section: 'fixed-assets', group: 'Behavior', label: 'Confirm before deleting an asset', type: 'toggle', default: true },
  { id: 'beh-auto-post-depreciation', section: 'fixed-assets', group: 'Behavior', label: 'Auto-post depreciation journal entries', type: 'toggle', default: false },
  { id: 'beh-auto-calc-on-edit', section: 'fixed-assets', group: 'Behavior', label: 'Recalculate depreciation on edit', type: 'toggle', default: true },
  { id: 'beh-prevent-backdated', section: 'fixed-assets', group: 'Behavior', label: 'Prevent backdated acquisitions', type: 'toggle', default: false },
  { id: 'beh-lock-after-depreciation', section: 'fixed-assets', group: 'Behavior', label: 'Lock cost after first depreciation run', type: 'toggle', default: true },
  { id: 'beh-warn-below-threshold', section: 'fixed-assets', group: 'Behavior', label: 'Warn when below capitalization threshold', type: 'toggle', default: true },
  { id: 'beh-autosave-draft', section: 'fixed-assets', group: 'Behavior', label: 'Auto-save asset draft while editing', type: 'toggle', default: true },
  { id: 'beh-autosave-interval', section: 'fixed-assets', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'beh-duplicate-on-create', section: 'fixed-assets', group: 'Behavior', label: 'Copy last asset values on new asset', type: 'toggle', default: false },
  { id: 'beh-open-after-create', section: 'fixed-assets', group: 'Behavior', label: 'Open asset detail after creating', type: 'toggle', default: true },
  { id: 'beh-keep-disposed-history', section: 'fixed-assets', group: 'Behavior', label: 'Retain full history for disposed assets', type: 'toggle', default: true },
  { id: 'beh-recalc-on-impairment', section: 'fixed-assets', group: 'Behavior', label: 'Recalculate schedule after impairment', type: 'toggle', default: true },
  { id: 'beh-auto-retire-zero', section: 'fixed-assets', group: 'Behavior', label: 'Auto-flag fully depreciated assets for review', type: 'toggle', default: false },
  { id: 'beh-require-approval-disposal', section: 'fixed-assets', group: 'Behavior', label: 'Require approval for disposals', type: 'toggle', default: false },
  { id: 'beh-disposal-approval-threshold', section: 'fixed-assets', group: 'Behavior', label: 'Disposal approval threshold amount', type: 'number', default: 5000, min: 0, max: 1000000, step: 500 },
  { id: 'beh-prorate-partial-period', section: 'fixed-assets', group: 'Behavior', label: 'Prorate depreciation for partial periods', type: 'toggle', default: true },
  { id: 'beh-rounding-strategy', section: 'fixed-assets', group: 'Behavior', label: 'Depreciation rounding strategy', type: 'select', default: 'last-period', options: [ { value: 'each-period', label: 'Round each period' }, { value: 'last-period', label: 'Absorb in last period' }, { value: 'none', label: 'No rounding' } ] },
  { id: 'beh-allow-negative-nbv', section: 'fixed-assets', group: 'Behavior', label: 'Allow net book value below salvage', type: 'toggle', default: false },
  { id: 'beh-link-maintenance', section: 'fixed-assets', group: 'Behavior', label: 'Link maintenance records to assets', type: 'toggle', default: true },
  { id: 'beh-default-action-row-click', section: 'fixed-assets', group: 'Behavior', label: 'Row click action', type: 'select', default: 'detail', options: [ { value: 'detail', label: 'Open detail' }, { value: 'edit', label: 'Open edit' }, { value: 'select', label: 'Select row' } ] },
  { id: 'beh-bulk-edit-enabled', section: 'fixed-assets', group: 'Behavior', label: 'Enable bulk edit actions', type: 'toggle', default: true },
  { id: 'beh-bulk-max-selection', section: 'fixed-assets', group: 'Behavior', label: 'Maximum bulk selection size', type: 'number', default: 200, min: 10, max: 5000, step: 10 },
  { id: 'beh-undo-window-seconds', section: 'fixed-assets', group: 'Behavior', label: 'Undo window after disposal (seconds)', type: 'number', default: 10, min: 0, max: 60, step: 1 },

  // ===== Notifications (129-148) =====
  { id: 'notif-eol-approaching', section: 'fixed-assets', group: 'Notifications', label: 'Notify when assets approach end of life', type: 'toggle', default: true },
  { id: 'notif-warranty-expiring', section: 'fixed-assets', group: 'Notifications', label: 'Notify when warranty is expiring', type: 'toggle', default: true },
  { id: 'notif-warranty-lead-days', section: 'fixed-assets', group: 'Notifications', label: 'Warranty expiry notice lead time (days)', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'notif-depreciation-due', section: 'fixed-assets', group: 'Notifications', label: 'Notify when depreciation run is due', type: 'toggle', default: true },
  { id: 'notif-fully-depreciated', section: 'fixed-assets', group: 'Notifications', label: 'Notify when an asset becomes fully depreciated', type: 'toggle', default: false },
  { id: 'notif-maintenance-due', section: 'fixed-assets', group: 'Notifications', label: 'Notify when maintenance is due', type: 'toggle', default: true },
  { id: 'notif-insurance-renewal', section: 'fixed-assets', group: 'Notifications', label: 'Notify on insurance renewal date', type: 'toggle', default: false },
  { id: 'notif-lease-expiry', section: 'fixed-assets', group: 'Notifications', label: 'Notify on leased asset expiry', type: 'toggle', default: true },
  { id: 'notif-channel', section: 'fixed-assets', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [ { value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' } ] },
  { id: 'notif-digest-frequency', section: 'fixed-assets', group: 'Notifications', label: 'Notification digest frequency', type: 'select', default: 'weekly', options: [ { value: 'realtime', label: 'Real-time' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' } ] },
  { id: 'notif-disposal-posted', section: 'fixed-assets', group: 'Notifications', label: 'Notify when disposal is posted', type: 'toggle', default: true },
  { id: 'notif-impairment-recorded', section: 'fixed-assets', group: 'Notifications', label: 'Notify when impairment is recorded', type: 'toggle', default: true },
  { id: 'notif-custodian-change', section: 'fixed-assets', group: 'Notifications', label: 'Notify on custodian reassignment', type: 'toggle', default: false },
  { id: 'notif-location-change', section: 'fixed-assets', group: 'Notifications', label: 'Notify on location transfer', type: 'toggle', default: false },
  { id: 'notif-audit-due', section: 'fixed-assets', group: 'Notifications', label: 'Notify when physical audit is due', type: 'toggle', default: true },
  { id: 'notif-audit-interval-months', section: 'fixed-assets', group: 'Notifications', label: 'Physical audit interval (months)', type: 'number', default: 12, min: 1, max: 60, step: 1 },
  { id: 'notif-sound', section: 'fixed-assets', group: 'Notifications', label: 'Play sound on notification', type: 'toggle', default: false },
  { id: 'notif-recipient-email', section: 'fixed-assets', group: 'Notifications', label: 'Notification recipient email', type: 'text', default: '' },
  { id: 'notif-quiet-start', section: 'fixed-assets', group: 'Notifications', label: 'Quiet hours start (24h)', type: 'number', default: 18, min: 0, max: 23, step: 1 },
  { id: 'notif-quiet-end', section: 'fixed-assets', group: 'Notifications', label: 'Quiet hours end (24h)', type: 'number', default: 8, min: 0, max: 23, step: 1 },

  // ===== Export (149-168) =====
  { id: 'exp-default-format', section: 'fixed-assets', group: 'Export', label: 'Default export format', type: 'select', default: 'xlsx', options: [ { value: 'xlsx', label: 'Excel (.xlsx)' }, { value: 'csv', label: 'CSV' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' } ] },
  { id: 'exp-include-disposed', section: 'fixed-assets', group: 'Export', label: 'Include disposed assets in export', type: 'toggle', default: false },
  { id: 'exp-include-depreciation-schedule', section: 'fixed-assets', group: 'Export', label: 'Include full depreciation schedule', type: 'toggle', default: false },
  { id: 'exp-include-photos', section: 'fixed-assets', group: 'Export', label: 'Embed asset photos in export', type: 'toggle', default: false },
  { id: 'exp-include-totals-row', section: 'fixed-assets', group: 'Export', label: 'Include totals row', type: 'toggle', default: true },
  { id: 'exp-only-visible-columns', section: 'fixed-assets', group: 'Export', label: 'Export only visible columns', type: 'toggle', default: true },
  { id: 'exp-date-format', section: 'fixed-assets', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [ { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' } ] },
  { id: 'exp-filename-pattern', section: 'fixed-assets', group: 'Export', label: 'Export filename pattern', type: 'text', default: 'fixed-assets-{date}' },
  { id: 'exp-pdf-orientation', section: 'fixed-assets', group: 'Export', label: 'PDF page orientation', type: 'select', default: 'landscape', options: [ { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' } ] },
  { id: 'exp-pdf-page-size', section: 'fixed-assets', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [ { value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' } ] },
  { id: 'exp-include-company-header', section: 'fixed-assets', group: 'Export', label: 'Include company header on PDF', type: 'toggle', default: true },
  { id: 'exp-include-logo', section: 'fixed-assets', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'exp-csv-delimiter', section: 'fixed-assets', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [ { value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' } ] },
  { id: 'exp-include-gl-mapping', section: 'fixed-assets', group: 'Export', label: 'Include GL account mapping', type: 'toggle', default: false },
  { id: 'exp-include-tax-book', section: 'fixed-assets', group: 'Export', label: 'Include tax book values', type: 'toggle', default: false },
  { id: 'exp-group-by-category', section: 'fixed-assets', group: 'Export', label: 'Group export rows by category', type: 'toggle', default: false },
  { id: 'exp-subtotals-per-group', section: 'fixed-assets', group: 'Export', label: 'Include subtotals per group', type: 'toggle', default: true },
  { id: 'exp-open-after-export', section: 'fixed-assets', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'exp-include-footer-timestamp', section: 'fixed-assets', group: 'Export', label: 'Include generation timestamp footer', type: 'toggle', default: true },
  { id: 'exp-decimal-places', section: 'fixed-assets', group: 'Export', label: 'Export decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },

  // ===== Colors & Theme (169-184) =====
  { id: 'color-active-status', section: 'fixed-assets', group: 'Colors & Theme', label: 'Active status color', type: 'color', default: '#22c55e' },
  { id: 'color-disposed-status', section: 'fixed-assets', group: 'Colors & Theme', label: 'Disposed status color', type: 'color', default: '#64748b' },
  { id: 'color-idle-status', section: 'fixed-assets', group: 'Colors & Theme', label: 'Idle status color', type: 'color', default: '#f59e0b' },
  { id: 'color-impaired-status', section: 'fixed-assets', group: 'Colors & Theme', label: 'Impaired status color', type: 'color', default: '#ef4444' },
  { id: 'color-eol-highlight', section: 'fixed-assets', group: 'Colors & Theme', label: 'End-of-life highlight color', type: 'color', default: '#fb923c' },
  { id: 'color-fully-depreciated', section: 'fixed-assets', group: 'Colors & Theme', label: 'Fully depreciated row color', type: 'color', default: '#94a3b8' },
  { id: 'color-net-book-positive', section: 'fixed-assets', group: 'Colors & Theme', label: 'Positive net book value color', type: 'color', default: '#16a34a' },
  { id: 'color-net-book-negative', section: 'fixed-assets', group: 'Colors & Theme', label: 'Negative value color', type: 'color', default: '#dc2626' },
  { id: 'color-chart-accent', section: 'fixed-assets', group: 'Colors & Theme', label: 'Chart accent color', type: 'color', default: '#3b82f6' },
  { id: 'color-depreciation-line', section: 'fixed-assets', group: 'Colors & Theme', label: 'Depreciation chart line color', type: 'color', default: '#8b5cf6' },
  { id: 'color-warranty-active', section: 'fixed-assets', group: 'Colors & Theme', label: 'Active warranty color', type: 'color', default: '#06b6d4' },
  { id: 'color-warranty-expired', section: 'fixed-assets', group: 'Colors & Theme', label: 'Expired warranty color', type: 'color', default: '#a16207' },
  { id: 'color-category-equipment', section: 'fixed-assets', group: 'Colors & Theme', label: 'Equipment category color', type: 'color', default: '#0ea5e9' },
  { id: 'color-category-vehicles', section: 'fixed-assets', group: 'Colors & Theme', label: 'Vehicles category color', type: 'color', default: '#f43f5e' },
  { id: 'color-selected-row', section: 'fixed-assets', group: 'Colors & Theme', label: 'Selected row highlight color', type: 'color', default: '#1d4ed8' },
  { id: 'color-theme-mode', section: 'fixed-assets', group: 'Colors & Theme', label: 'Module color theme', type: 'select', default: 'system', options: [ { value: 'system', label: 'Follow system' }, { value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' } ] },

  // ===== Accessibility (185-192) =====
  { id: 'a11y-high-contrast', section: 'fixed-assets', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'a11y-font-size', section: 'fixed-assets', group: 'Accessibility', label: 'Base font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'a11y-status-icons', section: 'fixed-assets', group: 'Accessibility', label: 'Use icons alongside status colors', type: 'toggle', default: true },
  { id: 'a11y-reduce-motion', section: 'fixed-assets', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'a11y-focus-outline', section: 'fixed-assets', group: 'Accessibility', label: 'Show strong keyboard focus outline', type: 'toggle', default: true },
  { id: 'a11y-screen-reader-summaries', section: 'fixed-assets', group: 'Accessibility', label: 'Announce table summaries to screen readers', type: 'toggle', default: true },
  { id: 'a11y-colorblind-palette', section: 'fixed-assets', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'select', default: 'off', options: [ { value: 'off', label: 'Off' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' } ] },
  { id: 'a11y-underline-links', section: 'fixed-assets', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },

  // ===== Shortcuts (193-196) =====
  { id: 'shortcut-new-asset', section: 'fixed-assets', group: 'Shortcuts', label: 'New asset shortcut', type: 'text', default: 'Ctrl+N' },
  { id: 'shortcut-run-depreciation', section: 'fixed-assets', group: 'Shortcuts', label: 'Run depreciation shortcut', type: 'text', default: 'Ctrl+D' },
  { id: 'shortcut-export', section: 'fixed-assets', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'Ctrl+E' },
  { id: 'shortcut-enabled', section: 'fixed-assets', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },

  // ===== Privacy (197-200) =====
  { id: 'privacy-mask-cost', section: 'fixed-assets', group: 'Privacy', label: 'Mask acquisition cost for non-admins', type: 'toggle', default: false },
  { id: 'privacy-hide-custodian', section: 'fixed-assets', group: 'Privacy', label: 'Hide custodian names in shared views', type: 'toggle', default: false },
  { id: 'privacy-audit-log-changes', section: 'fixed-assets', group: 'Privacy', label: 'Log all asset changes to audit trail', type: 'toggle', default: true },
  { id: 'privacy-retention-years', section: 'fixed-assets', group: 'Privacy', label: 'Disposed asset retention period (years)', type: 'number', default: 7, min: 1, max: 30, step: 1 },
];
