import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-18) =====
  { id: 'inv-display-density', section: 'inventory', group: 'Display', label: 'Row density', description: 'Vertical spacing of item rows', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'inv-display-thumbnails', section: 'inventory', group: 'Display', label: 'Show product thumbnails', description: 'Display a product image in each row', type: 'toggle', default: true },
  { id: 'inv-display-thumbnail-size', section: 'inventory', group: 'Display', label: 'Thumbnail size (px)', type: 'number', default: 40, min: 24, max: 96, step: 4 },
  { id: 'inv-display-view-mode', section: 'inventory', group: 'Display', label: 'Default view mode', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'grid', label: 'Grid' }, { value: 'kanban', label: 'Kanban by status' }] },
  { id: 'inv-display-rows-per-page', section: 'inventory', group: 'Display', label: 'Items per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'inv-display-zebra-stripes', section: 'inventory', group: 'Display', label: 'Zebra-striped rows', type: 'toggle', default: true },
  { id: 'inv-display-sticky-header', section: 'inventory', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'inv-display-pin-low-stock', section: 'inventory', group: 'Display', label: 'Pin low-stock items to top', type: 'toggle', default: false },
  { id: 'inv-display-show-archived', section: 'inventory', group: 'Display', label: 'Show archived items', type: 'toggle', default: false },
  { id: 'inv-display-show-inactive', section: 'inventory', group: 'Display', label: 'Show inactive SKUs', type: 'toggle', default: true },
  { id: 'inv-display-group-by', section: 'inventory', group: 'Display', label: 'Group items by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'category', label: 'Category' }, { value: 'warehouse', label: 'Warehouse' }, { value: 'vendor', label: 'Vendor' }, { value: 'status', label: 'Stock status' }] },
  { id: 'inv-display-collapse-groups', section: 'inventory', group: 'Display', label: 'Collapse groups by default', type: 'toggle', default: false },
  { id: 'inv-display-empty-placeholder', section: 'inventory', group: 'Display', label: 'Empty list message', type: 'text', default: 'No inventory items found' },
  { id: 'inv-display-show-item-count', section: 'inventory', group: 'Display', label: 'Show total item count badge', type: 'toggle', default: true },
  { id: 'inv-display-show-total-value', section: 'inventory', group: 'Display', label: 'Show total inventory value', type: 'toggle', default: true },
  { id: 'inv-display-truncate-names', section: 'inventory', group: 'Display', label: 'Truncate long product names', type: 'toggle', default: true },
  { id: 'inv-display-name-max-chars', section: 'inventory', group: 'Display', label: 'Product name max characters', type: 'number', default: 60, min: 20, max: 200, step: 5 },
  { id: 'inv-display-show-barcode-preview', section: 'inventory', group: 'Display', label: 'Show barcode preview in detail', type: 'toggle', default: false },

  // ===== Columns (19-44) =====
  { id: 'inv-col-sku', section: 'inventory', group: 'Columns', label: 'Show SKU column', type: 'toggle', default: true },
  { id: 'inv-col-barcode', section: 'inventory', group: 'Columns', label: 'Show barcode/UPC column', type: 'toggle', default: false },
  { id: 'inv-col-name', section: 'inventory', group: 'Columns', label: 'Show product name column', type: 'toggle', default: true },
  { id: 'inv-col-category', section: 'inventory', group: 'Columns', label: 'Show category column', type: 'toggle', default: true },
  { id: 'inv-col-on-hand', section: 'inventory', group: 'Columns', label: 'Show quantity on hand', type: 'toggle', default: true },
  { id: 'inv-col-available', section: 'inventory', group: 'Columns', label: 'Show available quantity', type: 'toggle', default: true },
  { id: 'inv-col-committed', section: 'inventory', group: 'Columns', label: 'Show committed quantity', type: 'toggle', default: false },
  { id: 'inv-col-incoming', section: 'inventory', group: 'Columns', label: 'Show incoming (PO) quantity', type: 'toggle', default: false },
  { id: 'inv-col-reorder-point', section: 'inventory', group: 'Columns', label: 'Show reorder point column', type: 'toggle', default: true },
  { id: 'inv-col-unit-cost', section: 'inventory', group: 'Columns', label: 'Show unit cost column', type: 'toggle', default: true },
  { id: 'inv-col-sell-price', section: 'inventory', group: 'Columns', label: 'Show sell price column', type: 'toggle', default: true },
  { id: 'inv-col-margin', section: 'inventory', group: 'Columns', label: 'Show margin % column', type: 'toggle', default: false },
  { id: 'inv-col-total-value', section: 'inventory', group: 'Columns', label: 'Show line total value column', type: 'toggle', default: true },
  { id: 'inv-col-warehouse', section: 'inventory', group: 'Columns', label: 'Show warehouse/location column', type: 'toggle', default: true },
  { id: 'inv-col-bin', section: 'inventory', group: 'Columns', label: 'Show bin/shelf location column', type: 'toggle', default: false },
  { id: 'inv-col-vendor', section: 'inventory', group: 'Columns', label: 'Show preferred vendor column', type: 'toggle', default: false },
  { id: 'inv-col-uom', section: 'inventory', group: 'Columns', label: 'Show unit of measure column', type: 'toggle', default: true },
  { id: 'inv-col-status', section: 'inventory', group: 'Columns', label: 'Show stock status column', type: 'toggle', default: true },
  { id: 'inv-col-last-received', section: 'inventory', group: 'Columns', label: 'Show last received date column', type: 'toggle', default: false },
  { id: 'inv-col-last-sold', section: 'inventory', group: 'Columns', label: 'Show last sold date column', type: 'toggle', default: false },
  { id: 'inv-col-lead-time', section: 'inventory', group: 'Columns', label: 'Show lead time column', type: 'toggle', default: false },
  { id: 'inv-col-lot', section: 'inventory', group: 'Columns', label: 'Show lot/batch column', type: 'toggle', default: false },
  { id: 'inv-col-expiry', section: 'inventory', group: 'Columns', label: 'Show expiry date column', type: 'toggle', default: false },
  { id: 'inv-col-serial', section: 'inventory', group: 'Columns', label: 'Show serial number column', type: 'toggle', default: false },
  { id: 'inv-col-tax-code', section: 'inventory', group: 'Columns', label: 'Show tax code column', type: 'toggle', default: false },
  { id: 'inv-col-frozen-first', section: 'inventory', group: 'Columns', label: 'Freeze first column on scroll', type: 'toggle', default: true },

  // ===== Formatting (45-66) =====
  { id: 'inv-fmt-currency-symbol', section: 'inventory', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'inv-fmt-currency-position', section: 'inventory', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'inv-fmt-cost-decimals', section: 'inventory', group: 'Formatting', label: 'Cost decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'inv-fmt-qty-decimals', section: 'inventory', group: 'Formatting', label: 'Quantity decimal places', type: 'number', default: 0, min: 0, max: 4, step: 1 },
  { id: 'inv-fmt-thousands-separator', section: 'inventory', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None (1000)' }] },
  { id: 'inv-fmt-negative-style', section: 'inventory', group: 'Formatting', label: 'Negative number style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-100' }, { value: 'parentheses', label: '(100)' }, { value: 'red', label: 'Red text' }] },
  { id: 'inv-fmt-date-format', section: 'inventory', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }] },
  { id: 'inv-fmt-margin-as-percent', section: 'inventory', group: 'Formatting', label: 'Show margin as percent (vs amount)', type: 'toggle', default: true },
  { id: 'inv-fmt-margin-decimals', section: 'inventory', group: 'Formatting', label: 'Margin decimal places', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'inv-fmt-uom-abbreviate', section: 'inventory', group: 'Formatting', label: 'Abbreviate units of measure', type: 'toggle', default: true },
  { id: 'inv-fmt-sku-uppercase', section: 'inventory', group: 'Formatting', label: 'Force SKU to uppercase', type: 'toggle', default: true },
  { id: 'inv-fmt-zero-as-dash', section: 'inventory', group: 'Formatting', label: 'Show zero quantities as dash', type: 'toggle', default: false },
  { id: 'inv-fmt-round-value-display', section: 'inventory', group: 'Formatting', label: 'Round displayed value to whole', type: 'toggle', default: false },
  { id: 'inv-fmt-percent-symbol', section: 'inventory', group: 'Formatting', label: 'Show % symbol on percentages', type: 'toggle', default: true },
  { id: 'inv-fmt-weight-unit', section: 'inventory', group: 'Formatting', label: 'Weight unit', type: 'select', default: 'lb', options: [{ value: 'lb', label: 'Pounds (lb)' }, { value: 'kg', label: 'Kilograms (kg)' }, { value: 'oz', label: 'Ounces (oz)' }, { value: 'g', label: 'Grams (g)' }] },
  { id: 'inv-fmt-dimension-unit', section: 'inventory', group: 'Formatting', label: 'Dimension unit', type: 'select', default: 'in', options: [{ value: 'in', label: 'Inches' }, { value: 'cm', label: 'Centimeters' }, { value: 'mm', label: 'Millimeters' }] },
  { id: 'inv-fmt-truncate-trailing-zeros', section: 'inventory', group: 'Formatting', label: 'Trim trailing zeros on quantities', type: 'toggle', default: true },
  { id: 'inv-fmt-relative-dates', section: 'inventory', group: 'Formatting', label: 'Use relative dates (3 days ago)', type: 'toggle', default: false },
  { id: 'inv-fmt-barcode-symbology', section: 'inventory', group: 'Formatting', label: 'Default barcode symbology', type: 'select', default: 'code128', options: [{ value: 'code128', label: 'Code 128' }, { value: 'ean13', label: 'EAN-13' }, { value: 'upca', label: 'UPC-A' }, { value: 'qr', label: 'QR Code' }] },
  { id: 'inv-fmt-cost-method-label', section: 'inventory', group: 'Formatting', label: 'Show costing method label', type: 'toggle', default: true },
  { id: 'inv-fmt-locale', section: 'inventory', group: 'Formatting', label: 'Number locale', type: 'text', default: 'en-US' },
  { id: 'inv-fmt-value-tooltip-breakdown', section: 'inventory', group: 'Formatting', label: 'Show cost breakdown tooltip on value', type: 'toggle', default: true },

  // ===== Defaults (67-88) =====
  { id: 'inv-def-costing-method', section: 'inventory', group: 'Defaults', label: 'Default costing method', type: 'select', default: 'fifo', options: [{ value: 'fifo', label: 'FIFO' }, { value: 'lifo', label: 'LIFO' }, { value: 'average', label: 'Weighted average' }, { value: 'standard', label: 'Standard cost' }] },
  { id: 'inv-def-track-method', section: 'inventory', group: 'Defaults', label: 'Default tracking method', type: 'select', default: 'quantity', options: [{ value: 'quantity', label: 'Quantity only' }, { value: 'lot', label: 'Lot/batch' }, { value: 'serial', label: 'Serial number' }] },
  { id: 'inv-def-reorder-point', section: 'inventory', group: 'Defaults', label: 'Default reorder point', type: 'number', default: 10, min: 0, max: 10000, step: 1 },
  { id: 'inv-def-reorder-qty', section: 'inventory', group: 'Defaults', label: 'Default reorder quantity', type: 'number', default: 50, min: 1, max: 10000, step: 1 },
  { id: 'inv-def-safety-stock', section: 'inventory', group: 'Defaults', label: 'Default safety stock', type: 'number', default: 5, min: 0, max: 10000, step: 1 },
  { id: 'inv-def-uom', section: 'inventory', group: 'Defaults', label: 'Default unit of measure', type: 'select', default: 'each', options: [{ value: 'each', label: 'Each' }, { value: 'case', label: 'Case' }, { value: 'box', label: 'Box' }, { value: 'lb', label: 'Pound' }, { value: 'kg', label: 'Kilogram' }] },
  { id: 'inv-def-warehouse', section: 'inventory', group: 'Defaults', label: 'Default warehouse', type: 'text', default: 'Main Warehouse' },
  { id: 'inv-def-category', section: 'inventory', group: 'Defaults', label: 'Default category for new items', type: 'text', default: 'Uncategorized' },
  { id: 'inv-def-markup-percent', section: 'inventory', group: 'Defaults', label: 'Default markup percent', type: 'number', default: 40, min: 0, max: 1000, step: 5 },
  { id: 'inv-def-tax-code', section: 'inventory', group: 'Defaults', label: 'Default tax code', type: 'text', default: 'TAX' },
  { id: 'inv-def-lead-time-days', section: 'inventory', group: 'Defaults', label: 'Default lead time (days)', type: 'number', default: 7, min: 0, max: 365, step: 1 },
  { id: 'inv-def-allow-negative-stock', section: 'inventory', group: 'Defaults', label: 'Allow negative stock by default', type: 'toggle', default: false },
  { id: 'inv-def-track-by-default', section: 'inventory', group: 'Defaults', label: 'Track new items in inventory', type: 'toggle', default: true },
  { id: 'inv-def-taxable', section: 'inventory', group: 'Defaults', label: 'New items taxable by default', type: 'toggle', default: true },
  { id: 'inv-def-sku-prefix', section: 'inventory', group: 'Defaults', label: 'Auto-SKU prefix', type: 'text', default: 'SKU-' },
  { id: 'inv-def-sku-auto', section: 'inventory', group: 'Defaults', label: 'Auto-generate SKU on new item', type: 'toggle', default: true },
  { id: 'inv-def-sku-pad-length', section: 'inventory', group: 'Defaults', label: 'Auto-SKU number padding', type: 'number', default: 5, min: 1, max: 10, step: 1 },
  { id: 'inv-def-active-status', section: 'inventory', group: 'Defaults', label: 'New items active by default', type: 'toggle', default: true },
  { id: 'inv-def-shrinkage-account', section: 'inventory', group: 'Defaults', label: 'Default shrinkage account', type: 'text', default: 'Inventory Adjustments' },
  { id: 'inv-def-cogs-account', section: 'inventory', group: 'Defaults', label: 'Default COGS account', type: 'text', default: 'Cost of Goods Sold' },
  { id: 'inv-def-asset-account', section: 'inventory', group: 'Defaults', label: 'Default inventory asset account', type: 'text', default: 'Inventory Asset' },
  { id: 'inv-def-valuation-currency', section: 'inventory', group: 'Defaults', label: 'Valuation currency', type: 'text', default: 'USD' },

  // ===== Sorting & Filtering (89-108) =====
  { id: 'inv-sort-default-field', section: 'inventory', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'name', options: [{ value: 'name', label: 'Name' }, { value: 'sku', label: 'SKU' }, { value: 'on_hand', label: 'Quantity' }, { value: 'value', label: 'Value' }, { value: 'category', label: 'Category' }] },
  { id: 'inv-sort-default-dir', section: 'inventory', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'inv-sort-low-stock-first', section: 'inventory', group: 'Sorting & Filtering', label: 'Low stock secondary sort', type: 'toggle', default: false },
  { id: 'inv-filter-remember', section: 'inventory', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'inv-filter-default-status', section: 'inventory', group: 'Sorting & Filtering', label: 'Default stock status filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'in_stock', label: 'In stock' }, { value: 'low', label: 'Low stock' }, { value: 'out', label: 'Out of stock' }] },
  { id: 'inv-filter-default-category', section: 'inventory', group: 'Sorting & Filtering', label: 'Default category filter', type: 'text', default: '' },
  { id: 'inv-filter-default-warehouse', section: 'inventory', group: 'Sorting & Filtering', label: 'Default warehouse filter', type: 'text', default: '' },
  { id: 'inv-filter-hide-zero-value', section: 'inventory', group: 'Sorting & Filtering', label: 'Hide zero-value items', type: 'toggle', default: false },
  { id: 'inv-filter-search-includes-sku', section: 'inventory', group: 'Sorting & Filtering', label: 'Search includes SKU', type: 'toggle', default: true },
  { id: 'inv-filter-search-includes-barcode', section: 'inventory', group: 'Sorting & Filtering', label: 'Search includes barcode', type: 'toggle', default: true },
  { id: 'inv-filter-search-includes-desc', section: 'inventory', group: 'Sorting & Filtering', label: 'Search includes description', type: 'toggle', default: false },
  { id: 'inv-filter-search-fuzzy', section: 'inventory', group: 'Sorting & Filtering', label: 'Fuzzy search matching', type: 'toggle', default: true },
  { id: 'inv-filter-search-debounce', section: 'inventory', group: 'Sorting & Filtering', label: 'Search debounce (ms)', type: 'number', default: 300, min: 0, max: 2000, step: 50 },
  { id: 'inv-filter-quick-low-stock', section: 'inventory', group: 'Sorting & Filtering', label: 'Show quick low-stock filter chip', type: 'toggle', default: true },
  { id: 'inv-filter-quick-expiring', section: 'inventory', group: 'Sorting & Filtering', label: 'Show quick expiring-soon filter chip', type: 'toggle', default: false },
  { id: 'inv-filter-saved-views', section: 'inventory', group: 'Sorting & Filtering', label: 'Enable saved filter views', type: 'toggle', default: true },
  { id: 'inv-filter-multi-category', section: 'inventory', group: 'Sorting & Filtering', label: 'Allow multi-category selection', type: 'toggle', default: true },
  { id: 'inv-filter-value-min', section: 'inventory', group: 'Sorting & Filtering', label: 'Default minimum value filter', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'inv-filter-clear-on-nav', section: 'inventory', group: 'Sorting & Filtering', label: 'Clear filters when leaving page', type: 'toggle', default: false },
  { id: 'inv-sort-natural-sku', section: 'inventory', group: 'Sorting & Filtering', label: 'Natural sort for SKU numbers', type: 'toggle', default: true },

  // ===== Behavior (109-130) =====
  { id: 'inv-beh-confirm-delete', section: 'inventory', group: 'Behavior', label: 'Confirm before deleting items', type: 'toggle', default: true },
  { id: 'inv-beh-confirm-adjust', section: 'inventory', group: 'Behavior', label: 'Confirm stock adjustments', type: 'toggle', default: true },
  { id: 'inv-beh-require-adjust-reason', section: 'inventory', group: 'Behavior', label: 'Require reason for adjustments', type: 'toggle', default: true },
  { id: 'inv-beh-auto-deduct-on-sale', section: 'inventory', group: 'Behavior', label: 'Auto-deduct stock on invoice', type: 'toggle', default: true },
  { id: 'inv-beh-auto-add-on-po', section: 'inventory', group: 'Behavior', label: 'Auto-add stock on PO receipt', type: 'toggle', default: true },
  { id: 'inv-beh-block-oversell', section: 'inventory', group: 'Behavior', label: 'Block selling below zero stock', type: 'toggle', default: false },
  { id: 'inv-beh-warn-oversell', section: 'inventory', group: 'Behavior', label: 'Warn when overselling', type: 'toggle', default: true },
  { id: 'inv-beh-auto-reorder-draft', section: 'inventory', group: 'Behavior', label: 'Auto-create draft PO at reorder point', type: 'toggle', default: false },
  { id: 'inv-beh-recalc-avg-on-receipt', section: 'inventory', group: 'Behavior', label: 'Recalculate average cost on receipt', type: 'toggle', default: true },
  { id: 'inv-beh-inline-edit', section: 'inventory', group: 'Behavior', label: 'Enable inline cell editing', type: 'toggle', default: true },
  { id: 'inv-beh-autosave-drafts', section: 'inventory', group: 'Behavior', label: 'Auto-save item drafts', type: 'toggle', default: true },
  { id: 'inv-beh-keep-form-open', section: 'inventory', group: 'Behavior', label: 'Keep form open after save (add another)', type: 'toggle', default: false },
  { id: 'inv-beh-duplicate-on-clone', section: 'inventory', group: 'Behavior', label: 'Copy stock levels when cloning item', type: 'toggle', default: false },
  { id: 'inv-beh-barcode-scan-focus', section: 'inventory', group: 'Behavior', label: 'Auto-focus barcode scan field', type: 'toggle', default: true },
  { id: 'inv-beh-scan-action', section: 'inventory', group: 'Behavior', label: 'Action on barcode scan', type: 'select', default: 'open', options: [{ value: 'open', label: 'Open item' }, { value: 'adjust', label: 'Quick adjust' }, { value: 'add_to_count', label: 'Add to count sheet' }] },
  { id: 'inv-beh-double-click-action', section: 'inventory', group: 'Behavior', label: 'Row double-click action', type: 'select', default: 'edit', options: [{ value: 'edit', label: 'Edit item' }, { value: 'detail', label: 'View detail' }, { value: 'adjust', label: 'Adjust stock' }] },
  { id: 'inv-beh-prevent-dup-sku', section: 'inventory', group: 'Behavior', label: 'Prevent duplicate SKUs', type: 'toggle', default: true },
  { id: 'inv-beh-prevent-dup-barcode', section: 'inventory', group: 'Behavior', label: 'Prevent duplicate barcodes', type: 'toggle', default: true },
  { id: 'inv-beh-cycle-count-mode', section: 'inventory', group: 'Behavior', label: 'Cycle count blind entry', description: 'Hide expected qty during counts', type: 'toggle', default: true },
  { id: 'inv-beh-negative-adjust-approval', section: 'inventory', group: 'Behavior', label: 'Require approval for large write-offs', type: 'toggle', default: false },
  { id: 'inv-beh-write-off-threshold', section: 'inventory', group: 'Behavior', label: 'Write-off approval threshold', type: 'number', default: 500, min: 0, max: 100000, step: 50 },
  { id: 'inv-beh-undo-window', section: 'inventory', group: 'Behavior', label: 'Undo window after adjustment (sec)', type: 'number', default: 10, min: 0, max: 60, step: 5 },

  // ===== Notifications (131-150) =====
  { id: 'inv-notif-low-stock', section: 'inventory', group: 'Notifications', label: 'Alert on low stock', type: 'toggle', default: true },
  { id: 'inv-notif-out-of-stock', section: 'inventory', group: 'Notifications', label: 'Alert on out of stock', type: 'toggle', default: true },
  { id: 'inv-notif-reorder-point', section: 'inventory', group: 'Notifications', label: 'Alert at reorder point', type: 'toggle', default: true },
  { id: 'inv-notif-overstock', section: 'inventory', group: 'Notifications', label: 'Alert on overstock', type: 'toggle', default: false },
  { id: 'inv-notif-overstock-multiplier', section: 'inventory', group: 'Notifications', label: 'Overstock threshold (x reorder qty)', type: 'number', default: 3, min: 1, max: 20, step: 1 },
  { id: 'inv-notif-expiring', section: 'inventory', group: 'Notifications', label: 'Alert on expiring lots', type: 'toggle', default: false },
  { id: 'inv-notif-expiry-lead-days', section: 'inventory', group: 'Notifications', label: 'Expiry alert lead time (days)', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'inv-notif-negative-stock', section: 'inventory', group: 'Notifications', label: 'Alert on negative stock', type: 'toggle', default: true },
  { id: 'inv-notif-dead-stock', section: 'inventory', group: 'Notifications', label: 'Alert on dead/slow-moving stock', type: 'toggle', default: false },
  { id: 'inv-notif-dead-stock-days', section: 'inventory', group: 'Notifications', label: 'Dead stock no-sale threshold (days)', type: 'number', default: 90, min: 7, max: 730, step: 7 },
  { id: 'inv-notif-cost-change', section: 'inventory', group: 'Notifications', label: 'Alert on unit cost change', type: 'toggle', default: false },
  { id: 'inv-notif-cost-change-percent', section: 'inventory', group: 'Notifications', label: 'Cost change alert threshold (%)', type: 'number', default: 15, min: 1, max: 100, step: 1 },
  { id: 'inv-notif-po-received', section: 'inventory', group: 'Notifications', label: 'Notify on PO receipt', type: 'toggle', default: true },
  { id: 'inv-notif-channel', section: 'inventory', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'inapp', options: [{ value: 'inapp', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'inv-notif-email-recipient', section: 'inventory', group: 'Notifications', label: 'Alert email recipient', type: 'text', default: '' },
  { id: 'inv-notif-digest', section: 'inventory', group: 'Notifications', label: 'Send daily inventory digest', type: 'toggle', default: false },
  { id: 'inv-notif-digest-time', section: 'inventory', group: 'Notifications', label: 'Digest send hour (24h)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'inv-notif-badge-count', section: 'inventory', group: 'Notifications', label: 'Show alert count badge in sidebar', type: 'toggle', default: true },
  { id: 'inv-notif-sound', section: 'inventory', group: 'Notifications', label: 'Play sound on critical alert', type: 'toggle', default: false },
  { id: 'inv-notif-snooze-hours', section: 'inventory', group: 'Notifications', label: 'Default alert snooze (hours)', type: 'number', default: 24, min: 1, max: 168, step: 1 },

  // ===== Export (151-168) =====
  { id: 'inv-exp-default-format', section: 'inventory', group: 'Export', label: 'Default export format', type: 'select', default: 'xlsx', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'inv-exp-include-archived', section: 'inventory', group: 'Export', label: 'Include archived items in export', type: 'toggle', default: false },
  { id: 'inv-exp-include-zero-stock', section: 'inventory', group: 'Export', label: 'Include zero-stock items', type: 'toggle', default: true },
  { id: 'inv-exp-respect-filters', section: 'inventory', group: 'Export', label: 'Export only filtered rows', type: 'toggle', default: true },
  { id: 'inv-exp-visible-cols-only', section: 'inventory', group: 'Export', label: 'Export visible columns only', type: 'toggle', default: false },
  { id: 'inv-exp-include-images', section: 'inventory', group: 'Export', label: 'Embed images in export', type: 'toggle', default: false },
  { id: 'inv-exp-include-totals', section: 'inventory', group: 'Export', label: 'Add totals row to export', type: 'toggle', default: true },
  { id: 'inv-exp-csv-delimiter', section: 'inventory', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }, { value: 'pipe', label: 'Pipe' }] },
  { id: 'inv-exp-encoding', section: 'inventory', group: 'Export', label: 'File encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'inv-exp-filename-template', section: 'inventory', group: 'Export', label: 'Export filename template', type: 'text', default: 'inventory_{date}' },
  { id: 'inv-exp-date-stamp', section: 'inventory', group: 'Export', label: 'Append date stamp to filename', type: 'toggle', default: true },
  { id: 'inv-exp-pdf-orientation', section: 'inventory', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'inv-exp-pdf-logo', section: 'inventory', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'inv-exp-pdf-page-size', section: 'inventory', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'inv-exp-label-template', section: 'inventory', group: 'Export', label: 'Default label/barcode sheet template', type: 'select', default: 'avery5160', options: [{ value: 'avery5160', label: 'Avery 5160' }, { value: 'avery5163', label: 'Avery 5163' }, { value: 'dymo', label: 'Dymo' }, { value: 'thermal', label: 'Thermal 2x1' }] },
  { id: 'inv-exp-valuation-snapshot', section: 'inventory', group: 'Export', label: 'Export valuation snapshot with timestamp', type: 'toggle', default: true },
  { id: 'inv-exp-open-after', section: 'inventory', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'inv-exp-auto-monthly', section: 'inventory', group: 'Export', label: 'Auto-export valuation monthly', type: 'toggle', default: false },

  // ===== Colors & Theme (169-184) =====
  { id: 'inv-color-in-stock', section: 'inventory', group: 'Colors & Theme', label: 'In-stock status color', type: 'color', default: '#22c55e' },
  { id: 'inv-color-low-stock', section: 'inventory', group: 'Colors & Theme', label: 'Low-stock status color', type: 'color', default: '#f59e0b' },
  { id: 'inv-color-out-of-stock', section: 'inventory', group: 'Colors & Theme', label: 'Out-of-stock status color', type: 'color', default: '#ef4444' },
  { id: 'inv-color-overstock', section: 'inventory', group: 'Colors & Theme', label: 'Overstock status color', type: 'color', default: '#3b82f6' },
  { id: 'inv-color-negative', section: 'inventory', group: 'Colors & Theme', label: 'Negative stock highlight', type: 'color', default: '#dc2626' },
  { id: 'inv-color-expiring', section: 'inventory', group: 'Colors & Theme', label: 'Expiring-soon highlight', type: 'color', default: '#a855f7' },
  { id: 'inv-color-header-bg', section: 'inventory', group: 'Colors & Theme', label: 'Table header background', type: 'color', default: '#1e293b' },
  { id: 'inv-color-row-hover', section: 'inventory', group: 'Colors & Theme', label: 'Row hover highlight', type: 'color', default: '#334155' },
  { id: 'inv-color-margin-good', section: 'inventory', group: 'Colors & Theme', label: 'Healthy margin color', type: 'color', default: '#22c55e' },
  { id: 'inv-color-margin-bad', section: 'inventory', group: 'Colors & Theme', label: 'Low margin color', type: 'color', default: '#ef4444' },
  { id: 'inv-color-selected-row', section: 'inventory', group: 'Colors & Theme', label: 'Selected row color', type: 'color', default: '#2563eb' },
  { id: 'inv-color-status-style', section: 'inventory', group: 'Colors & Theme', label: 'Status indicator style', type: 'select', default: 'badge', options: [{ value: 'badge', label: 'Badge' }, { value: 'dot', label: 'Dot' }, { value: 'text', label: 'Colored text' }, { value: 'bar', label: 'Left bar' }] },
  { id: 'inv-color-use-category-colors', section: 'inventory', group: 'Colors & Theme', label: 'Color rows by category', type: 'toggle', default: false },
  { id: 'inv-color-heatmap-value', section: 'inventory', group: 'Colors & Theme', label: 'Heatmap shading on value column', type: 'toggle', default: false },
  { id: 'inv-color-margin-good-threshold', section: 'inventory', group: 'Colors & Theme', label: 'Healthy margin threshold (%)', type: 'number', default: 30, min: 0, max: 100, step: 1 },
  { id: 'inv-color-margin-bad-threshold', section: 'inventory', group: 'Colors & Theme', label: 'Low margin threshold (%)', type: 'number', default: 10, min: 0, max: 100, step: 1 },

  // ===== Accessibility (185-192) =====
  { id: 'inv-a11y-high-contrast', section: 'inventory', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'inv-a11y-font-scale', section: 'inventory', group: 'Accessibility', label: 'Table font scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'inv-a11y-status-icons', section: 'inventory', group: 'Accessibility', label: 'Show icons alongside status colors', type: 'toggle', default: true },
  { id: 'inv-a11y-colorblind-palette', section: 'inventory', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'select', default: 'off', options: [{ value: 'off', label: 'Off' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' }] },
  { id: 'inv-a11y-reduce-motion', section: 'inventory', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'inv-a11y-focus-outline', section: 'inventory', group: 'Accessibility', label: 'Always show keyboard focus outline', type: 'toggle', default: true },
  { id: 'inv-a11y-screenreader-summaries', section: 'inventory', group: 'Accessibility', label: 'Announce stock alerts to screen reader', type: 'toggle', default: true },
  { id: 'inv-a11y-tooltip-delay', section: 'inventory', group: 'Accessibility', label: 'Tooltip hover delay (ms)', type: 'number', default: 500, min: 0, max: 2000, step: 100 },

  // ===== Shortcuts (193-197) =====
  { id: 'inv-sc-new-item', section: 'inventory', group: 'Shortcuts', label: 'New item shortcut', type: 'text', default: 'n' },
  { id: 'inv-sc-adjust-stock', section: 'inventory', group: 'Shortcuts', label: 'Adjust stock shortcut', type: 'text', default: 'a' },
  { id: 'inv-sc-search-focus', section: 'inventory', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'inv-sc-export', section: 'inventory', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'mod+e' },
  { id: 'inv-sc-enable-shortcuts', section: 'inventory', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },

  // ===== Privacy (198-200) =====
  { id: 'inv-priv-mask-cost', section: 'inventory', group: 'Privacy', label: 'Mask unit cost from non-managers', type: 'toggle', default: false },
  { id: 'inv-priv-mask-margin', section: 'inventory', group: 'Privacy', label: 'Hide margin from standard users', type: 'toggle', default: false },
  { id: 'inv-priv-audit-log', section: 'inventory', group: 'Privacy', label: 'Log all stock changes to audit trail', type: 'toggle', default: true },
];
