// src/renderer/customization/sections/invoicing.ts
//
// Customization options for the Invoicing section. Auto-rendered by the
// generic Customization Center. Values are persisted keyed by
// `invoicing.${id}`.

import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ───────────────────────── Display ─────────────────────────
  { id: 'display-default-view', section: 'invoicing', group: 'Display', label: 'Default invoice view', description: 'Layout used when opening the Invoicing module.', type: 'select', default: 'list', options: [ { value: 'list', label: 'List' }, { value: 'grid', label: 'Card grid' }, { value: 'kanban', label: 'Status board' }, { value: 'calendar', label: 'Due-date calendar' } ] },
  { id: 'display-rows-per-page', section: 'invoicing', group: 'Display', label: 'Invoices per page', description: 'Number of invoices shown before pagination.', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'display-compact-rows', section: 'invoicing', group: 'Display', label: 'Compact row height', description: 'Reduce padding to fit more invoices on screen.', type: 'toggle', default: false },
  { id: 'display-zebra-striping', section: 'invoicing', group: 'Display', label: 'Zebra striping', description: 'Alternate row background shading in the invoice table.', type: 'toggle', default: true },
  { id: 'display-show-totals-bar', section: 'invoicing', group: 'Display', label: 'Show totals bar', description: 'Display a summary bar with outstanding and overdue totals.', type: 'toggle', default: true },
  { id: 'display-show-avatars', section: 'invoicing', group: 'Display', label: 'Show client avatars', description: 'Render client logo or initials beside each invoice.', type: 'toggle', default: true },
  { id: 'display-thumbnail-preview', section: 'invoicing', group: 'Display', label: 'Hover PDF preview', description: 'Show a PDF thumbnail when hovering an invoice row.', type: 'toggle', default: false },
  { id: 'display-status-as-pills', section: 'invoicing', group: 'Display', label: 'Status as pills', description: 'Render invoice status as colored pills instead of text.', type: 'toggle', default: true },
  { id: 'display-density', section: 'invoicing', group: 'Display', label: 'Table density', description: 'Overall spacing of the invoice table.', type: 'select', default: 'comfortable', options: [ { value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' } ] },
  { id: 'display-show-aging-buckets', section: 'invoicing', group: 'Display', label: 'Show aging buckets', description: 'Display 0-30 / 31-60 / 61-90 / 90+ aging summary.', type: 'toggle', default: true },
  { id: 'display-sticky-header', section: 'invoicing', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible while scrolling.', type: 'toggle', default: true },
  { id: 'display-overdue-highlight', section: 'invoicing', group: 'Display', label: 'Highlight overdue rows', description: 'Tint overdue invoice rows for quick scanning.', type: 'toggle', default: true },
  { id: 'display-show-quick-filters', section: 'invoicing', group: 'Display', label: 'Show quick filter chips', description: 'Display one-click status filter chips above the list.', type: 'toggle', default: true },

  // ───────────────────────── Columns ─────────────────────────
  { id: 'columns-show-invoice-number', section: 'invoicing', group: 'Columns', label: 'Invoice number column', type: 'toggle', default: true },
  { id: 'columns-show-client', section: 'invoicing', group: 'Columns', label: 'Client column', type: 'toggle', default: true },
  { id: 'columns-show-issue-date', section: 'invoicing', group: 'Columns', label: 'Issue date column', type: 'toggle', default: true },
  { id: 'columns-show-due-date', section: 'invoicing', group: 'Columns', label: 'Due date column', type: 'toggle', default: true },
  { id: 'columns-show-amount', section: 'invoicing', group: 'Columns', label: 'Amount column', type: 'toggle', default: true },
  { id: 'columns-show-balance-due', section: 'invoicing', group: 'Columns', label: 'Balance due column', type: 'toggle', default: true },
  { id: 'columns-show-status', section: 'invoicing', group: 'Columns', label: 'Status column', type: 'toggle', default: true },
  { id: 'columns-show-po-number', section: 'invoicing', group: 'Columns', label: 'PO number column', type: 'toggle', default: false },
  { id: 'columns-show-tax', section: 'invoicing', group: 'Columns', label: 'Tax column', type: 'toggle', default: false },
  { id: 'columns-show-currency', section: 'invoicing', group: 'Columns', label: 'Currency column', type: 'toggle', default: false },
  { id: 'columns-show-days-overdue', section: 'invoicing', group: 'Columns', label: 'Days overdue column', type: 'toggle', default: true },
  { id: 'columns-show-payment-method', section: 'invoicing', group: 'Columns', label: 'Payment method column', type: 'toggle', default: false },
  { id: 'columns-show-project', section: 'invoicing', group: 'Columns', label: 'Project column', type: 'toggle', default: false },
  { id: 'columns-show-tags', section: 'invoicing', group: 'Columns', label: 'Tags column', type: 'toggle', default: false },
  { id: 'columns-show-attachments', section: 'invoicing', group: 'Columns', label: 'Attachment icon column', type: 'toggle', default: false },
  { id: 'columns-frozen-count', section: 'invoicing', group: 'Columns', label: 'Frozen leading columns', description: 'Number of left columns to freeze during horizontal scroll.', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'columns-amount-alignment', section: 'invoicing', group: 'Columns', label: 'Amount column alignment', type: 'select', default: 'right', options: [ { value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' } ] },

  // ───────────────────────── Formatting ─────────────────────────
  { id: 'formatting-currency-symbol', section: 'invoicing', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'formatting-default-currency', section: 'invoicing', group: 'Formatting', label: 'Default currency', type: 'select', default: 'USD', options: [ { value: 'USD', label: 'US Dollar' }, { value: 'EUR', label: 'Euro' }, { value: 'GBP', label: 'British Pound' }, { value: 'CAD', label: 'Canadian Dollar' }, { value: 'AUD', label: 'Australian Dollar' } ] },
  { id: 'formatting-currency-position', section: 'invoicing', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [ { value: 'before', label: 'Before amount ($100)' }, { value: 'after', label: 'After amount (100$)' } ] },
  { id: 'formatting-decimal-places', section: 'invoicing', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'formatting-thousands-separator', section: 'invoicing', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [ { value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None (1000)' } ] },
  { id: 'formatting-decimal-separator', section: 'invoicing', group: 'Formatting', label: 'Decimal separator', type: 'select', default: 'period', options: [ { value: 'period', label: 'Period (1.50)' }, { value: 'comma', label: 'Comma (1,50)' } ] },
  { id: 'formatting-negative-style', section: 'invoicing', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [ { value: 'minus', label: 'Minus sign (-100)' }, { value: 'parens', label: 'Parentheses (100)' }, { value: 'red', label: 'Red text' } ] },
  { id: 'formatting-date-format', section: 'invoicing', group: 'Formatting', label: 'Date format', type: 'select', default: 'MM/DD/YYYY', options: [ { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' }, { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' }, { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' }, { value: 'MMM D, YYYY', label: 'Mon D, YYYY' } ] },
  { id: 'formatting-zero-as-dash', section: 'invoicing', group: 'Formatting', label: 'Show zero as dash', description: 'Render $0.00 values as a dash for readability.', type: 'toggle', default: false },
  { id: 'formatting-round-totals', section: 'invoicing', group: 'Formatting', label: 'Round invoice totals', description: 'Round the grand total to the nearest whole unit.', type: 'toggle', default: false },
  { id: 'formatting-amount-in-words', section: 'invoicing', group: 'Formatting', label: 'Show amount in words', description: 'Print the total spelled out under the figure.', type: 'toggle', default: false },
  { id: 'formatting-tax-display', section: 'invoicing', group: 'Formatting', label: 'Tax display style', type: 'select', default: 'exclusive', options: [ { value: 'exclusive', label: 'Tax added to subtotal' }, { value: 'inclusive', label: 'Tax included in price' }, { value: 'both', label: 'Show both' } ] },
  { id: 'formatting-uppercase-status', section: 'invoicing', group: 'Formatting', label: 'Uppercase status labels', type: 'toggle', default: false },
  { id: 'formatting-percent-decimals', section: 'invoicing', group: 'Formatting', label: 'Percentage decimal places', description: 'Decimals shown on tax and discount percentages.', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'formatting-quantity-decimals', section: 'invoicing', group: 'Formatting', label: 'Quantity decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },

  // ───────────────────────── Numbering ─────────────────────────
  { id: 'numbering-prefix', section: 'invoicing', group: 'Numbering', label: 'Invoice number prefix', type: 'text', default: 'INV-' },
  { id: 'numbering-suffix', section: 'invoicing', group: 'Numbering', label: 'Invoice number suffix', type: 'text', default: '' },
  { id: 'numbering-pad-length', section: 'invoicing', group: 'Numbering', label: 'Zero-pad length', description: 'Total digits the sequence is padded to (e.g. 0001).', type: 'number', default: 4, min: 1, max: 10, step: 1 },
  { id: 'numbering-next-number', section: 'invoicing', group: 'Numbering', label: 'Next invoice number', description: 'The next sequential number to assign.', type: 'number', default: 1001, min: 1, max: 9999999, step: 1 },
  { id: 'numbering-reset-period', section: 'invoicing', group: 'Numbering', label: 'Reset sequence', type: 'select', default: 'never', options: [ { value: 'never', label: 'Never' }, { value: 'yearly', label: 'Each year' }, { value: 'monthly', label: 'Each month' }, { value: 'quarterly', label: 'Each quarter' } ] },
  { id: 'numbering-include-year', section: 'invoicing', group: 'Numbering', label: 'Include year in number', description: 'Embed the year (e.g. INV-2026-0001).', type: 'toggle', default: false },
  { id: 'numbering-include-month', section: 'invoicing', group: 'Numbering', label: 'Include month in number', type: 'toggle', default: false },
  { id: 'numbering-per-client-sequence', section: 'invoicing', group: 'Numbering', label: 'Per-client sequences', description: 'Maintain a separate counter for each client.', type: 'toggle', default: false },
  { id: 'numbering-allow-manual-override', section: 'invoicing', group: 'Numbering', label: 'Allow manual override', description: 'Let users edit the auto-generated number.', type: 'toggle', default: true },
  { id: 'numbering-warn-duplicate', section: 'invoicing', group: 'Numbering', label: 'Warn on duplicate number', type: 'toggle', default: true },
  { id: 'numbering-credit-note-prefix', section: 'invoicing', group: 'Numbering', label: 'Credit note prefix', type: 'text', default: 'CN-' },
  { id: 'numbering-estimate-prefix', section: 'invoicing', group: 'Numbering', label: 'Estimate/quote prefix', type: 'text', default: 'EST-' },

  // ───────────────────────── Defaults ─────────────────────────
  { id: 'defaults-payment-terms', section: 'invoicing', group: 'Defaults', label: 'Default payment terms', type: 'select', default: 'net30', options: [ { value: 'due_on_receipt', label: 'Due on receipt' }, { value: 'net7', label: 'Net 7' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net60', label: 'Net 60' }, { value: 'net90', label: 'Net 90' } ] },
  { id: 'defaults-tax-rate', section: 'invoicing', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 50, step: 0.25 },
  { id: 'defaults-discount-rate', section: 'invoicing', group: 'Defaults', label: 'Default discount (%)', type: 'number', default: 0, min: 0, max: 100, step: 0.5 },
  { id: 'defaults-notes', section: 'invoicing', group: 'Defaults', label: 'Default invoice notes', description: 'Text pre-filled in the notes field of new invoices.', type: 'text', default: 'Thank you for your business!' },
  { id: 'defaults-footer-text', section: 'invoicing', group: 'Defaults', label: 'Default footer text', type: 'text', default: 'Payment is due within the stated terms.' },
  { id: 'defaults-terms-conditions', section: 'invoicing', group: 'Defaults', label: 'Default terms & conditions', type: 'text', default: 'Late payments are subject to a service charge.' },
  { id: 'defaults-due-days', section: 'invoicing', group: 'Defaults', label: 'Default due in (days)', description: 'Days added to issue date to compute the due date.', type: 'number', default: 30, min: 0, max: 365, step: 1 },
  { id: 'defaults-currency-per-client', section: 'invoicing', group: 'Defaults', label: 'Use client preferred currency', type: 'toggle', default: true },
  { id: 'defaults-line-item-tax', section: 'invoicing', group: 'Defaults', label: 'Tax applied per line item', description: 'Allow setting tax individually on each line.', type: 'toggle', default: false },
  { id: 'defaults-include-shipping', section: 'invoicing', group: 'Defaults', label: 'Include shipping field', type: 'toggle', default: false },
  { id: 'defaults-default-quantity', section: 'invoicing', group: 'Defaults', label: 'Default line quantity', type: 'number', default: 1, min: 0, max: 1000, step: 1 },
  { id: 'defaults-discount-type', section: 'invoicing', group: 'Defaults', label: 'Default discount type', type: 'select', default: 'percent', options: [ { value: 'percent', label: 'Percentage' }, { value: 'fixed', label: 'Fixed amount' } ] },
  { id: 'defaults-bank-details', section: 'invoicing', group: 'Defaults', label: 'Default bank/payment details', type: 'text', default: '' },
  { id: 'defaults-language', section: 'invoicing', group: 'Defaults', label: 'Default invoice language', type: 'select', default: 'en', options: [ { value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' } ] },
  { id: 'defaults-auto-fill-last-items', section: 'invoicing', group: 'Defaults', label: 'Pre-fill last used items', description: 'Suggest the client’s most recent line items.', type: 'toggle', default: false },
  { id: 'defaults-require-po', section: 'invoicing', group: 'Defaults', label: 'Require PO number', type: 'toggle', default: false },

  // ───────────────────────── Sorting & Filtering ─────────────────────────
  { id: 'sort-default-field', section: 'invoicing', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'issue_date', options: [ { value: 'invoice_number', label: 'Invoice number' }, { value: 'issue_date', label: 'Issue date' }, { value: 'due_date', label: 'Due date' }, { value: 'amount', label: 'Amount' }, { value: 'client', label: 'Client' }, { value: 'status', label: 'Status' } ] },
  { id: 'sort-default-direction', section: 'invoicing', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [ { value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' } ] },
  { id: 'filter-default-status', section: 'invoicing', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'all', options: [ { value: 'all', label: 'All' }, { value: 'draft', label: 'Draft' }, { value: 'sent', label: 'Sent' }, { value: 'unpaid', label: 'Unpaid' }, { value: 'overdue', label: 'Overdue' }, { value: 'paid', label: 'Paid' } ] },
  { id: 'filter-default-range', section: 'invoicing', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'this_year', options: [ { value: 'this_month', label: 'This month' }, { value: 'this_quarter', label: 'This quarter' }, { value: 'this_year', label: 'This year' }, { value: 'all_time', label: 'All time' } ] },
  { id: 'filter-hide-paid', section: 'invoicing', group: 'Sorting & Filtering', label: 'Hide paid by default', type: 'toggle', default: false },
  { id: 'filter-hide-drafts', section: 'invoicing', group: 'Sorting & Filtering', label: 'Hide drafts by default', type: 'toggle', default: false },
  { id: 'filter-remember-last', section: 'invoicing', group: 'Sorting & Filtering', label: 'Remember last filters', description: 'Restore filters used in the previous session.', type: 'toggle', default: true },
  { id: 'filter-search-includes-items', section: 'invoicing', group: 'Sorting & Filtering', label: 'Search line item text', description: 'Include line item descriptions in keyword search.', type: 'toggle', default: false },
  { id: 'filter-search-includes-notes', section: 'invoicing', group: 'Sorting & Filtering', label: 'Search notes', type: 'toggle', default: true },
  { id: 'sort-secondary-field', section: 'invoicing', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'invoice_number', options: [ { value: 'none', label: 'None' }, { value: 'invoice_number', label: 'Invoice number' }, { value: 'client', label: 'Client' }, { value: 'amount', label: 'Amount' } ] },
  { id: 'filter-min-amount', section: 'invoicing', group: 'Sorting & Filtering', label: 'Minimum amount filter', description: 'Default lower bound for the amount filter.', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'filter-overdue-grace-days', section: 'invoicing', group: 'Sorting & Filtering', label: 'Overdue grace period (days)', description: 'Days past due before an invoice counts as overdue.', type: 'number', default: 0, min: 0, max: 30, step: 1 },

  // ───────────────────────── Behavior ─────────────────────────
  { id: 'behavior-auto-save-draft', section: 'invoicing', group: 'Behavior', label: 'Auto-save drafts', description: 'Periodically save invoices while editing.', type: 'toggle', default: true },
  { id: 'behavior-autosave-interval', section: 'invoicing', group: 'Behavior', label: 'Auto-save interval (sec)', type: 'number', default: 30, min: 10, max: 300, step: 5 },
  { id: 'behavior-confirm-before-send', section: 'invoicing', group: 'Behavior', label: 'Confirm before sending', type: 'toggle', default: true },
  { id: 'behavior-confirm-before-delete', section: 'invoicing', group: 'Behavior', label: 'Confirm before deleting', type: 'toggle', default: true },
  { id: 'behavior-lock-sent-invoices', section: 'invoicing', group: 'Behavior', label: 'Lock invoices after sending', description: 'Prevent edits once an invoice has been issued.', type: 'toggle', default: false },
  { id: 'behavior-auto-mark-sent', section: 'invoicing', group: 'Behavior', label: 'Auto-mark as sent on email', type: 'toggle', default: true },
  { id: 'behavior-duplicate-keeps-dates', section: 'invoicing', group: 'Behavior', label: 'Duplicate keeps original dates', description: 'Carry over dates when duplicating an invoice.', type: 'toggle', default: false },
  { id: 'behavior-auto-apply-credits', section: 'invoicing', group: 'Behavior', label: 'Auto-apply client credits', type: 'toggle', default: true },
  { id: 'behavior-partial-payments', section: 'invoicing', group: 'Behavior', label: 'Allow partial payments', type: 'toggle', default: true },
  { id: 'behavior-tab-adds-line', section: 'invoicing', group: 'Behavior', label: 'Tab adds new line item', description: 'Pressing Tab on the last field inserts a new line.', type: 'toggle', default: true },
  { id: 'behavior-late-fee-enabled', section: 'invoicing', group: 'Behavior', label: 'Apply late fees automatically', type: 'toggle', default: false },
  { id: 'behavior-late-fee-rate', section: 'invoicing', group: 'Behavior', label: 'Late fee rate (%)', type: 'number', default: 1.5, min: 0, max: 25, step: 0.25 },
  { id: 'behavior-recurring-auto-issue', section: 'invoicing', group: 'Behavior', label: 'Auto-issue recurring invoices', type: 'toggle', default: false },
  { id: 'behavior-default-action-on-save', section: 'invoicing', group: 'Behavior', label: 'After saving an invoice', type: 'select', default: 'stay', options: [ { value: 'stay', label: 'Stay on invoice' }, { value: 'list', label: 'Return to list' }, { value: 'new', label: 'Start new invoice' }, { value: 'send', label: 'Open send dialog' } ] },
  { id: 'behavior-warn-unsaved', section: 'invoicing', group: 'Behavior', label: 'Warn about unsaved changes', type: 'toggle', default: true },
  { id: 'behavior-round-line-totals', section: 'invoicing', group: 'Behavior', label: 'Round each line total', type: 'toggle', default: false },
  { id: 'behavior-deposit-request', section: 'invoicing', group: 'Behavior', label: 'Allow deposit requests', description: 'Enable requesting an upfront deposit percentage.', type: 'toggle', default: false },

  // ───────────────────────── Notifications ─────────────────────────
  { id: 'notify-send-reminders', section: 'invoicing', group: 'Notifications', label: 'Send payment reminders', type: 'toggle', default: true },
  { id: 'notify-reminder-before-days', section: 'invoicing', group: 'Notifications', label: 'Reminder before due (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'notify-reminder-after-days', section: 'invoicing', group: 'Notifications', label: 'Reminder after due (days)', type: 'number', default: 7, min: 0, max: 90, step: 1 },
  { id: 'notify-reminder-cadence', section: 'invoicing', group: 'Notifications', label: 'Overdue reminder cadence', type: 'select', default: 'weekly', options: [ { value: 'daily', label: 'Daily' }, { value: 'every_3_days', label: 'Every 3 days' }, { value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Every 2 weeks' } ] },
  { id: 'notify-max-reminders', section: 'invoicing', group: 'Notifications', label: 'Max reminders per invoice', type: 'number', default: 3, min: 0, max: 20, step: 1 },
  { id: 'notify-on-payment-received', section: 'invoicing', group: 'Notifications', label: 'Notify me on payment', type: 'toggle', default: true },
  { id: 'notify-on-invoice-viewed', section: 'invoicing', group: 'Notifications', label: 'Notify when client views', type: 'toggle', default: false },
  { id: 'notify-thank-you-on-paid', section: 'invoicing', group: 'Notifications', label: 'Send thank-you on payment', type: 'toggle', default: true },
  { id: 'notify-cc-self', section: 'invoicing', group: 'Notifications', label: 'CC myself on sent invoices', type: 'toggle', default: false },
  { id: 'notify-bcc-address', section: 'invoicing', group: 'Notifications', label: 'BCC address', description: 'Hidden recipient copied on every invoice email.', type: 'text', default: '' },
  { id: 'notify-reply-to', section: 'invoicing', group: 'Notifications', label: 'Reply-to address', type: 'text', default: '' },
  { id: 'notify-channel', section: 'invoicing', group: 'Notifications', label: 'Reminder channel', type: 'select', default: 'email', options: [ { value: 'email', label: 'Email' }, { value: 'sms', label: 'SMS' }, { value: 'both', label: 'Email + SMS' } ] },
  { id: 'notify-daily-digest', section: 'invoicing', group: 'Notifications', label: 'Daily overdue digest', description: 'Receive one summary of overdue invoices each day.', type: 'toggle', default: false },
  { id: 'notify-send-time', section: 'invoicing', group: 'Notifications', label: 'Preferred send time', type: 'select', default: 'morning', options: [ { value: 'morning', label: 'Morning (9am)' }, { value: 'noon', label: 'Midday (12pm)' }, { value: 'afternoon', label: 'Afternoon (3pm)' } ] },
  { id: 'notify-skip-weekends', section: 'invoicing', group: 'Notifications', label: 'Skip weekend sends', type: 'toggle', default: true },

  // ───────────────────────── Email ─────────────────────────
  { id: 'email-default-subject', section: 'invoicing', group: 'Email', label: 'Default email subject', type: 'text', default: 'Invoice {number} from {company}' },
  { id: 'email-default-body', section: 'invoicing', group: 'Email', label: 'Default email body', type: 'text', default: 'Please find your invoice attached. Thank you!' },
  { id: 'email-attach-pdf', section: 'invoicing', group: 'Email', label: 'Attach PDF copy', type: 'toggle', default: true },
  { id: 'email-include-pay-link', section: 'invoicing', group: 'Email', label: 'Include online payment link', type: 'toggle', default: true },
  { id: 'email-include-view-link', section: 'invoicing', group: 'Email', label: 'Include view-online link', type: 'toggle', default: true },
  { id: 'email-signature', section: 'invoicing', group: 'Email', label: 'Email signature', type: 'text', default: '' },
  { id: 'email-from-name', section: 'invoicing', group: 'Email', label: 'From display name', type: 'text', default: '' },
  { id: 'email-tracking', section: 'invoicing', group: 'Email', label: 'Track email opens', type: 'toggle', default: true },
  { id: 'email-retry-failed', section: 'invoicing', group: 'Email', label: 'Retry failed sends', type: 'toggle', default: true },

  // ───────────────────────── Export ─────────────────────────
  { id: 'export-default-format', section: 'invoicing', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [ { value: 'pdf', label: 'PDF' }, { value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'json', label: 'JSON' } ] },
  { id: 'export-pdf-page-size', section: 'invoicing', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [ { value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' } ] },
  { id: 'export-pdf-orientation', section: 'invoicing', group: 'Export', label: 'PDF orientation', type: 'select', default: 'portrait', options: [ { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' } ] },
  { id: 'export-include-logo', section: 'invoicing', group: 'Export', label: 'Include company logo', type: 'toggle', default: true },
  { id: 'export-include-payment-history', section: 'invoicing', group: 'Export', label: 'Include payment history', type: 'toggle', default: true },
  { id: 'export-csv-delimiter', section: 'invoicing', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [ { value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' } ] },
  { id: 'export-filename-pattern', section: 'invoicing', group: 'Export', label: 'Export filename pattern', description: 'Tokens: {number} {client} {date}.', type: 'text', default: 'Invoice-{number}' },
  { id: 'export-batch-as-zip', section: 'invoicing', group: 'Export', label: 'Bundle batch exports as ZIP', type: 'toggle', default: true },
  { id: 'export-include-header-row', section: 'invoicing', group: 'Export', label: 'Include CSV header row', type: 'toggle', default: true },
  { id: 'export-quickbooks-compatible', section: 'invoicing', group: 'Export', label: 'QuickBooks-compatible columns', type: 'toggle', default: false },

  // ───────────────────────── Template & Branding ─────────────────────────
  { id: 'template-style', section: 'invoicing', group: 'Template & Branding', label: 'Invoice template style', type: 'select', default: 'modern', options: [ { value: 'classic', label: 'Classic' }, { value: 'modern', label: 'Modern' }, { value: 'minimal', label: 'Minimal' }, { value: 'bold', label: 'Bold' } ] },
  { id: 'template-show-logo', section: 'invoicing', group: 'Template & Branding', label: 'Show logo on invoice', type: 'toggle', default: true },
  { id: 'template-logo-position', section: 'invoicing', group: 'Template & Branding', label: 'Logo position', type: 'select', default: 'left', options: [ { value: 'left', label: 'Top left' }, { value: 'center', label: 'Top center' }, { value: 'right', label: 'Top right' } ] },
  { id: 'template-show-company-address', section: 'invoicing', group: 'Template & Branding', label: 'Show company address', type: 'toggle', default: true },
  { id: 'template-show-client-address', section: 'invoicing', group: 'Template & Branding', label: 'Show client address', type: 'toggle', default: true },
  { id: 'template-show-tax-id', section: 'invoicing', group: 'Template & Branding', label: 'Show tax/VAT ID', type: 'toggle', default: true },
  { id: 'template-show-due-banner', section: 'invoicing', group: 'Template & Branding', label: 'Show amount-due banner', type: 'toggle', default: true },
  { id: 'template-font', section: 'invoicing', group: 'Template & Branding', label: 'Template font', type: 'select', default: 'sans', options: [ { value: 'sans', label: 'Sans-serif' }, { value: 'serif', label: 'Serif' }, { value: 'mono', label: 'Monospace' } ] },
  { id: 'template-show-signature-line', section: 'invoicing', group: 'Template & Branding', label: 'Show signature line', type: 'toggle', default: false },
  { id: 'template-show-qr-pay', section: 'invoicing', group: 'Template & Branding', label: 'Show QR payment code', type: 'toggle', default: false },
  { id: 'template-watermark-text', section: 'invoicing', group: 'Template & Branding', label: 'Draft watermark text', type: 'text', default: 'DRAFT' },
  { id: 'template-show-page-numbers', section: 'invoicing', group: 'Template & Branding', label: 'Show page numbers', type: 'toggle', default: true },

  // ───────────────────────── Colors & Theme ─────────────────────────
  { id: 'color-accent', section: 'invoicing', group: 'Colors & Theme', label: 'Accent color', type: 'color', default: '#3b82f6' },
  { id: 'color-header-bg', section: 'invoicing', group: 'Colors & Theme', label: 'Invoice header background', type: 'color', default: '#1e293b' },
  { id: 'color-header-text', section: 'invoicing', group: 'Colors & Theme', label: 'Invoice header text', type: 'color', default: '#ffffff' },
  { id: 'color-table-header', section: 'invoicing', group: 'Colors & Theme', label: 'Line-item header color', type: 'color', default: '#f1f5f9' },
  { id: 'color-status-paid', section: 'invoicing', group: 'Colors & Theme', label: 'Paid status color', type: 'color', default: '#22c55e' },
  { id: 'color-status-overdue', section: 'invoicing', group: 'Colors & Theme', label: 'Overdue status color', type: 'color', default: '#ef4444' },
  { id: 'color-status-draft', section: 'invoicing', group: 'Colors & Theme', label: 'Draft status color', type: 'color', default: '#94a3b8' },
  { id: 'color-status-sent', section: 'invoicing', group: 'Colors & Theme', label: 'Sent status color', type: 'color', default: '#3b82f6' },
  { id: 'color-status-partial', section: 'invoicing', group: 'Colors & Theme', label: 'Partial payment color', type: 'color', default: '#f59e0b' },
  { id: 'color-total-highlight', section: 'invoicing', group: 'Colors & Theme', label: 'Total amount highlight', type: 'color', default: '#0ea5e9' },
  { id: 'color-link', section: 'invoicing', group: 'Colors & Theme', label: 'Payment link color', type: 'color', default: '#2563eb' },
  { id: 'color-watermark', section: 'invoicing', group: 'Colors & Theme', label: 'Watermark color', type: 'color', default: '#e2e8f0' },
  { id: 'color-overdue-row-tint', section: 'invoicing', group: 'Colors & Theme', label: 'Overdue row tint', type: 'color', default: '#fee2e2' },

  // ───────────────────────── Accessibility ─────────────────────────
  { id: 'a11y-high-contrast', section: 'invoicing', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'a11y-font-scale', section: 'invoicing', group: 'Accessibility', label: 'Font size scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'a11y-status-icons', section: 'invoicing', group: 'Accessibility', label: 'Status icons + color', description: 'Pair colors with icons for color-blind users.', type: 'toggle', default: true },
  { id: 'a11y-reduce-motion', section: 'invoicing', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'a11y-focus-outline', section: 'invoicing', group: 'Accessibility', label: 'Visible focus outlines', type: 'toggle', default: true },
  { id: 'a11y-screenreader-labels', section: 'invoicing', group: 'Accessibility', label: 'Verbose screen-reader labels', type: 'toggle', default: false },
  { id: 'a11y-underline-links', section: 'invoicing', group: 'Accessibility', label: 'Always underline links', type: 'toggle', default: false },
  { id: 'a11y-min-touch-target', section: 'invoicing', group: 'Accessibility', label: 'Min touch target (px)', type: 'number', default: 44, min: 24, max: 64, step: 2 },
  { id: 'a11y-keyboard-hints', section: 'invoicing', group: 'Accessibility', label: 'Show keyboard hints', type: 'toggle', default: false },
  { id: 'a11y-colorblind-palette', section: 'invoicing', group: 'Accessibility', label: 'Color-blind safe palette', type: 'select', default: 'default', options: [ { value: 'default', label: 'Default' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' } ] },

  // ───────────────────────── Shortcuts ─────────────────────────
  { id: 'shortcut-new-invoice', section: 'invoicing', group: 'Shortcuts', label: 'New invoice shortcut', type: 'text', default: 'Ctrl+N' },
  { id: 'shortcut-save', section: 'invoicing', group: 'Shortcuts', label: 'Save shortcut', type: 'text', default: 'Ctrl+S' },
  { id: 'shortcut-send', section: 'invoicing', group: 'Shortcuts', label: 'Send shortcut', type: 'text', default: 'Ctrl+Enter' },
  { id: 'shortcut-add-line', section: 'invoicing', group: 'Shortcuts', label: 'Add line item shortcut', type: 'text', default: 'Ctrl+L' },
  { id: 'shortcut-duplicate', section: 'invoicing', group: 'Shortcuts', label: 'Duplicate invoice shortcut', type: 'text', default: 'Ctrl+D' },
  { id: 'shortcut-record-payment', section: 'invoicing', group: 'Shortcuts', label: 'Record payment shortcut', type: 'text', default: 'Ctrl+P' },
  { id: 'shortcut-search', section: 'invoicing', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: 'Ctrl+F' },
  { id: 'shortcut-print', section: 'invoicing', group: 'Shortcuts', label: 'Print shortcut', type: 'text', default: 'Ctrl+Shift+P' },
  { id: 'shortcut-enabled', section: 'invoicing', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'shortcut-show-cheatsheet', section: 'invoicing', group: 'Shortcuts', label: 'Show shortcut cheatsheet', description: 'Display the “?” shortcut overlay.', type: 'toggle', default: true },

  // ───────────────────────── Privacy & Security ─────────────────────────
  { id: 'privacy-mask-amounts', section: 'invoicing', group: 'Privacy & Security', label: 'Mask amounts by default', description: 'Hide monetary figures until revealed.', type: 'toggle', default: false },
  { id: 'privacy-hide-client-contact', section: 'invoicing', group: 'Privacy & Security', label: 'Hide client contact info', type: 'toggle', default: false },
  { id: 'privacy-require-pin-delete', section: 'invoicing', group: 'Privacy & Security', label: 'Require PIN to delete', type: 'toggle', default: false },
  { id: 'privacy-audit-log', section: 'invoicing', group: 'Privacy & Security', label: 'Keep edit audit log', type: 'toggle', default: true },
  { id: 'privacy-redact-on-export', section: 'invoicing', group: 'Privacy & Security', label: 'Redact bank details on export', type: 'toggle', default: false },
  { id: 'privacy-watermark-shared', section: 'invoicing', group: 'Privacy & Security', label: 'Watermark shared copies', description: 'Stamp recipient identity on shared PDFs.', type: 'toggle', default: false },
  { id: 'privacy-link-expiry-days', section: 'invoicing', group: 'Privacy & Security', label: 'Payment link expiry (days)', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'privacy-require-2fa-refund', section: 'invoicing', group: 'Privacy & Security', label: 'Require 2FA for refunds', type: 'toggle', default: false },
  { id: 'privacy-auto-lock-minutes', section: 'invoicing', group: 'Privacy & Security', label: 'Auto-lock after idle (min)', type: 'number', default: 15, min: 1, max: 120, step: 1 },
  { id: 'privacy-anonymize-demo', section: 'invoicing', group: 'Privacy & Security', label: 'Anonymize in demo mode', type: 'toggle', default: true },
  { id: 'privacy-restrict-export-role', section: 'invoicing', group: 'Privacy & Security', label: 'Restrict export to admins', type: 'toggle', default: false },

  // ───────────────────────── Payments ─────────────────────────
  { id: 'payments-accept-card', section: 'invoicing', group: 'Payments', label: 'Accept card payments', type: 'toggle', default: true },
  { id: 'payments-accept-ach', section: 'invoicing', group: 'Payments', label: 'Accept ACH/bank transfer', type: 'toggle', default: true },
  { id: 'payments-accept-paypal', section: 'invoicing', group: 'Payments', label: 'Accept PayPal', type: 'toggle', default: false },
  { id: 'payments-surcharge-card', section: 'invoicing', group: 'Payments', label: 'Pass card surcharge to client', type: 'toggle', default: false },
  { id: 'payments-surcharge-rate', section: 'invoicing', group: 'Payments', label: 'Card surcharge rate (%)', type: 'number', default: 2.9, min: 0, max: 10, step: 0.1 },
  { id: 'payments-min-partial', section: 'invoicing', group: 'Payments', label: 'Minimum partial payment (%)', type: 'number', default: 10, min: 0, max: 100, step: 5 },
  { id: 'payments-auto-receipt', section: 'invoicing', group: 'Payments', label: 'Auto-send payment receipt', type: 'toggle', default: true },
  { id: 'payments-default-method', section: 'invoicing', group: 'Payments', label: 'Default recorded method', type: 'select', default: 'card', options: [ { value: 'card', label: 'Card' }, { value: 'ach', label: 'Bank transfer' }, { value: 'cash', label: 'Cash' }, { value: 'check', label: 'Check' }, { value: 'other', label: 'Other' } ] },
];
