import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-20) =====
  { id: 'loans-display-default-view', section: 'loans', group: 'Display', label: 'Default loan view', description: 'View shown when opening the Loans module.', type: 'select', default: 'list', options: [{ value: 'list', label: 'List' }, { value: 'cards', label: 'Cards' }, { value: 'kanban', label: 'Status board' }, { value: 'timeline', label: 'Timeline' }] },
  { id: 'loans-display-rows-per-page', section: 'loans', group: 'Display', label: 'Rows per page', description: 'Number of loans shown per page.', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'loans-display-compact-rows', section: 'loans', group: 'Display', label: 'Compact row density', description: 'Use tighter row spacing in the loan list.', type: 'toggle', default: false },
  { id: 'loans-display-show-progress-bars', section: 'loans', group: 'Display', label: 'Show payoff progress bars', description: 'Render a progress bar for principal paid.', type: 'toggle', default: true },
  { id: 'loans-display-show-lender-logos', section: 'loans', group: 'Display', label: 'Show lender logos', description: 'Display lender/bank logos next to loan names.', type: 'toggle', default: true },
  { id: 'loans-display-show-avatars', section: 'loans', group: 'Display', label: 'Show borrower avatars', description: 'Show avatar for the borrowing entity.', type: 'toggle', default: false },
  { id: 'loans-display-zebra-stripes', section: 'loans', group: 'Display', label: 'Zebra-striped rows', description: 'Alternate row background shading.', type: 'toggle', default: true },
  { id: 'loans-display-sticky-header', section: 'loans', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible while scrolling.', type: 'toggle', default: true },
  { id: 'loans-display-pinned-summary', section: 'loans', group: 'Display', label: 'Pin summary bar', description: 'Keep the totals summary bar pinned to the top.', type: 'toggle', default: true },
  { id: 'loans-display-card-size', section: 'loans', group: 'Display', label: 'Card size', description: 'Size of loan cards in card view.', type: 'select', default: 'medium', options: [{ value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large' }] },
  { id: 'loans-display-show-loan-id', section: 'loans', group: 'Display', label: 'Show internal loan ID', description: 'Display the internal numeric loan ID.', type: 'toggle', default: false },
  { id: 'loans-display-show-account-number', section: 'loans', group: 'Display', label: 'Show loan account number', description: 'Display the lender account number.', type: 'toggle', default: true },
  { id: 'loans-display-empty-state-message', section: 'loans', group: 'Display', label: 'Empty state message', description: 'Message shown when no loans exist.', type: 'text', default: 'No loans recorded yet.' },
  { id: 'loans-display-show-row-numbers', section: 'loans', group: 'Display', label: 'Show row numbers', description: 'Display a leading row number column.', type: 'toggle', default: false },
  { id: 'loans-display-collapse-paid-off', section: 'loans', group: 'Display', label: 'Collapse paid-off loans', description: 'Group fully-paid loans into a collapsed section.', type: 'toggle', default: true },
  { id: 'loans-display-show-mini-amort', section: 'loans', group: 'Display', label: 'Inline mini amortization sparkline', description: 'Show a sparkline of the balance curve per row.', type: 'toggle', default: false },
  { id: 'loans-display-highlight-due-soon', section: 'loans', group: 'Display', label: 'Highlight payments due soon', description: 'Emphasize loans with payments due within a window.', type: 'toggle', default: true },
  { id: 'loans-display-due-soon-days', section: 'loans', group: 'Display', label: 'Due-soon window (days)', description: 'Days ahead counted as "due soon".', type: 'number', default: 7, min: 1, max: 60, step: 1 },
  { id: 'loans-display-show-loan-type-badge', section: 'loans', group: 'Display', label: 'Show loan type badge', description: 'Show a badge for term/revolving/balloon types.', type: 'toggle', default: true },
  { id: 'loans-display-thousands-grouping', section: 'loans', group: 'Display', label: 'Group thousands in balances', description: 'Use thousands separators in balance figures.', type: 'toggle', default: true },

  // ===== Columns (21-44) =====
  { id: 'loans-columns-lender', section: 'loans', group: 'Columns', label: 'Show lender column', type: 'toggle', default: true },
  { id: 'loans-columns-original-amount', section: 'loans', group: 'Columns', label: 'Show original amount column', type: 'toggle', default: true },
  { id: 'loans-columns-current-balance', section: 'loans', group: 'Columns', label: 'Show current balance column', type: 'toggle', default: true },
  { id: 'loans-columns-interest-rate', section: 'loans', group: 'Columns', label: 'Show interest rate column', type: 'toggle', default: true },
  { id: 'loans-columns-apr', section: 'loans', group: 'Columns', label: 'Show APR column', type: 'toggle', default: false },
  { id: 'loans-columns-monthly-payment', section: 'loans', group: 'Columns', label: 'Show monthly payment column', type: 'toggle', default: true },
  { id: 'loans-columns-next-due-date', section: 'loans', group: 'Columns', label: 'Show next due date column', type: 'toggle', default: true },
  { id: 'loans-columns-maturity-date', section: 'loans', group: 'Columns', label: 'Show maturity date column', type: 'toggle', default: true },
  { id: 'loans-columns-origination-date', section: 'loans', group: 'Columns', label: 'Show origination date column', type: 'toggle', default: false },
  { id: 'loans-columns-term-months', section: 'loans', group: 'Columns', label: 'Show term (months) column', type: 'toggle', default: true },
  { id: 'loans-columns-remaining-term', section: 'loans', group: 'Columns', label: 'Show remaining term column', type: 'toggle', default: true },
  { id: 'loans-columns-principal-paid', section: 'loans', group: 'Columns', label: 'Show principal paid column', type: 'toggle', default: false },
  { id: 'loans-columns-interest-paid', section: 'loans', group: 'Columns', label: 'Show interest paid-to-date column', type: 'toggle', default: false },
  { id: 'loans-columns-loan-type', section: 'loans', group: 'Columns', label: 'Show loan type column', type: 'toggle', default: true },
  { id: 'loans-columns-collateral', section: 'loans', group: 'Columns', label: 'Show collateral column', type: 'toggle', default: false },
  { id: 'loans-columns-status', section: 'loans', group: 'Columns', label: 'Show status column', type: 'toggle', default: true },
  { id: 'loans-columns-escrow-balance', section: 'loans', group: 'Columns', label: 'Show escrow balance column', type: 'toggle', default: false },
  { id: 'loans-columns-payoff-amount', section: 'loans', group: 'Columns', label: 'Show payoff amount column', type: 'toggle', default: false },
  { id: 'loans-columns-account-number', section: 'loans', group: 'Columns', label: 'Show account number column', type: 'toggle', default: false },
  { id: 'loans-columns-rate-type', section: 'loans', group: 'Columns', label: 'Show rate type (fixed/variable) column', type: 'toggle', default: true },
  { id: 'loans-columns-guarantor', section: 'loans', group: 'Columns', label: 'Show guarantor column', type: 'toggle', default: false },
  { id: 'loans-columns-notes', section: 'loans', group: 'Columns', label: 'Show notes column', type: 'toggle', default: false },
  { id: 'loans-columns-order', section: 'loans', group: 'Columns', label: 'Column order preset', description: 'Predefined column ordering.', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'finance-first', label: 'Finance-first' }, { value: 'dates-first', label: 'Dates-first' }, { value: 'custom', label: 'Custom' }] },
  { id: 'loans-columns-freeze-first', section: 'loans', group: 'Columns', label: 'Freeze first column', description: 'Keep the loan name column frozen while scrolling.', type: 'toggle', default: true },

  // ===== Formatting (45-66) =====
  { id: 'loans-format-currency-symbol', section: 'loans', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'loans-format-currency-position', section: 'loans', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'loans-format-decimal-places', section: 'loans', group: 'Formatting', label: 'Balance decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'loans-format-rate-decimal-places', section: 'loans', group: 'Formatting', label: 'Interest rate decimal places', type: 'number', default: 3, min: 1, max: 5, step: 1 },
  { id: 'loans-format-negative-style', section: 'loans', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'parentheses', options: [{ value: 'minus', label: 'Minus sign' }, { value: 'parentheses', label: 'Parentheses' }, { value: 'red', label: 'Red text' }] },
  { id: 'loans-format-date-format', section: 'loans', group: 'Formatting', label: 'Date format', type: 'select', default: 'mm-dd-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Month D, YYYY' }] },
  { id: 'loans-format-rate-as-percent', section: 'loans', group: 'Formatting', label: 'Append % to rates', type: 'toggle', default: true },
  { id: 'loans-format-round-balances', section: 'loans', group: 'Formatting', label: 'Round balances to whole units', type: 'toggle', default: false },
  { id: 'loans-format-term-display', section: 'loans', group: 'Formatting', label: 'Term display unit', type: 'select', default: 'months', options: [{ value: 'months', label: 'Months' }, { value: 'years', label: 'Years' }, { value: 'years-months', label: 'Years & months' }] },
  { id: 'loans-format-thousands-separator', section: 'loans', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'period', label: 'Period' }, { value: 'space', label: 'Space' }, { value: 'none', label: 'None' }] },
  { id: 'loans-format-decimal-separator', section: 'loans', group: 'Formatting', label: 'Decimal separator', type: 'select', default: 'period', options: [{ value: 'period', label: 'Period' }, { value: 'comma', label: 'Comma' }] },
  { id: 'loans-format-abbreviate-large', section: 'loans', group: 'Formatting', label: 'Abbreviate large balances (K/M)', type: 'toggle', default: false },
  { id: 'loans-format-show-cents-zero', section: 'loans', group: 'Formatting', label: 'Show .00 cents', type: 'toggle', default: true },
  { id: 'loans-format-payment-frequency-label', section: 'loans', group: 'Formatting', label: 'Payment frequency label style', type: 'select', default: 'word', options: [{ value: 'word', label: 'Monthly/Weekly' }, { value: 'abbrev', label: 'Mo/Wk' }, { value: 'per', label: 'per month' }] },
  { id: 'loans-format-relative-due-dates', section: 'loans', group: 'Formatting', label: 'Show relative due dates', description: 'e.g. "in 3 days" instead of an absolute date.', type: 'toggle', default: false },
  { id: 'loans-format-default-currency', section: 'loans', group: 'Formatting', label: 'Default loan currency', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' }] },
  { id: 'loans-format-rate-basis', section: 'loans', group: 'Formatting', label: 'Rate basis label', type: 'select', default: 'annual', options: [{ value: 'annual', label: 'Annual (APR)' }, { value: 'monthly', label: 'Monthly' }, { value: 'effective', label: 'Effective annual' }] },
  { id: 'loans-format-uppercase-status', section: 'loans', group: 'Formatting', label: 'Uppercase status labels', type: 'toggle', default: false },
  { id: 'loans-format-show-trailing-rate-zeros', section: 'loans', group: 'Formatting', label: 'Show trailing zeros on rates', type: 'toggle', default: true },
  { id: 'loans-format-amount-alignment', section: 'loans', group: 'Formatting', label: 'Numeric column alignment', type: 'select', default: 'right', options: [{ value: 'right', label: 'Right' }, { value: 'left', label: 'Left' }, { value: 'decimal', label: 'Decimal-aligned' }] },
  { id: 'loans-format-percent-of-loan', section: 'loans', group: 'Formatting', label: 'Show balance as % of original', type: 'toggle', default: false },
  { id: 'loans-format-fiscal-year-start', section: 'loans', group: 'Formatting', label: 'Fiscal year start month', type: 'number', default: 1, min: 1, max: 12, step: 1 },

  // ===== Defaults (67-90) =====
  { id: 'loans-default-interest-method', section: 'loans', group: 'Defaults', label: 'Default interest calculation method', type: 'select', default: 'amortized', options: [{ value: 'amortized', label: 'Amortized' }, { value: 'simple', label: 'Simple interest' }, { value: 'compound', label: 'Compound' }, { value: 'interest-only', label: 'Interest-only' }] },
  { id: 'loans-default-compounding', section: 'loans', group: 'Defaults', label: 'Default compounding frequency', type: 'select', default: 'monthly', options: [{ value: 'daily', label: 'Daily' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annually', label: 'Annually' }] },
  { id: 'loans-default-payment-frequency', section: 'loans', group: 'Defaults', label: 'Default payment frequency', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'loans-default-rate-type', section: 'loans', group: 'Defaults', label: 'Default rate type', type: 'select', default: 'fixed', options: [{ value: 'fixed', label: 'Fixed' }, { value: 'variable', label: 'Variable' }] },
  { id: 'loans-default-term-months', section: 'loans', group: 'Defaults', label: 'Default term (months)', type: 'number', default: 60, min: 1, max: 600, step: 1 },
  { id: 'loans-default-interest-rate', section: 'loans', group: 'Defaults', label: 'Default interest rate (%)', type: 'number', default: 7.5, min: 0, max: 50, step: 0.125 },
  { id: 'loans-default-day-count', section: 'loans', group: 'Defaults', label: 'Default day-count convention', type: 'select', default: '30-360', options: [{ value: '30-360', label: '30/360' }, { value: 'actual-360', label: 'Actual/360' }, { value: 'actual-365', label: 'Actual/365' }, { value: 'actual-actual', label: 'Actual/Actual' }] },
  { id: 'loans-default-loan-type', section: 'loans', group: 'Defaults', label: 'Default loan type for new loans', type: 'select', default: 'term', options: [{ value: 'term', label: 'Term loan' }, { value: 'revolving', label: 'Revolving / line of credit' }, { value: 'balloon', label: 'Balloon' }, { value: 'mortgage', label: 'Mortgage' }] },
  { id: 'loans-default-first-payment-offset', section: 'loans', group: 'Defaults', label: 'First payment offset (days)', description: 'Days after origination the first payment is due.', type: 'number', default: 30, min: 0, max: 90, step: 1 },
  { id: 'loans-default-rounding-mode', section: 'loans', group: 'Defaults', label: 'Payment rounding mode', type: 'select', default: 'nearest-cent', options: [{ value: 'nearest-cent', label: 'Nearest cent' }, { value: 'up', label: 'Round up' }, { value: 'down', label: 'Round down' }] },
  { id: 'loans-default-final-payment-adjust', section: 'loans', group: 'Defaults', label: 'Adjust final payment for rounding', type: 'toggle', default: true },
  { id: 'loans-default-extra-to-principal', section: 'loans', group: 'Defaults', label: 'Apply extra payments to principal', type: 'toggle', default: true },
  { id: 'loans-default-grace-period-days', section: 'loans', group: 'Defaults', label: 'Default grace period (days)', type: 'number', default: 10, min: 0, max: 60, step: 1 },
  { id: 'loans-default-late-fee-amount', section: 'loans', group: 'Defaults', label: 'Default late fee amount', type: 'number', default: 25, min: 0, max: 1000, step: 1 },
  { id: 'loans-default-late-fee-type', section: 'loans', group: 'Defaults', label: 'Default late fee type', type: 'select', default: 'flat', options: [{ value: 'flat', label: 'Flat amount' }, { value: 'percent', label: 'Percent of payment' }] },
  { id: 'loans-default-prepayment-penalty', section: 'loans', group: 'Defaults', label: 'Default prepayment penalty (%)', type: 'number', default: 0, min: 0, max: 10, step: 0.25 },
  { id: 'loans-default-lender-name', section: 'loans', group: 'Defaults', label: 'Default lender name', type: 'text', default: '' },
  { id: 'loans-default-liability-account', section: 'loans', group: 'Defaults', label: 'Default liability GL account', type: 'text', default: '2100 - Loans Payable' },
  { id: 'loans-default-interest-expense-account', section: 'loans', group: 'Defaults', label: 'Default interest expense GL account', type: 'text', default: '6200 - Interest Expense' },
  { id: 'loans-default-auto-generate-schedule', section: 'loans', group: 'Defaults', label: 'Auto-generate amortization schedule', type: 'toggle', default: true },
  { id: 'loans-default-include-escrow', section: 'loans', group: 'Defaults', label: 'Include escrow by default', type: 'toggle', default: false },
  { id: 'loans-default-status-new', section: 'loans', group: 'Defaults', label: 'Default status for new loans', type: 'select', default: 'active', options: [{ value: 'pending', label: 'Pending' }, { value: 'active', label: 'Active' }, { value: 'draft', label: 'Draft' }] },
  { id: 'loans-default-business-day-convention', section: 'loans', group: 'Defaults', label: 'Due-date business-day convention', type: 'select', default: 'following', options: [{ value: 'none', label: 'No adjustment' }, { value: 'following', label: 'Following business day' }, { value: 'preceding', label: 'Preceding business day' }, { value: 'modified', label: 'Modified following' }] },
  { id: 'loans-default-amount', section: 'loans', group: 'Defaults', label: 'Default loan principal amount', type: 'number', default: 10000, min: 0, max: 100000000, step: 100 },

  // ===== Sorting & Filtering (91-110) =====
  { id: 'loans-sort-default-field', section: 'loans', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'next-due', options: [{ value: 'next-due', label: 'Next due date' }, { value: 'balance', label: 'Current balance' }, { value: 'lender', label: 'Lender' }, { value: 'rate', label: 'Interest rate' }, { value: 'maturity', label: 'Maturity date' }] },
  { id: 'loans-sort-default-direction', section: 'loans', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'loans-sort-secondary-field', section: 'loans', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'lender', options: [{ value: 'none', label: 'None' }, { value: 'lender', label: 'Lender' }, { value: 'balance', label: 'Balance' }, { value: 'rate', label: 'Rate' }] },
  { id: 'loans-filter-default-status', section: 'loans', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'paid-off', label: 'Paid off' }, { value: 'delinquent', label: 'Delinquent' }] },
  { id: 'loans-filter-hide-paid-off', section: 'loans', group: 'Sorting & Filtering', label: 'Hide paid-off loans by default', type: 'toggle', default: true },
  { id: 'loans-filter-hide-zero-balance', section: 'loans', group: 'Sorting & Filtering', label: 'Hide zero-balance loans', type: 'toggle', default: false },
  { id: 'loans-filter-remember-last', section: 'loans', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'loans-filter-default-lender', section: 'loans', group: 'Sorting & Filtering', label: 'Default lender filter', type: 'text', default: '' },
  { id: 'loans-filter-default-type', section: 'loans', group: 'Sorting & Filtering', label: 'Default loan type filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All types' }, { value: 'term', label: 'Term' }, { value: 'revolving', label: 'Revolving' }, { value: 'mortgage', label: 'Mortgage' }] },
  { id: 'loans-filter-min-balance', section: 'loans', group: 'Sorting & Filtering', label: 'Default minimum balance filter', type: 'number', default: 0, min: 0, max: 100000000, step: 100 },
  { id: 'loans-filter-rate-type', section: 'loans', group: 'Sorting & Filtering', label: 'Default rate-type filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'fixed', label: 'Fixed only' }, { value: 'variable', label: 'Variable only' }] },
  { id: 'loans-filter-search-includes-notes', section: 'loans', group: 'Sorting & Filtering', label: 'Search includes notes', type: 'toggle', default: true },
  { id: 'loans-filter-search-includes-account', section: 'loans', group: 'Sorting & Filtering', label: 'Search includes account numbers', type: 'toggle', default: false },
  { id: 'loans-filter-case-sensitive-search', section: 'loans', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'loans-filter-group-by', section: 'loans', group: 'Sorting & Filtering', label: 'Group loans by', type: 'select', default: 'none', options: [{ value: 'none', label: 'No grouping' }, { value: 'lender', label: 'Lender' }, { value: 'type', label: 'Loan type' }, { value: 'status', label: 'Status' }] },
  { id: 'loans-filter-maturing-within', section: 'loans', group: 'Sorting & Filtering', label: 'Highlight loans maturing within (months)', type: 'number', default: 12, min: 1, max: 60, step: 1 },
  { id: 'loans-filter-sticky-search', section: 'loans', group: 'Sorting & Filtering', label: 'Keep search bar always visible', type: 'toggle', default: true },
  { id: 'loans-filter-show-filter-chips', section: 'loans', group: 'Sorting & Filtering', label: 'Show active filter chips', type: 'toggle', default: true },
  { id: 'loans-filter-quick-presets', section: 'loans', group: 'Sorting & Filtering', label: 'Show quick filter presets', type: 'toggle', default: true },
  { id: 'loans-filter-saved-default', section: 'loans', group: 'Sorting & Filtering', label: 'Default saved filter view', type: 'text', default: '' },

  // ===== Behavior (111-130) =====
  { id: 'loans-behavior-confirm-delete', section: 'loans', group: 'Behavior', label: 'Confirm before deleting a loan', type: 'toggle', default: true },
  { id: 'loans-behavior-autosave-edits', section: 'loans', group: 'Behavior', label: 'Auto-save loan edits', type: 'toggle', default: false },
  { id: 'loans-behavior-recalc-on-edit', section: 'loans', group: 'Behavior', label: 'Recalculate schedule on rate/term edit', type: 'toggle', default: true },
  { id: 'loans-behavior-auto-post-interest', section: 'loans', group: 'Behavior', label: 'Auto-post monthly interest accrual', type: 'toggle', default: false },
  { id: 'loans-behavior-auto-record-payment', section: 'loans', group: 'Behavior', label: 'Auto-record scheduled payments', type: 'toggle', default: false },
  { id: 'loans-behavior-open-after-create', section: 'loans', group: 'Behavior', label: 'Open loan detail after creating', type: 'toggle', default: true },
  { id: 'loans-behavior-duplicate-warn', section: 'loans', group: 'Behavior', label: 'Warn on possible duplicate loan', type: 'toggle', default: true },
  { id: 'loans-behavior-overpayment-handling', section: 'loans', group: 'Behavior', label: 'Overpayment handling', type: 'select', default: 'principal', options: [{ value: 'principal', label: 'Reduce principal' }, { value: 'next-payment', label: 'Apply to next payment' }, { value: 'hold', label: 'Hold as credit' }] },
  { id: 'loans-behavior-rounding-tolerance', section: 'loans', group: 'Behavior', label: 'Payoff rounding tolerance (cents)', type: 'number', default: 2, min: 0, max: 100, step: 1 },
  { id: 'loans-behavior-link-bank-feed', section: 'loans', group: 'Behavior', label: 'Auto-match loan payments from bank feed', type: 'toggle', default: true },
  { id: 'loans-behavior-mark-paid-on-zero', section: 'loans', group: 'Behavior', label: 'Auto mark paid-off at zero balance', type: 'toggle', default: true },
  { id: 'loans-behavior-allow-negative-balance', section: 'loans', group: 'Behavior', label: 'Allow negative balance (credit)', type: 'toggle', default: false },
  { id: 'loans-behavior-default-tab', section: 'loans', group: 'Behavior', label: 'Default loan detail tab', type: 'select', default: 'overview', options: [{ value: 'overview', label: 'Overview' }, { value: 'schedule', label: 'Schedule' }, { value: 'payments', label: 'Payments' }, { value: 'documents', label: 'Documents' }] },
  { id: 'loans-behavior-keep-edit-open', section: 'loans', group: 'Behavior', label: 'Keep editor open after save', type: 'toggle', default: false },
  { id: 'loans-behavior-variable-rate-prompt', section: 'loans', group: 'Behavior', label: 'Prompt to update variable rates monthly', type: 'toggle', default: true },
  { id: 'loans-behavior-recompute-on-extra', section: 'loans', group: 'Behavior', label: 'Recompute schedule after extra payment', type: 'toggle', default: true },
  { id: 'loans-behavior-auto-archive-months', section: 'loans', group: 'Behavior', label: 'Auto-archive paid loans after (months)', type: 'number', default: 12, min: 0, max: 120, step: 1 },
  { id: 'loans-behavior-undo-window', section: 'loans', group: 'Behavior', label: 'Undo window for deletes (seconds)', type: 'number', default: 8, min: 0, max: 60, step: 1 },
  { id: 'loans-behavior-double-entry-link', section: 'loans', group: 'Behavior', label: 'Create journal entries for loan activity', type: 'toggle', default: true },
  { id: 'loans-behavior-prepay-applies-to', section: 'loans', group: 'Behavior', label: 'Prepayment recalculates', type: 'select', default: 'term', options: [{ value: 'term', label: 'Shorten term' }, { value: 'payment', label: 'Lower payment' }] },

  // ===== Notifications (131-150) =====
  { id: 'loans-notify-payment-due', section: 'loans', group: 'Notifications', label: 'Notify on upcoming payment due', type: 'toggle', default: true },
  { id: 'loans-notify-payment-due-days', section: 'loans', group: 'Notifications', label: 'Payment-due reminder lead time (days)', type: 'number', default: 5, min: 0, max: 30, step: 1 },
  { id: 'loans-notify-payment-overdue', section: 'loans', group: 'Notifications', label: 'Notify on overdue payment', type: 'toggle', default: true },
  { id: 'loans-notify-rate-change', section: 'loans', group: 'Notifications', label: 'Notify on variable rate change', type: 'toggle', default: true },
  { id: 'loans-notify-maturity-approaching', section: 'loans', group: 'Notifications', label: 'Notify when maturity approaches', type: 'toggle', default: true },
  { id: 'loans-notify-maturity-lead-days', section: 'loans', group: 'Notifications', label: 'Maturity reminder lead time (days)', type: 'number', default: 60, min: 1, max: 365, step: 1 },
  { id: 'loans-notify-balloon-due', section: 'loans', group: 'Notifications', label: 'Notify on upcoming balloon payment', type: 'toggle', default: true },
  { id: 'loans-notify-paid-off', section: 'loans', group: 'Notifications', label: 'Notify when a loan is paid off', type: 'toggle', default: true },
  { id: 'loans-notify-escrow-shortfall', section: 'loans', group: 'Notifications', label: 'Notify on escrow shortfall', type: 'toggle', default: false },
  { id: 'loans-notify-channel', section: 'loans', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }, { value: 'none', label: 'None' }] },
  { id: 'loans-notify-email-address', section: 'loans', group: 'Notifications', label: 'Notification email address', type: 'text', default: '' },
  { id: 'loans-notify-digest', section: 'loans', group: 'Notifications', label: 'Bundle reminders into a digest', type: 'toggle', default: false },
  { id: 'loans-notify-digest-frequency', section: 'loans', group: 'Notifications', label: 'Digest frequency', type: 'select', default: 'weekly', options: [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }] },
  { id: 'loans-notify-quiet-hours', section: 'loans', group: 'Notifications', label: 'Respect quiet hours', type: 'toggle', default: true },
  { id: 'loans-notify-quiet-start', section: 'loans', group: 'Notifications', label: 'Quiet hours start (24h)', type: 'number', default: 20, min: 0, max: 23, step: 1 },
  { id: 'loans-notify-quiet-end', section: 'loans', group: 'Notifications', label: 'Quiet hours end (24h)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'loans-notify-sound', section: 'loans', group: 'Notifications', label: 'Play sound on loan alerts', type: 'toggle', default: false },
  { id: 'loans-notify-covenant-breach', section: 'loans', group: 'Notifications', label: 'Notify on covenant breach risk', type: 'toggle', default: false },
  { id: 'loans-notify-large-interest', section: 'loans', group: 'Notifications', label: 'Alert when monthly interest exceeds threshold', type: 'toggle', default: false },
  { id: 'loans-notify-large-interest-threshold', section: 'loans', group: 'Notifications', label: 'Interest alert threshold amount', type: 'number', default: 1000, min: 0, max: 1000000, step: 50 },

  // ===== Export (151-168) =====
  { id: 'loans-export-default-format', section: 'loans', group: 'Export', label: 'Default export format', type: 'select', default: 'xlsx', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel (XLSX)' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'loans-export-include-schedule', section: 'loans', group: 'Export', label: 'Include amortization schedule in export', type: 'toggle', default: true },
  { id: 'loans-export-include-payments', section: 'loans', group: 'Export', label: 'Include payment history in export', type: 'toggle', default: true },
  { id: 'loans-export-include-summary', section: 'loans', group: 'Export', label: 'Include summary totals row', type: 'toggle', default: true },
  { id: 'loans-export-include-headers', section: 'loans', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'loans-export-date-format', section: 'loans', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'YYYY-MM-DD' }, { value: 'us', label: 'MM/DD/YYYY' }, { value: 'eu', label: 'DD/MM/YYYY' }] },
  { id: 'loans-export-currency-as-number', section: 'loans', group: 'Export', label: 'Export amounts as raw numbers', description: 'Strip currency symbols for spreadsheet math.', type: 'toggle', default: true },
  { id: 'loans-export-csv-delimiter', section: 'loans', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }, { value: 'pipe', label: 'Pipe' }] },
  { id: 'loans-export-filename-pattern', section: 'loans', group: 'Export', label: 'Export filename pattern', type: 'text', default: 'loans_{date}' },
  { id: 'loans-export-pdf-orientation', section: 'loans', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'loans-export-pdf-include-logo', section: 'loans', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'loans-export-pdf-page-size', section: 'loans', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'loans-export-only-visible-columns', section: 'loans', group: 'Export', label: 'Export only visible columns', type: 'toggle', default: false },
  { id: 'loans-export-respect-filters', section: 'loans', group: 'Export', label: 'Export respects active filters', type: 'toggle', default: true },
  { id: 'loans-export-include-notes', section: 'loans', group: 'Export', label: 'Include notes field in export', type: 'toggle', default: false },
  { id: 'loans-export-encoding', section: 'loans', group: 'Export', label: 'CSV character encoding', type: 'select', default: 'utf-8', options: [{ value: 'utf-8', label: 'UTF-8' }, { value: 'utf-8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'loans-export-split-by-lender', section: 'loans', group: 'Export', label: 'Split export into a sheet per lender', type: 'toggle', default: false },
  { id: 'loans-export-include-payoff-quote', section: 'loans', group: 'Export', label: 'Include payoff quote in export', type: 'toggle', default: false },

  // ===== Colors & Theme (169-182) =====
  { id: 'loans-color-active', section: 'loans', group: 'Colors & Theme', label: 'Active loan accent color', type: 'color', default: '#3b82f6' },
  { id: 'loans-color-paid-off', section: 'loans', group: 'Colors & Theme', label: 'Paid-off color', type: 'color', default: '#10b981' },
  { id: 'loans-color-overdue', section: 'loans', group: 'Colors & Theme', label: 'Overdue/delinquent color', type: 'color', default: '#ef4444' },
  { id: 'loans-color-due-soon', section: 'loans', group: 'Colors & Theme', label: 'Due-soon highlight color', type: 'color', default: '#f59e0b' },
  { id: 'loans-color-principal', section: 'loans', group: 'Colors & Theme', label: 'Principal chart color', type: 'color', default: '#6366f1' },
  { id: 'loans-color-interest', section: 'loans', group: 'Colors & Theme', label: 'Interest chart color', type: 'color', default: '#ec4899' },
  { id: 'loans-color-escrow', section: 'loans', group: 'Colors & Theme', label: 'Escrow chart color', type: 'color', default: '#14b8a6' },
  { id: 'loans-color-progress-bar', section: 'loans', group: 'Colors & Theme', label: 'Payoff progress bar color', type: 'color', default: '#22c55e' },
  { id: 'loans-color-variable-rate-badge', section: 'loans', group: 'Colors & Theme', label: 'Variable-rate badge color', type: 'color', default: '#8b5cf6' },
  { id: 'loans-color-summary-bar', section: 'loans', group: 'Colors & Theme', label: 'Summary bar background color', type: 'color', default: '#1e293b' },
  { id: 'loans-color-chart-grid', section: 'loans', group: 'Colors & Theme', label: 'Chart gridline color', type: 'color', default: '#334155' },
  { id: 'loans-color-balloon-flag', section: 'loans', group: 'Colors & Theme', label: 'Balloon payment flag color', type: 'color', default: '#f97316' },
  { id: 'loans-color-use-status-colors', section: 'loans', group: 'Colors & Theme', label: 'Color rows by status', type: 'toggle', default: true },
  { id: 'loans-color-chart-style', section: 'loans', group: 'Colors & Theme', label: 'Amortization chart style', type: 'select', default: 'stacked-area', options: [{ value: 'stacked-area', label: 'Stacked area' }, { value: 'line', label: 'Line' }, { value: 'bar', label: 'Bar' }] },

  // ===== Accessibility (183-190) =====
  { id: 'loans-a11y-high-contrast', section: 'loans', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'loans-a11y-font-scale', section: 'loans', group: 'Accessibility', label: 'Table font scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'loans-a11y-reduce-motion', section: 'loans', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'loans-a11y-status-icons', section: 'loans', group: 'Accessibility', label: 'Show status as icon plus color', description: 'Do not rely on color alone for status.', type: 'toggle', default: true },
  { id: 'loans-a11y-screen-reader-summaries', section: 'loans', group: 'Accessibility', label: 'Verbose screen-reader summaries', type: 'toggle', default: false },
  { id: 'loans-a11y-focus-outline', section: 'loans', group: 'Accessibility', label: 'Prominent keyboard focus outline', type: 'toggle', default: true },
  { id: 'loans-a11y-colorblind-palette', section: 'loans', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'select', default: 'off', options: [{ value: 'off', label: 'Off' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' }] },
  { id: 'loans-a11y-underline-links', section: 'loans', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },

  // ===== Shortcuts (191-196) =====
  { id: 'loans-shortcut-new-loan', section: 'loans', group: 'Shortcuts', label: 'New loan shortcut', type: 'text', default: 'Cmd+N' },
  { id: 'loans-shortcut-record-payment', section: 'loans', group: 'Shortcuts', label: 'Record payment shortcut', type: 'text', default: 'Cmd+P' },
  { id: 'loans-shortcut-search', section: 'loans', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: 'Cmd+F' },
  { id: 'loans-shortcut-export', section: 'loans', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'Cmd+E' },
  { id: 'loans-shortcut-enable', section: 'loans', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'loans-shortcut-vim-nav', section: 'loans', group: 'Shortcuts', label: 'Enable j/k row navigation', type: 'toggle', default: false },

  // ===== Privacy (197-200) =====
  { id: 'loans-privacy-mask-balances', section: 'loans', group: 'Privacy', label: 'Mask balances until hover', type: 'toggle', default: false },
  { id: 'loans-privacy-mask-account-numbers', section: 'loans', group: 'Privacy', label: 'Mask account numbers', description: 'Show only the last 4 digits.', type: 'toggle', default: true },
  { id: 'loans-privacy-hide-on-blur', section: 'loans', group: 'Privacy', label: 'Blur figures when window loses focus', type: 'toggle', default: false },
  { id: 'loans-privacy-audit-log', section: 'loans', group: 'Privacy', label: 'Log all loan edits to audit trail', type: 'toggle', default: true },
];
