import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display =====
  { id: 'payroll-display-default-view', section: 'payroll', group: 'Display', label: 'Default payroll view', description: 'Initial screen when opening the Payroll module.', type: 'select', default: 'employees', options: [{ value: 'employees', label: 'Employee List' }, { value: 'runs', label: 'Pay Runs' }, { value: 'calendar', label: 'Pay Calendar' }, { value: 'dashboard', label: 'Overview Dashboard' }] },
  { id: 'payroll-display-density', section: 'payroll', group: 'Display', label: 'Row density', description: 'Vertical spacing of employee and pay-run rows.', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'payroll-display-show-avatars', section: 'payroll', group: 'Display', label: 'Show employee photos', description: 'Display profile avatars in the employee roster.', type: 'toggle', default: true },
  { id: 'payroll-display-show-inactive', section: 'payroll', group: 'Display', label: 'Show terminated employees', description: 'Include terminated staff in the default roster.', type: 'toggle', default: false },
  { id: 'payroll-display-rows-per-page', section: 'payroll', group: 'Display', label: 'Employees per page', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'payroll-display-sticky-header', section: 'payroll', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible while scrolling.', type: 'toggle', default: true },
  { id: 'payroll-display-zebra-rows', section: 'payroll', group: 'Display', label: 'Alternating row shading', type: 'toggle', default: true },
  { id: 'payroll-display-employee-id-badge', section: 'payroll', group: 'Display', label: 'Show employee ID badge', description: 'Render the employee number as a pill next to the name.', type: 'toggle', default: false },
  { id: 'payroll-display-department-grouping', section: 'payroll', group: 'Display', label: 'Group roster by department', type: 'toggle', default: false },
  { id: 'payroll-display-name-format', section: 'payroll', group: 'Display', label: 'Employee name format', type: 'select', default: 'first_last', options: [{ value: 'first_last', label: 'First Last' }, { value: 'last_first', label: 'Last, First' }, { value: 'last_first_mi', label: 'Last, First M.' }] },
  { id: 'payroll-display-show-tenure', section: 'payroll', group: 'Display', label: 'Show years of service', type: 'toggle', default: false },
  { id: 'payroll-display-summary-bar', section: 'payroll', group: 'Display', label: 'Show summary totals bar', description: 'Headcount, gross, net totals above the roster.', type: 'toggle', default: true },
  { id: 'payroll-display-quick-filters', section: 'payroll', group: 'Display', label: 'Show quick-filter chips', type: 'toggle', default: true },
  { id: 'payroll-display-status-dot', section: 'payroll', group: 'Display', label: 'Show employment status dot', type: 'toggle', default: true },
  { id: 'payroll-display-pay-frequency-label', section: 'payroll', group: 'Display', label: 'Show pay frequency on roster', type: 'toggle', default: false },
  { id: 'payroll-display-empty-state-tips', section: 'payroll', group: 'Display', label: 'Show empty-state tips', type: 'toggle', default: true },
  { id: 'payroll-display-card-or-table', section: 'payroll', group: 'Display', label: 'Roster layout', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'grid', label: 'Grid' }] },

  // ===== Columns =====
  { id: 'payroll-col-employee-id', section: 'payroll', group: 'Columns', label: 'Column: Employee ID', type: 'toggle', default: true },
  { id: 'payroll-col-job-title', section: 'payroll', group: 'Columns', label: 'Column: Job title', type: 'toggle', default: true },
  { id: 'payroll-col-department', section: 'payroll', group: 'Columns', label: 'Column: Department', type: 'toggle', default: true },
  { id: 'payroll-col-employment-type', section: 'payroll', group: 'Columns', label: 'Column: Employment type', description: 'Full-time, part-time, contractor.', type: 'toggle', default: true },
  { id: 'payroll-col-pay-rate', section: 'payroll', group: 'Columns', label: 'Column: Pay rate', type: 'toggle', default: true },
  { id: 'payroll-col-pay-frequency', section: 'payroll', group: 'Columns', label: 'Column: Pay frequency', type: 'toggle', default: true },
  { id: 'payroll-col-hire-date', section: 'payroll', group: 'Columns', label: 'Column: Hire date', type: 'toggle', default: false },
  { id: 'payroll-col-manager', section: 'payroll', group: 'Columns', label: 'Column: Reporting manager', type: 'toggle', default: false },
  { id: 'payroll-col-status', section: 'payroll', group: 'Columns', label: 'Column: Employment status', type: 'toggle', default: true },
  { id: 'payroll-col-ytd-gross', section: 'payroll', group: 'Columns', label: 'Column: YTD gross', type: 'toggle', default: false },
  { id: 'payroll-col-ytd-net', section: 'payroll', group: 'Columns', label: 'Column: YTD net', type: 'toggle', default: false },
  { id: 'payroll-col-last-paid', section: 'payroll', group: 'Columns', label: 'Column: Last paid date', type: 'toggle', default: false },
  { id: 'payroll-col-email', section: 'payroll', group: 'Columns', label: 'Column: Email', type: 'toggle', default: false },
  { id: 'payroll-col-phone', section: 'payroll', group: 'Columns', label: 'Column: Phone', type: 'toggle', default: false },
  { id: 'payroll-col-location', section: 'payroll', group: 'Columns', label: 'Column: Work location', type: 'toggle', default: false },
  { id: 'payroll-col-filing-status', section: 'payroll', group: 'Columns', label: 'Column: Tax filing status', type: 'toggle', default: false },
  { id: 'payroll-col-allowances', section: 'payroll', group: 'Columns', label: 'Column: Withholding allowances', type: 'toggle', default: false },
  { id: 'payroll-col-direct-deposit', section: 'payroll', group: 'Columns', label: 'Column: Direct deposit on file', type: 'toggle', default: true },
  { id: 'payroll-col-pto-balance', section: 'payroll', group: 'Columns', label: 'Column: PTO balance', type: 'toggle', default: false },
  { id: 'payroll-col-cost-center', section: 'payroll', group: 'Columns', label: 'Column: Cost center', type: 'toggle', default: false },

  // ===== Pay Runs =====
  { id: 'payroll-run-default-frequency', section: 'payroll', group: 'Pay Runs', label: 'Default pay frequency', type: 'select', default: 'biweekly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'semimonthly', label: 'Semi-monthly' }, { value: 'monthly', label: 'Monthly' }] },
  { id: 'payroll-run-default-payday-offset', section: 'payroll', group: 'Pay Runs', label: 'Default payday offset (days)', description: 'Days after period end that pay is issued.', type: 'number', default: 5, min: 0, max: 30, step: 1 },
  { id: 'payroll-run-auto-populate-hours', section: 'payroll', group: 'Pay Runs', label: 'Auto-populate standard hours', description: 'Pre-fill salaried hours each run.', type: 'toggle', default: true },
  { id: 'payroll-run-require-approval', section: 'payroll', group: 'Pay Runs', label: 'Require approval before submit', type: 'toggle', default: true },
  { id: 'payroll-run-lock-after-submit', section: 'payroll', group: 'Pay Runs', label: 'Lock run after submission', type: 'toggle', default: true },
  { id: 'payroll-run-default-overtime-multiplier', section: 'payroll', group: 'Pay Runs', label: 'Overtime multiplier', type: 'number', default: 1.5, min: 1, max: 3, step: 0.1 },
  { id: 'payroll-run-doubletime-multiplier', section: 'payroll', group: 'Pay Runs', label: 'Double-time multiplier', type: 'number', default: 2, min: 1, max: 4, step: 0.1 },
  { id: 'payroll-run-overtime-threshold', section: 'payroll', group: 'Pay Runs', label: 'Weekly overtime threshold (hours)', type: 'number', default: 40, min: 0, max: 80, step: 1 },
  { id: 'payroll-run-show-preview-diff', section: 'payroll', group: 'Pay Runs', label: 'Show changes vs previous run', type: 'toggle', default: true },
  { id: 'payroll-run-include-contractors', section: 'payroll', group: 'Pay Runs', label: 'Include contractors in runs', type: 'toggle', default: false },
  { id: 'payroll-run-auto-advance-period', section: 'payroll', group: 'Pay Runs', label: 'Auto-advance to next period', description: 'Roll the pay period forward after finalizing.', type: 'toggle', default: true },
  { id: 'payroll-run-confirm-large-changes', section: 'payroll', group: 'Pay Runs', label: 'Confirm runs with large variance', type: 'toggle', default: true },
  { id: 'payroll-run-variance-threshold', section: 'payroll', group: 'Pay Runs', label: 'Variance warning threshold (%)', type: 'number', default: 20, min: 5, max: 100, step: 5 },
  { id: 'payroll-run-default-memo', section: 'payroll', group: 'Pay Runs', label: 'Default pay-run memo', type: 'text', default: 'Regular payroll' },
  { id: 'payroll-run-skip-zero-pay', section: 'payroll', group: 'Pay Runs', label: 'Skip employees with zero pay', type: 'toggle', default: true },
  { id: 'payroll-run-rounding', section: 'payroll', group: 'Pay Runs', label: 'Hours rounding', type: 'select', default: 'nearest_quarter', options: [{ value: 'none', label: 'No rounding' }, { value: 'nearest_quarter', label: 'Nearest 15 min' }, { value: 'nearest_tenth', label: 'Nearest 6 min' }, { value: 'nearest_hour', label: 'Nearest hour' }] },
  { id: 'payroll-run-batch-by-department', section: 'payroll', group: 'Pay Runs', label: 'Batch runs by department', type: 'toggle', default: false },

  // ===== Pay Stubs =====
  { id: 'payroll-stub-show-ytd', section: 'payroll', group: 'Pay Stubs', label: 'Show YTD totals on stub', type: 'toggle', default: true },
  { id: 'payroll-stub-show-employer-contrib', section: 'payroll', group: 'Pay Stubs', label: 'Show employer contributions', type: 'toggle', default: true },
  { id: 'payroll-stub-show-pto-balance', section: 'payroll', group: 'Pay Stubs', label: 'Show PTO balance on stub', type: 'toggle', default: true },
  { id: 'payroll-stub-show-tax-breakdown', section: 'payroll', group: 'Pay Stubs', label: 'Itemize tax withholdings', type: 'toggle', default: true },
  { id: 'payroll-stub-logo', section: 'payroll', group: 'Pay Stubs', label: 'Show company logo on stub', type: 'toggle', default: true },
  { id: 'payroll-stub-mask-ssn', section: 'payroll', group: 'Pay Stubs', label: 'Mask SSN on stub', description: 'Show only last 4 digits.', type: 'toggle', default: true },
  { id: 'payroll-stub-paper-size', section: 'payroll', group: 'Pay Stubs', label: 'Stub paper size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'payroll-stub-footer-note', section: 'payroll', group: 'Pay Stubs', label: 'Stub footer note', type: 'text', default: 'This is not a negotiable instrument.' },
  { id: 'payroll-stub-show-rate', section: 'payroll', group: 'Pay Stubs', label: 'Show pay rate on stub', type: 'toggle', default: true },
  { id: 'payroll-stub-show-hours-detail', section: 'payroll', group: 'Pay Stubs', label: 'Show hours breakdown', description: 'Regular, OT, holiday split.', type: 'toggle', default: true },
  { id: 'payroll-stub-color', section: 'payroll', group: 'Pay Stubs', label: 'Stub accent color', type: 'color', default: '#2563eb' },
  { id: 'payroll-stub-auto-email', section: 'payroll', group: 'Pay Stubs', label: 'Email stubs automatically', type: 'toggle', default: false },
  { id: 'payroll-stub-password-protect', section: 'payroll', group: 'Pay Stubs', label: 'Password-protect stub PDFs', type: 'toggle', default: true },
  { id: 'payroll-stub-show-deduction-codes', section: 'payroll', group: 'Pay Stubs', label: 'Show deduction codes', type: 'toggle', default: false },
  { id: 'payroll-stub-show-net-words', section: 'payroll', group: 'Pay Stubs', label: 'Spell net pay in words', type: 'toggle', default: false },
  { id: 'payroll-stub-template', section: 'payroll', group: 'Pay Stubs', label: 'Stub template', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'detailed', label: 'Detailed' }, { value: 'minimal', label: 'Minimal' }] },

  // ===== Taxes & Deductions =====
  { id: 'payroll-tax-default-fed-method', section: 'payroll', group: 'Taxes & Deductions', label: 'Federal withholding method', type: 'select', default: 'percentage', options: [{ value: 'percentage', label: 'Percentage' }, { value: 'wage_bracket', label: 'Wage bracket' }] },
  { id: 'payroll-tax-auto-calc-fica', section: 'payroll', group: 'Taxes & Deductions', label: 'Auto-calculate FICA', type: 'toggle', default: true },
  { id: 'payroll-tax-ss-wage-base', section: 'payroll', group: 'Taxes & Deductions', label: 'Social Security wage base ($)', type: 'number', default: 168600, min: 100000, max: 250000, step: 100 },
  { id: 'payroll-tax-ss-rate', section: 'payroll', group: 'Taxes & Deductions', label: 'Social Security rate (%)', type: 'number', default: 6.2, min: 0, max: 15, step: 0.1 },
  { id: 'payroll-tax-medicare-rate', section: 'payroll', group: 'Taxes & Deductions', label: 'Medicare rate (%)', type: 'number', default: 1.45, min: 0, max: 5, step: 0.05 },
  { id: 'payroll-tax-addl-medicare-threshold', section: 'payroll', group: 'Taxes & Deductions', label: 'Additional Medicare threshold ($)', type: 'number', default: 200000, min: 100000, max: 500000, step: 1000 },
  { id: 'payroll-tax-suta-rate', section: 'payroll', group: 'Taxes & Deductions', label: 'State unemployment (SUTA) rate (%)', type: 'number', default: 2.7, min: 0, max: 15, step: 0.1 },
  { id: 'payroll-tax-futa-rate', section: 'payroll', group: 'Taxes & Deductions', label: 'Federal unemployment (FUTA) rate (%)', type: 'number', default: 0.6, min: 0, max: 6, step: 0.1 },
  { id: 'payroll-tax-state', section: 'payroll', group: 'Taxes & Deductions', label: 'Default work state', type: 'text', default: 'UT' },
  { id: 'payroll-tax-local-enabled', section: 'payroll', group: 'Taxes & Deductions', label: 'Enable local tax withholding', type: 'toggle', default: false },
  { id: 'payroll-tax-pretax-order', section: 'payroll', group: 'Taxes & Deductions', label: 'Apply pre-tax deductions first', type: 'toggle', default: true },
  { id: 'payroll-tax-401k-default-pct', section: 'payroll', group: 'Taxes & Deductions', label: 'Default 401(k) contribution (%)', type: 'number', default: 3, min: 0, max: 100, step: 0.5 },
  { id: 'payroll-tax-401k-match-pct', section: 'payroll', group: 'Taxes & Deductions', label: 'Employer 401(k) match (%)', type: 'number', default: 3, min: 0, max: 25, step: 0.5 },
  { id: 'payroll-tax-hsa-enabled', section: 'payroll', group: 'Taxes & Deductions', label: 'Enable HSA deductions', type: 'toggle', default: false },
  { id: 'payroll-tax-garnishment-priority', section: 'payroll', group: 'Taxes & Deductions', label: 'Garnishments take priority', type: 'toggle', default: true },
  { id: 'payroll-tax-roundtaxes', section: 'payroll', group: 'Taxes & Deductions', label: 'Round tax amounts to cents', type: 'toggle', default: true },
  { id: 'payroll-tax-show-effective-rate', section: 'payroll', group: 'Taxes & Deductions', label: 'Show effective tax rate', type: 'toggle', default: false },

  // ===== Time & Attendance =====
  { id: 'payroll-time-track-hours', section: 'payroll', group: 'Time & Attendance', label: 'Enable hours tracking', type: 'toggle', default: true },
  { id: 'payroll-time-default-workweek', section: 'payroll', group: 'Time & Attendance', label: 'Standard workweek hours', type: 'number', default: 40, min: 1, max: 80, step: 0.5 },
  { id: 'payroll-time-week-start', section: 'payroll', group: 'Time & Attendance', label: 'Workweek starts on', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }, { value: 'saturday', label: 'Saturday' }] },
  { id: 'payroll-time-require-approval', section: 'payroll', group: 'Time & Attendance', label: 'Require timesheet approval', type: 'toggle', default: true },
  { id: 'payroll-time-allow-negative', section: 'payroll', group: 'Time & Attendance', label: 'Allow negative hour entries', type: 'toggle', default: false },
  { id: 'payroll-time-lunch-auto-deduct', section: 'payroll', group: 'Time & Attendance', label: 'Auto-deduct lunch break', type: 'toggle', default: false },
  { id: 'payroll-time-lunch-minutes', section: 'payroll', group: 'Time & Attendance', label: 'Lunch deduction (minutes)', type: 'number', default: 30, min: 0, max: 120, step: 5 },
  { id: 'payroll-time-overtime-daily', section: 'payroll', group: 'Time & Attendance', label: 'Enable daily overtime', description: 'OT after a daily hour threshold (e.g. CA).', type: 'toggle', default: false },
  { id: 'payroll-time-daily-ot-threshold', section: 'payroll', group: 'Time & Attendance', label: 'Daily overtime threshold (hours)', type: 'number', default: 8, min: 1, max: 24, step: 0.5 },
  { id: 'payroll-time-holiday-pay-multiplier', section: 'payroll', group: 'Time & Attendance', label: 'Holiday pay multiplier', type: 'number', default: 1.5, min: 1, max: 3, step: 0.1 },
  { id: 'payroll-time-show-clock-status', section: 'payroll', group: 'Time & Attendance', label: 'Show clocked-in status', type: 'toggle', default: false },
  { id: 'payroll-time-flag-missing', section: 'payroll', group: 'Time & Attendance', label: 'Flag missing timesheets', type: 'toggle', default: true },

  // ===== Defaults =====
  { id: 'payroll-default-employment-type', section: 'payroll', group: 'Defaults', label: 'Default employment type', type: 'select', default: 'full_time', options: [{ value: 'full_time', label: 'Full-time' }, { value: 'part_time', label: 'Part-time' }, { value: 'contractor', label: 'Contractor' }, { value: 'seasonal', label: 'Seasonal' }] },
  { id: 'payroll-default-pay-type', section: 'payroll', group: 'Defaults', label: 'Default pay type', type: 'select', default: 'salary', options: [{ value: 'salary', label: 'Salary' }, { value: 'hourly', label: 'Hourly' }, { value: 'commission', label: 'Commission' }] },
  { id: 'payroll-default-filing-status', section: 'payroll', group: 'Defaults', label: 'Default filing status', type: 'select', default: 'single', options: [{ value: 'single', label: 'Single' }, { value: 'married_filing_jointly', label: 'Married filing jointly' }, { value: 'head_of_household', label: 'Head of household' }] },
  { id: 'payroll-default-payment-method', section: 'payroll', group: 'Defaults', label: 'Default payment method', type: 'select', default: 'direct_deposit', options: [{ value: 'direct_deposit', label: 'Direct deposit' }, { value: 'check', label: 'Paper check' }, { value: 'pay_card', label: 'Pay card' }] },
  { id: 'payroll-default-pto-accrual-rate', section: 'payroll', group: 'Defaults', label: 'Default PTO accrual (hrs/pay period)', type: 'number', default: 4, min: 0, max: 40, step: 0.5 },
  { id: 'payroll-default-currency', section: 'payroll', group: 'Defaults', label: 'Payroll currency', type: 'select', default: 'usd', options: [{ value: 'usd', label: 'USD' }, { value: 'cad', label: 'CAD' }, { value: 'eur', label: 'EUR' }, { value: 'gbp', label: 'GBP' }] },
  { id: 'payroll-default-cost-center', section: 'payroll', group: 'Defaults', label: 'Default cost center', type: 'text', default: 'General' },
  { id: 'payroll-default-probation-days', section: 'payroll', group: 'Defaults', label: 'Default probation period (days)', type: 'number', default: 90, min: 0, max: 365, step: 1 },
  { id: 'payroll-default-pto-cap', section: 'payroll', group: 'Defaults', label: 'Default PTO accrual cap (hrs)', type: 'number', default: 160, min: 0, max: 1000, step: 8 },
  { id: 'payroll-default-new-hire-onboarding', section: 'payroll', group: 'Defaults', label: 'Auto-start onboarding for new hires', type: 'toggle', default: true },
  { id: 'payroll-default-employee-prefix', section: 'payroll', group: 'Defaults', label: 'Employee ID prefix', type: 'text', default: 'EMP-' },
  { id: 'payroll-default-overtime-eligible', section: 'payroll', group: 'Defaults', label: 'New employees overtime-eligible', type: 'toggle', default: true },

  // ===== Sorting & Filtering =====
  { id: 'payroll-sort-default-field', section: 'payroll', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'name', options: [{ value: 'name', label: 'Name' }, { value: 'hire_date', label: 'Hire date' }, { value: 'department', label: 'Department' }, { value: 'pay_rate', label: 'Pay rate' }] },
  { id: 'payroll-sort-direction', section: 'payroll', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'payroll-filter-default-status', section: 'payroll', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'on_leave', label: 'On leave' }, { value: 'terminated', label: 'Terminated' }] },
  { id: 'payroll-filter-remember', section: 'payroll', group: 'Sorting & Filtering', label: 'Remember last filters', type: 'toggle', default: true },
  { id: 'payroll-filter-department', section: 'payroll', group: 'Sorting & Filtering', label: 'Default department filter', type: 'text', default: '' },
  { id: 'payroll-filter-employment-type', section: 'payroll', group: 'Sorting & Filtering', label: 'Default employment-type filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'full_time', label: 'Full-time' }, { value: 'part_time', label: 'Part-time' }, { value: 'contractor', label: 'Contractor' }] },
  { id: 'payroll-filter-secondary-sort', section: 'payroll', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'name', label: 'Name' }, { value: 'department', label: 'Department' }, { value: 'hire_date', label: 'Hire date' }] },
  { id: 'payroll-filter-search-fuzzy', section: 'payroll', group: 'Sorting & Filtering', label: 'Fuzzy employee search', type: 'toggle', default: true },
  { id: 'payroll-filter-show-count', section: 'payroll', group: 'Sorting & Filtering', label: 'Show filtered result count', type: 'toggle', default: true },
  { id: 'payroll-filter-pinned-departments', section: 'payroll', group: 'Sorting & Filtering', label: 'Pinned departments', description: 'Comma-separated departments shown first.', type: 'text', default: '' },

  // ===== Behavior =====
  { id: 'payroll-behavior-confirm-delete', section: 'payroll', group: 'Behavior', label: 'Confirm before deleting employee', type: 'toggle', default: true },
  { id: 'payroll-behavior-autosave-draft', section: 'payroll', group: 'Behavior', label: 'Auto-save pay-run drafts', type: 'toggle', default: true },
  { id: 'payroll-behavior-autosave-interval', section: 'payroll', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 10, max: 300, step: 5 },
  { id: 'payroll-behavior-warn-unsaved', section: 'payroll', group: 'Behavior', label: 'Warn on unsaved changes', type: 'toggle', default: true },
  { id: 'payroll-behavior-duplicate-detection', section: 'payroll', group: 'Behavior', label: 'Detect duplicate SSNs', type: 'toggle', default: true },
  { id: 'payroll-behavior-block-future-hire', section: 'payroll', group: 'Behavior', label: 'Block future-dated hires in runs', type: 'toggle', default: true },
  { id: 'payroll-behavior-auto-terminate-cleanup', section: 'payroll', group: 'Behavior', label: 'Archive data on termination', type: 'toggle', default: false },
  { id: 'payroll-behavior-recalc-on-edit', section: 'payroll', group: 'Behavior', label: 'Recalculate taxes on edit', type: 'toggle', default: true },
  { id: 'payroll-behavior-double-entry-confirm', section: 'payroll', group: 'Behavior', label: 'Require double-entry for rate changes', type: 'toggle', default: false },
  { id: 'payroll-behavior-keyboard-nav', section: 'payroll', group: 'Behavior', label: 'Enable keyboard row navigation', type: 'toggle', default: true },
  { id: 'payroll-behavior-inline-edit', section: 'payroll', group: 'Behavior', label: 'Allow inline cell editing', type: 'toggle', default: false },
  { id: 'payroll-behavior-undo-window', section: 'payroll', group: 'Behavior', label: 'Undo window (seconds)', type: 'number', default: 10, min: 0, max: 60, step: 1 },

  // ===== Notifications =====
  { id: 'payroll-notify-payday-reminder', section: 'payroll', group: 'Notifications', label: 'Payday reminder', type: 'toggle', default: true },
  { id: 'payroll-notify-payday-lead-days', section: 'payroll', group: 'Notifications', label: 'Payday reminder lead time (days)', type: 'number', default: 2, min: 0, max: 14, step: 1 },
  { id: 'payroll-notify-approval-pending', section: 'payroll', group: 'Notifications', label: 'Pending approval alerts', type: 'toggle', default: true },
  { id: 'payroll-notify-tax-deadline', section: 'payroll', group: 'Notifications', label: 'Tax deposit deadline alerts', type: 'toggle', default: true },
  { id: 'payroll-notify-missing-timesheet', section: 'payroll', group: 'Notifications', label: 'Missing timesheet alerts', type: 'toggle', default: true },
  { id: 'payroll-notify-birthday', section: 'payroll', group: 'Notifications', label: 'Employee birthday reminders', type: 'toggle', default: false },
  { id: 'payroll-notify-work-anniversary', section: 'payroll', group: 'Notifications', label: 'Work anniversary reminders', type: 'toggle', default: false },
  { id: 'payroll-notify-probation-ending', section: 'payroll', group: 'Notifications', label: 'Probation ending alerts', type: 'toggle', default: true },
  { id: 'payroll-notify-pto-low', section: 'payroll', group: 'Notifications', label: 'Low PTO balance alerts', type: 'toggle', default: false },
  { id: 'payroll-notify-channel', section: 'payroll', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in_app', options: [{ value: 'in_app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'payroll-notify-direct-deposit-fail', section: 'payroll', group: 'Notifications', label: 'Direct deposit failure alerts', type: 'toggle', default: true },
  { id: 'payroll-notify-new-hire-checklist', section: 'payroll', group: 'Notifications', label: 'New-hire checklist reminders', type: 'toggle', default: true },
  { id: 'payroll-notify-quiet-hours', section: 'payroll', group: 'Notifications', label: 'Suppress notifications during quiet hours', type: 'toggle', default: false },
  { id: 'payroll-notify-digest', section: 'payroll', group: 'Notifications', label: 'Notification digest frequency', type: 'select', default: 'immediate', options: [{ value: 'immediate', label: 'Immediate' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }] },

  // ===== Export =====
  { id: 'payroll-export-default-format', section: 'payroll', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'payroll-export-include-ssn', section: 'payroll', group: 'Export', label: 'Include SSN in exports', type: 'toggle', default: false },
  { id: 'payroll-export-include-bank', section: 'payroll', group: 'Export', label: 'Include bank details in exports', type: 'toggle', default: false },
  { id: 'payroll-export-date-format', section: 'payroll', group: 'Export', label: 'Export date format', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'YYYY-MM-DD' }, { value: 'us', label: 'MM/DD/YYYY' }, { value: 'eu', label: 'DD/MM/YYYY' }] },
  { id: 'payroll-export-ach-format', section: 'payroll', group: 'Export', label: 'ACH/NACHA export enabled', type: 'toggle', default: false },
  { id: 'payroll-export-gl-summary', section: 'payroll', group: 'Export', label: 'Export GL journal summary', type: 'toggle', default: true },
  { id: 'payroll-export-filename-template', section: 'payroll', group: 'Export', label: 'Export filename template', type: 'text', default: 'payroll_{period}_{date}' },
  { id: 'payroll-export-encrypt', section: 'payroll', group: 'Export', label: 'Encrypt exported files', type: 'toggle', default: true },
  { id: 'payroll-export-include-employer-taxes', section: 'payroll', group: 'Export', label: 'Include employer taxes in export', type: 'toggle', default: true },
  { id: 'payroll-export-941-ready', section: 'payroll', group: 'Export', label: 'Generate Form 941 worksheet', type: 'toggle', default: false },
  { id: 'payroll-export-w2-batch', section: 'payroll', group: 'Export', label: 'Batch W-2 generation', type: 'toggle', default: true },
  { id: 'payroll-export-delimiter', section: 'payroll', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'payroll-export-rounding-detail', section: 'payroll', group: 'Export', label: 'Include rounding detail', type: 'toggle', default: false },

  // ===== Colors & Theme =====
  { id: 'payroll-theme-active-color', section: 'payroll', group: 'Colors & Theme', label: 'Active employee color', type: 'color', default: '#22c55e' },
  { id: 'payroll-theme-leave-color', section: 'payroll', group: 'Colors & Theme', label: 'On-leave color', type: 'color', default: '#f59e0b' },
  { id: 'payroll-theme-terminated-color', section: 'payroll', group: 'Colors & Theme', label: 'Terminated color', type: 'color', default: '#ef4444' },
  { id: 'payroll-theme-contractor-color', section: 'payroll', group: 'Colors & Theme', label: 'Contractor accent color', type: 'color', default: '#8b5cf6' },
  { id: 'payroll-theme-overtime-color', section: 'payroll', group: 'Colors & Theme', label: 'Overtime highlight color', type: 'color', default: '#f97316' },
  { id: 'payroll-theme-pending-color', section: 'payroll', group: 'Colors & Theme', label: 'Pending approval color', type: 'color', default: '#eab308' },
  { id: 'payroll-theme-paid-color', section: 'payroll', group: 'Colors & Theme', label: 'Paid run color', type: 'color', default: '#10b981' },
  { id: 'payroll-theme-chart-palette', section: 'payroll', group: 'Colors & Theme', label: 'Chart palette', type: 'select', default: 'default', options: [{ value: 'default', label: 'Default' }, { value: 'colorblind', label: 'Colorblind-safe' }, { value: 'mono', label: 'Monochrome' }, { value: 'vivid', label: 'Vivid' }] },
  { id: 'payroll-theme-highlight-overdue', section: 'payroll', group: 'Colors & Theme', label: 'Highlight overdue items', type: 'toggle', default: true },
  { id: 'payroll-theme-negative-color', section: 'payroll', group: 'Colors & Theme', label: 'Negative amount color', type: 'color', default: '#dc2626' },
  { id: 'payroll-theme-positive-color', section: 'payroll', group: 'Colors & Theme', label: 'Positive amount color', type: 'color', default: '#16a34a' },
  { id: 'payroll-theme-header-color', section: 'payroll', group: 'Colors & Theme', label: 'Table header color', type: 'color', default: '#1e293b' },

  // ===== Formatting =====
  { id: 'payroll-format-currency-symbol', section: 'payroll', group: 'Formatting', label: 'Show currency symbol', type: 'toggle', default: true },
  { id: 'payroll-format-decimal-places', section: 'payroll', group: 'Formatting', label: 'Amount decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'payroll-format-thousands-sep', section: 'payroll', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'period', label: 'Period' }, { value: 'space', label: 'Space' }, { value: 'none', label: 'None' }] },
  { id: 'payroll-format-negative-style', section: 'payroll', group: 'Formatting', label: 'Negative number style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-1,000' }, { value: 'parens', label: '(1,000)' }, { value: 'red', label: 'Red text' }] },
  { id: 'payroll-format-hours-decimal', section: 'payroll', group: 'Formatting', label: 'Hours display style', type: 'select', default: 'decimal', options: [{ value: 'decimal', label: 'Decimal (7.5)' }, { value: 'hhmm', label: 'HH:MM (7:30)' }] },
  { id: 'payroll-format-rate-precision', section: 'payroll', group: 'Formatting', label: 'Pay rate decimal places', type: 'number', default: 2, min: 2, max: 4, step: 1 },
  { id: 'payroll-format-date-style', section: 'payroll', group: 'Formatting', label: 'Date display format', type: 'select', default: 'us', options: [{ value: 'us', label: 'MM/DD/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Month D, YYYY' }] },
  { id: 'payroll-format-percent-decimals', section: 'payroll', group: 'Formatting', label: 'Percentage decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'payroll-format-mask-character', section: 'payroll', group: 'Formatting', label: 'Sensitive data mask character', type: 'text', default: '•' },
  { id: 'payroll-format-rounding-mode', section: 'payroll', group: 'Formatting', label: 'Rounding mode', type: 'select', default: 'half_up', options: [{ value: 'half_up', label: 'Half up' }, { value: 'half_even', label: 'Banker\'s' }, { value: 'floor', label: 'Floor' }, { value: 'ceil', label: 'Ceiling' }] },

  // ===== Accessibility =====
  { id: 'payroll-a11y-high-contrast', section: 'payroll', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'payroll-a11y-font-size', section: 'payroll', group: 'Accessibility', label: 'Base font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'payroll-a11y-reduce-motion', section: 'payroll', group: 'Accessibility', label: 'Reduce motion', type: 'toggle', default: false },
  { id: 'payroll-a11y-status-icons', section: 'payroll', group: 'Accessibility', label: 'Use icons with status colors', description: 'Don\'t rely on color alone.', type: 'toggle', default: true },
  { id: 'payroll-a11y-focus-outline', section: 'payroll', group: 'Accessibility', label: 'Strong focus outlines', type: 'toggle', default: true },
  { id: 'payroll-a11y-screenreader-summaries', section: 'payroll', group: 'Accessibility', label: 'Screen-reader table summaries', type: 'toggle', default: true },
  { id: 'payroll-a11y-underline-links', section: 'payroll', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },
  { id: 'payroll-a11y-min-touch-target', section: 'payroll', group: 'Accessibility', label: 'Minimum touch target (px)', type: 'number', default: 44, min: 24, max: 64, step: 2 },
  { id: 'payroll-a11y-keyboard-shortcuts-overlay', section: 'payroll', group: 'Accessibility', label: 'Show keyboard shortcut overlay', type: 'toggle', default: false },

  // ===== Shortcuts =====
  { id: 'payroll-shortcut-new-employee', section: 'payroll', group: 'Shortcuts', label: 'New employee shortcut', type: 'text', default: 'n' },
  { id: 'payroll-shortcut-new-run', section: 'payroll', group: 'Shortcuts', label: 'New pay run shortcut', type: 'text', default: 'r' },
  { id: 'payroll-shortcut-search', section: 'payroll', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'payroll-shortcut-approve', section: 'payroll', group: 'Shortcuts', label: 'Approve run shortcut', type: 'text', default: 'a' },
  { id: 'payroll-shortcut-export', section: 'payroll', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'e' },
  { id: 'payroll-shortcut-enabled', section: 'payroll', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'payroll-shortcut-next-employee', section: 'payroll', group: 'Shortcuts', label: 'Next employee shortcut', type: 'text', default: 'j' },
  { id: 'payroll-shortcut-prev-employee', section: 'payroll', group: 'Shortcuts', label: 'Previous employee shortcut', type: 'text', default: 'k' },
  { id: 'payroll-shortcut-print-stub', section: 'payroll', group: 'Shortcuts', label: 'Print stub shortcut', type: 'text', default: 'p' },
  { id: 'payroll-shortcut-mode', section: 'payroll', group: 'Shortcuts', label: 'Shortcut key scheme', type: 'select', default: 'default', options: [{ value: 'default', label: 'Default' }, { value: 'vim', label: 'Vim-style' }, { value: 'emacs', label: 'Emacs-style' }] },

  // ===== Privacy & Security =====
  { id: 'payroll-privacy-mask-pay-rates', section: 'payroll', group: 'Privacy', label: 'Mask pay rates by default', type: 'toggle', default: false },
  { id: 'payroll-privacy-mask-ssn-roster', section: 'payroll', group: 'Privacy', label: 'Mask SSN in roster', type: 'toggle', default: true },
  { id: 'payroll-privacy-require-pin', section: 'payroll', group: 'Privacy', label: 'Require PIN to view compensation', type: 'toggle', default: false },
  { id: 'payroll-privacy-audit-log', section: 'payroll', group: 'Privacy', label: 'Enable change audit log', type: 'toggle', default: true },
  { id: 'payroll-privacy-restrict-export', section: 'payroll', group: 'Privacy', label: 'Restrict exports to admins', type: 'toggle', default: true },
  { id: 'payroll-privacy-session-timeout', section: 'payroll', group: 'Privacy', label: 'Auto-lock timeout (minutes)', type: 'number', default: 15, min: 1, max: 120, step: 1 },
  { id: 'payroll-privacy-watermark-exports', section: 'payroll', group: 'Privacy', label: 'Watermark exported documents', type: 'toggle', default: false },
  { id: 'payroll-privacy-hide-bank-last4', section: 'payroll', group: 'Privacy', label: 'Show only last 4 of account number', type: 'toggle', default: true },
  { id: 'payroll-privacy-blur-on-blur', section: 'payroll', group: 'Privacy', label: 'Blur sensitive fields when window inactive', type: 'toggle', default: false },
  { id: 'payroll-privacy-redact-print', section: 'payroll', group: 'Privacy', label: 'Redact SSN on printouts', type: 'toggle', default: true },

  // ===== Benefits =====
  { id: 'payroll-benefits-track-health', section: 'payroll', group: 'Benefits', label: 'Track health insurance', type: 'toggle', default: true },
  { id: 'payroll-benefits-employer-health-pct', section: 'payroll', group: 'Benefits', label: 'Employer health contribution (%)', type: 'number', default: 70, min: 0, max: 100, step: 5 },
  { id: 'payroll-benefits-track-dental', section: 'payroll', group: 'Benefits', label: 'Track dental insurance', type: 'toggle', default: false },
  { id: 'payroll-benefits-track-vision', section: 'payroll', group: 'Benefits', label: 'Track vision insurance', type: 'toggle', default: false },
  { id: 'payroll-benefits-track-life', section: 'payroll', group: 'Benefits', label: 'Track life insurance', type: 'toggle', default: false },
  { id: 'payroll-benefits-open-enrollment-month', section: 'payroll', group: 'Benefits', label: 'Open enrollment month', type: 'number', default: 11, min: 1, max: 12, step: 1 },
  { id: 'payroll-benefits-show-on-stub', section: 'payroll', group: 'Benefits', label: 'Show benefits summary on stub', type: 'toggle', default: true },
  { id: 'payroll-benefits-fsa-enabled', section: 'payroll', group: 'Benefits', label: 'Enable FSA deductions', type: 'toggle', default: false },
  { id: 'payroll-benefits-commuter-enabled', section: 'payroll', group: 'Benefits', label: 'Enable commuter benefits', type: 'toggle', default: false },
  { id: 'payroll-benefits-default-plan', section: 'payroll', group: 'Benefits', label: 'Default health plan tier', type: 'select', default: 'standard', options: [{ value: 'basic', label: 'Basic' }, { value: 'standard', label: 'Standard' }, { value: 'premium', label: 'Premium' }] },

  // ===== Reports =====
  { id: 'payroll-report-default', section: 'payroll', group: 'Reports', label: 'Default payroll report', type: 'select', default: 'register', options: [{ value: 'register', label: 'Payroll register' }, { value: 'summary', label: 'Period summary' }, { value: 'tax_liability', label: 'Tax liability' }, { value: 'labor_cost', label: 'Labor cost' }] },
  { id: 'payroll-report-period', section: 'payroll', group: 'Reports', label: 'Default report period', type: 'select', default: 'current_quarter', options: [{ value: 'current_pay', label: 'Current pay period' }, { value: 'mtd', label: 'Month-to-date' }, { value: 'current_quarter', label: 'Current quarter' }, { value: 'ytd', label: 'Year-to-date' }] },
  { id: 'payroll-report-show-charts', section: 'payroll', group: 'Reports', label: 'Show charts in reports', type: 'toggle', default: true },
  { id: 'payroll-report-group-by', section: 'payroll', group: 'Reports', label: 'Default report grouping', type: 'select', default: 'department', options: [{ value: 'none', label: 'None' }, { value: 'department', label: 'Department' }, { value: 'location', label: 'Location' }, { value: 'cost_center', label: 'Cost center' }] },
  { id: 'payroll-report-include-employer-cost', section: 'payroll', group: 'Reports', label: 'Include fully-loaded labor cost', type: 'toggle', default: true },
  { id: 'payroll-report-comparative', section: 'payroll', group: 'Reports', label: 'Show period-over-period comparison', type: 'toggle', default: false },
  { id: 'payroll-report-decimals', section: 'payroll', group: 'Reports', label: 'Report amount decimals', type: 'number', default: 2, min: 0, max: 2, step: 1 },
  { id: 'payroll-report-auto-schedule', section: 'payroll', group: 'Reports', label: 'Auto-schedule period report', type: 'toggle', default: false },
  { id: 'payroll-report-schedule-frequency', section: 'payroll', group: 'Reports', label: 'Scheduled report frequency', type: 'select', default: 'monthly', options: [{ value: 'per_run', label: 'Per pay run' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'payroll-report-include-zero', section: 'payroll', group: 'Reports', label: 'Include zero-dollar lines', type: 'toggle', default: false },

  // ===== Compliance =====
  { id: 'payroll-compliance-min-wage', section: 'payroll', group: 'Compliance', label: 'Minimum wage enforcement ($/hr)', type: 'number', default: 7.25, min: 0, max: 30, step: 0.25 },
  { id: 'payroll-compliance-warn-below-min', section: 'payroll', group: 'Compliance', label: 'Warn on sub-minimum-wage pay', type: 'toggle', default: true },
  { id: 'payroll-compliance-i9-tracking', section: 'payroll', group: 'Compliance', label: 'Track I-9 verification', type: 'toggle', default: true },
  { id: 'payroll-compliance-w4-tracking', section: 'payroll', group: 'Compliance', label: 'Track W-4 on file', type: 'toggle', default: true },
  { id: 'payroll-compliance-eeo-reporting', section: 'payroll', group: 'Compliance', label: 'Collect EEO-1 categories', type: 'toggle', default: false },
  { id: 'payroll-compliance-aca-tracking', section: 'payroll', group: 'Compliance', label: 'ACA hours tracking', type: 'toggle', default: false },
  { id: 'payroll-compliance-aca-threshold', section: 'payroll', group: 'Compliance', label: 'ACA full-time threshold (hrs/wk)', type: 'number', default: 30, min: 20, max: 40, step: 1 },
  { id: 'payroll-compliance-retention-years', section: 'payroll', group: 'Compliance', label: 'Record retention period (years)', type: 'number', default: 7, min: 1, max: 20, step: 1 },
  { id: 'payroll-compliance-newhire-reporting', section: 'payroll', group: 'Compliance', label: 'State new-hire reporting reminders', type: 'toggle', default: true },
  { id: 'payroll-compliance-sick-leave-mandate', section: 'payroll', group: 'Compliance', label: 'Enforce sick leave accrual mandate', type: 'toggle', default: false },

  // ===== Direct Deposit =====
  { id: 'payroll-dd-enabled', section: 'payroll', group: 'Direct Deposit', label: 'Enable direct deposit', type: 'toggle', default: true },
  { id: 'payroll-dd-prenote', section: 'payroll', group: 'Direct Deposit', label: 'Require prenote verification', type: 'toggle', default: true },
  { id: 'payroll-dd-prenote-days', section: 'payroll', group: 'Direct Deposit', label: 'Prenote waiting period (days)', type: 'number', default: 3, min: 0, max: 14, step: 1 },
  { id: 'payroll-dd-max-accounts', section: 'payroll', group: 'Direct Deposit', label: 'Max split accounts per employee', type: 'number', default: 3, min: 1, max: 6, step: 1 },
  { id: 'payroll-dd-allow-percentage-split', section: 'payroll', group: 'Direct Deposit', label: 'Allow percentage splits', type: 'toggle', default: true },
  { id: 'payroll-dd-lead-time-days', section: 'payroll', group: 'Direct Deposit', label: 'ACH submission lead time (days)', type: 'number', default: 2, min: 1, max: 5, step: 1 },
  { id: 'payroll-dd-verify-routing', section: 'payroll', group: 'Direct Deposit', label: 'Validate routing numbers', type: 'toggle', default: true },
  { id: 'payroll-dd-company-id', section: 'payroll', group: 'Direct Deposit', label: 'ACH company identifier', type: 'text', default: '' },
  { id: 'payroll-dd-same-day-ach', section: 'payroll', group: 'Direct Deposit', label: 'Allow same-day ACH', type: 'toggle', default: false },
  { id: 'payroll-dd-fallback-check', section: 'payroll', group: 'Direct Deposit', label: 'Fall back to paper check on failure', type: 'toggle', default: true },
];
