import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (20) =====
  { id: 'projects-default-view', section: 'projects', group: 'Display', label: 'Default view', description: 'View shown when opening Projects.', type: 'select', default: 'list', options: [{ value: 'list', label: 'List' }, { value: 'board', label: 'Kanban board' }, { value: 'gantt', label: 'Gantt chart' }, { value: 'calendar', label: 'Calendar' }, { value: 'cards', label: 'Cards' }] },
  { id: 'projects-rows-per-page', section: 'projects', group: 'Display', label: 'Rows per page', description: 'Projects listed per page.', type: 'number', default: 25, min: 5, max: 200, step: 5 },
  { id: 'projects-show-archived', section: 'projects', group: 'Display', label: 'Show archived projects', type: 'toggle', default: false },
  { id: 'projects-show-completed', section: 'projects', group: 'Display', label: 'Show completed projects', type: 'toggle', default: true },
  { id: 'projects-density', section: 'projects', group: 'Display', label: 'Row density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'projects-show-progress-bar', section: 'projects', group: 'Display', label: 'Show progress bar', description: 'Inline completion bar per project.', type: 'toggle', default: true },
  { id: 'projects-show-thumbnails', section: 'projects', group: 'Display', label: 'Show project thumbnails', type: 'toggle', default: false },
  { id: 'projects-card-size', section: 'projects', group: 'Display', label: 'Card size', type: 'select', default: 'medium', options: [{ value: 'small', label: 'Small' }, { value: 'medium', label: 'Medium' }, { value: 'large', label: 'Large' }] },
  { id: 'projects-sidebar-summary', section: 'projects', group: 'Display', label: 'Show summary sidebar', description: 'Totals and health panel beside the list.', type: 'toggle', default: true },
  { id: 'projects-show-client-avatar', section: 'projects', group: 'Display', label: 'Show client avatar', type: 'toggle', default: true },
  { id: 'projects-show-team-avatars', section: 'projects', group: 'Display', label: 'Show team member avatars', type: 'toggle', default: true },
  { id: 'projects-max-avatars', section: 'projects', group: 'Display', label: 'Max avatars shown', description: 'Overflow collapses to a +N badge.', type: 'number', default: 4, min: 1, max: 12, step: 1 },
  { id: 'projects-show-health-icon', section: 'projects', group: 'Display', label: 'Show health status icon', type: 'toggle', default: true },
  { id: 'projects-board-collapse-empty', section: 'projects', group: 'Display', label: 'Collapse empty board columns', type: 'toggle', default: false },
  { id: 'projects-gantt-zoom', section: 'projects', group: 'Display', label: 'Default Gantt zoom', type: 'select', default: 'week', options: [{ value: 'day', label: 'Day' }, { value: 'week', label: 'Week' }, { value: 'month', label: 'Month' }, { value: 'quarter', label: 'Quarter' }] },
  { id: 'projects-show-milestones-timeline', section: 'projects', group: 'Display', label: 'Show milestones on timeline', type: 'toggle', default: true },
  { id: 'projects-show-weekend-shading', section: 'projects', group: 'Display', label: 'Shade weekends in timeline', type: 'toggle', default: true },
  { id: 'projects-sticky-header', section: 'projects', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'projects-show-id-column', section: 'projects', group: 'Display', label: 'Show project ID column', type: 'toggle', default: false },
  { id: 'projects-empty-state-tips', section: 'projects', group: 'Display', label: 'Show tips on empty state', type: 'toggle', default: true },

  // ===== Columns (20) =====
  { id: 'projects-col-name', section: 'projects', group: 'Columns', label: 'Column: Project name', type: 'toggle', default: true },
  { id: 'projects-col-code', section: 'projects', group: 'Columns', label: 'Column: Project code', type: 'toggle', default: true },
  { id: 'projects-col-client', section: 'projects', group: 'Columns', label: 'Column: Client', type: 'toggle', default: true },
  { id: 'projects-col-manager', section: 'projects', group: 'Columns', label: 'Column: Project manager', type: 'toggle', default: true },
  { id: 'projects-col-status', section: 'projects', group: 'Columns', label: 'Column: Status', type: 'toggle', default: true },
  { id: 'projects-col-priority', section: 'projects', group: 'Columns', label: 'Column: Priority', type: 'toggle', default: true },
  { id: 'projects-col-start-date', section: 'projects', group: 'Columns', label: 'Column: Start date', type: 'toggle', default: true },
  { id: 'projects-col-due-date', section: 'projects', group: 'Columns', label: 'Column: Due date', type: 'toggle', default: true },
  { id: 'projects-col-budget', section: 'projects', group: 'Columns', label: 'Column: Budget', type: 'toggle', default: true },
  { id: 'projects-col-spent', section: 'projects', group: 'Columns', label: 'Column: Amount spent', type: 'toggle', default: true },
  { id: 'projects-col-remaining-budget', section: 'projects', group: 'Columns', label: 'Column: Remaining budget', type: 'toggle', default: false },
  { id: 'projects-col-billable-hours', section: 'projects', group: 'Columns', label: 'Column: Billable hours', type: 'toggle', default: false },
  { id: 'projects-col-logged-hours', section: 'projects', group: 'Columns', label: 'Column: Logged hours', type: 'toggle', default: false },
  { id: 'projects-col-progress', section: 'projects', group: 'Columns', label: 'Column: Progress %', type: 'toggle', default: true },
  { id: 'projects-col-tasks-count', section: 'projects', group: 'Columns', label: 'Column: Task count', type: 'toggle', default: false },
  { id: 'projects-col-health', section: 'projects', group: 'Columns', label: 'Column: Health', type: 'toggle', default: true },
  { id: 'projects-col-tags', section: 'projects', group: 'Columns', label: 'Column: Tags', type: 'toggle', default: false },
  { id: 'projects-col-last-activity', section: 'projects', group: 'Columns', label: 'Column: Last activity', type: 'toggle', default: false },
  { id: 'projects-col-invoiced', section: 'projects', group: 'Columns', label: 'Column: Invoiced to date', type: 'toggle', default: false },
  { id: 'projects-col-profit-margin', section: 'projects', group: 'Columns', label: 'Column: Profit margin', type: 'toggle', default: false },

  // ===== Formatting (18) =====
  { id: 'projects-currency-symbol', section: 'projects', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'projects-currency-position', section: 'projects', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'projects-decimal-places', section: 'projects', group: 'Formatting', label: 'Currency decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'projects-thousands-separator', section: 'projects', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None (1000)' }] },
  { id: 'projects-date-format', section: 'projects', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'ymd', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Mon DD, YYYY' }] },
  { id: 'projects-relative-dates', section: 'projects', group: 'Formatting', label: 'Use relative dates', description: 'Show "in 3 days" instead of a date.', type: 'toggle', default: true },
  { id: 'projects-hours-format', section: 'projects', group: 'Formatting', label: 'Time/hours format', type: 'select', default: 'decimal', options: [{ value: 'decimal', label: 'Decimal (1.5h)' }, { value: 'hm', label: 'Hours & minutes (1h 30m)' }] },
  { id: 'projects-progress-format', section: 'projects', group: 'Formatting', label: 'Progress format', type: 'select', default: 'percent', options: [{ value: 'percent', label: 'Percentage' }, { value: 'fraction', label: 'Tasks fraction' }, { value: 'both', label: 'Both' }] },
  { id: 'projects-round-budget', section: 'projects', group: 'Formatting', label: 'Round budget figures', type: 'toggle', default: false },
  { id: 'projects-abbreviate-large', section: 'projects', group: 'Formatting', label: 'Abbreviate large amounts', description: 'Show 1.2M instead of 1,200,000.', type: 'toggle', default: false },
  { id: 'projects-negative-style', section: 'projects', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-1,000' }, { value: 'parentheses', label: '(1,000)' }, { value: 'red', label: 'Red text' }] },
  { id: 'projects-name-truncate', section: 'projects', group: 'Formatting', label: 'Truncate long names', type: 'toggle', default: true },
  { id: 'projects-name-max-chars', section: 'projects', group: 'Formatting', label: 'Name truncation length', type: 'number', default: 40, min: 10, max: 120, step: 5 },
  { id: 'projects-uppercase-codes', section: 'projects', group: 'Formatting', label: 'Uppercase project codes', type: 'toggle', default: true },
  { id: 'projects-percent-decimals', section: 'projects', group: 'Formatting', label: 'Progress decimal places', type: 'number', default: 0, min: 0, max: 2, step: 1 },
  { id: 'projects-first-day-of-week', section: 'projects', group: 'Formatting', label: 'First day of week', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }, { value: 'saturday', label: 'Saturday' }] },
  { id: 'projects-time-zone-label', section: 'projects', group: 'Formatting', label: 'Show time zone on dates', type: 'toggle', default: false },
  { id: 'projects-duration-unit', section: 'projects', group: 'Formatting', label: 'Default duration unit', type: 'select', default: 'days', options: [{ value: 'hours', label: 'Hours' }, { value: 'days', label: 'Days' }, { value: 'weeks', label: 'Weeks' }] },

  // ===== Defaults (18) =====
  { id: 'projects-default-status', section: 'projects', group: 'Defaults', label: 'Default new-project status', type: 'select', default: 'planning', options: [{ value: 'planning', label: 'Planning' }, { value: 'active', label: 'Active' }, { value: 'on_hold', label: 'On hold' }, { value: 'draft', label: 'Draft' }] },
  { id: 'projects-default-priority', section: 'projects', group: 'Defaults', label: 'Default priority', type: 'select', default: 'medium', options: [{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'urgent', label: 'Urgent' }] },
  { id: 'projects-default-billing-type', section: 'projects', group: 'Defaults', label: 'Default billing type', type: 'select', default: 'hourly', options: [{ value: 'hourly', label: 'Hourly' }, { value: 'fixed', label: 'Fixed fee' }, { value: 'retainer', label: 'Retainer' }, { value: 'non_billable', label: 'Non-billable' }] },
  { id: 'projects-default-hourly-rate', section: 'projects', group: 'Defaults', label: 'Default hourly rate', type: 'number', default: 100, min: 0, max: 2000, step: 5 },
  { id: 'projects-default-budget', section: 'projects', group: 'Defaults', label: 'Default budget', type: 'number', default: 0, min: 0, max: 10000000, step: 100 },
  { id: 'projects-default-currency', section: 'projects', group: 'Defaults', label: 'Default currency', type: 'select', default: 'usd', options: [{ value: 'usd', label: 'USD' }, { value: 'eur', label: 'EUR' }, { value: 'gbp', label: 'GBP' }, { value: 'cad', label: 'CAD' }, { value: 'aud', label: 'AUD' }] },
  { id: 'projects-default-duration-days', section: 'projects', group: 'Defaults', label: 'Default project duration (days)', type: 'number', default: 30, min: 1, max: 730, step: 1 },
  { id: 'projects-default-manager-self', section: 'projects', group: 'Defaults', label: 'Assign me as manager by default', type: 'toggle', default: true },
  { id: 'projects-default-tax-rate', section: 'projects', group: 'Defaults', label: 'Default tax rate %', type: 'number', default: 0, min: 0, max: 30, step: 0.25 },
  { id: 'projects-code-prefix', section: 'projects', group: 'Defaults', label: 'Project code prefix', type: 'text', default: 'PRJ-' },
  { id: 'projects-auto-code', section: 'projects', group: 'Defaults', label: 'Auto-generate project codes', type: 'toggle', default: true },
  { id: 'projects-code-next-number', section: 'projects', group: 'Defaults', label: 'Next code sequence number', type: 'number', default: 1001, min: 1, max: 999999, step: 1 },
  { id: 'projects-default-template', section: 'projects', group: 'Defaults', label: 'Default project template', type: 'text', default: '' },
  { id: 'projects-default-visibility', section: 'projects', group: 'Defaults', label: 'Default visibility', type: 'select', default: 'team', options: [{ value: 'private', label: 'Private' }, { value: 'team', label: 'Team' }, { value: 'company', label: 'Whole company' }] },
  { id: 'projects-default-budget-alert', section: 'projects', group: 'Defaults', label: 'Default budget alert threshold %', type: 'number', default: 80, min: 50, max: 100, step: 5 },
  { id: 'projects-default-tags', section: 'projects', group: 'Defaults', label: 'Default tags', type: 'text', default: '' },
  { id: 'projects-default-expense-markup', section: 'projects', group: 'Defaults', label: 'Default expense markup %', type: 'number', default: 0, min: 0, max: 100, step: 1 },
  { id: 'projects-default-rounding-increment', section: 'projects', group: 'Defaults', label: 'Time rounding increment (min)', type: 'number', default: 15, min: 1, max: 60, step: 1 },

  // ===== Sorting & Filtering (16) =====
  { id: 'projects-default-sort-field', section: 'projects', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'due_date', options: [{ value: 'name', label: 'Name' }, { value: 'due_date', label: 'Due date' }, { value: 'start_date', label: 'Start date' }, { value: 'budget', label: 'Budget' }, { value: 'progress', label: 'Progress' }, { value: 'priority', label: 'Priority' }] },
  { id: 'projects-default-sort-dir', section: 'projects', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'projects-pin-overdue-top', section: 'projects', group: 'Sorting & Filtering', label: 'Pin overdue projects to top', type: 'toggle', default: true },
  { id: 'projects-default-status-filter', section: 'projects', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'mine', label: 'Assigned to me' }, { value: 'at_risk', label: 'At risk' }] },
  { id: 'projects-remember-filters', section: 'projects', group: 'Sorting & Filtering', label: 'Remember filters between sessions', type: 'toggle', default: true },
  { id: 'projects-filter-by-client', section: 'projects', group: 'Sorting & Filtering', label: 'Show client quick-filter', type: 'toggle', default: true },
  { id: 'projects-filter-by-manager', section: 'projects', group: 'Sorting & Filtering', label: 'Show manager quick-filter', type: 'toggle', default: true },
  { id: 'projects-filter-by-tag', section: 'projects', group: 'Sorting & Filtering', label: 'Show tag quick-filter', type: 'toggle', default: true },
  { id: 'projects-group-by', section: 'projects', group: 'Sorting & Filtering', label: 'Group projects by', type: 'select', default: 'none', options: [{ value: 'none', label: 'No grouping' }, { value: 'client', label: 'Client' }, { value: 'status', label: 'Status' }, { value: 'manager', label: 'Manager' }, { value: 'priority', label: 'Priority' }] },
  { id: 'projects-search-includes-tasks', section: 'projects', group: 'Sorting & Filtering', label: 'Search includes task names', type: 'toggle', default: false },
  { id: 'projects-search-includes-notes', section: 'projects', group: 'Sorting & Filtering', label: 'Search includes notes', type: 'toggle', default: false },
  { id: 'projects-fuzzy-search', section: 'projects', group: 'Sorting & Filtering', label: 'Enable fuzzy search', type: 'toggle', default: true },
  { id: 'projects-default-date-range', section: 'projects', group: 'Sorting & Filtering', label: 'Default date-range filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All time' }, { value: 'this_month', label: 'This month' }, { value: 'this_quarter', label: 'This quarter' }, { value: 'this_year', label: 'This year' }] },
  { id: 'projects-saved-filter-name', section: 'projects', group: 'Sorting & Filtering', label: 'Saved filter name', type: 'text', default: '' },
  { id: 'projects-secondary-sort', section: 'projects', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'name', options: [{ value: 'name', label: 'Name' }, { value: 'priority', label: 'Priority' }, { value: 'budget', label: 'Budget' }, { value: 'created', label: 'Created date' }] },
  { id: 'projects-hide-no-budget', section: 'projects', group: 'Sorting & Filtering', label: 'Hide projects without a budget', type: 'toggle', default: false },

  // ===== Behavior (18) =====
  { id: 'projects-confirm-delete', section: 'projects', group: 'Behavior', label: 'Confirm before deleting', type: 'toggle', default: true },
  { id: 'projects-confirm-archive', section: 'projects', group: 'Behavior', label: 'Confirm before archiving', type: 'toggle', default: false },
  { id: 'projects-auto-archive-completed', section: 'projects', group: 'Behavior', label: 'Auto-archive completed projects', type: 'toggle', default: false },
  { id: 'projects-auto-archive-days', section: 'projects', group: 'Behavior', label: 'Auto-archive after (days)', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'projects-auto-complete-on-tasks', section: 'projects', group: 'Behavior', label: 'Auto-complete when all tasks done', type: 'toggle', default: false },
  { id: 'projects-auto-save-edits', section: 'projects', group: 'Behavior', label: 'Auto-save inline edits', type: 'toggle', default: true },
  { id: 'projects-inline-edit', section: 'projects', group: 'Behavior', label: 'Enable inline cell editing', type: 'toggle', default: true },
  { id: 'projects-double-click-opens', section: 'projects', group: 'Behavior', label: 'Double-click row to open', type: 'toggle', default: true },
  { id: 'projects-open-in-panel', section: 'projects', group: 'Behavior', label: 'Open detail in side panel', description: 'Otherwise open full page.', type: 'toggle', default: false },
  { id: 'projects-drag-reorder', section: 'projects', group: 'Behavior', label: 'Allow drag to reorder', type: 'toggle', default: true },
  { id: 'projects-drag-status-board', section: 'projects', group: 'Behavior', label: 'Allow drag between board columns', type: 'toggle', default: true },
  { id: 'projects-warn-over-budget', section: 'projects', group: 'Behavior', label: 'Warn when logging over budget', type: 'toggle', default: true },
  { id: 'projects-block-over-budget', section: 'projects', group: 'Behavior', label: 'Block time entries over budget', type: 'toggle', default: false },
  { id: 'projects-recalc-progress-auto', section: 'projects', group: 'Behavior', label: 'Recalculate progress automatically', type: 'toggle', default: true },
  { id: 'projects-duplicate-includes-tasks', section: 'projects', group: 'Behavior', label: 'Duplicate copies tasks', type: 'toggle', default: true },
  { id: 'projects-duplicate-includes-team', section: 'projects', group: 'Behavior', label: 'Duplicate copies team members', type: 'toggle', default: false },
  { id: 'projects-autosave-interval', section: 'projects', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'projects-keep-deleted-days', section: 'projects', group: 'Behavior', label: 'Keep deleted projects (days)', type: 'number', default: 30, min: 0, max: 365, step: 1 },

  // ===== Notifications (16) =====
  { id: 'projects-notify-due-soon', section: 'projects', group: 'Notifications', label: 'Notify when due date approaches', type: 'toggle', default: true },
  { id: 'projects-due-soon-days', section: 'projects', group: 'Notifications', label: 'Due-soon lead time (days)', type: 'number', default: 3, min: 1, max: 30, step: 1 },
  { id: 'projects-notify-overdue', section: 'projects', group: 'Notifications', label: 'Notify when overdue', type: 'toggle', default: true },
  { id: 'projects-notify-milestone', section: 'projects', group: 'Notifications', label: 'Notify on milestone completion', type: 'toggle', default: true },
  { id: 'projects-notify-budget-threshold', section: 'projects', group: 'Notifications', label: 'Notify at budget threshold', type: 'toggle', default: true },
  { id: 'projects-budget-notify-percent', section: 'projects', group: 'Notifications', label: 'Budget notification threshold %', type: 'number', default: 90, min: 50, max: 100, step: 5 },
  { id: 'projects-notify-status-change', section: 'projects', group: 'Notifications', label: 'Notify on status change', type: 'toggle', default: false },
  { id: 'projects-notify-assignment', section: 'projects', group: 'Notifications', label: 'Notify when assigned to project', type: 'toggle', default: true },
  { id: 'projects-notify-comment', section: 'projects', group: 'Notifications', label: 'Notify on new comments', type: 'toggle', default: true },
  { id: 'projects-notify-at-risk', section: 'projects', group: 'Notifications', label: 'Notify when health turns at-risk', type: 'toggle', default: true },
  { id: 'projects-notify-channel', section: 'projects', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in_app', options: [{ value: 'in_app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'In-app + email' }, { value: 'none', label: 'None' }] },
  { id: 'projects-digest-frequency', section: 'projects', group: 'Notifications', label: 'Summary digest frequency', type: 'select', default: 'weekly', options: [{ value: 'off', label: 'Off' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }] },
  { id: 'projects-digest-time', section: 'projects', group: 'Notifications', label: 'Digest send time', type: 'select', default: '08:00', options: [{ value: '07:00', label: '7:00 AM' }, { value: '08:00', label: '8:00 AM' }, { value: '09:00', label: '9:00 AM' }, { value: '17:00', label: '5:00 PM' }] },
  { id: 'projects-notify-sound', section: 'projects', group: 'Notifications', label: 'Play sound on alerts', type: 'toggle', default: false },
  { id: 'projects-notify-invoice-ready', section: 'projects', group: 'Notifications', label: 'Notify when project ready to invoice', type: 'toggle', default: true },
  { id: 'projects-quiet-hours', section: 'projects', group: 'Notifications', label: 'Mute notifications outside work hours', type: 'toggle', default: false },

  // ===== Export (14) =====
  { id: 'projects-export-format', section: 'projects', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'projects-export-scope', section: 'projects', group: 'Export', label: 'Export scope', type: 'select', default: 'filtered', options: [{ value: 'all', label: 'All projects' }, { value: 'filtered', label: 'Current filter' }, { value: 'selected', label: 'Selected only' }] },
  { id: 'projects-export-include-tasks', section: 'projects', group: 'Export', label: 'Include tasks in export', type: 'toggle', default: false },
  { id: 'projects-export-include-time', section: 'projects', group: 'Export', label: 'Include time entries', type: 'toggle', default: false },
  { id: 'projects-export-include-expenses', section: 'projects', group: 'Export', label: 'Include expenses', type: 'toggle', default: false },
  { id: 'projects-export-include-notes', section: 'projects', group: 'Export', label: 'Include notes', type: 'toggle', default: false },
  { id: 'projects-export-headers', section: 'projects', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'projects-export-date-stamp', section: 'projects', group: 'Export', label: 'Append date to filename', type: 'toggle', default: true },
  { id: 'projects-export-filename', section: 'projects', group: 'Export', label: 'Export filename prefix', type: 'text', default: 'projects' },
  { id: 'projects-export-delimiter', section: 'projects', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'projects-export-pdf-orientation', section: 'projects', group: 'Export', label: 'PDF orientation', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'projects-export-pdf-logo', section: 'projects', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'projects-export-currency-code', section: 'projects', group: 'Export', label: 'Use currency codes in export', type: 'toggle', default: false },
  { id: 'projects-export-encoding', section: 'projects', group: 'Export', label: 'CSV character encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },

  // ===== Colors & Theme (16) =====
  { id: 'projects-color-status-active', section: 'projects', group: 'Colors & Theme', label: 'Active status color', type: 'color', default: '#22c55e' },
  { id: 'projects-color-status-planning', section: 'projects', group: 'Colors & Theme', label: 'Planning status color', type: 'color', default: '#3b82f6' },
  { id: 'projects-color-status-onhold', section: 'projects', group: 'Colors & Theme', label: 'On-hold status color', type: 'color', default: '#f59e0b' },
  { id: 'projects-color-status-completed', section: 'projects', group: 'Colors & Theme', label: 'Completed status color', type: 'color', default: '#6b7280' },
  { id: 'projects-color-status-cancelled', section: 'projects', group: 'Colors & Theme', label: 'Cancelled status color', type: 'color', default: '#ef4444' },
  { id: 'projects-color-priority-high', section: 'projects', group: 'Colors & Theme', label: 'High priority color', type: 'color', default: '#ef4444' },
  { id: 'projects-color-priority-medium', section: 'projects', group: 'Colors & Theme', label: 'Medium priority color', type: 'color', default: '#f59e0b' },
  { id: 'projects-color-priority-low', section: 'projects', group: 'Colors & Theme', label: 'Low priority color', type: 'color', default: '#10b981' },
  { id: 'projects-color-overdue', section: 'projects', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#dc2626' },
  { id: 'projects-color-progress-bar', section: 'projects', group: 'Colors & Theme', label: 'Progress bar color', type: 'color', default: '#3b82f6' },
  { id: 'projects-color-over-budget', section: 'projects', group: 'Colors & Theme', label: 'Over-budget color', type: 'color', default: '#dc2626' },
  { id: 'projects-color-milestone', section: 'projects', group: 'Colors & Theme', label: 'Milestone marker color', type: 'color', default: '#8b5cf6' },
  { id: 'projects-color-by', section: 'projects', group: 'Colors & Theme', label: 'Color rows by', type: 'select', default: 'status', options: [{ value: 'status', label: 'Status' }, { value: 'priority', label: 'Priority' }, { value: 'health', label: 'Health' }, { value: 'client', label: 'Client' }, { value: 'none', label: 'None' }] },
  { id: 'projects-zebra-striping', section: 'projects', group: 'Colors & Theme', label: 'Zebra row striping', type: 'toggle', default: true },
  { id: 'projects-status-as-badge', section: 'projects', group: 'Colors & Theme', label: 'Show status as colored badge', type: 'toggle', default: true },
  { id: 'projects-board-column-tint', section: 'projects', group: 'Colors & Theme', label: 'Tint board columns by status', type: 'toggle', default: true },

  // ===== Accessibility (12) =====
  { id: 'projects-high-contrast', section: 'projects', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'projects-font-scale', section: 'projects', group: 'Accessibility', label: 'Font size scale', type: 'select', default: 'normal', options: [{ value: 'small', label: 'Small' }, { value: 'normal', label: 'Normal' }, { value: 'large', label: 'Large' }, { value: 'xlarge', label: 'Extra large' }] },
  { id: 'projects-reduce-motion', section: 'projects', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'projects-color-blind-mode', section: 'projects', group: 'Accessibility', label: 'Color-blind friendly palette', type: 'toggle', default: false },
  { id: 'projects-status-text-labels', section: 'projects', group: 'Accessibility', label: 'Always show text labels on icons', type: 'toggle', default: false },
  { id: 'projects-focus-outlines', section: 'projects', group: 'Accessibility', label: 'Strong keyboard focus outlines', type: 'toggle', default: true },
  { id: 'projects-screen-reader-hints', section: 'projects', group: 'Accessibility', label: 'Extra screen-reader hints', type: 'toggle', default: false },
  { id: 'projects-underline-links', section: 'projects', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },
  { id: 'projects-min-row-height', section: 'projects', group: 'Accessibility', label: 'Minimum row height (px)', type: 'number', default: 40, min: 28, max: 72, step: 2 },
  { id: 'projects-tooltip-delay', section: 'projects', group: 'Accessibility', label: 'Tooltip delay (ms)', type: 'number', default: 500, min: 0, max: 2000, step: 50 },
  { id: 'projects-dyslexia-font', section: 'projects', group: 'Accessibility', label: 'Use dyslexia-friendly font', type: 'toggle', default: false },
  { id: 'projects-pattern-fills', section: 'projects', group: 'Accessibility', label: 'Use patterns in addition to color', type: 'toggle', default: false },

  // ===== Shortcuts (10) =====
  { id: 'projects-enable-shortcuts', section: 'projects', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'projects-shortcut-new', section: 'projects', group: 'Shortcuts', label: 'New project shortcut', type: 'text', default: 'n' },
  { id: 'projects-shortcut-search', section: 'projects', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'projects-shortcut-filter', section: 'projects', group: 'Shortcuts', label: 'Toggle filters shortcut', type: 'text', default: 'f' },
  { id: 'projects-shortcut-toggle-view', section: 'projects', group: 'Shortcuts', label: 'Switch view shortcut', type: 'text', default: 'v' },
  { id: 'projects-shortcut-archive', section: 'projects', group: 'Shortcuts', label: 'Archive selected shortcut', type: 'text', default: 'e' },
  { id: 'projects-shortcut-export', section: 'projects', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'x' },
  { id: 'projects-vim-navigation', section: 'projects', group: 'Shortcuts', label: 'Vim-style j/k navigation', type: 'toggle', default: false },
  { id: 'projects-shortcut-hints', section: 'projects', group: 'Shortcuts', label: 'Show shortcut hints in menus', type: 'toggle', default: true },
  { id: 'projects-shortcut-quick-log', section: 'projects', group: 'Shortcuts', label: 'Quick time-log shortcut', type: 'text', default: 't' },

  // ===== Privacy (12) =====
  { id: 'projects-hide-budgets', section: 'projects', group: 'Privacy', label: 'Hide budget figures', description: 'Mask amounts until clicked.', type: 'toggle', default: false },
  { id: 'projects-hide-rates', section: 'projects', group: 'Privacy', label: 'Hide hourly rates', type: 'toggle', default: false },
  { id: 'projects-hide-profit', section: 'projects', group: 'Privacy', label: 'Hide profit margins', type: 'toggle', default: false },
  { id: 'projects-mask-client-names', section: 'projects', group: 'Privacy', label: 'Mask client names', type: 'toggle', default: false },
  { id: 'projects-restrict-by-role', section: 'projects', group: 'Privacy', label: 'Restrict visibility by role', type: 'toggle', default: true },
  { id: 'projects-blur-on-idle', section: 'projects', group: 'Privacy', label: 'Blur financials when idle', type: 'toggle', default: false },
  { id: 'projects-idle-blur-minutes', section: 'projects', group: 'Privacy', label: 'Idle blur delay (minutes)', type: 'number', default: 5, min: 1, max: 60, step: 1 },
  { id: 'projects-log-access', section: 'projects', group: 'Privacy', label: 'Log project access in audit trail', type: 'toggle', default: true },
  { id: 'projects-hide-team-from-clients', section: 'projects', group: 'Privacy', label: 'Hide team details from client view', type: 'toggle', default: true },
  { id: 'projects-anonymize-export', section: 'projects', group: 'Privacy', label: 'Anonymize names in exports', type: 'toggle', default: false },
  { id: 'projects-watermark-pdf', section: 'projects', group: 'Privacy', label: 'Watermark exported PDFs', type: 'toggle', default: false },
  { id: 'projects-watermark-text', section: 'projects', group: 'Privacy', label: 'PDF watermark text', type: 'text', default: 'Confidential' },

  // ===== Billing & Invoicing (14) =====
  { id: 'projects-auto-create-invoice', section: 'projects', group: 'Billing & Invoicing', label: 'Auto-create invoice on completion', type: 'toggle', default: false },
  { id: 'projects-invoice-grouping', section: 'projects', group: 'Billing & Invoicing', label: 'Invoice line grouping', type: 'select', default: 'task', options: [{ value: 'task', label: 'By task' }, { value: 'person', label: 'By person' }, { value: 'date', label: 'By date' }, { value: 'flat', label: 'Single line' }] },
  { id: 'projects-show-rate-on-invoice', section: 'projects', group: 'Billing & Invoicing', label: 'Show rate on invoice lines', type: 'toggle', default: true },
  { id: 'projects-show-hours-on-invoice', section: 'projects', group: 'Billing & Invoicing', label: 'Show hours on invoice lines', type: 'toggle', default: true },
  { id: 'projects-bill-expenses', section: 'projects', group: 'Billing & Invoicing', label: 'Bill expenses to client by default', type: 'toggle', default: true },
  { id: 'projects-round-billable-hours', section: 'projects', group: 'Billing & Invoicing', label: 'Round billable hours up', type: 'toggle', default: false },
  { id: 'projects-min-billable-increment', section: 'projects', group: 'Billing & Invoicing', label: 'Minimum billable increment (min)', type: 'number', default: 6, min: 1, max: 60, step: 1 },
  { id: 'projects-retainer-rollover', section: 'projects', group: 'Billing & Invoicing', label: 'Roll over unused retainer hours', type: 'toggle', default: false },
  { id: 'projects-invoice-terms-days', section: 'projects', group: 'Billing & Invoicing', label: 'Default payment terms (days)', type: 'number', default: 30, min: 0, max: 120, step: 1 },
  { id: 'projects-default-discount', section: 'projects', group: 'Billing & Invoicing', label: 'Default project discount %', type: 'number', default: 0, min: 0, max: 100, step: 1 },
  { id: 'projects-invoice-prefix', section: 'projects', group: 'Billing & Invoicing', label: 'Project invoice prefix', type: 'text', default: 'INV-' },
  { id: 'projects-warn-unbilled', section: 'projects', group: 'Billing & Invoicing', label: 'Warn about unbilled time', type: 'toggle', default: true },
  { id: 'projects-unbilled-threshold', section: 'projects', group: 'Billing & Invoicing', label: 'Unbilled warning threshold (hours)', type: 'number', default: 40, min: 1, max: 500, step: 1 },
  { id: 'projects-tax-inclusive', section: 'projects', group: 'Billing & Invoicing', label: 'Treat project amounts as tax-inclusive', type: 'toggle', default: false },
];
