import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display =====
  { id: 'po-display-density', section: 'purchase-orders', group: 'Display', label: 'Row density', description: 'Spacing of rows in the PO list', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'po-display-page-size', section: 'purchase-orders', group: 'Display', label: 'Purchase orders per page', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'po-display-show-thumbnails', section: 'purchase-orders', group: 'Display', label: 'Show vendor logo thumbnails', type: 'toggle', default: false },
  { id: 'po-display-zebra-striping', section: 'purchase-orders', group: 'Display', label: 'Alternate row shading', type: 'toggle', default: true },
  { id: 'po-display-sticky-header', section: 'purchase-orders', group: 'Display', label: 'Sticky table header on scroll', type: 'toggle', default: true },
  { id: 'po-display-show-line-count', section: 'purchase-orders', group: 'Display', label: 'Show line-item count badge', type: 'toggle', default: true },
  { id: 'po-display-default-view', section: 'purchase-orders', group: 'Display', label: 'Default view mode', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'kanban', label: 'Kanban' }] },
  { id: 'po-display-show-vendor-rating', section: 'purchase-orders', group: 'Display', label: 'Show vendor rating stars', type: 'toggle', default: false },
  { id: 'po-display-highlight-overdue', section: 'purchase-orders', group: 'Display', label: 'Highlight overdue deliveries', type: 'toggle', default: true },
  { id: 'po-display-collapse-fulfilled', section: 'purchase-orders', group: 'Display', label: 'Collapse fully-received POs', type: 'toggle', default: false },
  { id: 'po-display-show-progress-bar', section: 'purchase-orders', group: 'Display', label: 'Show receipt progress bar', type: 'toggle', default: true },
  { id: 'po-display-preview-pane', section: 'purchase-orders', group: 'Display', label: 'Show side preview pane', type: 'toggle', default: false },
  { id: 'po-display-row-height', section: 'purchase-orders', group: 'Display', label: 'Row height (px)', type: 'number', default: 40, min: 28, max: 80, step: 2 },
  { id: 'po-display-truncate-notes', section: 'purchase-orders', group: 'Display', label: 'Truncate long notes', type: 'toggle', default: true },
  { id: 'po-display-show-empty-state-hint', section: 'purchase-orders', group: 'Display', label: 'Show getting-started hint when empty', type: 'toggle', default: true },
  { id: 'po-display-show-attachment-icon', section: 'purchase-orders', group: 'Display', label: 'Show attachment paperclip icon', type: 'toggle', default: true },
  { id: 'po-display-vendor-name-style', section: 'purchase-orders', group: 'Display', label: 'Vendor name emphasis', type: 'select', default: 'bold', options: [{ value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' }, { value: 'uppercase', label: 'Uppercase' }] },

  // ===== Columns =====
  { id: 'po-col-number', section: 'purchase-orders', group: 'Columns', label: 'Show PO number column', type: 'toggle', default: true },
  { id: 'po-col-vendor', section: 'purchase-orders', group: 'Columns', label: 'Show vendor column', type: 'toggle', default: true },
  { id: 'po-col-order-date', section: 'purchase-orders', group: 'Columns', label: 'Show order date column', type: 'toggle', default: true },
  { id: 'po-col-expected-date', section: 'purchase-orders', group: 'Columns', label: 'Show expected delivery column', type: 'toggle', default: true },
  { id: 'po-col-status', section: 'purchase-orders', group: 'Columns', label: 'Show status column', type: 'toggle', default: true },
  { id: 'po-col-total', section: 'purchase-orders', group: 'Columns', label: 'Show total amount column', type: 'toggle', default: true },
  { id: 'po-col-subtotal', section: 'purchase-orders', group: 'Columns', label: 'Show subtotal column', type: 'toggle', default: false },
  { id: 'po-col-tax', section: 'purchase-orders', group: 'Columns', label: 'Show tax column', type: 'toggle', default: false },
  { id: 'po-col-shipping', section: 'purchase-orders', group: 'Columns', label: 'Show shipping cost column', type: 'toggle', default: false },
  { id: 'po-col-received-qty', section: 'purchase-orders', group: 'Columns', label: 'Show received quantity column', type: 'toggle', default: true },
  { id: 'po-col-outstanding', section: 'purchase-orders', group: 'Columns', label: 'Show outstanding balance column', type: 'toggle', default: true },
  { id: 'po-col-currency', section: 'purchase-orders', group: 'Columns', label: 'Show currency column', type: 'toggle', default: false },
  { id: 'po-col-buyer', section: 'purchase-orders', group: 'Columns', label: 'Show buyer/requester column', type: 'toggle', default: false },
  { id: 'po-col-department', section: 'purchase-orders', group: 'Columns', label: 'Show department column', type: 'toggle', default: false },
  { id: 'po-col-project', section: 'purchase-orders', group: 'Columns', label: 'Show project/job column', type: 'toggle', default: false },
  { id: 'po-col-payment-terms', section: 'purchase-orders', group: 'Columns', label: 'Show payment terms column', type: 'toggle', default: false },
  { id: 'po-col-ship-to', section: 'purchase-orders', group: 'Columns', label: 'Show ship-to location column', type: 'toggle', default: false },
  { id: 'po-col-approval-status', section: 'purchase-orders', group: 'Columns', label: 'Show approval status column', type: 'toggle', default: true },
  { id: 'po-col-created-by', section: 'purchase-orders', group: 'Columns', label: 'Show created-by column', type: 'toggle', default: false },
  { id: 'po-col-last-modified', section: 'purchase-orders', group: 'Columns', label: 'Show last-modified column', type: 'toggle', default: false },
  { id: 'po-col-bill-matched', section: 'purchase-orders', group: 'Columns', label: 'Show bill-matched indicator', type: 'toggle', default: true },
  { id: 'po-col-reference', section: 'purchase-orders', group: 'Columns', label: 'Show external reference column', type: 'toggle', default: false },
  { id: 'po-col-order', section: 'purchase-orders', group: 'Columns', label: 'Pinned column order', type: 'select', default: 'number-first', options: [{ value: 'number-first', label: 'PO number first' }, { value: 'vendor-first', label: 'Vendor first' }, { value: 'date-first', label: 'Date first' }] },

  // ===== Formatting =====
  { id: 'po-fmt-date-format', section: 'purchase-orders', group: 'Formatting', label: 'Date format', type: 'select', default: 'MM/DD/YYYY', options: [{ value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' }, { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' }, { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' }, { value: 'MMM D, YYYY', label: 'MMM D, YYYY' }] },
  { id: 'po-fmt-currency-symbol', section: 'purchase-orders', group: 'Formatting', label: 'Currency symbol', type: 'select', default: '$', options: [{ value: '$', label: '$ Dollar' }, { value: '€', label: '€ Euro' }, { value: '£', label: '£ Pound' }, { value: '¥', label: '¥ Yen' }] },
  { id: 'po-fmt-decimal-places', section: 'purchase-orders', group: 'Formatting', label: 'Amount decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'po-fmt-thousands-separator', section: 'purchase-orders', group: 'Formatting', label: 'Use thousands separator', type: 'toggle', default: true },
  { id: 'po-fmt-negative-style', section: 'purchase-orders', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-100.00' }, { value: 'parentheses', label: '(100.00)' }, { value: 'red', label: 'Red text' }] },
  { id: 'po-fmt-quantity-decimals', section: 'purchase-orders', group: 'Formatting', label: 'Quantity decimal places', type: 'number', default: 0, min: 0, max: 4, step: 1 },
  { id: 'po-fmt-number-prefix', section: 'purchase-orders', group: 'Formatting', label: 'PO number prefix', type: 'text', default: 'PO-' },
  { id: 'po-fmt-number-padding', section: 'purchase-orders', group: 'Formatting', label: 'PO number digit padding', type: 'number', default: 5, min: 1, max: 10, step: 1 },
  { id: 'po-fmt-relative-dates', section: 'purchase-orders', group: 'Formatting', label: 'Show relative dates (in 3 days)', type: 'toggle', default: false },
  { id: 'po-fmt-currency-position', section: 'purchase-orders', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before amount' }, { value: 'after', label: 'After amount' }] },
  { id: 'po-fmt-status-label-case', section: 'purchase-orders', group: 'Formatting', label: 'Status label casing', type: 'select', default: 'title', options: [{ value: 'title', label: 'Title Case' }, { value: 'upper', label: 'UPPERCASE' }, { value: 'lower', label: 'lowercase' }] },
  { id: 'po-fmt-show-cents-trailing-zero', section: 'purchase-orders', group: 'Formatting', label: 'Always show trailing zero cents', type: 'toggle', default: true },
  { id: 'po-fmt-weekend-marker', section: 'purchase-orders', group: 'Formatting', label: 'Mark weekend delivery dates', type: 'toggle', default: false },
  { id: 'po-fmt-uom-display', section: 'purchase-orders', group: 'Formatting', label: 'Unit of measure display', type: 'select', default: 'abbrev', options: [{ value: 'abbrev', label: 'Abbreviated (ea, kg)' }, { value: 'full', label: 'Full (each, kilogram)' }] },

  // ===== Defaults =====
  { id: 'po-def-payment-terms', section: 'purchase-orders', group: 'Defaults', label: 'Default payment terms', type: 'select', default: 'net30', options: [{ value: 'due', label: 'Due on receipt' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net60', label: 'Net 60' }] },
  { id: 'po-def-tax-rate', section: 'purchase-orders', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 30, step: 0.1 },
  { id: 'po-def-currency', section: 'purchase-orders', group: 'Defaults', label: 'Default currency', type: 'text', default: 'USD' },
  { id: 'po-def-shipping-method', section: 'purchase-orders', group: 'Defaults', label: 'Default shipping method', type: 'select', default: 'ground', options: [{ value: 'ground', label: 'Ground' }, { value: 'air', label: 'Air' }, { value: 'freight', label: 'Freight' }, { value: 'pickup', label: 'Pickup' }] },
  { id: 'po-def-lead-time-days', section: 'purchase-orders', group: 'Defaults', label: 'Default lead time (days)', type: 'number', default: 7, min: 0, max: 180, step: 1 },
  { id: 'po-def-ship-to', section: 'purchase-orders', group: 'Defaults', label: 'Default ship-to location', type: 'text', default: 'Main Warehouse' },
  { id: 'po-def-line-tax-inclusive', section: 'purchase-orders', group: 'Defaults', label: 'Line prices include tax by default', type: 'toggle', default: false },
  { id: 'po-def-auto-number', section: 'purchase-orders', group: 'Defaults', label: 'Auto-generate PO numbers', type: 'toggle', default: true },
  { id: 'po-def-next-number', section: 'purchase-orders', group: 'Defaults', label: 'Next PO number', type: 'number', default: 1001, min: 1, max: 9999999, step: 1 },
  { id: 'po-def-terms-text', section: 'purchase-orders', group: 'Defaults', label: 'Default terms & conditions text', type: 'text', default: 'Goods subject to inspection upon receipt.' },
  { id: 'po-def-footer-note', section: 'purchase-orders', group: 'Defaults', label: 'Default footer note', type: 'text', default: 'Thank you for your business.' },
  { id: 'po-def-buyer', section: 'purchase-orders', group: 'Defaults', label: 'Default buyer name', type: 'text', default: '' },
  { id: 'po-def-expected-date-offset', section: 'purchase-orders', group: 'Defaults', label: 'Default expected-date offset (days)', type: 'number', default: 14, min: 0, max: 365, step: 1 },
  { id: 'po-def-copy-last-vendor', section: 'purchase-orders', group: 'Defaults', label: 'Pre-fill last used vendor', type: 'toggle', default: false },
  { id: 'po-def-account', section: 'purchase-orders', group: 'Defaults', label: 'Default expense account', type: 'text', default: 'Cost of Goods Sold' },
  { id: 'po-def-discount-mode', section: 'purchase-orders', group: 'Defaults', label: 'Default discount mode', type: 'select', default: 'percent', options: [{ value: 'percent', label: 'Percentage' }, { value: 'amount', label: 'Fixed amount' }, { value: 'none', label: 'No discount' }] },

  // ===== Sorting & Filtering =====
  { id: 'po-sort-default-field', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'order-date', options: [{ value: 'po-number', label: 'PO number' }, { value: 'order-date', label: 'Order date' }, { value: 'expected-date', label: 'Expected date' }, { value: 'vendor', label: 'Vendor' }, { value: 'total', label: 'Total' }] },
  { id: 'po-sort-default-direction', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'po-filter-default-status', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'open', options: [{ value: 'all', label: 'All' }, { value: 'open', label: 'Open' }, { value: 'draft', label: 'Draft' }, { value: 'received', label: 'Received' }, { value: 'closed', label: 'Closed' }] },
  { id: 'po-filter-date-range', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'last-90', options: [{ value: 'last-30', label: 'Last 30 days' }, { value: 'last-90', label: 'Last 90 days' }, { value: 'ytd', label: 'Year to date' }, { value: 'all', label: 'All time' }] },
  { id: 'po-filter-remember', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'po-filter-hide-closed', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Hide closed POs by default', type: 'toggle', default: true },
  { id: 'po-filter-hide-cancelled', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Hide cancelled POs by default', type: 'toggle', default: true },
  { id: 'po-filter-quick-vendor', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Show quick vendor filter chips', type: 'toggle', default: true },
  { id: 'po-filter-min-amount', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default minimum amount filter', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'po-filter-secondary-sort', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'vendor', options: [{ value: 'vendor', label: 'Vendor' }, { value: 'total', label: 'Total' }, { value: 'status', label: 'Status' }, { value: 'none', label: 'None' }] },
  { id: 'po-filter-search-includes-lines', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Search includes line-item text', type: 'toggle', default: true },
  { id: 'po-filter-show-saved-views', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Show saved filter views', type: 'toggle', default: true },
  { id: 'po-filter-group-by', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Default grouping', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'vendor', label: 'Vendor' }, { value: 'status', label: 'Status' }, { value: 'month', label: 'Month' }] },
  { id: 'po-filter-pin-overdue-top', section: 'purchase-orders', group: 'Sorting & Filtering', label: 'Pin overdue POs to top', type: 'toggle', default: false },

  // ===== Behavior =====
  { id: 'po-beh-confirm-delete', section: 'purchase-orders', group: 'Behavior', label: 'Confirm before deleting PO', type: 'toggle', default: true },
  { id: 'po-beh-confirm-cancel', section: 'purchase-orders', group: 'Behavior', label: 'Confirm before cancelling PO', type: 'toggle', default: true },
  { id: 'po-beh-autosave-draft', section: 'purchase-orders', group: 'Behavior', label: 'Auto-save drafts while editing', type: 'toggle', default: true },
  { id: 'po-beh-autosave-interval', section: 'purchase-orders', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'po-beh-lock-after-send', section: 'purchase-orders', group: 'Behavior', label: 'Lock PO after sending to vendor', type: 'toggle', default: true },
  { id: 'po-beh-allow-edit-received', section: 'purchase-orders', group: 'Behavior', label: 'Allow editing partially-received POs', type: 'toggle', default: false },
  { id: 'po-beh-auto-close-on-receipt', section: 'purchase-orders', group: 'Behavior', label: 'Auto-close PO when fully received', type: 'toggle', default: true },
  { id: 'po-beh-duplicate-includes-lines', section: 'purchase-orders', group: 'Behavior', label: 'Duplicate copies line items', type: 'toggle', default: true },
  { id: 'po-beh-convert-to-bill', section: 'purchase-orders', group: 'Behavior', label: 'Enable convert-to-bill action', type: 'toggle', default: true },
  { id: 'po-beh-auto-create-bill-on-receipt', section: 'purchase-orders', group: 'Behavior', label: 'Auto-create bill on full receipt', type: 'toggle', default: false },
  { id: 'po-beh-default-new-action', section: 'purchase-orders', group: 'Behavior', label: 'Action after creating PO', type: 'select', default: 'view', options: [{ value: 'view', label: 'View PO' }, { value: 'new', label: 'Start another' }, { value: 'list', label: 'Return to list' }] },
  { id: 'po-beh-tab-on-enter', section: 'purchase-orders', group: 'Behavior', label: 'Enter key adds new line', type: 'toggle', default: true },
  { id: 'po-beh-warn-over-budget', section: 'purchase-orders', group: 'Behavior', label: 'Warn when PO exceeds budget', type: 'toggle', default: true },
  { id: 'po-beh-warn-duplicate-vendor', section: 'purchase-orders', group: 'Behavior', label: 'Warn on duplicate open PO to vendor', type: 'toggle', default: false },
  { id: 'po-beh-require-expected-date', section: 'purchase-orders', group: 'Behavior', label: 'Require expected delivery date', type: 'toggle', default: false },
  { id: 'po-beh-require-vendor', section: 'purchase-orders', group: 'Behavior', label: 'Require vendor before saving', type: 'toggle', default: true },
  { id: 'po-beh-allow-negative-qty', section: 'purchase-orders', group: 'Behavior', label: 'Allow negative line quantities', type: 'toggle', default: false },
  { id: 'po-beh-recalc-on-blur', section: 'purchase-orders', group: 'Behavior', label: 'Recalculate totals on field blur', type: 'toggle', default: true },
  { id: 'po-beh-keep-draft-on-close', section: 'purchase-orders', group: 'Behavior', label: 'Keep draft when closing without saving', type: 'toggle', default: true },
  { id: 'po-beh-default-receive-full', section: 'purchase-orders', group: 'Behavior', label: 'Pre-fill full quantity when receiving', type: 'toggle', default: true },

  // ===== Approvals =====
  { id: 'po-appr-require-approval', section: 'purchase-orders', group: 'Approvals', label: 'Require approval before sending', type: 'toggle', default: false },
  { id: 'po-appr-threshold', section: 'purchase-orders', group: 'Approvals', label: 'Approval required above amount', type: 'number', default: 5000, min: 0, max: 1000000, step: 500 },
  { id: 'po-appr-levels', section: 'purchase-orders', group: 'Approvals', label: 'Number of approval levels', type: 'number', default: 1, min: 1, max: 5, step: 1 },
  { id: 'po-appr-self-approve', section: 'purchase-orders', group: 'Approvals', label: 'Allow self-approval', type: 'toggle', default: false },
  { id: 'po-appr-notify-approver', section: 'purchase-orders', group: 'Approvals', label: 'Notify approver on submission', type: 'toggle', default: true },
  { id: 'po-appr-auto-approve-under', section: 'purchase-orders', group: 'Approvals', label: 'Auto-approve under amount', type: 'number', default: 500, min: 0, max: 100000, step: 100 },
  { id: 'po-appr-show-history', section: 'purchase-orders', group: 'Approvals', label: 'Show approval history trail', type: 'toggle', default: true },
  { id: 'po-appr-reminder-days', section: 'purchase-orders', group: 'Approvals', label: 'Pending-approval reminder (days)', type: 'number', default: 2, min: 1, max: 30, step: 1 },
  { id: 'po-appr-require-comment-reject', section: 'purchase-orders', group: 'Approvals', label: 'Require comment on rejection', type: 'toggle', default: true },
  { id: 'po-appr-delegate', section: 'purchase-orders', group: 'Approvals', label: 'Allow delegated approvers', type: 'toggle', default: false },
  { id: 'po-appr-escalate-after-days', section: 'purchase-orders', group: 'Approvals', label: 'Escalate after (days)', type: 'number', default: 5, min: 1, max: 60, step: 1 },

  // ===== Receiving =====
  { id: 'po-recv-allow-partial', section: 'purchase-orders', group: 'Receiving', label: 'Allow partial receipts', type: 'toggle', default: true },
  { id: 'po-recv-allow-over-receipt', section: 'purchase-orders', group: 'Receiving', label: 'Allow over-receipt of quantities', type: 'toggle', default: false },
  { id: 'po-recv-over-tolerance', section: 'purchase-orders', group: 'Receiving', label: 'Over-receipt tolerance (%)', type: 'number', default: 0, min: 0, max: 50, step: 1 },
  { id: 'po-recv-require-receipt-date', section: 'purchase-orders', group: 'Receiving', label: 'Require receipt date', type: 'toggle', default: true },
  { id: 'po-recv-track-lot', section: 'purchase-orders', group: 'Receiving', label: 'Track lot/batch numbers', type: 'toggle', default: false },
  { id: 'po-recv-track-serial', section: 'purchase-orders', group: 'Receiving', label: 'Track serial numbers', type: 'toggle', default: false },
  { id: 'po-recv-require-inspection', section: 'purchase-orders', group: 'Receiving', label: 'Require inspection step', type: 'toggle', default: false },
  { id: 'po-recv-update-inventory', section: 'purchase-orders', group: 'Receiving', label: 'Update inventory on receipt', type: 'toggle', default: true },
  { id: 'po-recv-default-warehouse', section: 'purchase-orders', group: 'Receiving', label: 'Default receiving warehouse', type: 'text', default: 'Main Warehouse' },
  { id: 'po-recv-print-label', section: 'purchase-orders', group: 'Receiving', label: 'Auto-print receiving label', type: 'toggle', default: false },
  { id: 'po-recv-capture-damage', section: 'purchase-orders', group: 'Receiving', label: 'Capture damaged/rejected quantity', type: 'toggle', default: true },
  { id: 'po-recv-photo-required', section: 'purchase-orders', group: 'Receiving', label: 'Require photo on receipt', type: 'toggle', default: false },
  { id: 'po-recv-three-way-match', section: 'purchase-orders', group: 'Receiving', label: 'Enforce three-way match', type: 'toggle', default: false },

  // ===== Notifications =====
  { id: 'po-notif-vendor-confirm', section: 'purchase-orders', group: 'Notifications', label: 'Notify on vendor confirmation', type: 'toggle', default: true },
  { id: 'po-notif-overdue-delivery', section: 'purchase-orders', group: 'Notifications', label: 'Alert on overdue delivery', type: 'toggle', default: true },
  { id: 'po-notif-overdue-lead-days', section: 'purchase-orders', group: 'Notifications', label: 'Overdue alert lead time (days)', type: 'number', default: 1, min: 0, max: 30, step: 1 },
  { id: 'po-notif-approval-pending', section: 'purchase-orders', group: 'Notifications', label: 'Notify when approval pending', type: 'toggle', default: true },
  { id: 'po-notif-received', section: 'purchase-orders', group: 'Notifications', label: 'Notify when PO received', type: 'toggle', default: false },
  { id: 'po-notif-partial-received', section: 'purchase-orders', group: 'Notifications', label: 'Notify on partial receipt', type: 'toggle', default: false },
  { id: 'po-notif-budget-exceeded', section: 'purchase-orders', group: 'Notifications', label: 'Notify when budget exceeded', type: 'toggle', default: true },
  { id: 'po-notif-channel', section: 'purchase-orders', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'po-notif-digest', section: 'purchase-orders', group: 'Notifications', label: 'Daily PO digest email', type: 'toggle', default: false },
  { id: 'po-notif-digest-time', section: 'purchase-orders', group: 'Notifications', label: 'Digest send time (hour)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'po-notif-price-change', section: 'purchase-orders', group: 'Notifications', label: 'Alert on vendor price change', type: 'toggle', default: false },
  { id: 'po-notif-sound', section: 'purchase-orders', group: 'Notifications', label: 'Play sound on new alert', type: 'toggle', default: false },
  { id: 'po-notif-bill-mismatch', section: 'purchase-orders', group: 'Notifications', label: 'Alert on bill/PO amount mismatch', type: 'toggle', default: true },

  // ===== Export =====
  { id: 'po-exp-default-format', section: 'purchase-orders', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [{ value: 'pdf', label: 'PDF' }, { value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'json', label: 'JSON' }] },
  { id: 'po-exp-include-line-items', section: 'purchase-orders', group: 'Export', label: 'Include line items in export', type: 'toggle', default: true },
  { id: 'po-exp-include-notes', section: 'purchase-orders', group: 'Export', label: 'Include notes in export', type: 'toggle', default: true },
  { id: 'po-exp-include-attachments', section: 'purchase-orders', group: 'Export', label: 'Bundle attachments in export', type: 'toggle', default: false },
  { id: 'po-exp-filename-pattern', section: 'purchase-orders', group: 'Export', label: 'Export filename pattern', type: 'text', default: 'PO-{number}-{vendor}' },
  { id: 'po-exp-csv-delimiter', section: 'purchase-orders', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'po-exp-pdf-paper-size', section: 'purchase-orders', group: 'Export', label: 'PDF paper size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'po-exp-pdf-logo', section: 'purchase-orders', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'po-exp-pdf-show-terms', section: 'purchase-orders', group: 'Export', label: 'Print terms & conditions on PDF', type: 'toggle', default: true },
  { id: 'po-exp-pdf-show-tax-breakdown', section: 'purchase-orders', group: 'Export', label: 'Show tax breakdown on PDF', type: 'toggle', default: true },
  { id: 'po-exp-include-history', section: 'purchase-orders', group: 'Export', label: 'Include status history in export', type: 'toggle', default: false },
  { id: 'po-exp-currency-column', section: 'purchase-orders', group: 'Export', label: 'Add currency column to CSV', type: 'toggle', default: true },
  { id: 'po-exp-watermark-draft', section: 'purchase-orders', group: 'Export', label: 'Watermark drafts on PDF', type: 'toggle', default: true },
  { id: 'po-exp-page-orientation', section: 'purchase-orders', group: 'Export', label: 'PDF orientation', type: 'select', default: 'portrait', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },

  // ===== Email & Vendor =====
  { id: 'po-email-default-subject', section: 'purchase-orders', group: 'Email & Vendor', label: 'Default email subject', type: 'text', default: 'Purchase Order {number} from {company}' },
  { id: 'po-email-default-body', section: 'purchase-orders', group: 'Email & Vendor', label: 'Default email body', type: 'text', default: 'Please find attached our purchase order. Kindly confirm receipt.' },
  { id: 'po-email-attach-pdf', section: 'purchase-orders', group: 'Email & Vendor', label: 'Attach PDF to vendor email', type: 'toggle', default: true },
  { id: 'po-email-cc-self', section: 'purchase-orders', group: 'Email & Vendor', label: 'CC myself on vendor emails', type: 'toggle', default: true },
  { id: 'po-email-cc-address', section: 'purchase-orders', group: 'Email & Vendor', label: 'Additional CC address', type: 'text', default: '' },
  { id: 'po-email-request-confirmation', section: 'purchase-orders', group: 'Email & Vendor', label: 'Request read confirmation', type: 'toggle', default: false },
  { id: 'po-email-reply-to', section: 'purchase-orders', group: 'Email & Vendor', label: 'Reply-to address', type: 'text', default: '' },
  { id: 'po-email-signature', section: 'purchase-orders', group: 'Email & Vendor', label: 'Email signature', type: 'text', default: 'Purchasing Department' },
  { id: 'po-email-auto-send-on-approve', section: 'purchase-orders', group: 'Email & Vendor', label: 'Auto-send to vendor on approval', type: 'toggle', default: false },
  { id: 'po-email-resend-reminder-days', section: 'purchase-orders', group: 'Email & Vendor', label: 'Resend if no confirm after (days)', type: 'number', default: 3, min: 1, max: 30, step: 1 },
  { id: 'po-email-portal-link', section: 'purchase-orders', group: 'Email & Vendor', label: 'Include vendor portal link', type: 'toggle', default: false },

  // ===== Colors & Theme =====
  { id: 'po-color-status-draft', section: 'purchase-orders', group: 'Colors & Theme', label: 'Draft status color', type: 'color', default: '#94a3b8' },
  { id: 'po-color-status-open', section: 'purchase-orders', group: 'Colors & Theme', label: 'Open status color', type: 'color', default: '#3b82f6' },
  { id: 'po-color-status-partial', section: 'purchase-orders', group: 'Colors & Theme', label: 'Partially-received status color', type: 'color', default: '#f59e0b' },
  { id: 'po-color-status-received', section: 'purchase-orders', group: 'Colors & Theme', label: 'Received status color', type: 'color', default: '#10b981' },
  { id: 'po-color-status-closed', section: 'purchase-orders', group: 'Colors & Theme', label: 'Closed status color', type: 'color', default: '#6b7280' },
  { id: 'po-color-status-cancelled', section: 'purchase-orders', group: 'Colors & Theme', label: 'Cancelled status color', type: 'color', default: '#ef4444' },
  { id: 'po-color-overdue', section: 'purchase-orders', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#dc2626' },
  { id: 'po-color-approved', section: 'purchase-orders', group: 'Colors & Theme', label: 'Approved badge color', type: 'color', default: '#22c55e' },
  { id: 'po-color-pending-approval', section: 'purchase-orders', group: 'Colors & Theme', label: 'Pending-approval badge color', type: 'color', default: '#eab308' },
  { id: 'po-color-progress-bar', section: 'purchase-orders', group: 'Colors & Theme', label: 'Receipt progress bar color', type: 'color', default: '#0ea5e9' },
  { id: 'po-color-row-hover', section: 'purchase-orders', group: 'Colors & Theme', label: 'Row hover highlight color', type: 'color', default: '#1e293b' },
  { id: 'po-color-total-emphasis', section: 'purchase-orders', group: 'Colors & Theme', label: 'Total amount emphasis color', type: 'color', default: '#f8fafc' },
  { id: 'po-color-pdf-accent', section: 'purchase-orders', group: 'Colors & Theme', label: 'PDF accent color', type: 'color', default: '#2563eb' },
  { id: 'po-color-badge-style', section: 'purchase-orders', group: 'Colors & Theme', label: 'Status badge style', type: 'select', default: 'filled', options: [{ value: 'filled', label: 'Filled' }, { value: 'outline', label: 'Outline' }, { value: 'dot', label: 'Dot' }] },

  // ===== Accessibility =====
  { id: 'po-a11y-high-contrast', section: 'purchase-orders', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'po-a11y-font-scale', section: 'purchase-orders', group: 'Accessibility', label: 'Font size scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'po-a11y-status-icons', section: 'purchase-orders', group: 'Accessibility', label: 'Show status as icon + text', type: 'toggle', default: true },
  { id: 'po-a11y-reduce-motion', section: 'purchase-orders', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },
  { id: 'po-a11y-focus-outline', section: 'purchase-orders', group: 'Accessibility', label: 'Always show focus outline', type: 'toggle', default: true },
  { id: 'po-a11y-colorblind-palette', section: 'purchase-orders', group: 'Accessibility', label: 'Colorblind-safe status palette', type: 'toggle', default: false },
  { id: 'po-a11y-screen-reader-totals', section: 'purchase-orders', group: 'Accessibility', label: 'Announce totals to screen reader', type: 'toggle', default: true },
  { id: 'po-a11y-underline-links', section: 'purchase-orders', group: 'Accessibility', label: 'Underline links', type: 'toggle', default: true },
  { id: 'po-a11y-keyboard-row-nav', section: 'purchase-orders', group: 'Accessibility', label: 'Arrow-key row navigation', type: 'toggle', default: true },
  { id: 'po-a11y-tooltip-delay', section: 'purchase-orders', group: 'Accessibility', label: 'Tooltip delay (ms)', type: 'number', default: 400, min: 0, max: 2000, step: 50 },

  // ===== Shortcuts =====
  { id: 'po-sc-new', section: 'purchase-orders', group: 'Shortcuts', label: 'New PO shortcut', type: 'text', default: 'Ctrl+N' },
  { id: 'po-sc-save', section: 'purchase-orders', group: 'Shortcuts', label: 'Save PO shortcut', type: 'text', default: 'Ctrl+S' },
  { id: 'po-sc-send', section: 'purchase-orders', group: 'Shortcuts', label: 'Send to vendor shortcut', type: 'text', default: 'Ctrl+Enter' },
  { id: 'po-sc-duplicate', section: 'purchase-orders', group: 'Shortcuts', label: 'Duplicate PO shortcut', type: 'text', default: 'Ctrl+D' },
  { id: 'po-sc-receive', section: 'purchase-orders', group: 'Shortcuts', label: 'Receive items shortcut', type: 'text', default: 'Ctrl+R' },
  { id: 'po-sc-add-line', section: 'purchase-orders', group: 'Shortcuts', label: 'Add line item shortcut', type: 'text', default: 'Ctrl+L' },
  { id: 'po-sc-search', section: 'purchase-orders', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'po-sc-print', section: 'purchase-orders', group: 'Shortcuts', label: 'Print PO shortcut', type: 'text', default: 'Ctrl+P' },
  { id: 'po-sc-enable', section: 'purchase-orders', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'po-sc-next-po', section: 'purchase-orders', group: 'Shortcuts', label: 'Next PO shortcut', type: 'text', default: 'J' },
  { id: 'po-sc-prev-po', section: 'purchase-orders', group: 'Shortcuts', label: 'Previous PO shortcut', type: 'text', default: 'K' },
  { id: 'po-sc-approve', section: 'purchase-orders', group: 'Shortcuts', label: 'Approve PO shortcut', type: 'text', default: 'Ctrl+Shift+A' },

  // ===== Privacy & Audit =====
  { id: 'po-priv-audit-log', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Keep audit log of changes', type: 'toggle', default: true },
  { id: 'po-priv-audit-retention-days', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Audit log retention (days)', type: 'number', default: 365, min: 30, max: 3650, step: 30 },
  { id: 'po-priv-mask-amounts', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Mask amounts for restricted users', type: 'toggle', default: false },
  { id: 'po-priv-hide-vendor-bank', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Hide vendor bank details', type: 'toggle', default: true },
  { id: 'po-priv-redact-export', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Redact sensitive fields on export', type: 'toggle', default: false },
  { id: 'po-priv-require-reason-edit', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Require reason for post-send edits', type: 'toggle', default: false },
  { id: 'po-priv-watermark-user', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Watermark PDFs with viewer name', type: 'toggle', default: false },
  { id: 'po-priv-restrict-delete-role', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Restrict delete to admins', type: 'toggle', default: true },
  { id: 'po-priv-log-views', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Log PO view events', type: 'toggle', default: false },
  { id: 'po-priv-data-region', section: 'purchase-orders', group: 'Privacy & Audit', label: 'Preferred data region', type: 'select', default: 'us', options: [{ value: 'us', label: 'United States' }, { value: 'eu', label: 'European Union' }, { value: 'apac', label: 'Asia-Pacific' }] },

  // ===== Integrations =====
  { id: 'po-int-sync-inventory', section: 'purchase-orders', group: 'Integrations', label: 'Sync with inventory module', type: 'toggle', default: true },
  { id: 'po-int-sync-accounting', section: 'purchase-orders', group: 'Integrations', label: 'Post commitments to accounting', type: 'toggle', default: false },
  { id: 'po-int-quickbooks', section: 'purchase-orders', group: 'Integrations', label: 'Sync POs to QuickBooks', type: 'toggle', default: false },
  { id: 'po-int-edi', section: 'purchase-orders', group: 'Integrations', label: 'Enable EDI 850 transmission', type: 'toggle', default: false },
  { id: 'po-int-webhook-url', section: 'purchase-orders', group: 'Integrations', label: 'Webhook URL on status change', type: 'text', default: '' },
  { id: 'po-int-vendor-catalog', section: 'purchase-orders', group: 'Integrations', label: 'Use punchout vendor catalogs', type: 'toggle', default: false },
  { id: 'po-int-currency-rate-source', section: 'purchase-orders', group: 'Integrations', label: 'Exchange rate source', type: 'select', default: 'auto', options: [{ value: 'auto', label: 'Auto (daily)' }, { value: 'manual', label: 'Manual entry' }, { value: 'fixed', label: 'Fixed rate' }] },
  { id: 'po-int-auto-pull-rates', section: 'purchase-orders', group: 'Integrations', label: 'Auto-pull FX rates on PO date', type: 'toggle', default: true },
  { id: 'po-int-barcode-scanner', section: 'purchase-orders', group: 'Integrations', label: 'Enable barcode scanner input', type: 'toggle', default: false },

  // ===== Line Items =====
  { id: 'po-line-default-rows', section: 'purchase-orders', group: 'Line Items', label: 'Default blank line rows', type: 'number', default: 3, min: 0, max: 20, step: 1 },
  { id: 'po-line-show-sku', section: 'purchase-orders', group: 'Line Items', label: 'Show SKU/item code column', type: 'toggle', default: true },
  { id: 'po-line-show-description', section: 'purchase-orders', group: 'Line Items', label: 'Show description column', type: 'toggle', default: true },
  { id: 'po-line-show-discount', section: 'purchase-orders', group: 'Line Items', label: 'Show per-line discount column', type: 'toggle', default: false },
  { id: 'po-line-show-tax', section: 'purchase-orders', group: 'Line Items', label: 'Show per-line tax column', type: 'toggle', default: false },
  { id: 'po-line-show-account', section: 'purchase-orders', group: 'Line Items', label: 'Show GL account column', type: 'toggle', default: false },
  { id: 'po-line-show-uom', section: 'purchase-orders', group: 'Line Items', label: 'Show unit of measure column', type: 'toggle', default: true },
  { id: 'po-line-show-expected-date', section: 'purchase-orders', group: 'Line Items', label: 'Show per-line expected date', type: 'toggle', default: false },
  { id: 'po-line-auto-fill-price', section: 'purchase-orders', group: 'Line Items', label: 'Auto-fill last purchase price', type: 'toggle', default: true },
  { id: 'po-line-allow-free-text', section: 'purchase-orders', group: 'Line Items', label: 'Allow free-text non-catalog items', type: 'toggle', default: true },
  { id: 'po-line-show-line-number', section: 'purchase-orders', group: 'Line Items', label: 'Show line number column', type: 'toggle', default: true },
  { id: 'po-line-show-received-col', section: 'purchase-orders', group: 'Line Items', label: 'Show received quantity column', type: 'toggle', default: true },
  { id: 'po-line-default-qty', section: 'purchase-orders', group: 'Line Items', label: 'Default line quantity', type: 'number', default: 1, min: 0, max: 10000, step: 1 },
  { id: 'po-line-reorder-drag', section: 'purchase-orders', group: 'Line Items', label: 'Enable drag-to-reorder lines', type: 'toggle', default: true },
  { id: 'po-line-subtotal-per-section', section: 'purchase-orders', group: 'Line Items', label: 'Show subtotals per group', type: 'toggle', default: false },
  { id: 'po-line-show-image', section: 'purchase-orders', group: 'Line Items', label: 'Show item image thumbnail', type: 'toggle', default: false },
  { id: 'po-line-confirm-remove', section: 'purchase-orders', group: 'Line Items', label: 'Confirm before removing a line', type: 'toggle', default: false },
];
