// src/renderer/customization/sections/quotes.ts
//
// Customization options for the Quotes & Estimates section.
// 200 genuine display/behavior/formatting/export/notification preferences
// a user managing quotes and estimates would actually want.

import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ── Display (1-20) ──────────────────────────────────────────────
  { id: 'show-quote-list-density', section: 'quotes', group: 'Display', label: 'List density', description: 'Row spacing in the quotes list.', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'show-quote-thumbnails', section: 'quotes', group: 'Display', label: 'Show document thumbnails', description: 'Render a mini preview of each quote.', type: 'toggle', default: false },
  { id: 'show-status-badges', section: 'quotes', group: 'Display', label: 'Show status badges', description: 'Colored draft/sent/accepted chips.', type: 'toggle', default: true },
  { id: 'show-client-avatars', section: 'quotes', group: 'Display', label: 'Show client avatars', type: 'toggle', default: true },
  { id: 'show-expiry-countdown', section: 'quotes', group: 'Display', label: 'Show expiry countdown', description: 'Days remaining until the quote expires.', type: 'toggle', default: true },
  { id: 'rows-per-page', section: 'quotes', group: 'Display', label: 'Rows per page', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'sticky-list-header', section: 'quotes', group: 'Display', label: 'Sticky list header', type: 'toggle', default: true },
  { id: 'show-line-item-preview', section: 'quotes', group: 'Display', label: 'Inline line-item preview', description: 'Expand first few line items in the list.', type: 'toggle', default: false },
  { id: 'show-quote-total-bar', section: 'quotes', group: 'Display', label: 'Show running total bar', type: 'toggle', default: true },
  { id: 'default-view-mode', section: 'quotes', group: 'Display', label: 'Default view mode', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'kanban', label: 'Kanban' }] },
  { id: 'show-revision-indicator', section: 'quotes', group: 'Display', label: 'Show revision indicator', description: 'Mark quotes that have multiple versions.', type: 'toggle', default: true },
  { id: 'highlight-expiring-soon', section: 'quotes', group: 'Display', label: 'Highlight expiring soon', type: 'toggle', default: true },
  { id: 'expiring-soon-threshold-days', section: 'quotes', group: 'Display', label: 'Expiring-soon threshold (days)', type: 'number', default: 3, min: 1, max: 30, step: 1 },
  { id: 'show-empty-state-tips', section: 'quotes', group: 'Display', label: 'Show empty-state tips', type: 'toggle', default: true },
  { id: 'compact-currency-display', section: 'quotes', group: 'Display', label: 'Compact currency in list', description: 'Show $1.2k instead of $1,200.00.', type: 'toggle', default: false },
  { id: 'show-quote-age', section: 'quotes', group: 'Display', label: 'Show quote age', description: 'Days since the quote was created.', type: 'toggle', default: false },
  { id: 'show-owner-column', section: 'quotes', group: 'Display', label: 'Show owner/rep', type: 'toggle', default: true },
  { id: 'show-probability-meter', section: 'quotes', group: 'Display', label: 'Show win-probability meter', type: 'toggle', default: false },
  { id: 'collapse-rejected', section: 'quotes', group: 'Display', label: 'Collapse rejected quotes', description: 'Hide rejected quotes behind a toggle.', type: 'toggle', default: false },
  { id: 'preview-pane-position', section: 'quotes', group: 'Display', label: 'Preview pane position', type: 'select', default: 'right', options: [{ value: 'right', label: 'Right' }, { value: 'bottom', label: 'Bottom' }, { value: 'off', label: 'Off' }] },

  // ── Columns (21-40) ─────────────────────────────────────────────
  { id: 'col-quote-number', section: 'quotes', group: 'Columns', label: 'Column: Quote number', type: 'toggle', default: true },
  { id: 'col-client', section: 'quotes', group: 'Columns', label: 'Column: Client', type: 'toggle', default: true },
  { id: 'col-title', section: 'quotes', group: 'Columns', label: 'Column: Title/subject', type: 'toggle', default: true },
  { id: 'col-amount', section: 'quotes', group: 'Columns', label: 'Column: Amount', type: 'toggle', default: true },
  { id: 'col-status', section: 'quotes', group: 'Columns', label: 'Column: Status', type: 'toggle', default: true },
  { id: 'col-issue-date', section: 'quotes', group: 'Columns', label: 'Column: Issue date', type: 'toggle', default: true },
  { id: 'col-expiry-date', section: 'quotes', group: 'Columns', label: 'Column: Expiry date', type: 'toggle', default: true },
  { id: 'col-accepted-date', section: 'quotes', group: 'Columns', label: 'Column: Accepted date', type: 'toggle', default: false },
  { id: 'col-tax', section: 'quotes', group: 'Columns', label: 'Column: Tax', type: 'toggle', default: false },
  { id: 'col-discount', section: 'quotes', group: 'Columns', label: 'Column: Discount', type: 'toggle', default: false },
  { id: 'col-margin', section: 'quotes', group: 'Columns', label: 'Column: Margin', type: 'toggle', default: false },
  { id: 'col-currency', section: 'quotes', group: 'Columns', label: 'Column: Currency', type: 'toggle', default: false },
  { id: 'col-sales-rep', section: 'quotes', group: 'Columns', label: 'Column: Sales rep', type: 'toggle', default: true },
  { id: 'col-converted-invoice', section: 'quotes', group: 'Columns', label: 'Column: Converted invoice', type: 'toggle', default: false },
  { id: 'col-last-viewed', section: 'quotes', group: 'Columns', label: 'Column: Last viewed by client', type: 'toggle', default: false },
  { id: 'col-tags', section: 'quotes', group: 'Columns', label: 'Column: Tags', type: 'toggle', default: false },
  { id: 'col-project', section: 'quotes', group: 'Columns', label: 'Column: Project', type: 'toggle', default: false },
  { id: 'col-probability', section: 'quotes', group: 'Columns', label: 'Column: Win probability', type: 'toggle', default: false },
  { id: 'col-actions-pinned', section: 'quotes', group: 'Columns', label: 'Pin actions column', type: 'toggle', default: true },
  { id: 'amount-column-alignment', section: 'quotes', group: 'Columns', label: 'Amount column alignment', type: 'select', default: 'right', options: [{ value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }] },

  // ── Formatting (41-62) ──────────────────────────────────────────
  { id: 'currency-symbol', section: 'quotes', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'currency-code-default', section: 'quotes', group: 'Formatting', label: 'Default currency', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' }] },
  { id: 'decimal-places', section: 'quotes', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'thousands-separator', section: 'quotes', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'currency-symbol-position', section: 'quotes', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($100)' }, { value: 'after', label: 'After (100$)' }] },
  { id: 'date-format', section: 'quotes', group: 'Formatting', label: 'Date format', type: 'select', default: 'mm-dd-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }] },
  { id: 'negative-amount-style', section: 'quotes', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-$100' }, { value: 'parens', label: '($100)' }, { value: 'red', label: 'Red $100' }] },
  { id: 'quote-number-prefix', section: 'quotes', group: 'Formatting', label: 'Quote number prefix', type: 'text', default: 'QUO-' },
  { id: 'quote-number-padding', section: 'quotes', group: 'Formatting', label: 'Quote number digit padding', type: 'number', default: 4, min: 1, max: 10, step: 1 },
  { id: 'estimate-number-prefix', section: 'quotes', group: 'Formatting', label: 'Estimate number prefix', type: 'text', default: 'EST-' },
  { id: 'include-year-in-number', section: 'quotes', group: 'Formatting', label: 'Include year in number', description: 'e.g. QUO-2026-0001.', type: 'toggle', default: true },
  { id: 'percent-decimal-places', section: 'quotes', group: 'Formatting', label: 'Percent decimal places', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'round-line-totals', section: 'quotes', group: 'Formatting', label: 'Round line totals', type: 'toggle', default: false },
  { id: 'rounding-mode', section: 'quotes', group: 'Formatting', label: 'Rounding mode', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Half up' }, { value: 'half-even', label: 'Banker\'s' }, { value: 'down', label: 'Down' }, { value: 'up', label: 'Up' }] },
  { id: 'quantity-decimal-places', section: 'quotes', group: 'Formatting', label: 'Quantity decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'capitalize-status-labels', section: 'quotes', group: 'Formatting', label: 'Capitalize status labels', type: 'toggle', default: true },
  { id: 'show-currency-code', section: 'quotes', group: 'Formatting', label: 'Show currency code on totals', description: 'e.g. $1,200.00 USD.', type: 'toggle', default: false },
  { id: 'thousand-grouping-style', section: 'quotes', group: 'Formatting', label: 'Indian grouping (lakh/crore)', type: 'toggle', default: false },
  { id: 'long-date-format', section: 'quotes', group: 'Formatting', label: 'Use long dates on PDF', description: 'e.g. May 31, 2026.', type: 'toggle', default: true },
  { id: 'amount-in-words', section: 'quotes', group: 'Formatting', label: 'Show total amount in words', type: 'toggle', default: false },
  { id: 'tax-label-text', section: 'quotes', group: 'Formatting', label: 'Tax line label', type: 'text', default: 'Sales Tax' },
  { id: 'subtotal-label-text', section: 'quotes', group: 'Formatting', label: 'Subtotal line label', type: 'text', default: 'Subtotal' },

  // ── Defaults (63-86) ────────────────────────────────────────────
  { id: 'default-validity-days', section: 'quotes', group: 'Defaults', label: 'Default validity period (days)', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'default-tax-rate', section: 'quotes', group: 'Defaults', label: 'Default tax rate (%)', type: 'number', default: 0, min: 0, max: 30, step: 0.25 },
  { id: 'default-tax-inclusive', section: 'quotes', group: 'Defaults', label: 'Prices tax-inclusive by default', type: 'toggle', default: false },
  { id: 'default-discount-type', section: 'quotes', group: 'Defaults', label: 'Default discount type', type: 'select', default: 'percent', options: [{ value: 'percent', label: 'Percentage' }, { value: 'fixed', label: 'Fixed amount' }] },
  { id: 'default-terms-text', section: 'quotes', group: 'Defaults', label: 'Default terms & conditions', type: 'text', default: 'This quote is valid for 30 days from the date of issue.' },
  { id: 'default-footer-note', section: 'quotes', group: 'Defaults', label: 'Default footer note', type: 'text', default: 'Thank you for your business.' },
  { id: 'default-line-item-tax', section: 'quotes', group: 'Defaults', label: 'Apply tax to new line items', type: 'toggle', default: true },
  { id: 'auto-fill-from-last-quote', section: 'quotes', group: 'Defaults', label: 'Pre-fill from client\'s last quote', type: 'toggle', default: false },
  { id: 'default-quantity', section: 'quotes', group: 'Defaults', label: 'Default line item quantity', type: 'number', default: 1, min: 0, max: 1000, step: 1 },
  { id: 'default-payment-terms', section: 'quotes', group: 'Defaults', label: 'Default payment terms', type: 'select', default: 'net30', options: [{ value: 'due', label: 'Due on receipt' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net60', label: 'Net 60' }] },
  { id: 'default-deposit-percent', section: 'quotes', group: 'Defaults', label: 'Default deposit (%)', type: 'number', default: 0, min: 0, max: 100, step: 5 },
  { id: 'require-deposit', section: 'quotes', group: 'Defaults', label: 'Require deposit on acceptance', type: 'toggle', default: false },
  { id: 'default-template', section: 'quotes', group: 'Defaults', label: 'Default quote template', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'detailed', label: 'Detailed' }, { value: 'minimal', label: 'Minimal' }, { value: 'service', label: 'Service' }] },
  { id: 'default-rep-from-account', section: 'quotes', group: 'Defaults', label: 'Auto-assign rep from client', type: 'toggle', default: true },
  { id: 'default-show-line-numbers', section: 'quotes', group: 'Defaults', label: 'Show line numbers by default', type: 'toggle', default: false },
  { id: 'default-include-tax-summary', section: 'quotes', group: 'Defaults', label: 'Include tax summary block', type: 'toggle', default: true },
  { id: 'default-currency-locks', section: 'quotes', group: 'Defaults', label: 'Lock currency after first line', type: 'toggle', default: true },
  { id: 'default-notes-internal', section: 'quotes', group: 'Defaults', label: 'Default internal note', type: 'text', default: '' },
  { id: 'auto-set-issue-date-today', section: 'quotes', group: 'Defaults', label: 'Set issue date to today', type: 'toggle', default: true },
  { id: 'default-unit-label', section: 'quotes', group: 'Defaults', label: 'Default unit label', type: 'text', default: 'ea' },
  { id: 'default-shipping-line', section: 'quotes', group: 'Defaults', label: 'Add shipping line by default', type: 'toggle', default: false },
  { id: 'default-margin-target', section: 'quotes', group: 'Defaults', label: 'Target margin (%)', type: 'number', default: 30, min: 0, max: 100, step: 1 },
  { id: 'default-language', section: 'quotes', group: 'Defaults', label: 'Default document language', type: 'select', default: 'en', options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }] },
  { id: 'default-valid-until-business-days', section: 'quotes', group: 'Defaults', label: 'Count validity in business days', type: 'toggle', default: false },

  // ── Numbering (87-98) ───────────────────────────────────────────
  { id: 'numbering-scheme', section: 'quotes', group: 'Numbering', label: 'Numbering scheme', type: 'select', default: 'sequential', options: [{ value: 'sequential', label: 'Sequential' }, { value: 'per-client', label: 'Per client' }, { value: 'per-year', label: 'Reset yearly' }, { value: 'random', label: 'Random' }] },
  { id: 'numbering-start', section: 'quotes', group: 'Numbering', label: 'Starting number', type: 'number', default: 1, min: 0, max: 1000000, step: 1 },
  { id: 'numbering-increment', section: 'quotes', group: 'Numbering', label: 'Increment step', type: 'number', default: 1, min: 1, max: 100, step: 1 },
  { id: 'separate-estimate-sequence', section: 'quotes', group: 'Numbering', label: 'Separate estimate sequence', description: 'Estimates and quotes use independent counters.', type: 'toggle', default: true },
  { id: 'numbering-suffix', section: 'quotes', group: 'Numbering', label: 'Number suffix', type: 'text', default: '' },
  { id: 'numbering-separator', section: 'quotes', group: 'Numbering', label: 'Number segment separator', type: 'select', default: 'dash', options: [{ value: 'dash', label: 'Dash (-)' }, { value: 'slash', label: 'Slash (/)' }, { value: 'dot', label: 'Dot (.)' }, { value: 'none', label: 'None' }] },
  { id: 'reset-numbering-period', section: 'quotes', group: 'Numbering', label: 'Reset numbering period', type: 'select', default: 'never', options: [{ value: 'never', label: 'Never' }, { value: 'yearly', label: 'Yearly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'allow-manual-number-override', section: 'quotes', group: 'Numbering', label: 'Allow manual number override', type: 'toggle', default: true },
  { id: 'revision-number-suffix', section: 'quotes', group: 'Numbering', label: 'Revision suffix style', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter (-A)' }, { value: 'number', label: 'Number (-r2)' }, { value: 'rev', label: 'Rev (Rev 2)' }] },
  { id: 'warn-on-number-gap', section: 'quotes', group: 'Numbering', label: 'Warn on numbering gaps', type: 'toggle', default: false },
  { id: 'preview-next-number', section: 'quotes', group: 'Numbering', label: 'Preview next number in form', type: 'toggle', default: true },
  { id: 'include-company-code', section: 'quotes', group: 'Numbering', label: 'Include company code', type: 'text', default: '' },

  // ── Sorting & Filtering (99-115) ────────────────────────────────
  { id: 'default-sort-field', section: 'quotes', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'issue-date', options: [{ value: 'issue-date', label: 'Issue date' }, { value: 'expiry-date', label: 'Expiry date' }, { value: 'amount', label: 'Amount' }, { value: 'client', label: 'Client' }, { value: 'number', label: 'Number' }] },
  { id: 'default-sort-direction', section: 'quotes', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'default-status-filter', section: 'quotes', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'open', label: 'Open only' }, { value: 'draft', label: 'Drafts' }, { value: 'accepted', label: 'Accepted' }, { value: 'expired', label: 'Expired' }] },
  { id: 'remember-last-filter', section: 'quotes', group: 'Sorting & Filtering', label: 'Remember last filter', type: 'toggle', default: true },
  { id: 'hide-expired-by-default', section: 'quotes', group: 'Sorting & Filtering', label: 'Hide expired by default', type: 'toggle', default: false },
  { id: 'hide-converted-by-default', section: 'quotes', group: 'Sorting & Filtering', label: 'Hide converted quotes', type: 'toggle', default: false },
  { id: 'default-date-range', section: 'quotes', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'this-year', options: [{ value: 'this-month', label: 'This month' }, { value: 'this-quarter', label: 'This quarter' }, { value: 'this-year', label: 'This year' }, { value: 'all', label: 'All time' }] },
  { id: 'filter-by-rep-default', section: 'quotes', group: 'Sorting & Filtering', label: 'Filter to my quotes by default', type: 'toggle', default: false },
  { id: 'secondary-sort-field', section: 'quotes', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'number', options: [{ value: 'number', label: 'Number' }, { value: 'client', label: 'Client' }, { value: 'amount', label: 'Amount' }, { value: 'none', label: 'None' }] },
  { id: 'min-amount-filter', section: 'quotes', group: 'Sorting & Filtering', label: 'Default minimum amount filter', type: 'number', default: 0, min: 0, max: 1000000, step: 100 },
  { id: 'group-by-status', section: 'quotes', group: 'Sorting & Filtering', label: 'Group list by status', type: 'toggle', default: false },
  { id: 'group-by-client', section: 'quotes', group: 'Sorting & Filtering', label: 'Group list by client', type: 'toggle', default: false },
  { id: 'pin-drafts-top', section: 'quotes', group: 'Sorting & Filtering', label: 'Pin drafts to top', type: 'toggle', default: false },
  { id: 'quick-filter-tags', section: 'quotes', group: 'Sorting & Filtering', label: 'Show quick filter tag chips', type: 'toggle', default: true },
  { id: 'search-includes-line-items', section: 'quotes', group: 'Sorting & Filtering', label: 'Search inside line items', type: 'toggle', default: true },
  { id: 'search-includes-notes', section: 'quotes', group: 'Sorting & Filtering', label: 'Search inside notes', type: 'toggle', default: false },
  { id: 'saved-views-enabled', section: 'quotes', group: 'Sorting & Filtering', label: 'Enable saved views', type: 'toggle', default: true },

  // ── Behavior (116-138) ──────────────────────────────────────────
  { id: 'auto-save-drafts', section: 'quotes', group: 'Behavior', label: 'Auto-save drafts', type: 'toggle', default: true },
  { id: 'auto-save-interval', section: 'quotes', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'confirm-before-send', section: 'quotes', group: 'Behavior', label: 'Confirm before sending', type: 'toggle', default: true },
  { id: 'confirm-before-delete', section: 'quotes', group: 'Behavior', label: 'Confirm before deleting', type: 'toggle', default: true },
  { id: 'auto-expire-overdue', section: 'quotes', group: 'Behavior', label: 'Auto-expire past validity', type: 'toggle', default: true },
  { id: 'auto-convert-on-accept', section: 'quotes', group: 'Behavior', label: 'Auto-convert to invoice on accept', type: 'toggle', default: false },
  { id: 'lock-after-accept', section: 'quotes', group: 'Behavior', label: 'Lock quote after acceptance', type: 'toggle', default: true },
  { id: 'allow-edit-sent', section: 'quotes', group: 'Behavior', label: 'Allow editing sent quotes', description: 'Creates a new revision.', type: 'toggle', default: true },
  { id: 'duplicate-keeps-dates', section: 'quotes', group: 'Behavior', label: 'Keep dates when duplicating', type: 'toggle', default: false },
  { id: 'recalculate-on-tax-change', section: 'quotes', group: 'Behavior', label: 'Recalculate totals on tax change', type: 'toggle', default: true },
  { id: 'tab-adds-new-line', section: 'quotes', group: 'Behavior', label: 'Tab on last cell adds new line', type: 'toggle', default: true },
  { id: 'auto-collapse-on-save', section: 'quotes', group: 'Behavior', label: 'Collapse editor after save', type: 'toggle', default: false },
  { id: 'keep-editor-open-after-create', section: 'quotes', group: 'Behavior', label: 'Stay in editor after create', type: 'toggle', default: false },
  { id: 'warn-unsaved-changes', section: 'quotes', group: 'Behavior', label: 'Warn on unsaved changes', type: 'toggle', default: true },
  { id: 'auto-number-on-save', section: 'quotes', group: 'Behavior', label: 'Assign number only on save', description: 'Avoids gaps from abandoned drafts.', type: 'toggle', default: true },
  { id: 'snap-line-item-from-catalog', section: 'quotes', group: 'Behavior', label: 'Autofill line items from catalog', type: 'toggle', default: true },
  { id: 'default-action-on-row-click', section: 'quotes', group: 'Behavior', label: 'Row click action', type: 'select', default: 'preview', options: [{ value: 'preview', label: 'Open preview' }, { value: 'edit', label: 'Open editor' }, { value: 'select', label: 'Select row' }] },
  { id: 'enable-client-portal-accept', section: 'quotes', group: 'Behavior', label: 'Allow online acceptance', type: 'toggle', default: true },
  { id: 'require-signature-on-accept', section: 'quotes', group: 'Behavior', label: 'Require e-signature to accept', type: 'toggle', default: false },
  { id: 'auto-followup-enabled', section: 'quotes', group: 'Behavior', label: 'Enable automated follow-ups', type: 'toggle', default: false },
  { id: 'followup-delay-days', section: 'quotes', group: 'Behavior', label: 'Follow-up delay (days)', type: 'number', default: 5, min: 1, max: 60, step: 1 },
  { id: 'auto-archive-after-days', section: 'quotes', group: 'Behavior', label: 'Auto-archive expired after (days)', type: 'number', default: 90, min: 0, max: 730, step: 5 },
  { id: 'duplicate-bumps-number', section: 'quotes', group: 'Behavior', label: 'Assign new number on duplicate', type: 'toggle', default: true },

  // ── Notifications (139-156) ─────────────────────────────────────
  { id: 'notify-on-view', section: 'quotes', group: 'Notifications', label: 'Notify when client views', type: 'toggle', default: true },
  { id: 'notify-on-accept', section: 'quotes', group: 'Notifications', label: 'Notify on acceptance', type: 'toggle', default: true },
  { id: 'notify-on-reject', section: 'quotes', group: 'Notifications', label: 'Notify on rejection', type: 'toggle', default: true },
  { id: 'notify-on-expiry', section: 'quotes', group: 'Notifications', label: 'Notify before expiry', type: 'toggle', default: true },
  { id: 'expiry-warning-days', section: 'quotes', group: 'Notifications', label: 'Expiry warning lead (days)', type: 'number', default: 2, min: 1, max: 30, step: 1 },
  { id: 'notify-on-comment', section: 'quotes', group: 'Notifications', label: 'Notify on client comment', type: 'toggle', default: true },
  { id: 'notify-channel', section: 'quotes', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'daily-digest', section: 'quotes', group: 'Notifications', label: 'Daily quote digest', type: 'toggle', default: false },
  { id: 'digest-time', section: 'quotes', group: 'Notifications', label: 'Digest delivery time', type: 'text', default: '08:00' },
  { id: 'notify-rep-only', section: 'quotes', group: 'Notifications', label: 'Notify assigned rep only', type: 'toggle', default: true },
  { id: 'notify-on-conversion', section: 'quotes', group: 'Notifications', label: 'Notify on invoice conversion', type: 'toggle', default: true },
  { id: 'sound-on-accept', section: 'quotes', group: 'Notifications', label: 'Play sound on acceptance', type: 'toggle', default: false },
  { id: 'notify-high-value-threshold', section: 'quotes', group: 'Notifications', label: 'High-value alert threshold', type: 'number', default: 10000, min: 0, max: 1000000, step: 500 },
  { id: 'notify-high-value', section: 'quotes', group: 'Notifications', label: 'Alert on high-value quotes', type: 'toggle', default: false },
  { id: 'remind-stale-drafts', section: 'quotes', group: 'Notifications', label: 'Remind about stale drafts', type: 'toggle', default: true },
  { id: 'stale-draft-days', section: 'quotes', group: 'Notifications', label: 'Stale draft threshold (days)', type: 'number', default: 7, min: 1, max: 90, step: 1 },
  { id: 'notify-followup-due', section: 'quotes', group: 'Notifications', label: 'Notify when follow-up is due', type: 'toggle', default: true },
  { id: 'mute-weekend-notifications', section: 'quotes', group: 'Notifications', label: 'Mute notifications on weekends', type: 'toggle', default: false },

  // ── Email & Sending (157-170) ───────────────────────────────────
  { id: 'email-subject-template', section: 'quotes', group: 'Email & Sending', label: 'Email subject template', type: 'text', default: 'Quote {number} from {company}' },
  { id: 'email-body-template', section: 'quotes', group: 'Email & Sending', label: 'Email body template', type: 'text', default: 'Please find your quote attached. Let us know if you have questions.' },
  { id: 'attach-pdf', section: 'quotes', group: 'Email & Sending', label: 'Attach PDF to email', type: 'toggle', default: true },
  { id: 'include-portal-link', section: 'quotes', group: 'Email & Sending', label: 'Include online view link', type: 'toggle', default: true },
  { id: 'send-copy-to-self', section: 'quotes', group: 'Email & Sending', label: 'Send a copy to myself', type: 'toggle', default: false },
  { id: 'bcc-address', section: 'quotes', group: 'Email & Sending', label: 'Default BCC address', type: 'text', default: '' },
  { id: 'reply-to-address', section: 'quotes', group: 'Email & Sending', label: 'Reply-to address', type: 'text', default: '' },
  { id: 'send-read-receipt', section: 'quotes', group: 'Email & Sending', label: 'Request read receipt', type: 'toggle', default: false },
  { id: 'default-send-method', section: 'quotes', group: 'Email & Sending', label: 'Default send method', type: 'select', default: 'email', options: [{ value: 'email', label: 'Email' }, { value: 'link', label: 'Share link' }, { value: 'download', label: 'Download only' }] },
  { id: 'auto-cc-account-rep', section: 'quotes', group: 'Email & Sending', label: 'CC the account rep', type: 'toggle', default: true },
  { id: 'send-schedule-enabled', section: 'quotes', group: 'Email & Sending', label: 'Allow scheduled sending', type: 'toggle', default: false },
  { id: 'email-signature', section: 'quotes', group: 'Email & Sending', label: 'Email signature', type: 'text', default: '' },
  { id: 'embed-quote-in-body', section: 'quotes', group: 'Email & Sending', label: 'Embed quote preview in body', type: 'toggle', default: false },
  { id: 'link-expiry-days', section: 'quotes', group: 'Email & Sending', label: 'Share link expiry (days)', type: 'number', default: 60, min: 1, max: 365, step: 1 },

  // ── Export (171-182) ────────────────────────────────────────────
  { id: 'pdf-page-size', section: 'quotes', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'pdf-orientation', section: 'quotes', group: 'Export', label: 'PDF orientation', type: 'select', default: 'portrait', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'pdf-include-logo', section: 'quotes', group: 'Export', label: 'Include logo on PDF', type: 'toggle', default: true },
  { id: 'pdf-include-watermark', section: 'quotes', group: 'Export', label: 'Watermark drafts', type: 'toggle', default: true },
  { id: 'pdf-watermark-text', section: 'quotes', group: 'Export', label: 'Watermark text', type: 'text', default: 'DRAFT' },
  { id: 'csv-delimiter', section: 'quotes', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'export-include-line-items', section: 'quotes', group: 'Export', label: 'Include line items in export', type: 'toggle', default: true },
  { id: 'export-include-notes', section: 'quotes', group: 'Export', label: 'Include notes in export', type: 'toggle', default: false },
  { id: 'default-export-format', section: 'quotes', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [{ value: 'pdf', label: 'PDF' }, { value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }] },
  { id: 'pdf-show-page-numbers', section: 'quotes', group: 'Export', label: 'Show page numbers on PDF', type: 'toggle', default: true },
  { id: 'pdf-attach-terms-page', section: 'quotes', group: 'Export', label: 'Append terms page', type: 'toggle', default: true },
  { id: 'export-date-in-filename', section: 'quotes', group: 'Export', label: 'Include date in filename', type: 'toggle', default: true },

  // ── Colors & Theme (183-192) ────────────────────────────────────
  { id: 'accent-color', section: 'quotes', group: 'Colors & Theme', label: 'Document accent color', type: 'color', default: '#3b82f6' },
  { id: 'status-draft-color', section: 'quotes', group: 'Colors & Theme', label: 'Draft status color', type: 'color', default: '#9ca3af' },
  { id: 'status-sent-color', section: 'quotes', group: 'Colors & Theme', label: 'Sent status color', type: 'color', default: '#3b82f6' },
  { id: 'status-accepted-color', section: 'quotes', group: 'Colors & Theme', label: 'Accepted status color', type: 'color', default: '#22c55e' },
  { id: 'status-rejected-color', section: 'quotes', group: 'Colors & Theme', label: 'Rejected status color', type: 'color', default: '#ef4444' },
  { id: 'status-expired-color', section: 'quotes', group: 'Colors & Theme', label: 'Expired status color', type: 'color', default: '#f59e0b' },
  { id: 'pdf-header-bg', section: 'quotes', group: 'Colors & Theme', label: 'PDF header background', type: 'color', default: '#1e293b' },
  { id: 'pdf-table-stripe', section: 'quotes', group: 'Colors & Theme', label: 'PDF table stripe color', type: 'color', default: '#f1f5f9' },
  { id: 'totals-highlight-color', section: 'quotes', group: 'Colors & Theme', label: 'Totals highlight color', type: 'color', default: '#0ea5e9' },
  { id: 'use-brand-colors-on-pdf', section: 'quotes', group: 'Colors & Theme', label: 'Use brand colors on PDF', type: 'toggle', default: true },

  // ── Accessibility (193-196) ─────────────────────────────────────
  { id: 'high-contrast-status', section: 'quotes', group: 'Accessibility', label: 'High-contrast status badges', type: 'toggle', default: false },
  { id: 'status-text-labels', section: 'quotes', group: 'Accessibility', label: 'Always show status text labels', description: 'Don\'t rely on color alone.', type: 'toggle', default: true },
  { id: 'larger-list-font', section: 'quotes', group: 'Accessibility', label: 'Larger list font size', type: 'toggle', default: false },
  { id: 'reduce-motion', section: 'quotes', group: 'Accessibility', label: 'Reduce animations', type: 'toggle', default: false },

  // ── Shortcuts & Privacy (197-200) ───────────────────────────────
  { id: 'shortcut-new-quote', section: 'quotes', group: 'Shortcuts', label: 'New quote shortcut', type: 'text', default: 'cmd+n' },
  { id: 'shortcut-quick-search', section: 'quotes', group: 'Shortcuts', label: 'Quick search shortcut', type: 'text', default: 'cmd+k' },
  { id: 'mask-amounts', section: 'quotes', group: 'Privacy', label: 'Mask amounts until hover', description: 'Hide totals in shared-screen scenarios.', type: 'toggle', default: false },
  { id: 'hide-client-pii-in-list', section: 'quotes', group: 'Privacy', label: 'Hide client PII in list', type: 'toggle', default: false },
];
