import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ============================ Display (1-20) ============================
  { id: 'display-default-view', section: 'recurring', group: 'Display', label: 'Default view', description: 'Layout used when opening Recurring Transactions.', type: 'select', default: 'list', options: [{ value: 'list', label: 'List' }, { value: 'calendar', label: 'Calendar' }, { value: 'cards', label: 'Cards' }, { value: 'timeline', label: 'Timeline' }] },
  { id: 'display-rows-per-page', section: 'recurring', group: 'Display', label: 'Rows per page', description: 'Number of recurring templates per page.', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'display-compact-rows', section: 'recurring', group: 'Display', label: 'Compact rows', description: 'Reduce row height for denser tables.', type: 'toggle', default: false },
  { id: 'display-show-inactive', section: 'recurring', group: 'Display', label: 'Show inactive templates', description: 'Include paused and ended schedules in the list.', type: 'toggle', default: true },
  { id: 'display-show-ended', section: 'recurring', group: 'Display', label: 'Show ended schedules', description: 'Display schedules past their end date.', type: 'toggle', default: false },
  { id: 'display-zebra-striping', section: 'recurring', group: 'Display', label: 'Zebra striping', description: 'Alternate row background shading.', type: 'toggle', default: true },
  { id: 'display-sticky-header', section: 'recurring', group: 'Display', label: 'Sticky table header', description: 'Keep column headers visible when scrolling.', type: 'toggle', default: true },
  { id: 'display-row-hover-highlight', section: 'recurring', group: 'Display', label: 'Row hover highlight', description: 'Highlight the row under the cursor.', type: 'toggle', default: true },
  { id: 'display-group-by', section: 'recurring', group: 'Display', label: 'Group templates by', description: 'Optional grouping of the template list.', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'frequency', label: 'Frequency' }, { value: 'type', label: 'Transaction type' }, { value: 'vendor', label: 'Vendor / customer' }, { value: 'status', label: 'Status' }] },
  { id: 'display-show-next-run-badge', section: 'recurring', group: 'Display', label: 'Next run badge', description: 'Show a colored badge with the next run date.', type: 'toggle', default: true },
  { id: 'display-show-occurrence-count', section: 'recurring', group: 'Display', label: 'Show occurrence count', description: 'Display how many times a schedule has run.', type: 'toggle', default: true },
  { id: 'display-show-progress-bar', section: 'recurring', group: 'Display', label: 'Progress bar for fixed series', description: 'Show progress toward the occurrence limit.', type: 'toggle', default: true },
  { id: 'display-density', section: 'recurring', group: 'Display', label: 'Display density', description: 'Overall spacing of list elements.', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'display-show-avatars', section: 'recurring', group: 'Display', label: 'Show party avatars', description: 'Show vendor/customer initials avatars.', type: 'toggle', default: false },
  { id: 'display-truncate-memo', section: 'recurring', group: 'Display', label: 'Truncate memo text', description: 'Cut long memos with an ellipsis.', type: 'toggle', default: true },
  { id: 'display-memo-max-chars', section: 'recurring', group: 'Display', label: 'Memo truncation length', description: 'Maximum memo characters before truncating.', type: 'number', default: 60, min: 20, max: 200, step: 5 },
  { id: 'display-show-empty-state-tips', section: 'recurring', group: 'Display', label: 'Show empty-state tips', description: 'Helpful hints when no templates exist.', type: 'toggle', default: true },
  { id: 'display-pin-active-top', section: 'recurring', group: 'Display', label: 'Pin active to top', description: 'Float active schedules above paused ones.', type: 'toggle', default: false },
  { id: 'display-show-tags', section: 'recurring', group: 'Display', label: 'Show template tags', description: 'Render tag chips on each template.', type: 'toggle', default: true },
  { id: 'display-highlight-overdue', section: 'recurring', group: 'Display', label: 'Highlight overdue runs', description: 'Emphasize templates with missed runs.', type: 'toggle', default: true },

  // ============================ Columns (21-44) ============================
  { id: 'col-template-name', section: 'recurring', group: 'Columns', label: 'Template name column', description: 'Show the schedule name column.', type: 'toggle', default: true },
  { id: 'col-type', section: 'recurring', group: 'Columns', label: 'Transaction type column', description: 'Show invoice/bill/journal type.', type: 'toggle', default: true },
  { id: 'col-party', section: 'recurring', group: 'Columns', label: 'Vendor / customer column', description: 'Show the associated party.', type: 'toggle', default: true },
  { id: 'col-amount', section: 'recurring', group: 'Columns', label: 'Amount column', description: 'Show the recurring amount.', type: 'toggle', default: true },
  { id: 'col-frequency', section: 'recurring', group: 'Columns', label: 'Frequency column', description: 'Show the repeat frequency.', type: 'toggle', default: true },
  { id: 'col-next-run', section: 'recurring', group: 'Columns', label: 'Next run date column', description: 'Show when the next transaction posts.', type: 'toggle', default: true },
  { id: 'col-last-run', section: 'recurring', group: 'Columns', label: 'Last run date column', description: 'Show the most recent run.', type: 'toggle', default: false },
  { id: 'col-start-date', section: 'recurring', group: 'Columns', label: 'Start date column', description: 'Show the schedule start date.', type: 'toggle', default: false },
  { id: 'col-end-date', section: 'recurring', group: 'Columns', label: 'End date column', description: 'Show the schedule end date.', type: 'toggle', default: false },
  { id: 'col-status', section: 'recurring', group: 'Columns', label: 'Status column', description: 'Show active/paused/ended status.', type: 'toggle', default: true },
  { id: 'col-occurrences-remaining', section: 'recurring', group: 'Columns', label: 'Occurrences remaining column', description: 'Show runs left for fixed series.', type: 'toggle', default: false },
  { id: 'col-account', section: 'recurring', group: 'Columns', label: 'Account column', description: 'Show the posting account.', type: 'toggle', default: false },
  { id: 'col-category', section: 'recurring', group: 'Columns', label: 'Category column', description: 'Show the expense/income category.', type: 'toggle', default: false },
  { id: 'col-payment-method', section: 'recurring', group: 'Columns', label: 'Payment method column', description: 'Show the default payment method.', type: 'toggle', default: false },
  { id: 'col-currency', section: 'recurring', group: 'Columns', label: 'Currency column', description: 'Show transaction currency.', type: 'toggle', default: false },
  { id: 'col-tax', section: 'recurring', group: 'Columns', label: 'Tax column', description: 'Show applied tax rate.', type: 'toggle', default: false },
  { id: 'col-auto-post', section: 'recurring', group: 'Columns', label: 'Auto-post column', description: 'Show whether runs post automatically.', type: 'toggle', default: true },
  { id: 'col-tags', section: 'recurring', group: 'Columns', label: 'Tags column', description: 'Show tag chips as a column.', type: 'toggle', default: false },
  { id: 'col-created-by', section: 'recurring', group: 'Columns', label: 'Created by column', description: 'Show who created the template.', type: 'toggle', default: false },
  { id: 'col-actions', section: 'recurring', group: 'Columns', label: 'Actions column', description: 'Show inline action buttons.', type: 'toggle', default: true },
  { id: 'col-frozen-count', section: 'recurring', group: 'Columns', label: 'Frozen left columns', description: 'Number of leading columns pinned while scrolling.', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'col-amount-align', section: 'recurring', group: 'Columns', label: 'Amount alignment', description: 'Horizontal alignment of amount values.', type: 'select', default: 'right', options: [{ value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' }] },
  { id: 'col-name-width', section: 'recurring', group: 'Columns', label: 'Name column width', description: 'Pixel width of the name column.', type: 'number', default: 220, min: 120, max: 480, step: 10 },
  { id: 'col-resizable', section: 'recurring', group: 'Columns', label: 'Resizable columns', description: 'Allow dragging column borders to resize.', type: 'toggle', default: true },

  // ============================ Formatting (45-64) ============================
  { id: 'fmt-date-format', section: 'recurring', group: 'Formatting', label: 'Date format', description: 'How dates render across the section.', type: 'select', default: 'mmm-d-yyyy', options: [{ value: 'mm-dd-yyyy', label: 'MM/DD/YYYY' }, { value: 'dd-mm-yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }, { value: 'mmm-d-yyyy', label: 'Mmm D, YYYY' }] },
  { id: 'fmt-relative-dates', section: 'recurring', group: 'Formatting', label: 'Relative next-run dates', description: 'Show "in 3 days" instead of a date.', type: 'toggle', default: true },
  { id: 'fmt-currency-symbol', section: 'recurring', group: 'Formatting', label: 'Show currency symbol', description: 'Prefix amounts with the currency symbol.', type: 'toggle', default: true },
  { id: 'fmt-currency-code', section: 'recurring', group: 'Formatting', label: 'Show currency code', description: 'Append the ISO currency code (USD).', type: 'toggle', default: false },
  { id: 'fmt-thousands-separator', section: 'recurring', group: 'Formatting', label: 'Thousands separator', description: 'Group thousands in amounts.', type: 'toggle', default: true },
  { id: 'fmt-decimal-places', section: 'recurring', group: 'Formatting', label: 'Decimal places', description: 'Digits after the decimal for amounts.', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'fmt-negative-style', section: 'recurring', group: 'Formatting', label: 'Negative amount style', description: 'How negative amounts display.', type: 'select', default: 'minus', options: [{ value: 'minus', label: 'Minus sign' }, { value: 'parentheses', label: 'Parentheses' }, { value: 'red', label: 'Red text' }] },
  { id: 'fmt-frequency-label-style', section: 'recurring', group: 'Formatting', label: 'Frequency label style', description: 'Verbosity of frequency descriptions.', type: 'select', default: 'verbose', options: [{ value: 'short', label: 'Short (Mo)' }, { value: 'verbose', label: 'Verbose (Monthly)' }, { value: 'cron', label: 'Cron-like' }] },
  { id: 'fmt-time-format', section: 'recurring', group: 'Formatting', label: 'Time format', description: 'Clock format for run times.', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'fmt-show-run-time', section: 'recurring', group: 'Formatting', label: 'Show run time', description: 'Display the time of day runs execute.', type: 'toggle', default: false },
  { id: 'fmt-capitalize-status', section: 'recurring', group: 'Formatting', label: 'Capitalize status labels', description: 'Render statuses in title case.', type: 'toggle', default: true },
  { id: 'fmt-amount-color-by-type', section: 'recurring', group: 'Formatting', label: 'Color amounts by type', description: 'Income green, expense red.', type: 'toggle', default: true },
  { id: 'fmt-zero-amount-display', section: 'recurring', group: 'Formatting', label: 'Zero amount display', description: 'How zero amounts render.', type: 'select', default: 'zero', options: [{ value: 'zero', label: '0.00' }, { value: 'dash', label: 'Dash' }, { value: 'blank', label: 'Blank' }] },
  { id: 'fmt-week-start', section: 'recurring', group: 'Formatting', label: 'Week starts on', description: 'First day of the week in calendars.', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }, { value: 'saturday', label: 'Saturday' }] },
  { id: 'fmt-ordinal-day', section: 'recurring', group: 'Formatting', label: 'Ordinal day-of-month', description: 'Show "15th" instead of "15".', type: 'toggle', default: true },
  { id: 'fmt-timezone-label', section: 'recurring', group: 'Formatting', label: 'Show timezone label', description: 'Append timezone to run times.', type: 'toggle', default: false },
  { id: 'fmt-amount-rounding', section: 'recurring', group: 'Formatting', label: 'Amount rounding mode', description: 'Rounding applied when displaying amounts.', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Half up' }, { value: 'half-even', label: 'Banker’s' }, { value: 'truncate', label: 'Truncate' }] },
  { id: 'fmt-prefix-template-id', section: 'recurring', group: 'Formatting', label: 'Show template ID prefix', description: 'Prefix names with the internal ID.', type: 'toggle', default: false },
  { id: 'fmt-uppercase-currency', section: 'recurring', group: 'Formatting', label: 'Uppercase currency codes', description: 'Render currency codes in uppercase.', type: 'toggle', default: true },
  { id: 'fmt-percent-decimals', section: 'recurring', group: 'Formatting', label: 'Tax percent decimals', description: 'Decimals shown on tax percentages.', type: 'number', default: 2, min: 0, max: 4, step: 1 },

  // ============================ Defaults (65-90) ============================
  { id: 'def-frequency', section: 'recurring', group: 'Defaults', label: 'Default frequency', description: 'Frequency preselected for new templates.', type: 'select', default: 'monthly', options: [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'yearly', label: 'Yearly' }] },
  { id: 'def-transaction-type', section: 'recurring', group: 'Defaults', label: 'Default transaction type', description: 'Type preselected for new templates.', type: 'select', default: 'invoice', options: [{ value: 'invoice', label: 'Invoice' }, { value: 'bill', label: 'Bill' }, { value: 'expense', label: 'Expense' }, { value: 'journal', label: 'Journal entry' }] },
  { id: 'def-auto-post', section: 'recurring', group: 'Defaults', label: 'Auto-post by default', description: 'New templates post automatically on run.', type: 'toggle', default: false },
  { id: 'def-create-as-draft', section: 'recurring', group: 'Defaults', label: 'Create runs as draft', description: 'Generated transactions start as drafts.', type: 'toggle', default: true },
  { id: 'def-start-offset-days', section: 'recurring', group: 'Defaults', label: 'Default start offset (days)', description: 'Days from today for the default start date.', type: 'number', default: 0, min: 0, max: 90, step: 1 },
  { id: 'def-end-type', section: 'recurring', group: 'Defaults', label: 'Default end condition', description: 'How new schedules terminate.', type: 'select', default: 'never', options: [{ value: 'never', label: 'Never' }, { value: 'after-n', label: 'After N occurrences' }, { value: 'on-date', label: 'On a date' }] },
  { id: 'def-occurrence-limit', section: 'recurring', group: 'Defaults', label: 'Default occurrence limit', description: 'Default count for fixed-length series.', type: 'number', default: 12, min: 1, max: 999, step: 1 },
  { id: 'def-run-time', section: 'recurring', group: 'Defaults', label: 'Default run time', description: 'Time of day generation runs.', type: 'text', default: '06:00' },
  { id: 'def-payment-terms', section: 'recurring', group: 'Defaults', label: 'Default payment terms', description: 'Terms applied to generated invoices/bills.', type: 'select', default: 'net30', options: [{ value: 'due', label: 'Due on receipt' }, { value: 'net15', label: 'Net 15' }, { value: 'net30', label: 'Net 30' }, { value: 'net60', label: 'Net 60' }] },
  { id: 'def-currency', section: 'recurring', group: 'Defaults', label: 'Default currency', description: 'Currency preselected for new templates.', type: 'text', default: 'USD' },
  { id: 'def-account', section: 'recurring', group: 'Defaults', label: 'Default posting account', description: 'Account preselected for new templates.', type: 'text', default: '' },
  { id: 'def-category', section: 'recurring', group: 'Defaults', label: 'Default category', description: 'Category preselected for new templates.', type: 'text', default: '' },
  { id: 'def-memo-template', section: 'recurring', group: 'Defaults', label: 'Default memo template', description: 'Memo text with tokens like {{date}}.', type: 'text', default: 'Recurring charge {{month}} {{year}}' },
  { id: 'def-tax-rate', section: 'recurring', group: 'Defaults', label: 'Default tax rate (%)', description: 'Tax applied to new recurring lines.', type: 'number', default: 0, min: 0, max: 30, step: 0.25 },
  { id: 'def-weekend-handling', section: 'recurring', group: 'Defaults', label: 'Weekend run handling', description: 'How runs landing on weekends shift.', type: 'select', default: 'next-business', options: [{ value: 'as-scheduled', label: 'As scheduled' }, { value: 'next-business', label: 'Next business day' }, { value: 'prev-business', label: 'Previous business day' }] },
  { id: 'def-holiday-handling', section: 'recurring', group: 'Defaults', label: 'Holiday run handling', description: 'How runs on holidays shift.', type: 'select', default: 'next-business', options: [{ value: 'as-scheduled', label: 'As scheduled' }, { value: 'next-business', label: 'Next business day' }, { value: 'prev-business', label: 'Previous business day' }] },
  { id: 'def-month-end-rule', section: 'recurring', group: 'Defaults', label: 'Month-end rule', description: 'Behavior for the 29th-31st in short months.', type: 'select', default: 'last-day', options: [{ value: 'last-day', label: 'Use last day' }, { value: 'skip', label: 'Skip month' }, { value: 'clamp', label: 'Clamp to 28th' }] },
  { id: 'def-prorate-first', section: 'recurring', group: 'Defaults', label: 'Prorate first period', description: 'Prorate the first run by partial period.', type: 'toggle', default: false },
  { id: 'def-copy-line-items', section: 'recurring', group: 'Defaults', label: 'Copy line items from source', description: 'Carry source transaction lines into the template.', type: 'toggle', default: true },
  { id: 'def-auto-name', section: 'recurring', group: 'Defaults', label: 'Auto-generate template name', description: 'Suggest a name from party and frequency.', type: 'toggle', default: true },
  { id: 'def-default-tag', section: 'recurring', group: 'Defaults', label: 'Default tag', description: 'Tag automatically applied to new templates.', type: 'text', default: 'recurring' },
  { id: 'def-send-on-create', section: 'recurring', group: 'Defaults', label: 'Send invoice on creation', description: 'Email generated invoices immediately.', type: 'toggle', default: false },
  { id: 'def-reference-prefix', section: 'recurring', group: 'Defaults', label: 'Reference number prefix', description: 'Prefix for generated transaction numbers.', type: 'text', default: 'REC-' },
  { id: 'def-default-status', section: 'recurring', group: 'Defaults', label: 'Default new template status', description: 'State new templates start in.', type: 'select', default: 'active', options: [{ value: 'active', label: 'Active' }, { value: 'paused', label: 'Paused' }] },
  { id: 'def-lead-time-days', section: 'recurring', group: 'Defaults', label: 'Generation lead time (days)', description: 'Generate runs this many days early.', type: 'number', default: 0, min: 0, max: 30, step: 1 },
  { id: 'def-attach-pdf', section: 'recurring', group: 'Defaults', label: 'Attach PDF to generated docs', description: 'Render and attach a PDF on each run.', type: 'toggle', default: true },

  // ====================== Sorting & Filtering (91-110) ======================
  { id: 'sort-default-field', section: 'recurring', group: 'Sorting & Filtering', label: 'Default sort field', description: 'Column sorted by default.', type: 'select', default: 'next-run', options: [{ value: 'name', label: 'Name' }, { value: 'next-run', label: 'Next run' }, { value: 'amount', label: 'Amount' }, { value: 'frequency', label: 'Frequency' }, { value: 'status', label: 'Status' }] },
  { id: 'sort-default-direction', section: 'recurring', group: 'Sorting & Filtering', label: 'Default sort direction', description: 'Ascending or descending by default.', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'sort-secondary-field', section: 'recurring', group: 'Sorting & Filtering', label: 'Secondary sort field', description: 'Tie-breaker sort column.', type: 'select', default: 'name', options: [{ value: 'none', label: 'None' }, { value: 'name', label: 'Name' }, { value: 'amount', label: 'Amount' }, { value: 'next-run', label: 'Next run' }] },
  { id: 'sort-remember-last', section: 'recurring', group: 'Sorting & Filtering', label: 'Remember last sort', description: 'Persist sort choice between sessions.', type: 'toggle', default: true },
  { id: 'filter-default-status', section: 'recurring', group: 'Sorting & Filtering', label: 'Default status filter', description: 'Status filter applied on open.', type: 'select', default: 'active', options: [{ value: 'all', label: 'All' }, { value: 'active', label: 'Active only' }, { value: 'paused', label: 'Paused only' }, { value: 'ended', label: 'Ended only' }] },
  { id: 'filter-default-type', section: 'recurring', group: 'Sorting & Filtering', label: 'Default type filter', description: 'Transaction type filter on open.', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'invoice', label: 'Invoices' }, { value: 'bill', label: 'Bills' }, { value: 'expense', label: 'Expenses' }, { value: 'journal', label: 'Journals' }] },
  { id: 'filter-remember-filters', section: 'recurring', group: 'Sorting & Filtering', label: 'Remember filters', description: 'Persist filters between sessions.', type: 'toggle', default: true },
  { id: 'filter-quick-search', section: 'recurring', group: 'Sorting & Filtering', label: 'Quick search box', description: 'Show the inline search field.', type: 'toggle', default: true },
  { id: 'filter-search-includes-memo', section: 'recurring', group: 'Sorting & Filtering', label: 'Search includes memo', description: 'Match memo text in quick search.', type: 'toggle', default: true },
  { id: 'filter-search-includes-party', section: 'recurring', group: 'Sorting & Filtering', label: 'Search includes party', description: 'Match vendor/customer in quick search.', type: 'toggle', default: true },
  { id: 'filter-amount-min', section: 'recurring', group: 'Sorting & Filtering', label: 'Default minimum amount filter', description: 'Hide templates below this amount.', type: 'number', default: 0, min: 0, max: 100000, step: 50 },
  { id: 'filter-due-within-days', section: 'recurring', group: 'Sorting & Filtering', label: 'Highlight due within (days)', description: 'Window for "due soon" emphasis.', type: 'number', default: 7, min: 1, max: 90, step: 1 },
  { id: 'filter-show-only-auto', section: 'recurring', group: 'Sorting & Filtering', label: 'Show only auto-post', description: 'Filter to auto-posting templates.', type: 'toggle', default: false },
  { id: 'filter-tag-filter', section: 'recurring', group: 'Sorting & Filtering', label: 'Default tag filter', description: 'Tag preselected in the filter bar.', type: 'text', default: '' },
  { id: 'filter-saved-views', section: 'recurring', group: 'Sorting & Filtering', label: 'Enable saved views', description: 'Allow saving filter/sort combinations.', type: 'toggle', default: true },
  { id: 'filter-default-saved-view', section: 'recurring', group: 'Sorting & Filtering', label: 'Default saved view', description: 'Saved view loaded on open.', type: 'text', default: '' },
  { id: 'filter-case-sensitive-search', section: 'recurring', group: 'Sorting & Filtering', label: 'Case-sensitive search', description: 'Match case exactly in quick search.', type: 'toggle', default: false },
  { id: 'filter-currency', section: 'recurring', group: 'Sorting & Filtering', label: 'Default currency filter', description: 'Currency preselected in the filter bar.', type: 'text', default: '' },
  { id: 'filter-clear-on-close', section: 'recurring', group: 'Sorting & Filtering', label: 'Clear filters on close', description: 'Reset filters when leaving the section.', type: 'toggle', default: false },
  { id: 'sort-active-first', section: 'recurring', group: 'Sorting & Filtering', label: 'Active templates sort first', description: 'Always sort active above other statuses.', type: 'toggle', default: false },

  // ============================ Behavior (111-138) ============================
  { id: 'behavior-confirm-delete', section: 'recurring', group: 'Behavior', label: 'Confirm before delete', description: 'Show a dialog before deleting a template.', type: 'toggle', default: true },
  { id: 'behavior-confirm-pause', section: 'recurring', group: 'Behavior', label: 'Confirm before pause', description: 'Confirm pausing a schedule.', type: 'toggle', default: false },
  { id: 'behavior-confirm-skip', section: 'recurring', group: 'Behavior', label: 'Confirm skip next run', description: 'Confirm skipping the next occurrence.', type: 'toggle', default: true },
  { id: 'behavior-confirm-run-now', section: 'recurring', group: 'Behavior', label: 'Confirm run now', description: 'Confirm manually triggering a run.', type: 'toggle', default: true },
  { id: 'behavior-pause-on-failed-payment', section: 'recurring', group: 'Behavior', label: 'Pause on failed payment', description: 'Auto-pause when a charge fails.', type: 'toggle', default: true },
  { id: 'behavior-retry-failed', section: 'recurring', group: 'Behavior', label: 'Retry failed runs', description: 'Automatically retry failed generations.', type: 'toggle', default: true },
  { id: 'behavior-retry-attempts', section: 'recurring', group: 'Behavior', label: 'Retry attempts', description: 'Maximum automatic retry attempts.', type: 'number', default: 3, min: 0, max: 10, step: 1 },
  { id: 'behavior-retry-interval-hours', section: 'recurring', group: 'Behavior', label: 'Retry interval (hours)', description: 'Hours between retry attempts.', type: 'number', default: 24, min: 1, max: 168, step: 1 },
  { id: 'behavior-catch-up-missed', section: 'recurring', group: 'Behavior', label: 'Catch up missed runs', description: 'Generate runs missed while app was closed.', type: 'toggle', default: true },
  { id: 'behavior-catch-up-limit', section: 'recurring', group: 'Behavior', label: 'Max catch-up runs', description: 'Cap on missed runs generated at once.', type: 'number', default: 12, min: 1, max: 100, step: 1 },
  { id: 'behavior-duplicate-detection', section: 'recurring', group: 'Behavior', label: 'Duplicate run detection', description: 'Block generating a duplicate for the same period.', type: 'toggle', default: true },
  { id: 'behavior-auto-number', section: 'recurring', group: 'Behavior', label: 'Auto-number generated docs', description: 'Assign sequential numbers automatically.', type: 'toggle', default: true },
  { id: 'behavior-open-after-create', section: 'recurring', group: 'Behavior', label: 'Open after create', description: 'Open the template editor after creating.', type: 'toggle', default: true },
  { id: 'behavior-stay-after-save', section: 'recurring', group: 'Behavior', label: 'Stay on editor after save', description: 'Keep the editor open after saving.', type: 'toggle', default: false },
  { id: 'behavior-clone-keeps-schedule', section: 'recurring', group: 'Behavior', label: 'Clone keeps schedule', description: 'Cloning copies the recurrence rule.', type: 'toggle', default: true },
  { id: 'behavior-inline-edit', section: 'recurring', group: 'Behavior', label: 'Inline edit amounts', description: 'Edit amounts directly in the list.', type: 'toggle', default: false },
  { id: 'behavior-double-click-edit', section: 'recurring', group: 'Behavior', label: 'Double-click to edit', description: 'Open editor on row double-click.', type: 'toggle', default: true },
  { id: 'behavior-auto-save-draft', section: 'recurring', group: 'Behavior', label: 'Auto-save draft templates', description: 'Periodically save in-progress edits.', type: 'toggle', default: true },
  { id: 'behavior-auto-save-interval', section: 'recurring', group: 'Behavior', label: 'Auto-save interval (sec)', description: 'Seconds between draft auto-saves.', type: 'number', default: 30, min: 10, max: 300, step: 5 },
  { id: 'behavior-warn-end-approaching', section: 'recurring', group: 'Behavior', label: 'Warn when series ending', description: 'Flag schedules nearing their end.', type: 'toggle', default: true },
  { id: 'behavior-end-warn-runs', section: 'recurring', group: 'Behavior', label: 'End-warning lead (runs)', description: 'Warn this many runs before the end.', type: 'number', default: 2, min: 1, max: 12, step: 1 },
  { id: 'behavior-auto-archive-ended', section: 'recurring', group: 'Behavior', label: 'Auto-archive ended series', description: 'Move ended schedules to archive.', type: 'toggle', default: false },
  { id: 'behavior-archive-after-days', section: 'recurring', group: 'Behavior', label: 'Archive after (days)', description: 'Days after end before archiving.', type: 'number', default: 30, min: 1, max: 365, step: 1 },
  { id: 'behavior-bulk-actions', section: 'recurring', group: 'Behavior', label: 'Enable bulk actions', description: 'Allow multi-select bulk operations.', type: 'toggle', default: true },
  { id: 'behavior-undo-window', section: 'recurring', group: 'Behavior', label: 'Undo window (sec)', description: 'Time to undo an action via toast.', type: 'number', default: 8, min: 0, max: 60, step: 1 },
  { id: 'behavior-skip-zero-amount', section: 'recurring', group: 'Behavior', label: 'Skip zero-amount runs', description: 'Do not generate runs with a zero total.', type: 'toggle', default: false },
  { id: 'behavior-fx-rate-source', section: 'recurring', group: 'Behavior', label: 'FX rate at run time', description: 'Which rate to apply for foreign currency.', type: 'select', default: 'run-date', options: [{ value: 'run-date', label: 'Rate on run date' }, { value: 'template', label: 'Fixed template rate' }, { value: 'prompt', label: 'Prompt each run' }] },
  { id: 'behavior-rounding-adjustment', section: 'recurring', group: 'Behavior', label: 'Add rounding adjustment line', description: 'Insert a line to absorb rounding diffs.', type: 'toggle', default: false },

  // ========================= Notifications (139-160) =========================
  { id: 'notif-enable', section: 'recurring', group: 'Notifications', label: 'Enable notifications', description: 'Master switch for recurring alerts.', type: 'toggle', default: true },
  { id: 'notif-upcoming-run', section: 'recurring', group: 'Notifications', label: 'Upcoming run reminder', description: 'Notify before a scheduled run.', type: 'toggle', default: true },
  { id: 'notif-upcoming-lead-days', section: 'recurring', group: 'Notifications', label: 'Upcoming reminder lead (days)', description: 'Days ahead to send reminders.', type: 'number', default: 2, min: 0, max: 30, step: 1 },
  { id: 'notif-run-success', section: 'recurring', group: 'Notifications', label: 'Run success notice', description: 'Notify when a run posts successfully.', type: 'toggle', default: false },
  { id: 'notif-run-failure', section: 'recurring', group: 'Notifications', label: 'Run failure alert', description: 'Notify when a run fails.', type: 'toggle', default: true },
  { id: 'notif-payment-failed', section: 'recurring', group: 'Notifications', label: 'Payment failure alert', description: 'Notify on failed recurring payments.', type: 'toggle', default: true },
  { id: 'notif-series-ending', section: 'recurring', group: 'Notifications', label: 'Series ending alert', description: 'Notify when a series is about to end.', type: 'toggle', default: true },
  { id: 'notif-card-expiring', section: 'recurring', group: 'Notifications', label: 'Card expiring alert', description: 'Notify when a stored card nears expiry.', type: 'toggle', default: true },
  { id: 'notif-amount-change', section: 'recurring', group: 'Notifications', label: 'Amount change alert', description: 'Notify when a template amount changes.', type: 'toggle', default: false },
  { id: 'notif-channel', section: 'recurring', group: 'Notifications', label: 'Notification channel', description: 'Where alerts are delivered.', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'notif-email-recipient', section: 'recurring', group: 'Notifications', label: 'Notification email', description: 'Recipient for emailed alerts.', type: 'text', default: '' },
  { id: 'notif-digest', section: 'recurring', group: 'Notifications', label: 'Daily digest', description: 'Bundle alerts into a single daily email.', type: 'toggle', default: false },
  { id: 'notif-digest-time', section: 'recurring', group: 'Notifications', label: 'Digest send time', description: 'Time of day the digest is sent.', type: 'text', default: '08:00' },
  { id: 'notif-weekend-quiet', section: 'recurring', group: 'Notifications', label: 'Quiet on weekends', description: 'Suppress alerts on weekends.', type: 'toggle', default: false },
  { id: 'notif-sound', section: 'recurring', group: 'Notifications', label: 'Play notification sound', description: 'Sound for in-app alerts.', type: 'toggle', default: true },
  { id: 'notif-badge-count', section: 'recurring', group: 'Notifications', label: 'Show sidebar badge', description: 'Badge with pending-run count.', type: 'toggle', default: true },
  { id: 'notif-customer-receipt', section: 'recurring', group: 'Notifications', label: 'Email customer receipt', description: 'Send receipts to the customer on charge.', type: 'toggle', default: true },
  { id: 'notif-customer-upcoming', section: 'recurring', group: 'Notifications', label: 'Notify customer of upcoming charge', description: 'Pre-charge heads-up to the customer.', type: 'toggle', default: false },
  { id: 'notif-customer-lead-days', section: 'recurring', group: 'Notifications', label: 'Customer notice lead (days)', description: 'Days before charge to notify customer.', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'notif-snooze-default', section: 'recurring', group: 'Notifications', label: 'Default snooze (hours)', description: 'Default snooze duration for alerts.', type: 'number', default: 24, min: 1, max: 168, step: 1 },
  { id: 'notif-escalate-repeated-fail', section: 'recurring', group: 'Notifications', label: 'Escalate repeated failures', description: 'Send urgent alert after repeated failures.', type: 'toggle', default: true },
  { id: 'notif-escalate-threshold', section: 'recurring', group: 'Notifications', label: 'Escalation threshold', description: 'Failures before escalating.', type: 'number', default: 3, min: 1, max: 10, step: 1 },

  // ============================ Export (161-178) ============================
  { id: 'export-default-format', section: 'recurring', group: 'Export', label: 'Default export format', description: 'Format used when exporting the list.', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'export-include-headers', section: 'recurring', group: 'Export', label: 'Include headers', description: 'Add a header row to exports.', type: 'toggle', default: true },
  { id: 'export-only-visible-columns', section: 'recurring', group: 'Export', label: 'Only visible columns', description: 'Export just the columns currently shown.', type: 'toggle', default: false },
  { id: 'export-include-inactive', section: 'recurring', group: 'Export', label: 'Include inactive templates', description: 'Include paused/ended schedules in exports.', type: 'toggle', default: true },
  { id: 'export-include-occurrences', section: 'recurring', group: 'Export', label: 'Include occurrence history', description: 'Append generated-run history rows.', type: 'toggle', default: false },
  { id: 'export-date-format', section: 'recurring', group: 'Export', label: 'Export date format', description: 'Date format used in export files.', type: 'select', default: 'iso', options: [{ value: 'iso', label: 'ISO 8601' }, { value: 'us', label: 'US (MM/DD/YYYY)' }, { value: 'eu', label: 'EU (DD/MM/YYYY)' }] },
  { id: 'export-csv-delimiter', section: 'recurring', group: 'Export', label: 'CSV delimiter', description: 'Field separator for CSV exports.', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'export-encoding', section: 'recurring', group: 'Export', label: 'File encoding', description: 'Character encoding for text exports.', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'export-amount-raw', section: 'recurring', group: 'Export', label: 'Raw numeric amounts', description: 'Export amounts without symbols/formatting.', type: 'toggle', default: true },
  { id: 'export-filename-pattern', section: 'recurring', group: 'Export', label: 'Filename pattern', description: 'Tokens like {{date}} for export filenames.', type: 'text', default: 'recurring-{{date}}' },
  { id: 'export-pdf-orientation', section: 'recurring', group: 'Export', label: 'PDF orientation', description: 'Page orientation for PDF exports.', type: 'select', default: 'landscape', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'export-pdf-include-logo', section: 'recurring', group: 'Export', label: 'Include company logo in PDF', description: 'Render the company logo in PDF headers.', type: 'toggle', default: true },
  { id: 'export-include-totals', section: 'recurring', group: 'Export', label: 'Include totals row', description: 'Append a sum row to exports.', type: 'toggle', default: true },
  { id: 'export-group-by-frequency', section: 'recurring', group: 'Export', label: 'Group export by frequency', description: 'Section exports by frequency.', type: 'toggle', default: false },
  { id: 'export-open-after', section: 'recurring', group: 'Export', label: 'Open file after export', description: 'Launch the export when finished.', type: 'toggle', default: true },
  { id: 'export-copy-to-clipboard', section: 'recurring', group: 'Export', label: 'Enable copy to clipboard', description: 'Allow copying selection as TSV.', type: 'toggle', default: true },
  { id: 'export-projection-months', section: 'recurring', group: 'Export', label: 'Cash-flow projection months', description: 'Months to project forward in exports.', type: 'number', default: 12, min: 1, max: 60, step: 1 },
  { id: 'export-include-projection', section: 'recurring', group: 'Export', label: 'Include forward projection', description: 'Add projected future runs to export.', type: 'toggle', default: false },

  // ========================= Colors & Theme (179-190) =========================
  { id: 'color-active', section: 'recurring', group: 'Colors & Theme', label: 'Active status color', description: 'Accent for active schedules.', type: 'color', default: '#22c55e' },
  { id: 'color-paused', section: 'recurring', group: 'Colors & Theme', label: 'Paused status color', description: 'Accent for paused schedules.', type: 'color', default: '#f59e0b' },
  { id: 'color-ended', section: 'recurring', group: 'Colors & Theme', label: 'Ended status color', description: 'Accent for ended schedules.', type: 'color', default: '#6b7280' },
  { id: 'color-failed', section: 'recurring', group: 'Colors & Theme', label: 'Failed run color', description: 'Accent for failed runs.', type: 'color', default: '#ef4444' },
  { id: 'color-due-soon', section: 'recurring', group: 'Colors & Theme', label: 'Due-soon highlight', description: 'Color for runs due within the window.', type: 'color', default: '#3b82f6' },
  { id: 'color-income', section: 'recurring', group: 'Colors & Theme', label: 'Income amount color', description: 'Color for income/invoice amounts.', type: 'color', default: '#16a34a' },
  { id: 'color-expense', section: 'recurring', group: 'Colors & Theme', label: 'Expense amount color', description: 'Color for expense/bill amounts.', type: 'color', default: '#dc2626' },
  { id: 'color-calendar-event', section: 'recurring', group: 'Colors & Theme', label: 'Calendar event color', description: 'Default color of calendar run markers.', type: 'color', default: '#8b5cf6' },
  { id: 'color-row-selected', section: 'recurring', group: 'Colors & Theme', label: 'Selected row color', description: 'Highlight for selected rows.', type: 'color', default: '#1e40af' },
  { id: 'color-badge-text', section: 'recurring', group: 'Colors & Theme', label: 'Badge text color', description: 'Text color inside status badges.', type: 'color', default: '#ffffff' },
  { id: 'color-coding-mode', section: 'recurring', group: 'Colors & Theme', label: 'Color-coding mode', description: 'What drives row/badge coloring.', type: 'select', default: 'status', options: [{ value: 'status', label: 'By status' }, { value: 'type', label: 'By type' }, { value: 'frequency', label: 'By frequency' }, { value: 'none', label: 'None' }] },
  { id: 'color-intensity', section: 'recurring', group: 'Colors & Theme', label: 'Color intensity', description: 'Saturation of accent colors.', type: 'select', default: 'normal', options: [{ value: 'subtle', label: 'Subtle' }, { value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' }] },

  // ========================== Accessibility (191-196) ==========================
  { id: 'a11y-high-contrast', section: 'recurring', group: 'Accessibility', label: 'High-contrast mode', description: 'Increase contrast across the section.', type: 'toggle', default: false },
  { id: 'a11y-status-icons', section: 'recurring', group: 'Accessibility', label: 'Status icons with color', description: 'Pair shapes/icons with status colors.', type: 'toggle', default: true },
  { id: 'a11y-font-scale', section: 'recurring', group: 'Accessibility', label: 'Font scale (%)', description: 'Scale text size in the section.', type: 'number', default: 100, min: 80, max: 160, step: 5 },
  { id: 'a11y-reduce-motion', section: 'recurring', group: 'Accessibility', label: 'Reduce motion', description: 'Minimize animations and transitions.', type: 'toggle', default: false },
  { id: 'a11y-keyboard-focus-ring', section: 'recurring', group: 'Accessibility', label: 'Visible focus ring', description: 'Strong outline on keyboard focus.', type: 'toggle', default: true },
  { id: 'a11y-screen-reader-summaries', section: 'recurring', group: 'Accessibility', label: 'Screen-reader summaries', description: 'Announce row summaries to assistive tech.', type: 'toggle', default: true },

  // ============================ Shortcuts (197-200) ============================
  { id: 'shortcut-new-template', section: 'recurring', group: 'Shortcuts', label: 'New template shortcut', description: 'Keyboard shortcut to create a template.', type: 'text', default: 'n' },
  { id: 'shortcut-run-now', section: 'recurring', group: 'Shortcuts', label: 'Run now shortcut', description: 'Shortcut to trigger the selected run.', type: 'text', default: 'r' },
  { id: 'shortcut-pause-toggle', section: 'recurring', group: 'Shortcuts', label: 'Pause/resume shortcut', description: 'Shortcut to toggle pause on selection.', type: 'text', default: 'p' },
  { id: 'shortcut-enable-shortcuts', section: 'recurring', group: 'Shortcuts', label: 'Enable keyboard shortcuts', description: 'Master switch for section shortcuts.', type: 'toggle', default: true },
];
