import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (1-20) =====
  { id: 'default-report', section: 'reports', group: 'Display', label: 'Default report on open', description: 'Which report opens first.', type: 'select', default: 'pnl', options: [{ value: 'pnl', label: 'Profit & Loss' }, { value: 'balance-sheet', label: 'Balance Sheet' }, { value: 'cash-flow', label: 'Cash Flow' }, { value: 'ar-aging', label: 'A/R Aging' }, { value: 'trial-balance', label: 'Trial Balance' }] },
  { id: 'show-report-thumbnails', section: 'reports', group: 'Display', label: 'Show report thumbnails', description: 'Preview tiles in the report gallery.', type: 'toggle', default: true },
  { id: 'reports-per-row', section: 'reports', group: 'Display', label: 'Report tiles per row', type: 'number', default: 4, min: 2, max: 8, step: 1 },
  { id: 'show-favorites-first', section: 'reports', group: 'Display', label: 'Show favorite reports first', type: 'toggle', default: true },
  { id: 'collapse-empty-sections', section: 'reports', group: 'Display', label: 'Collapse empty report sections', type: 'toggle', default: false },
  { id: 'report-view-mode', section: 'reports', group: 'Display', label: 'Default view mode', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'chart', label: 'Chart' }, { value: 'split', label: 'Table + Chart' }] },
  { id: 'show-report-description', section: 'reports', group: 'Display', label: 'Show report descriptions', type: 'toggle', default: true },
  { id: 'sticky-report-header', section: 'reports', group: 'Display', label: 'Sticky column headers while scrolling', type: 'toggle', default: true },
  { id: 'sticky-totals-row', section: 'reports', group: 'Display', label: 'Pin totals row to bottom', type: 'toggle', default: true },
  { id: 'show-row-numbers', section: 'reports', group: 'Display', label: 'Show row numbers', type: 'toggle', default: false },
  { id: 'compact-density', section: 'reports', group: 'Display', label: 'Table density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'show-company-logo', section: 'reports', group: 'Display', label: 'Show company logo on report', type: 'toggle', default: true },
  { id: 'show-report-title', section: 'reports', group: 'Display', label: 'Show report title header', type: 'toggle', default: true },
  { id: 'show-period-subtitle', section: 'reports', group: 'Display', label: 'Show period subtitle', type: 'toggle', default: true },
  { id: 'show-basis-label', section: 'reports', group: 'Display', label: 'Show accounting basis label', description: 'Cash vs Accrual indicator.', type: 'toggle', default: true },
  { id: 'wrap-long-account-names', section: 'reports', group: 'Display', label: 'Wrap long account names', type: 'toggle', default: false },
  { id: 'max-account-name-width', section: 'reports', group: 'Display', label: 'Max account name column width (px)', type: 'number', default: 280, min: 120, max: 600, step: 10 },
  { id: 'show-watermark-draft', section: 'reports', group: 'Display', label: 'Show DRAFT watermark on unfinalized reports', type: 'toggle', default: false },
  { id: 'fullscreen-on-open', section: 'reports', group: 'Display', label: 'Open reports in fullscreen', type: 'toggle', default: false },
  { id: 'show-account-numbers', section: 'reports', group: 'Display', label: 'Show account numbers beside names', type: 'toggle', default: false },

  // ===== Columns (21-40) =====
  { id: 'col-account', section: 'reports', group: 'Columns', label: 'Account / Line column', type: 'toggle', default: true },
  { id: 'col-current-period', section: 'reports', group: 'Columns', label: 'Current period column', type: 'toggle', default: true },
  { id: 'col-prior-period', section: 'reports', group: 'Columns', label: 'Prior period column', type: 'toggle', default: false },
  { id: 'col-variance-amount', section: 'reports', group: 'Columns', label: 'Variance ($) column', type: 'toggle', default: false },
  { id: 'col-variance-percent', section: 'reports', group: 'Columns', label: 'Variance (%) column', type: 'toggle', default: false },
  { id: 'col-budget', section: 'reports', group: 'Columns', label: 'Budget column', type: 'toggle', default: false },
  { id: 'col-budget-variance', section: 'reports', group: 'Columns', label: 'Budget variance column', type: 'toggle', default: false },
  { id: 'col-percent-of-income', section: 'reports', group: 'Columns', label: '% of income column', type: 'toggle', default: false },
  { id: 'col-ytd', section: 'reports', group: 'Columns', label: 'Year-to-date column', type: 'toggle', default: true },
  { id: 'col-account-type', section: 'reports', group: 'Columns', label: 'Account type column', type: 'toggle', default: false },
  { id: 'col-class', section: 'reports', group: 'Columns', label: 'Class / department column', type: 'toggle', default: false },
  { id: 'col-location', section: 'reports', group: 'Columns', label: 'Location column', type: 'toggle', default: false },
  { id: 'col-quantity', section: 'reports', group: 'Columns', label: 'Quantity column', type: 'toggle', default: false },
  { id: 'aging-buckets', section: 'reports', group: 'Columns', label: 'Aging bucket scheme', description: 'Day ranges for A/R and A/P aging.', type: 'select', default: '30-60-90', options: [{ value: '30-60-90', label: '0-30 / 31-60 / 61-90 / 90+' }, { value: '15-30-45', label: '0-15 / 16-30 / 31-45 / 45+' }, { value: '7-14-30', label: 'Weekly buckets' }] },
  { id: 'col-days-overdue', section: 'reports', group: 'Columns', label: 'Days overdue column (aging)', type: 'toggle', default: true },
  { id: 'freeze-first-column', section: 'reports', group: 'Columns', label: 'Freeze first column', type: 'toggle', default: true },
  { id: 'frozen-column-count', section: 'reports', group: 'Columns', label: 'Number of frozen columns', type: 'number', default: 1, min: 0, max: 4, step: 1 },
  { id: 'col-min-width', section: 'reports', group: 'Columns', label: 'Minimum amount column width (px)', type: 'number', default: 110, min: 60, max: 300, step: 10 },
  { id: 'autosize-columns', section: 'reports', group: 'Columns', label: 'Auto-size columns to content', type: 'toggle', default: true },
  { id: 'col-running-balance', section: 'reports', group: 'Columns', label: 'Running balance column (registers)', type: 'toggle', default: true },

  // ===== Formatting (41-62) =====
  { id: 'currency-symbol', section: 'reports', group: 'Formatting', label: 'Show currency symbol', type: 'toggle', default: true },
  { id: 'currency-code-position', section: 'reports', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($100)' }, { value: 'after', label: 'After (100$)' }] },
  { id: 'decimal-places', section: 'reports', group: 'Formatting', label: 'Decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'thousands-separator', section: 'reports', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma (1,000)' }, { value: 'period', label: 'Period (1.000)' }, { value: 'space', label: 'Space (1 000)' }, { value: 'none', label: 'None' }] },
  { id: 'negative-style', section: 'reports', group: 'Formatting', label: 'Negative number style', type: 'select', default: 'parentheses', options: [{ value: 'parentheses', label: '(1,000)' }, { value: 'minus', label: '-1,000' }, { value: 'red', label: 'Red text' }, { value: 'red-parentheses', label: 'Red (1,000)' }] },
  { id: 'zero-as-dash', section: 'reports', group: 'Formatting', label: 'Show zero values as dash', type: 'toggle', default: false },
  { id: 'hide-zero-rows', section: 'reports', group: 'Formatting', label: 'Hide rows that are all zero', type: 'toggle', default: true },
  { id: 'scale-units', section: 'reports', group: 'Formatting', label: 'Number scale', type: 'select', default: 'actual', options: [{ value: 'actual', label: 'Actual' }, { value: 'thousands', label: 'Thousands (K)' }, { value: 'millions', label: 'Millions (M)' }] },
  { id: 'percent-decimal-places', section: 'reports', group: 'Formatting', label: 'Percentage decimal places', type: 'number', default: 1, min: 0, max: 3, step: 1 },
  { id: 'date-format', section: 'reports', group: 'Formatting', label: 'Date format', type: 'select', default: 'mdy', options: [{ value: 'mdy', label: 'MM/DD/YYYY' }, { value: 'dmy', label: 'DD/MM/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'long', label: 'Month D, YYYY' }] },
  { id: 'bold-subtotals', section: 'reports', group: 'Formatting', label: 'Bold subtotal rows', type: 'toggle', default: true },
  { id: 'bold-grand-total', section: 'reports', group: 'Formatting', label: 'Bold grand total row', type: 'toggle', default: true },
  { id: 'underline-totals', section: 'reports', group: 'Formatting', label: 'Underline above totals', type: 'toggle', default: true },
  { id: 'indent-subaccounts', section: 'reports', group: 'Formatting', label: 'Indent sub-accounts', type: 'toggle', default: true },
  { id: 'indent-width', section: 'reports', group: 'Formatting', label: 'Indent width per level (px)', type: 'number', default: 16, min: 4, max: 48, step: 2 },
  { id: 'font-size', section: 'reports', group: 'Formatting', label: 'Report font size (px)', type: 'number', default: 13, min: 9, max: 20, step: 1 },
  { id: 'report-font', section: 'reports', group: 'Formatting', label: 'Report font family', type: 'select', default: 'system', options: [{ value: 'system', label: 'System' }, { value: 'serif', label: 'Serif' }, { value: 'mono', label: 'Monospace' }] },
  { id: 'align-amounts', section: 'reports', group: 'Formatting', label: 'Amount alignment', type: 'select', default: 'right', options: [{ value: 'right', label: 'Right' }, { value: 'left', label: 'Left' }, { value: 'decimal', label: 'Decimal-aligned' }] },
  { id: 'show-cents-on-totals-only', section: 'reports', group: 'Formatting', label: 'Show cents on totals only', type: 'toggle', default: false },
  { id: 'rounding-mode', section: 'reports', group: 'Formatting', label: 'Rounding mode', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Half up' }, { value: 'half-even', label: 'Bankers' }, { value: 'down', label: 'Truncate' }] },
  { id: 'show-account-codes-prefix', section: 'reports', group: 'Formatting', label: 'Prefix lines with account codes', type: 'toggle', default: false },
  { id: 'blank-line-between-groups', section: 'reports', group: 'Formatting', label: 'Blank line between groups', type: 'toggle', default: true },

  // ===== Defaults (63-82) =====
  { id: 'default-basis', section: 'reports', group: 'Defaults', label: 'Default accounting basis', type: 'select', default: 'accrual', options: [{ value: 'accrual', label: 'Accrual' }, { value: 'cash', label: 'Cash' }] },
  { id: 'default-date-range', section: 'reports', group: 'Defaults', label: 'Default date range', type: 'select', default: 'this-month', options: [{ value: 'today', label: 'Today' }, { value: 'this-week', label: 'This week' }, { value: 'this-month', label: 'This month' }, { value: 'this-quarter', label: 'This quarter' }, { value: 'this-year', label: 'This year' }, { value: 'custom', label: 'Last used custom' }] },
  { id: 'fiscal-year-start', section: 'reports', group: 'Defaults', label: 'Fiscal year start month', type: 'select', default: 'january', options: [{ value: 'january', label: 'January' }, { value: 'april', label: 'April' }, { value: 'july', label: 'July' }, { value: 'october', label: 'October' }] },
  { id: 'default-comparison', section: 'reports', group: 'Defaults', label: 'Default comparison period', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'prior-period', label: 'Prior period' }, { value: 'prior-year', label: 'Prior year' }, { value: 'budget', label: 'Budget' }] },
  { id: 'default-period-grouping', section: 'reports', group: 'Defaults', label: 'Default column period grouping', type: 'select', default: 'total', options: [{ value: 'total', label: 'Total only' }, { value: 'month', label: 'By month' }, { value: 'quarter', label: 'By quarter' }, { value: 'year', label: 'By year' }] },
  { id: 'default-currency', section: 'reports', group: 'Defaults', label: 'Default reporting currency', type: 'text', default: 'USD' },
  { id: 'default-class-filter', section: 'reports', group: 'Defaults', label: 'Default class/department filter', type: 'text', default: '' },
  { id: 'remember-last-filters', section: 'reports', group: 'Defaults', label: 'Remember last-used filters per report', type: 'toggle', default: true },
  { id: 'default-rows-per-page', section: 'reports', group: 'Defaults', label: 'Default rows per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'default-sort-field', section: 'reports', group: 'Defaults', label: 'Default sort field', type: 'select', default: 'account', options: [{ value: 'account', label: 'Account' }, { value: 'amount', label: 'Amount' }, { value: 'date', label: 'Date' }, { value: 'name', label: 'Name' }] },
  { id: 'include-inactive-accounts', section: 'reports', group: 'Defaults', label: 'Include inactive accounts', type: 'toggle', default: false },
  { id: 'include-unposted', section: 'reports', group: 'Defaults', label: 'Include unposted transactions', type: 'toggle', default: false },
  { id: 'default-detail-level', section: 'reports', group: 'Defaults', label: 'Default detail level', type: 'select', default: 'summary', options: [{ value: 'summary', label: 'Summary' }, { value: 'detail', label: 'Detail' }, { value: 'full-detail', label: 'Full transaction detail' }] },
  { id: 'auto-expand-all', section: 'reports', group: 'Defaults', label: 'Auto-expand all groups on open', type: 'toggle', default: false },
  { id: 'default-aging-as-of', section: 'reports', group: 'Defaults', label: 'Default aging "as of" date', type: 'select', default: 'today', options: [{ value: 'today', label: 'Today' }, { value: 'period-end', label: 'Period end' }, { value: 'custom', label: 'Custom' }] },
  { id: 'default-budget-name', section: 'reports', group: 'Defaults', label: 'Default budget to compare against', type: 'text', default: '' },
  { id: 'multicompany-consolidate', section: 'reports', group: 'Defaults', label: 'Consolidate multi-company by default', type: 'toggle', default: false },
  { id: 'default-tax-line-mapping', section: 'reports', group: 'Defaults', label: 'Show tax-line mapping by default', type: 'toggle', default: false },
  { id: 'default-report-header-text', section: 'reports', group: 'Defaults', label: 'Custom report header text', type: 'text', default: '' },
  { id: 'default-report-footer-text', section: 'reports', group: 'Defaults', label: 'Custom report footer text', type: 'text', default: '' },

  // ===== Sorting & Filtering (83-100) =====
  { id: 'sort-direction', section: 'reports', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'sort-totals-by-amount', section: 'reports', group: 'Sorting & Filtering', label: 'Sort groups by total amount', type: 'toggle', default: false },
  { id: 'natural-sort-accounts', section: 'reports', group: 'Sorting & Filtering', label: 'Natural-sort account numbers', type: 'toggle', default: true },
  { id: 'amount-threshold-filter', section: 'reports', group: 'Sorting & Filtering', label: 'Hide rows below amount threshold', type: 'number', default: 0, min: 0, max: 100000, step: 50 },
  { id: 'show-filter-bar', section: 'reports', group: 'Sorting & Filtering', label: 'Show quick-filter bar', type: 'toggle', default: true },
  { id: 'persist-search-text', section: 'reports', group: 'Sorting & Filtering', label: 'Persist search text between sessions', type: 'toggle', default: false },
  { id: 'filter-match-mode', section: 'reports', group: 'Sorting & Filtering', label: 'Filter match mode', type: 'select', default: 'contains', options: [{ value: 'contains', label: 'Contains' }, { value: 'starts-with', label: 'Starts with' }, { value: 'exact', label: 'Exact' }] },
  { id: 'case-sensitive-search', section: 'reports', group: 'Sorting & Filtering', label: 'Case-sensitive search', type: 'toggle', default: false },
  { id: 'top-n-rows', section: 'reports', group: 'Sorting & Filtering', label: 'Limit to top N rows (0 = all)', type: 'number', default: 0, min: 0, max: 1000, step: 5 },
  { id: 'group-by-field', section: 'reports', group: 'Sorting & Filtering', label: 'Group rows by', type: 'select', default: 'account-type', options: [{ value: 'account-type', label: 'Account type' }, { value: 'class', label: 'Class' }, { value: 'location', label: 'Location' }, { value: 'customer', label: 'Customer' }, { value: 'vendor', label: 'Vendor' }, { value: 'none', label: 'None' }] },
  { id: 'exclude-zero-balance-customers', section: 'reports', group: 'Sorting & Filtering', label: 'Exclude zero-balance customers (aging)', type: 'toggle', default: true },
  { id: 'show-only-overdue', section: 'reports', group: 'Sorting & Filtering', label: 'Show only overdue items by default', type: 'toggle', default: false },
  { id: 'default-account-filter', section: 'reports', group: 'Sorting & Filtering', label: 'Default account filter (range)', type: 'text', default: '' },
  { id: 'highlight-search-matches', section: 'reports', group: 'Sorting & Filtering', label: 'Highlight search matches', type: 'toggle', default: true },
  { id: 'remember-collapsed-groups', section: 'reports', group: 'Sorting & Filtering', label: 'Remember collapsed groups', type: 'toggle', default: true },
  { id: 'multi-sort', section: 'reports', group: 'Sorting & Filtering', label: 'Enable multi-column sort', type: 'toggle', default: false },
  { id: 'filter-by-tag', section: 'reports', group: 'Sorting & Filtering', label: 'Default transaction tag filter', type: 'text', default: '' },
  { id: 'min-days-overdue-filter', section: 'reports', group: 'Sorting & Filtering', label: 'Minimum days overdue to show', type: 'number', default: 0, min: 0, max: 365, step: 1 },

  // ===== Behavior (101-118) =====
  { id: 'auto-refresh', section: 'reports', group: 'Behavior', label: 'Auto-refresh reports on data change', type: 'toggle', default: true },
  { id: 'auto-refresh-interval', section: 'reports', group: 'Behavior', label: 'Auto-refresh interval (seconds)', type: 'number', default: 60, min: 5, max: 600, step: 5 },
  { id: 'drill-down-enabled', section: 'reports', group: 'Behavior', label: 'Enable drill-down on amounts', type: 'toggle', default: true },
  { id: 'drill-down-target', section: 'reports', group: 'Behavior', label: 'Drill-down opens', type: 'select', default: 'modal', options: [{ value: 'modal', label: 'Modal' }, { value: 'panel', label: 'Side panel' }, { value: 'new-tab', label: 'New tab' }] },
  { id: 'confirm-before-large-report', section: 'reports', group: 'Behavior', label: 'Confirm before running large reports', type: 'toggle', default: true },
  { id: 'large-report-row-warning', section: 'reports', group: 'Behavior', label: 'Row count that triggers warning', type: 'number', default: 5000, min: 500, max: 100000, step: 500 },
  { id: 'cache-report-results', section: 'reports', group: 'Behavior', label: 'Cache report results', type: 'toggle', default: true },
  { id: 'cache-ttl-minutes', section: 'reports', group: 'Behavior', label: 'Cache lifetime (minutes)', type: 'number', default: 15, min: 1, max: 240, step: 1 },
  { id: 'remember-scroll-position', section: 'reports', group: 'Behavior', label: 'Remember scroll position', type: 'toggle', default: true },
  { id: 'open-last-report-on-launch', section: 'reports', group: 'Behavior', label: 'Reopen last report on launch', type: 'toggle', default: false },
  { id: 'double-click-action', section: 'reports', group: 'Behavior', label: 'Double-click row action', type: 'select', default: 'drill', options: [{ value: 'drill', label: 'Drill down' }, { value: 'edit', label: 'Edit transaction' }, { value: 'nothing', label: 'Nothing' }] },
  { id: 'lazy-load-rows', section: 'reports', group: 'Behavior', label: 'Lazy-load long reports', type: 'toggle', default: true },
  { id: 'autosave-custom-reports', section: 'reports', group: 'Behavior', label: 'Auto-save custom report changes', type: 'toggle', default: false },
  { id: 'recalc-on-filter-change', section: 'reports', group: 'Behavior', label: 'Recalculate immediately on filter change', type: 'toggle', default: true },
  { id: 'keep-totals-while-filtering', section: 'reports', group: 'Behavior', label: 'Keep full totals while filtering', type: 'toggle', default: false },
  { id: 'warn-unsaved-customizations', section: 'reports', group: 'Behavior', label: 'Warn on unsaved customizations', type: 'toggle', default: true },
  { id: 'default-favorite-reports', section: 'reports', group: 'Behavior', label: 'Favorite report IDs (comma-separated)', type: 'text', default: 'pnl,balance-sheet' },
  { id: 'snap-date-to-period', section: 'reports', group: 'Behavior', label: 'Snap custom dates to period boundaries', type: 'toggle', default: true },

  // ===== Notifications (119-134) =====
  { id: 'notify-report-ready', section: 'reports', group: 'Notifications', label: 'Notify when long report finishes', type: 'toggle', default: true },
  { id: 'notify-scheduled-sent', section: 'reports', group: 'Notifications', label: 'Notify when scheduled report is sent', type: 'toggle', default: true },
  { id: 'notify-scheduled-failed', section: 'reports', group: 'Notifications', label: 'Alert when scheduled report fails', type: 'toggle', default: true },
  { id: 'notify-variance-threshold', section: 'reports', group: 'Notifications', label: 'Alert when variance exceeds threshold', type: 'toggle', default: false },
  { id: 'variance-alert-percent', section: 'reports', group: 'Notifications', label: 'Variance alert threshold (%)', type: 'number', default: 10, min: 1, max: 100, step: 1 },
  { id: 'notify-out-of-balance', section: 'reports', group: 'Notifications', label: 'Alert when balance sheet is out of balance', type: 'toggle', default: true },
  { id: 'notify-negative-cash', section: 'reports', group: 'Notifications', label: 'Alert on negative cash balance', type: 'toggle', default: true },
  { id: 'notify-overdue-spike', section: 'reports', group: 'Notifications', label: 'Alert on A/R overdue spike', type: 'toggle', default: false },
  { id: 'notification-channel', section: 'reports', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'notification-email', section: 'reports', group: 'Notifications', label: 'Notification email address', type: 'text', default: '' },
  { id: 'digest-frequency', section: 'reports', group: 'Notifications', label: 'Report digest frequency', type: 'select', default: 'weekly', options: [{ value: 'off', label: 'Off' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }] },
  { id: 'digest-time', section: 'reports', group: 'Notifications', label: 'Digest send time (24h hour)', type: 'number', default: 8, min: 0, max: 23, step: 1 },
  { id: 'notify-data-stale', section: 'reports', group: 'Notifications', label: 'Warn when report data is stale', type: 'toggle', default: true },
  { id: 'stale-data-hours', section: 'reports', group: 'Notifications', label: 'Stale-data threshold (hours)', type: 'number', default: 24, min: 1, max: 168, step: 1 },
  { id: 'sound-on-alert', section: 'reports', group: 'Notifications', label: 'Play sound on report alert', type: 'toggle', default: false },
  { id: 'notify-budget-overrun', section: 'reports', group: 'Notifications', label: 'Alert when actuals exceed budget', type: 'toggle', default: false },

  // ===== Export (135-156) =====
  { id: 'default-export-format', section: 'reports', group: 'Export', label: 'Default export format', type: 'select', default: 'pdf', options: [{ value: 'pdf', label: 'PDF' }, { value: 'xlsx', label: 'Excel' }, { value: 'csv', label: 'CSV' }, { value: 'json', label: 'JSON' }] },
  { id: 'pdf-page-size', section: 'reports', group: 'Export', label: 'PDF page size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'legal', label: 'Legal' }, { value: 'a4', label: 'A4' }] },
  { id: 'pdf-orientation', section: 'reports', group: 'Export', label: 'PDF orientation', type: 'select', default: 'portrait', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'pdf-margin', section: 'reports', group: 'Export', label: 'PDF margin (mm)', type: 'number', default: 18, min: 5, max: 50, step: 1 },
  { id: 'include-cover-page', section: 'reports', group: 'Export', label: 'Include cover page in PDF', type: 'toggle', default: false },
  { id: 'export-include-logo', section: 'reports', group: 'Export', label: 'Include logo in exports', type: 'toggle', default: true },
  { id: 'export-include-footer', section: 'reports', group: 'Export', label: 'Include footer with page numbers', type: 'toggle', default: true },
  { id: 'export-include-timestamp', section: 'reports', group: 'Export', label: 'Include generated timestamp', type: 'toggle', default: true },
  { id: 'export-include-filters', section: 'reports', group: 'Export', label: 'Include applied filters summary', type: 'toggle', default: true },
  { id: 'csv-delimiter', section: 'reports', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'csv-include-header', section: 'reports', group: 'Export', label: 'Include header row in CSV', type: 'toggle', default: true },
  { id: 'csv-unformatted-numbers', section: 'reports', group: 'Export', label: 'Export raw unformatted numbers', type: 'toggle', default: true },
  { id: 'xlsx-freeze-header', section: 'reports', group: 'Export', label: 'Freeze header row in Excel', type: 'toggle', default: true },
  { id: 'xlsx-auto-filter', section: 'reports', group: 'Export', label: 'Add auto-filter in Excel', type: 'toggle', default: true },
  { id: 'xlsx-one-sheet-per-group', section: 'reports', group: 'Export', label: 'One worksheet per group', type: 'toggle', default: false },
  { id: 'export-filename-pattern', section: 'reports', group: 'Export', label: 'Export filename pattern', type: 'text', default: '{report}-{period}-{date}' },
  { id: 'export-open-after', section: 'reports', group: 'Export', label: 'Open file after export', type: 'toggle', default: true },
  { id: 'export-destination', section: 'reports', group: 'Export', label: 'Default export folder', type: 'text', default: '' },
  { id: 'email-export-default-subject', section: 'reports', group: 'Export', label: 'Default email subject for exports', type: 'text', default: 'Financial Report' },
  { id: 'export-password-protect-pdf', section: 'reports', group: 'Export', label: 'Password-protect exported PDFs', type: 'toggle', default: false },
  { id: 'export-compress-images', section: 'reports', group: 'Export', label: 'Compress chart images in export', type: 'toggle', default: true },
  { id: 'print-each-section-new-page', section: 'reports', group: 'Export', label: 'Start each section on a new page', type: 'toggle', default: false },

  // ===== Charts (157-172) =====
  { id: 'show-charts', section: 'reports', group: 'Charts', label: 'Show charts alongside tables', type: 'toggle', default: true },
  { id: 'default-chart-type', section: 'reports', group: 'Charts', label: 'Default chart type', type: 'select', default: 'bar', options: [{ value: 'bar', label: 'Bar' }, { value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }, { value: 'pie', label: 'Pie' }, { value: 'donut', label: 'Donut' }] },
  { id: 'chart-height', section: 'reports', group: 'Charts', label: 'Chart height (px)', type: 'number', default: 320, min: 150, max: 800, step: 10 },
  { id: 'chart-show-legend', section: 'reports', group: 'Charts', label: 'Show chart legend', type: 'toggle', default: true },
  { id: 'chart-legend-position', section: 'reports', group: 'Charts', label: 'Legend position', type: 'select', default: 'bottom', options: [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }, { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }] },
  { id: 'chart-show-data-labels', section: 'reports', group: 'Charts', label: 'Show data labels on points', type: 'toggle', default: false },
  { id: 'chart-show-gridlines', section: 'reports', group: 'Charts', label: 'Show gridlines', type: 'toggle', default: true },
  { id: 'chart-animations', section: 'reports', group: 'Charts', label: 'Enable chart animations', type: 'toggle', default: true },
  { id: 'chart-stacked', section: 'reports', group: 'Charts', label: 'Stack series by default', type: 'toggle', default: false },
  { id: 'chart-show-trendline', section: 'reports', group: 'Charts', label: 'Show trendline', type: 'toggle', default: false },
  { id: 'chart-y-axis-zero', section: 'reports', group: 'Charts', label: 'Force Y-axis to start at zero', type: 'toggle', default: true },
  { id: 'chart-smooth-lines', section: 'reports', group: 'Charts', label: 'Smooth line curves', type: 'toggle', default: false },
  { id: 'chart-max-slices', section: 'reports', group: 'Charts', label: 'Max pie slices before "Other"', type: 'number', default: 8, min: 3, max: 20, step: 1 },
  { id: 'chart-tooltip-detail', section: 'reports', group: 'Charts', label: 'Tooltip detail level', type: 'select', default: 'standard', options: [{ value: 'minimal', label: 'Minimal' }, { value: 'standard', label: 'Standard' }, { value: 'verbose', label: 'Verbose' }] },
  { id: 'chart-show-percent-labels', section: 'reports', group: 'Charts', label: 'Show percentage labels on pie', type: 'toggle', default: true },
  { id: 'sparklines-in-table', section: 'reports', group: 'Charts', label: 'Show sparklines in table rows', type: 'toggle', default: false },

  // ===== Colors & Theme (173-186) =====
  { id: 'positive-color', section: 'reports', group: 'Colors & Theme', label: 'Positive value color', type: 'color', default: '#16a34a' },
  { id: 'negative-color', section: 'reports', group: 'Colors & Theme', label: 'Negative value color', type: 'color', default: '#dc2626' },
  { id: 'total-row-bg', section: 'reports', group: 'Colors & Theme', label: 'Total row background', type: 'color', default: '#1e293b' },
  { id: 'header-bg-color', section: 'reports', group: 'Colors & Theme', label: 'Column header background', type: 'color', default: '#0f172a' },
  { id: 'zebra-stripe-rows', section: 'reports', group: 'Colors & Theme', label: 'Zebra-stripe rows', type: 'toggle', default: true },
  { id: 'zebra-stripe-color', section: 'reports', group: 'Colors & Theme', label: 'Zebra stripe color', type: 'color', default: '#111827' },
  { id: 'chart-accent-color', section: 'reports', group: 'Colors & Theme', label: 'Primary chart color', type: 'color', default: '#3b82f6' },
  { id: 'chart-secondary-color', section: 'reports', group: 'Colors & Theme', label: 'Secondary chart color', type: 'color', default: '#8b5cf6' },
  { id: 'budget-line-color', section: 'reports', group: 'Colors & Theme', label: 'Budget reference line color', type: 'color', default: '#f59e0b' },
  { id: 'overdue-highlight-color', section: 'reports', group: 'Colors & Theme', label: 'Overdue row highlight', type: 'color', default: '#7f1d1d' },
  { id: 'chart-palette', section: 'reports', group: 'Colors & Theme', label: 'Chart color palette', type: 'select', default: 'default', options: [{ value: 'default', label: 'Default' }, { value: 'colorblind', label: 'Colorblind-safe' }, { value: 'mono', label: 'Monochrome' }, { value: 'pastel', label: 'Pastel' }] },
  { id: 'grid-line-color', section: 'reports', group: 'Colors & Theme', label: 'Table grid line color', type: 'color', default: '#334155' },
  { id: 'show-grid-lines', section: 'reports', group: 'Colors & Theme', label: 'Show table grid lines', type: 'toggle', default: true },
  { id: 'highlight-current-row', section: 'reports', group: 'Colors & Theme', label: 'Highlight hovered row', type: 'toggle', default: true },

  // ===== Accessibility (187-194) =====
  { id: 'high-contrast', section: 'reports', group: 'Accessibility', label: 'High-contrast mode', type: 'toggle', default: false },
  { id: 'reduce-motion', section: 'reports', group: 'Accessibility', label: 'Reduce motion / animations', type: 'toggle', default: false },
  { id: 'never-color-only', section: 'reports', group: 'Accessibility', label: 'Never convey meaning by color alone', description: 'Add symbols for positive/negative.', type: 'toggle', default: false },
  { id: 'larger-touch-targets', section: 'reports', group: 'Accessibility', label: 'Larger touch targets', type: 'toggle', default: false },
  { id: 'screen-reader-summaries', section: 'reports', group: 'Accessibility', label: 'Announce report summaries to screen readers', type: 'toggle', default: true },
  { id: 'min-font-size', section: 'reports', group: 'Accessibility', label: 'Minimum enforced font size (px)', type: 'number', default: 12, min: 8, max: 24, step: 1 },
  { id: 'focus-outline-width', section: 'reports', group: 'Accessibility', label: 'Focus outline width (px)', type: 'number', default: 2, min: 1, max: 6, step: 1 },
  { id: 'keyboard-only-navigation', section: 'reports', group: 'Accessibility', label: 'Optimize for keyboard-only navigation', type: 'toggle', default: false },

  // ===== Shortcuts (195-197) =====
  { id: 'shortcut-run-report', section: 'reports', group: 'Shortcuts', label: 'Run/refresh report shortcut', type: 'text', default: 'Cmd+R' },
  { id: 'shortcut-export', section: 'reports', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'Cmd+E' },
  { id: 'enable-shortcuts', section: 'reports', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },

  // ===== Privacy (198-200) =====
  { id: 'mask-amounts', section: 'reports', group: 'Privacy', label: 'Mask amounts until hover', description: 'Hide figures for screen-sharing.', type: 'toggle', default: false },
  { id: 'redact-on-export', section: 'reports', group: 'Privacy', label: 'Allow redacting accounts on export', type: 'toggle', default: false },
  { id: 'audit-log-report-views', section: 'reports', group: 'Privacy', label: 'Log who views financial reports', type: 'toggle', default: true },
];
