import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display (group) =====
  { id: 'taxes-default-view', section: 'taxes', group: 'Display', label: 'Default tax view', description: 'Which screen opens first in the Taxes module', type: 'select', default: 'summary', options: [{ value: 'summary', label: 'Tax Summary' }, { value: 'liabilities', label: 'Liabilities' }, { value: 'filings', label: 'Filings' }, { value: 'estimates', label: 'Estimated Payments' }] },
  { id: 'taxes-show-ytd-banner', section: 'taxes', group: 'Display', label: 'Show year-to-date tax banner', description: 'Display a YTD tax liability banner at the top', type: 'toggle', default: true },
  { id: 'taxes-density', section: 'taxes', group: 'Display', label: 'Table row density', type: 'select', default: 'comfortable', options: [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] },
  { id: 'taxes-rows-per-page', section: 'taxes', group: 'Display', label: 'Rows per page', type: 'number', default: 25, min: 10, max: 200, step: 5 },
  { id: 'taxes-show-empty-periods', section: 'taxes', group: 'Display', label: 'Show periods with no liability', type: 'toggle', default: false },
  { id: 'taxes-collapse-paid', section: 'taxes', group: 'Display', label: 'Collapse fully paid filings', type: 'toggle', default: true },
  { id: 'taxes-show-jurisdiction-flags', section: 'taxes', group: 'Display', label: 'Show jurisdiction flag icons', type: 'toggle', default: true },
  { id: 'taxes-sticky-header', section: 'taxes', group: 'Display', label: 'Sticky table header on scroll', type: 'toggle', default: true },
  { id: 'taxes-show-record-count', section: 'taxes', group: 'Display', label: 'Show record count footer', type: 'toggle', default: true },
  { id: 'taxes-card-vs-table', section: 'taxes', group: 'Display', label: 'Filing layout style', type: 'select', default: 'table', options: [{ value: 'table', label: 'Table' }, { value: 'cards', label: 'Cards' }, { value: 'timeline', label: 'Timeline' }] },
  { id: 'taxes-show-progress-bars', section: 'taxes', group: 'Display', label: 'Show payment progress bars', type: 'toggle', default: true },
  { id: 'taxes-zebra-stripes', section: 'taxes', group: 'Display', label: 'Zebra-striped rows', type: 'toggle', default: false },
  { id: 'taxes-show-fiscal-quarter', section: 'taxes', group: 'Display', label: 'Show fiscal quarter labels', type: 'toggle', default: true },
  { id: 'taxes-pin-current-period', section: 'taxes', group: 'Display', label: 'Pin current tax period to top', type: 'toggle', default: true },
  { id: 'taxes-show-tax-id-masked', section: 'taxes', group: 'Display', label: 'Mask tax ID numbers in tables', type: 'toggle', default: true },

  // ===== Columns (group) =====
  { id: 'taxes-col-period', section: 'taxes', group: 'Columns', label: 'Show Period column', type: 'toggle', default: true },
  { id: 'taxes-col-jurisdiction', section: 'taxes', group: 'Columns', label: 'Show Jurisdiction column', type: 'toggle', default: true },
  { id: 'taxes-col-tax-type', section: 'taxes', group: 'Columns', label: 'Show Tax Type column', type: 'toggle', default: true },
  { id: 'taxes-col-taxable-base', section: 'taxes', group: 'Columns', label: 'Show Taxable Base column', type: 'toggle', default: false },
  { id: 'taxes-col-rate', section: 'taxes', group: 'Columns', label: 'Show Rate column', type: 'toggle', default: true },
  { id: 'taxes-col-liability', section: 'taxes', group: 'Columns', label: 'Show Liability column', type: 'toggle', default: true },
  { id: 'taxes-col-paid', section: 'taxes', group: 'Columns', label: 'Show Amount Paid column', type: 'toggle', default: true },
  { id: 'taxes-col-balance', section: 'taxes', group: 'Columns', label: 'Show Balance Due column', type: 'toggle', default: true },
  { id: 'taxes-col-due-date', section: 'taxes', group: 'Columns', label: 'Show Due Date column', type: 'toggle', default: true },
  { id: 'taxes-col-filed-date', section: 'taxes', group: 'Columns', label: 'Show Filed Date column', type: 'toggle', default: false },
  { id: 'taxes-col-confirmation', section: 'taxes', group: 'Columns', label: 'Show Confirmation # column', type: 'toggle', default: false },
  { id: 'taxes-col-status', section: 'taxes', group: 'Columns', label: 'Show Status column', type: 'toggle', default: true },
  { id: 'taxes-col-penalty', section: 'taxes', group: 'Columns', label: 'Show Penalty column', type: 'toggle', default: false },
  { id: 'taxes-col-interest', section: 'taxes', group: 'Columns', label: 'Show Interest column', type: 'toggle', default: false },
  { id: 'taxes-col-form-number', section: 'taxes', group: 'Columns', label: 'Show Form Number column', type: 'toggle', default: true },
  { id: 'taxes-col-preparer', section: 'taxes', group: 'Columns', label: 'Show Preparer column', type: 'toggle', default: false },
  { id: 'taxes-col-notes', section: 'taxes', group: 'Columns', label: 'Show Notes column', type: 'toggle', default: false },
  { id: 'taxes-col-attachments', section: 'taxes', group: 'Columns', label: 'Show Attachments column', type: 'toggle', default: true },
  { id: 'taxes-col-order', section: 'taxes', group: 'Columns', label: 'Column order preset', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'financial-first', label: 'Financial First' }, { value: 'compliance-first', label: 'Compliance First' }] },
  { id: 'taxes-frozen-columns', section: 'taxes', group: 'Columns', label: 'Number of frozen left columns', type: 'number', default: 1, min: 0, max: 4, step: 1 },

  // ===== Formatting (group) =====
  { id: 'taxes-currency-symbol', section: 'taxes', group: 'Formatting', label: 'Currency symbol', type: 'select', default: 'usd', options: [{ value: 'usd', label: '$ USD' }, { value: 'eur', label: '€ EUR' }, { value: 'gbp', label: '£ GBP' }, { value: 'cad', label: 'C$ CAD' }, { value: 'aud', label: 'A$ AUD' }] },
  { id: 'taxes-decimal-places', section: 'taxes', group: 'Formatting', label: 'Currency decimal places', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'taxes-thousands-separator', section: 'taxes', group: 'Formatting', label: 'Thousands separator', type: 'select', default: 'comma', options: [{ value: 'comma', label: '1,000' }, { value: 'period', label: '1.000' }, { value: 'space', label: '1 000' }, { value: 'none', label: '1000' }] },
  { id: 'taxes-negative-style', section: 'taxes', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'parentheses', options: [{ value: 'parentheses', label: '($1,000)' }, { value: 'minus', label: '-$1,000' }, { value: 'red', label: 'Red text' }] },
  { id: 'taxes-rate-format', section: 'taxes', group: 'Formatting', label: 'Tax rate display format', type: 'select', default: 'percent', options: [{ value: 'percent', label: '7.25%' }, { value: 'decimal', label: '0.0725' }, { value: 'basis', label: '725 bps' }] },
  { id: 'taxes-rate-decimals', section: 'taxes', group: 'Formatting', label: 'Tax rate decimal places', type: 'number', default: 3, min: 0, max: 6, step: 1 },
  { id: 'taxes-date-format', section: 'taxes', group: 'Formatting', label: 'Date format', type: 'select', default: 'us', options: [{ value: 'us', label: 'MM/DD/YYYY' }, { value: 'iso', label: 'YYYY-MM-DD' }, { value: 'eu', label: 'DD/MM/YYYY' }, { value: 'long', label: 'Month D, YYYY' }] },
  { id: 'taxes-round-display', section: 'taxes', group: 'Formatting', label: 'Round amounts to whole dollars in display', type: 'toggle', default: false },
  { id: 'taxes-period-label-style', section: 'taxes', group: 'Formatting', label: 'Period label style', type: 'select', default: 'quarter', options: [{ value: 'quarter', label: 'Q1 2026' }, { value: 'month', label: 'Jan 2026' }, { value: 'range', label: 'Jan 1 - Mar 31' }] },
  { id: 'taxes-show-currency-code', section: 'taxes', group: 'Formatting', label: 'Append ISO currency code', type: 'toggle', default: false },
  { id: 'taxes-abbreviate-large', section: 'taxes', group: 'Formatting', label: 'Abbreviate large amounts (1.2K, 3.4M)', type: 'toggle', default: false },
  { id: 'taxes-zero-display', section: 'taxes', group: 'Formatting', label: 'Display zero amounts as', type: 'select', default: 'dash', options: [{ value: 'dash', label: '—' }, { value: 'zero', label: '$0.00' }, { value: 'blank', label: '(blank)' }] },

  // ===== Defaults (group) =====
  { id: 'taxes-default-jurisdiction', section: 'taxes', group: 'Defaults', label: 'Default jurisdiction for new filings', type: 'text', default: 'Federal' },
  { id: 'taxes-default-tax-type', section: 'taxes', group: 'Defaults', label: 'Default tax type', type: 'select', default: 'sales', options: [{ value: 'sales', label: 'Sales Tax' }, { value: 'income', label: 'Income Tax' }, { value: 'payroll', label: 'Payroll Tax' }, { value: 'vat', label: 'VAT/GST' }, { value: 'use', label: 'Use Tax' }, { value: 'excise', label: 'Excise Tax' }] },
  { id: 'taxes-default-filing-frequency', section: 'taxes', group: 'Defaults', label: 'Default filing frequency', type: 'select', default: 'quarterly', options: [{ value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }, { value: 'annual', label: 'Annual' }, { value: 'semiannual', label: 'Semi-annual' }] },
  { id: 'taxes-default-sales-rate', section: 'taxes', group: 'Defaults', label: 'Default sales tax rate (%)', type: 'number', default: 7.25, min: 0, max: 30, step: 0.001 },
  { id: 'taxes-default-fiscal-start', section: 'taxes', group: 'Defaults', label: 'Fiscal year start month', type: 'select', default: 'january', options: [{ value: 'january', label: 'January' }, { value: 'april', label: 'April' }, { value: 'july', label: 'July' }, { value: 'october', label: 'October' }] },
  { id: 'taxes-default-accounting-method', section: 'taxes', group: 'Defaults', label: 'Tax accounting method', type: 'select', default: 'accrual', options: [{ value: 'cash', label: 'Cash basis' }, { value: 'accrual', label: 'Accrual basis' }] },
  { id: 'taxes-default-payment-method', section: 'taxes', group: 'Defaults', label: 'Default tax payment method', type: 'select', default: 'eft', options: [{ value: 'eft', label: 'EFT/ACH' }, { value: 'check', label: 'Check' }, { value: 'card', label: 'Credit Card' }, { value: 'wire', label: 'Wire' }] },
  { id: 'taxes-default-preparer', section: 'taxes', group: 'Defaults', label: 'Default preparer name', type: 'text', default: '' },
  { id: 'taxes-default-entity-type', section: 'taxes', group: 'Defaults', label: 'Default entity type', type: 'select', default: 'llc', options: [{ value: 'sole', label: 'Sole Proprietor' }, { value: 'llc', label: 'LLC' }, { value: 's-corp', label: 'S-Corp' }, { value: 'c-corp', label: 'C-Corp' }, { value: 'partnership', label: 'Partnership' }] },
  { id: 'taxes-default-rounding', section: 'taxes', group: 'Defaults', label: 'Tax calculation rounding', type: 'select', default: 'line', options: [{ value: 'line', label: 'Per line item' }, { value: 'invoice', label: 'Per invoice total' }, { value: 'period', label: 'Per period' }] },
  { id: 'taxes-default-est-safe-harbor', section: 'taxes', group: 'Defaults', label: 'Estimated payment safe-harbor (%)', type: 'number', default: 110, min: 90, max: 125, step: 1 },
  { id: 'taxes-default-deposit-schedule', section: 'taxes', group: 'Defaults', label: 'Payroll tax deposit schedule', type: 'select', default: 'monthly', options: [{ value: 'monthly', label: 'Monthly' }, { value: 'semiweekly', label: 'Semi-weekly' }, { value: 'next-day', label: 'Next-day' }] },

  // ===== Sorting & Filtering (group) =====
  { id: 'taxes-default-sort', section: 'taxes', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'due-date', options: [{ value: 'due-date', label: 'Due Date' }, { value: 'period', label: 'Period' }, { value: 'jurisdiction', label: 'Jurisdiction' }, { value: 'balance', label: 'Balance Due' }, { value: 'status', label: 'Status' }] },
  { id: 'taxes-sort-direction', section: 'taxes', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'asc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'taxes-default-year-filter', section: 'taxes', group: 'Sorting & Filtering', label: 'Default tax year filter', type: 'select', default: 'current', options: [{ value: 'current', label: 'Current Year' }, { value: 'prior', label: 'Prior Year' }, { value: 'all', label: 'All Years' }] },
  { id: 'taxes-hide-fully-paid', section: 'taxes', group: 'Sorting & Filtering', label: 'Hide fully paid by default', type: 'toggle', default: false },
  { id: 'taxes-hide-future', section: 'taxes', group: 'Sorting & Filtering', label: 'Hide future periods by default', type: 'toggle', default: false },
  { id: 'taxes-default-status-filter', section: 'taxes', group: 'Sorting & Filtering', label: 'Default status filter', type: 'select', default: 'all', options: [{ value: 'all', label: 'All' }, { value: 'draft', label: 'Draft' }, { value: 'filed', label: 'Filed' }, { value: 'overdue', label: 'Overdue' }, { value: 'paid', label: 'Paid' }] },
  { id: 'taxes-remember-filters', section: 'taxes', group: 'Sorting & Filtering', label: 'Remember last-used filters', type: 'toggle', default: true },
  { id: 'taxes-quickfilter-overdue', section: 'taxes', group: 'Sorting & Filtering', label: 'Show "Overdue" quick filter chip', type: 'toggle', default: true },
  { id: 'taxes-quickfilter-due-soon', section: 'taxes', group: 'Sorting & Filtering', label: 'Show "Due Soon" quick filter chip', type: 'toggle', default: true },
  { id: 'taxes-due-soon-window', section: 'taxes', group: 'Sorting & Filtering', label: '"Due Soon" window (days)', type: 'number', default: 14, min: 1, max: 90, step: 1 },
  { id: 'taxes-group-by', section: 'taxes', group: 'Sorting & Filtering', label: 'Group filings by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'jurisdiction', label: 'Jurisdiction' }, { value: 'tax-type', label: 'Tax Type' }, { value: 'quarter', label: 'Quarter' }] },
  { id: 'taxes-search-scope', section: 'taxes', group: 'Sorting & Filtering', label: 'Search scope', type: 'select', default: 'all-fields', options: [{ value: 'all-fields', label: 'All fields' }, { value: 'form-number', label: 'Form number only' }, { value: 'notes', label: 'Notes only' }] },

  // ===== Behavior (group) =====
  { id: 'taxes-auto-calc-liability', section: 'taxes', group: 'Behavior', label: 'Auto-calculate liability from transactions', type: 'toggle', default: true },
  { id: 'taxes-auto-create-periods', section: 'taxes', group: 'Behavior', label: 'Auto-create upcoming filing periods', type: 'toggle', default: true },
  { id: 'taxes-confirm-before-file', section: 'taxes', group: 'Behavior', label: 'Confirm before marking as filed', type: 'toggle', default: true },
  { id: 'taxes-lock-filed', section: 'taxes', group: 'Behavior', label: 'Lock filings after marking as filed', type: 'toggle', default: true },
  { id: 'taxes-autosave', section: 'taxes', group: 'Behavior', label: 'Auto-save filing drafts', type: 'toggle', default: true },
  { id: 'taxes-autosave-interval', section: 'taxes', group: 'Behavior', label: 'Auto-save interval (seconds)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'taxes-recompute-on-edit', section: 'taxes', group: 'Behavior', label: 'Recompute liability when transactions change', type: 'toggle', default: true },
  { id: 'taxes-auto-penalty-calc', section: 'taxes', group: 'Behavior', label: 'Auto-calculate penalties on overdue', type: 'toggle', default: false },
  { id: 'taxes-penalty-rate', section: 'taxes', group: 'Behavior', label: 'Late penalty rate (% per month)', type: 'number', default: 5, min: 0, max: 25, step: 0.5 },
  { id: 'taxes-interest-rate', section: 'taxes', group: 'Behavior', label: 'Late interest rate (% annual)', type: 'number', default: 8, min: 0, max: 30, step: 0.25 },
  { id: 'taxes-auto-mark-overdue', section: 'taxes', group: 'Behavior', label: 'Auto-mark filings overdue past due date', type: 'toggle', default: true },
  { id: 'taxes-prefill-from-prior', section: 'taxes', group: 'Behavior', label: 'Pre-fill new filing from prior period', type: 'toggle', default: true },
  { id: 'taxes-warn-rate-change', section: 'taxes', group: 'Behavior', label: 'Warn when tax rate differs from default', type: 'toggle', default: true },
  { id: 'taxes-duplicate-detection', section: 'taxes', group: 'Behavior', label: 'Detect duplicate filings for same period', type: 'toggle', default: true },
  { id: 'taxes-require-confirmation-number', section: 'taxes', group: 'Behavior', label: 'Require confirmation number when filing', type: 'toggle', default: false },
  { id: 'taxes-auto-link-payments', section: 'taxes', group: 'Behavior', label: 'Auto-link bank payments to filings', type: 'toggle', default: true },
  { id: 'taxes-keep-draft-on-error', section: 'taxes', group: 'Behavior', label: 'Keep draft if e-file submission fails', type: 'toggle', default: true },

  // ===== Notifications (group) =====
  { id: 'taxes-notify-due-soon', section: 'taxes', group: 'Notifications', label: 'Notify when filing due soon', type: 'toggle', default: true },
  { id: 'taxes-notify-lead-days', section: 'taxes', group: 'Notifications', label: 'Due-soon reminder lead time (days)', type: 'number', default: 7, min: 1, max: 60, step: 1 },
  { id: 'taxes-notify-overdue', section: 'taxes', group: 'Notifications', label: 'Notify on overdue filings', type: 'toggle', default: true },
  { id: 'taxes-notify-est-payment', section: 'taxes', group: 'Notifications', label: 'Notify on estimated payment due', type: 'toggle', default: true },
  { id: 'taxes-notify-rate-update', section: 'taxes', group: 'Notifications', label: 'Notify on jurisdiction rate updates', type: 'toggle', default: true },
  { id: 'taxes-notify-large-liability', section: 'taxes', group: 'Notifications', label: 'Notify on large liability threshold', type: 'toggle', default: false },
  { id: 'taxes-large-liability-threshold', section: 'taxes', group: 'Notifications', label: 'Large liability threshold ($)', type: 'number', default: 10000, min: 0, max: 1000000, step: 500 },
  { id: 'taxes-notify-channel', section: 'taxes', group: 'Notifications', label: 'Notification channel', type: 'select', default: 'in-app', options: [{ value: 'in-app', label: 'In-app' }, { value: 'email', label: 'Email' }, { value: 'both', label: 'Both' }] },
  { id: 'taxes-notify-email', section: 'taxes', group: 'Notifications', label: 'Tax notification email address', type: 'text', default: '' },
  { id: 'taxes-notify-digest', section: 'taxes', group: 'Notifications', label: 'Send weekly tax deadline digest', type: 'toggle', default: false },
  { id: 'taxes-notify-digest-day', section: 'taxes', group: 'Notifications', label: 'Digest delivery day', type: 'select', default: 'monday', options: [{ value: 'monday', label: 'Monday' }, { value: 'wednesday', label: 'Wednesday' }, { value: 'friday', label: 'Friday' }] },
  { id: 'taxes-notify-filed-receipt', section: 'taxes', group: 'Notifications', label: 'Notify when filing confirmation received', type: 'toggle', default: true },
  { id: 'taxes-notify-nexus-alert', section: 'taxes', group: 'Notifications', label: 'Alert on possible new nexus threshold', type: 'toggle', default: true },
  { id: 'taxes-notify-quiet-hours', section: 'taxes', group: 'Notifications', label: 'Respect quiet hours for tax alerts', type: 'toggle', default: true },

  // ===== Export (group) =====
  { id: 'taxes-export-format', section: 'taxes', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'taxes-export-include-paid', section: 'taxes', group: 'Export', label: 'Include paid filings in export', type: 'toggle', default: true },
  { id: 'taxes-export-include-notes', section: 'taxes', group: 'Export', label: 'Include notes column in export', type: 'toggle', default: false },
  { id: 'taxes-export-include-attachments', section: 'taxes', group: 'Export', label: 'Bundle attachments in export', type: 'toggle', default: false },
  { id: 'taxes-export-date-range', section: 'taxes', group: 'Export', label: 'Default export date range', type: 'select', default: 'tax-year', options: [{ value: 'tax-year', label: 'Tax Year' }, { value: 'quarter', label: 'Current Quarter' }, { value: 'ytd', label: 'Year to Date' }, { value: 'all', label: 'All' }] },
  { id: 'taxes-export-filename', section: 'taxes', group: 'Export', label: 'Export filename template', type: 'text', default: 'taxes_{jurisdiction}_{period}' },
  { id: 'taxes-pdf-include-logo', section: 'taxes', group: 'Export', label: 'Include company logo on PDF exports', type: 'toggle', default: true },
  { id: 'taxes-pdf-orientation', section: 'taxes', group: 'Export', label: 'PDF page orientation', type: 'select', default: 'portrait', options: [{ value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
  { id: 'taxes-pdf-paper-size', section: 'taxes', group: 'Export', label: 'PDF paper size', type: 'select', default: 'letter', options: [{ value: 'letter', label: 'Letter' }, { value: 'a4', label: 'A4' }, { value: 'legal', label: 'Legal' }] },
  { id: 'taxes-export-grand-total', section: 'taxes', group: 'Export', label: 'Append grand total row', type: 'toggle', default: true },
  { id: 'taxes-export-encoding', section: 'taxes', group: 'Export', label: 'CSV character encoding', type: 'select', default: 'utf8', options: [{ value: 'utf8', label: 'UTF-8' }, { value: 'utf8-bom', label: 'UTF-8 with BOM' }, { value: 'latin1', label: 'Latin-1' }] },
  { id: 'taxes-export-delimiter', section: 'taxes', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'taxes-export-efile-format', section: 'taxes', group: 'Export', label: 'E-file export schema', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'irs-mef', label: 'IRS MeF XML' }, { value: 'state-edi', label: 'State EDI' }] },

  // ===== Colors & Theme (group) =====
  { id: 'taxes-color-overdue', section: 'taxes', group: 'Colors & Theme', label: 'Overdue highlight color', type: 'color', default: '#ef4444' },
  { id: 'taxes-color-due-soon', section: 'taxes', group: 'Colors & Theme', label: 'Due-soon highlight color', type: 'color', default: '#f59e0b' },
  { id: 'taxes-color-paid', section: 'taxes', group: 'Colors & Theme', label: 'Paid status color', type: 'color', default: '#22c55e' },
  { id: 'taxes-color-draft', section: 'taxes', group: 'Colors & Theme', label: 'Draft status color', type: 'color', default: '#64748b' },
  { id: 'taxes-color-filed', section: 'taxes', group: 'Colors & Theme', label: 'Filed status color', type: 'color', default: '#3b82f6' },
  { id: 'taxes-color-liability', section: 'taxes', group: 'Colors & Theme', label: 'Liability figure color', type: 'color', default: '#e2e8f0' },
  { id: 'taxes-color-refund', section: 'taxes', group: 'Colors & Theme', label: 'Refund/credit color', type: 'color', default: '#14b8a6' },
  { id: 'taxes-color-chart-primary', section: 'taxes', group: 'Colors & Theme', label: 'Tax chart primary color', type: 'color', default: '#6366f1' },
  { id: 'taxes-color-chart-secondary', section: 'taxes', group: 'Colors & Theme', label: 'Tax chart secondary color', type: 'color', default: '#a855f7' },
  { id: 'taxes-color-penalty', section: 'taxes', group: 'Colors & Theme', label: 'Penalty/interest color', type: 'color', default: '#dc2626' },
  { id: 'taxes-status-badge-style', section: 'taxes', group: 'Colors & Theme', label: 'Status badge style', type: 'select', default: 'solid', options: [{ value: 'solid', label: 'Solid' }, { value: 'outline', label: 'Outline' }, { value: 'soft', label: 'Soft' }] },
  { id: 'taxes-heatmap-calendar', section: 'taxes', group: 'Colors & Theme', label: 'Use heatmap colors on deadline calendar', type: 'toggle', default: true },

  // ===== Accessibility (group) =====
  { id: 'taxes-high-contrast', section: 'taxes', group: 'Accessibility', label: 'High-contrast tax tables', type: 'toggle', default: false },
  { id: 'taxes-font-scale', section: 'taxes', group: 'Accessibility', label: 'Table font scale (%)', type: 'number', default: 100, min: 75, max: 200, step: 5 },
  { id: 'taxes-colorblind-mode', section: 'taxes', group: 'Accessibility', label: 'Colorblind-safe status palette', type: 'toggle', default: false },
  { id: 'taxes-status-icons', section: 'taxes', group: 'Accessibility', label: 'Show status icons alongside colors', type: 'toggle', default: true },
  { id: 'taxes-reduce-motion', section: 'taxes', group: 'Accessibility', label: 'Reduce animations in tax views', type: 'toggle', default: false },
  { id: 'taxes-screen-reader-summaries', section: 'taxes', group: 'Accessibility', label: 'Verbose screen-reader summaries', type: 'toggle', default: false },
  { id: 'taxes-focus-outline', section: 'taxes', group: 'Accessibility', label: 'Visible keyboard focus outline', type: 'toggle', default: true },
  { id: 'taxes-underline-links', section: 'taxes', group: 'Accessibility', label: 'Underline links in tax tables', type: 'toggle', default: true },
  { id: 'taxes-large-touch-targets', section: 'taxes', group: 'Accessibility', label: 'Larger touch targets for action buttons', type: 'toggle', default: false },
  { id: 'taxes-announce-recalc', section: 'taxes', group: 'Accessibility', label: 'Announce liability recalculations', type: 'toggle', default: false },

  // ===== Shortcuts (group) =====
  { id: 'taxes-shortcut-new-filing', section: 'taxes', group: 'Shortcuts', label: 'New filing shortcut', type: 'text', default: 'n' },
  { id: 'taxes-shortcut-mark-filed', section: 'taxes', group: 'Shortcuts', label: 'Mark as filed shortcut', type: 'text', default: 'f' },
  { id: 'taxes-shortcut-record-payment', section: 'taxes', group: 'Shortcuts', label: 'Record payment shortcut', type: 'text', default: 'p' },
  { id: 'taxes-shortcut-export', section: 'taxes', group: 'Shortcuts', label: 'Export shortcut', type: 'text', default: 'e' },
  { id: 'taxes-shortcut-search', section: 'taxes', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: '/' },
  { id: 'taxes-shortcut-recalculate', section: 'taxes', group: 'Shortcuts', label: 'Recalculate liability shortcut', type: 'text', default: 'r' },
  { id: 'taxes-shortcut-next-period', section: 'taxes', group: 'Shortcuts', label: 'Next period shortcut', type: 'text', default: ']' },
  { id: 'taxes-shortcut-prev-period', section: 'taxes', group: 'Shortcuts', label: 'Previous period shortcut', type: 'text', default: '[' },
  { id: 'taxes-shortcuts-enabled', section: 'taxes', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'taxes-shortcut-hints', section: 'taxes', group: 'Shortcuts', label: 'Show shortcut hints in tooltips', type: 'toggle', default: true },

  // ===== Privacy (group) =====
  { id: 'taxes-mask-ein', section: 'taxes', group: 'Privacy', label: 'Mask EIN/Tax ID in exports', type: 'toggle', default: true },
  { id: 'taxes-redact-on-share', section: 'taxes', group: 'Privacy', label: 'Redact sensitive fields when sharing', type: 'toggle', default: true },
  { id: 'taxes-require-pin-view', section: 'taxes', group: 'Privacy', label: 'Require PIN to view tax IDs', type: 'toggle', default: false },
  { id: 'taxes-audit-log', section: 'taxes', group: 'Privacy', label: 'Keep audit log of filing changes', type: 'toggle', default: true },
  { id: 'taxes-audit-retention', section: 'taxes', group: 'Privacy', label: 'Audit log retention (months)', type: 'number', default: 84, min: 12, max: 120, step: 12 },
  { id: 'taxes-hide-amounts-overview', section: 'taxes', group: 'Privacy', label: 'Hide amounts on shared overview screens', type: 'toggle', default: false },
  { id: 'taxes-blur-on-idle', section: 'taxes', group: 'Privacy', label: 'Blur tax figures when window idle', type: 'toggle', default: false },
  { id: 'taxes-exclude-from-backup-share', section: 'taxes', group: 'Privacy', label: 'Exclude tax IDs from shared backups', type: 'toggle', default: false },

  // ===== Estimated Payments (group) =====
  { id: 'taxes-est-show-vouchers', section: 'taxes', group: 'Estimated Payments', label: 'Show estimated payment vouchers', type: 'toggle', default: true },
  { id: 'taxes-est-method', section: 'taxes', group: 'Estimated Payments', label: 'Estimated tax projection method', type: 'select', default: 'annualized', options: [{ value: 'annualized', label: 'Annualized income' }, { value: 'prior-year', label: 'Prior-year safe harbor' }, { value: 'equal', label: 'Equal quarterly' }] },
  { id: 'taxes-est-effective-rate', section: 'taxes', group: 'Estimated Payments', label: 'Assumed effective tax rate (%)', type: 'number', default: 21, min: 0, max: 50, step: 0.5 },
  { id: 'taxes-est-include-se', section: 'taxes', group: 'Estimated Payments', label: 'Include self-employment tax in estimates', type: 'toggle', default: true },
  { id: 'taxes-est-se-rate', section: 'taxes', group: 'Estimated Payments', label: 'Self-employment tax rate (%)', type: 'number', default: 15.3, min: 0, max: 20, step: 0.1 },
  { id: 'taxes-est-quarter-due-display', section: 'taxes', group: 'Estimated Payments', label: 'Show standard IRS quarterly due dates', type: 'toggle', default: true },
  { id: 'taxes-est-rollover-overpayment', section: 'taxes', group: 'Estimated Payments', label: 'Roll over prior-year overpayment', type: 'toggle', default: true },
  { id: 'taxes-est-state-included', section: 'taxes', group: 'Estimated Payments', label: 'Include state estimated payments', type: 'toggle', default: true },
  { id: 'taxes-est-reminder-buffer', section: 'taxes', group: 'Estimated Payments', label: 'Estimated payment reminder buffer (days)', type: 'number', default: 10, min: 1, max: 45, step: 1 },
  { id: 'taxes-est-show-underpayment', section: 'taxes', group: 'Estimated Payments', label: 'Show underpayment risk indicator', type: 'toggle', default: true },

  // ===== Sales & Use Tax (group) =====
  { id: 'taxes-sales-tax-inclusive', section: 'taxes', group: 'Sales & Use Tax', label: 'Prices are tax-inclusive by default', type: 'toggle', default: false },
  { id: 'taxes-sales-track-exempt', section: 'taxes', group: 'Sales & Use Tax', label: 'Track exempt sales separately', type: 'toggle', default: true },
  { id: 'taxes-sales-exemption-cert', section: 'taxes', group: 'Sales & Use Tax', label: 'Require exemption certificate on exempt sales', type: 'toggle', default: true },
  { id: 'taxes-sales-cert-expiry-warn', section: 'taxes', group: 'Sales & Use Tax', label: 'Warn on expiring exemption certificates', type: 'toggle', default: true },
  { id: 'taxes-sales-rate-source', section: 'taxes', group: 'Sales & Use Tax', label: 'Sales tax rate source', type: 'select', default: 'manual', options: [{ value: 'manual', label: 'Manual entry' }, { value: 'zip', label: 'ZIP-based lookup' }, { value: 'address', label: 'Full address rooftop' }] },
  { id: 'taxes-sales-track-use-tax', section: 'taxes', group: 'Sales & Use Tax', label: 'Track accrued use tax on purchases', type: 'toggle', default: true },
  { id: 'taxes-sales-combined-rate', section: 'taxes', group: 'Sales & Use Tax', label: 'Show combined state+local rate', type: 'toggle', default: true },
  { id: 'taxes-sales-marketplace-facilitator', section: 'taxes', group: 'Sales & Use Tax', label: 'Exclude marketplace-facilitator sales', type: 'toggle', default: true },
  { id: 'taxes-sales-nexus-tracking', section: 'taxes', group: 'Sales & Use Tax', label: 'Track economic nexus thresholds', type: 'toggle', default: true },
  { id: 'taxes-sales-shipping-taxable', section: 'taxes', group: 'Sales & Use Tax', label: 'Treat shipping charges as taxable', type: 'toggle', default: false },
  { id: 'taxes-sales-rounding-method', section: 'taxes', group: 'Sales & Use Tax', label: 'Sales tax rounding method', type: 'select', default: 'half-up', options: [{ value: 'half-up', label: 'Round half up' }, { value: 'half-even', label: 'Banker\'s rounding' }, { value: 'truncate', label: 'Truncate' }] },

  // ===== VAT / GST (group) =====
  { id: 'taxes-vat-enabled', section: 'taxes', group: 'VAT / GST', label: 'Enable VAT/GST tracking', type: 'toggle', default: false },
  { id: 'taxes-vat-standard-rate', section: 'taxes', group: 'VAT / GST', label: 'Standard VAT rate (%)', type: 'number', default: 20, min: 0, max: 30, step: 0.5 },
  { id: 'taxes-vat-reduced-rate', section: 'taxes', group: 'VAT / GST', label: 'Reduced VAT rate (%)', type: 'number', default: 5, min: 0, max: 25, step: 0.5 },
  { id: 'taxes-vat-reverse-charge', section: 'taxes', group: 'VAT / GST', label: 'Apply reverse-charge for B2B EU', type: 'toggle', default: false },
  { id: 'taxes-vat-show-input-output', section: 'taxes', group: 'VAT / GST', label: 'Show input vs output VAT split', type: 'toggle', default: true },
  { id: 'taxes-vat-registration-number', section: 'taxes', group: 'VAT / GST', label: 'VAT registration number', type: 'text', default: '' },
  { id: 'taxes-vat-scheme', section: 'taxes', group: 'VAT / GST', label: 'VAT accounting scheme', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'flat-rate', label: 'Flat rate' }, { value: 'cash', label: 'Cash accounting' }, { value: 'margin', label: 'Margin scheme' }] },
  { id: 'taxes-vat-flat-rate-pct', section: 'taxes', group: 'VAT / GST', label: 'Flat-rate scheme percentage (%)', type: 'number', default: 16.5, min: 0, max: 20, step: 0.5 },
  { id: 'taxes-vat-mtd', section: 'taxes', group: 'VAT / GST', label: 'Enable Making Tax Digital submission', type: 'toggle', default: false },
  { id: 'taxes-vat-validate-eu-numbers', section: 'taxes', group: 'VAT / GST', label: 'Validate EU VAT numbers (VIES)', type: 'toggle', default: false },

  // ===== Payroll Tax (group) =====
  { id: 'taxes-payroll-track-fica', section: 'taxes', group: 'Payroll Tax', label: 'Track FICA (Social Security/Medicare)', type: 'toggle', default: true },
  { id: 'taxes-payroll-ss-wage-base', section: 'taxes', group: 'Payroll Tax', label: 'Social Security wage base ($)', type: 'number', default: 168600, min: 0, max: 300000, step: 100 },
  { id: 'taxes-payroll-track-futa', section: 'taxes', group: 'Payroll Tax', label: 'Track FUTA', type: 'toggle', default: true },
  { id: 'taxes-payroll-track-suta', section: 'taxes', group: 'Payroll Tax', label: 'Track state unemployment (SUTA)', type: 'toggle', default: true },
  { id: 'taxes-payroll-suta-rate', section: 'taxes', group: 'Payroll Tax', label: 'SUTA experience rate (%)', type: 'number', default: 2.7, min: 0, max: 15, step: 0.1 },
  { id: 'taxes-payroll-941-reminder', section: 'taxes', group: 'Payroll Tax', label: 'Remind on Form 941 deadlines', type: 'toggle', default: true },
  { id: 'taxes-payroll-940-reminder', section: 'taxes', group: 'Payroll Tax', label: 'Remind on Form 940 annual deadline', type: 'toggle', default: true },
  { id: 'taxes-payroll-additional-medicare', section: 'taxes', group: 'Payroll Tax', label: 'Apply additional Medicare surtax', type: 'toggle', default: true },
  { id: 'taxes-payroll-w2-tracking', section: 'taxes', group: 'Payroll Tax', label: 'Track W-2 filing status', type: 'toggle', default: true },
  { id: 'taxes-payroll-local-tax', section: 'taxes', group: 'Payroll Tax', label: 'Track local payroll taxes', type: 'toggle', default: false },

  // ===== 1099 & Information Returns (group) =====
  { id: 'taxes-1099-track', section: 'taxes', group: '1099 & Information Returns', label: 'Track 1099-eligible vendors', type: 'toggle', default: true },
  { id: 'taxes-1099-threshold', section: 'taxes', group: '1099 & Information Returns', label: '1099-NEC reporting threshold ($)', type: 'number', default: 600, min: 0, max: 5000, step: 50 },
  { id: 'taxes-1099-require-w9', section: 'taxes', group: '1099 & Information Returns', label: 'Require W-9 before payment', type: 'toggle', default: true },
  { id: 'taxes-1099-backup-withholding', section: 'taxes', group: '1099 & Information Returns', label: 'Apply backup withholding on missing TIN', type: 'toggle', default: false },
  { id: 'taxes-1099-backup-rate', section: 'taxes', group: '1099 & Information Returns', label: 'Backup withholding rate (%)', type: 'number', default: 24, min: 0, max: 40, step: 1 },
  { id: 'taxes-1099-tin-match', section: 'taxes', group: '1099 & Information Returns', label: 'Enable TIN matching validation', type: 'toggle', default: false },
  { id: 'taxes-1099-deadline-reminder', section: 'taxes', group: '1099 & Information Returns', label: 'Remind on January 31 filing deadline', type: 'toggle', default: true },
  { id: 'taxes-1099-default-form', section: 'taxes', group: '1099 & Information Returns', label: 'Default 1099 form type', type: 'select', default: 'nec', options: [{ value: 'nec', label: '1099-NEC' }, { value: 'misc', label: '1099-MISC' }, { value: 'k', label: '1099-K' }, { value: 'int', label: '1099-INT' }] },
  { id: 'taxes-1099-efile-vendor', section: 'taxes', group: '1099 & Information Returns', label: 'E-file 1099s through service', type: 'toggle', default: false },
  { id: 'taxes-1099-recipient-copy', section: 'taxes', group: '1099 & Information Returns', label: 'Auto-email recipient copies', type: 'toggle', default: false },

  // ===== Deductions & Credits (group) =====
  { id: 'taxes-track-deductions', section: 'taxes', group: 'Deductions & Credits', label: 'Track deductible expenses for tax', type: 'toggle', default: true },
  { id: 'taxes-mileage-rate', section: 'taxes', group: 'Deductions & Credits', label: 'Standard mileage rate ($/mi)', type: 'number', default: 0.67, min: 0, max: 2, step: 0.005 },
  { id: 'taxes-home-office-method', section: 'taxes', group: 'Deductions & Credits', label: 'Home office deduction method', type: 'select', default: 'simplified', options: [{ value: 'simplified', label: 'Simplified' }, { value: 'actual', label: 'Actual expenses' }] },
  { id: 'taxes-track-section179', section: 'taxes', group: 'Deductions & Credits', label: 'Track Section 179 depreciation', type: 'toggle', default: true },
  { id: 'taxes-meals-deduction-pct', section: 'taxes', group: 'Deductions & Credits', label: 'Business meals deduction (%)', type: 'number', default: 50, min: 0, max: 100, step: 5 },
  { id: 'taxes-track-credits', section: 'taxes', group: 'Deductions & Credits', label: 'Track available tax credits', type: 'toggle', default: true },
  { id: 'taxes-rd-credit', section: 'taxes', group: 'Deductions & Credits', label: 'Flag R&D credit-eligible expenses', type: 'toggle', default: false },
  { id: 'taxes-charitable-tracking', section: 'taxes', group: 'Deductions & Credits', label: 'Track charitable contributions', type: 'toggle', default: true },
  { id: 'taxes-depreciation-method', section: 'taxes', group: 'Deductions & Credits', label: 'Default depreciation method', type: 'select', default: 'macrs', options: [{ value: 'macrs', label: 'MACRS' }, { value: 'straight', label: 'Straight-line' }, { value: 'bonus', label: 'Bonus depreciation' }] },
  { id: 'taxes-deduction-warn-threshold', section: 'taxes', group: 'Deductions & Credits', label: 'Warn on unusually large deductions ($)', type: 'number', default: 25000, min: 0, max: 500000, step: 1000 },

  // ===== Reports & Dashboard (group) =====
  { id: 'taxes-dashboard-show-liability-tile', section: 'taxes', group: 'Reports & Dashboard', label: 'Show total liability tile', type: 'toggle', default: true },
  { id: 'taxes-dashboard-show-upcoming-tile', section: 'taxes', group: 'Reports & Dashboard', label: 'Show upcoming deadlines tile', type: 'toggle', default: true },
  { id: 'taxes-dashboard-show-effective-rate', section: 'taxes', group: 'Reports & Dashboard', label: 'Show effective tax rate tile', type: 'toggle', default: true },
  { id: 'taxes-dashboard-chart-type', section: 'taxes', group: 'Reports & Dashboard', label: 'Liability trend chart type', type: 'select', default: 'bar', options: [{ value: 'bar', label: 'Bar' }, { value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }] },
  { id: 'taxes-dashboard-period-comparison', section: 'taxes', group: 'Reports & Dashboard', label: 'Show year-over-year comparison', type: 'toggle', default: true },
  { id: 'taxes-report-default', section: 'taxes', group: 'Reports & Dashboard', label: 'Default tax report', type: 'select', default: 'liability-summary', options: [{ value: 'liability-summary', label: 'Liability Summary' }, { value: 'sales-tax', label: 'Sales Tax Report' }, { value: 'payroll-tax', label: 'Payroll Tax Report' }, { value: 'deductions', label: 'Deductions Report' }] },
  { id: 'taxes-report-breakdown-jurisdiction', section: 'taxes', group: 'Reports & Dashboard', label: 'Break down reports by jurisdiction', type: 'toggle', default: true },
  { id: 'taxes-dashboard-refresh', section: 'taxes', group: 'Reports & Dashboard', label: 'Dashboard auto-refresh interval (minutes)', type: 'number', default: 15, min: 0, max: 120, step: 5 },
  { id: 'taxes-report-show-projections', section: 'taxes', group: 'Reports & Dashboard', label: 'Include year-end liability projection', type: 'toggle', default: true },
  { id: 'taxes-dashboard-show-refund-tile', section: 'taxes', group: 'Reports & Dashboard', label: 'Show expected refund/credit tile', type: 'toggle', default: false },

  // ===== Integrations & Sync (group) =====
  { id: 'taxes-sync-rates-auto', section: 'taxes', group: 'Integrations & Sync', label: 'Auto-update tax rate tables', type: 'toggle', default: true },
  { id: 'taxes-sync-rates-frequency', section: 'taxes', group: 'Integrations & Sync', label: 'Rate table update frequency', type: 'select', default: 'monthly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }, { value: 'quarterly', label: 'Quarterly' }] },
  { id: 'taxes-efile-provider', section: 'taxes', group: 'Integrations & Sync', label: 'E-file provider', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'avalara', label: 'Avalara' }, { value: 'taxjar', label: 'TaxJar' }, { value: 'manual', label: 'Manual portal' }] },
  { id: 'taxes-bank-feed-link', section: 'taxes', group: 'Integrations & Sync', label: 'Link bank feed to tax payments', type: 'toggle', default: true },
  { id: 'taxes-accountant-share', section: 'taxes', group: 'Integrations & Sync', label: 'Enable accountant share access', type: 'toggle', default: false },
  { id: 'taxes-export-to-accounting', section: 'taxes', group: 'Integrations & Sync', label: 'Push tax journal entries to ledger', type: 'toggle', default: true },
  { id: 'taxes-sync-conflict', section: 'taxes', group: 'Integrations & Sync', label: 'Rate sync conflict resolution', type: 'select', default: 'prompt', options: [{ value: 'prompt', label: 'Prompt me' }, { value: 'keep-local', label: 'Keep local' }, { value: 'use-remote', label: 'Use remote' }] },
  { id: 'taxes-api-rate-cache-days', section: 'taxes', group: 'Integrations & Sync', label: 'Cache external rate lookups (days)', type: 'number', default: 7, min: 0, max: 90, step: 1 },

  // ===== Audit & Compliance (group) =====
  { id: 'taxes-audit-trail-required', section: 'taxes', group: 'Audit & Compliance', label: 'Require reason note on liability override', type: 'toggle', default: true },
  { id: 'taxes-compliance-checklist', section: 'taxes', group: 'Audit & Compliance', label: 'Show pre-filing compliance checklist', type: 'toggle', default: true },
  { id: 'taxes-flag-anomalies', section: 'taxes', group: 'Audit & Compliance', label: 'Flag anomalous period-over-period swings', type: 'toggle', default: true },
  { id: 'taxes-anomaly-threshold', section: 'taxes', group: 'Audit & Compliance', label: 'Anomaly swing threshold (%)', type: 'number', default: 40, min: 5, max: 200, step: 5 },
  { id: 'taxes-retain-filed-copies', section: 'taxes', group: 'Audit & Compliance', label: 'Retain PDF copies of filed returns', type: 'toggle', default: true },
  { id: 'taxes-retention-years', section: 'taxes', group: 'Audit & Compliance', label: 'Document retention period (years)', type: 'number', default: 7, min: 3, max: 15, step: 1 },
  { id: 'taxes-lock-prior-years', section: 'taxes', group: 'Audit & Compliance', label: 'Lock prior tax years from editing', type: 'toggle', default: true },
  { id: 'taxes-require-approval', section: 'taxes', group: 'Audit & Compliance', label: 'Require approval before filing', type: 'toggle', default: false },
  { id: 'taxes-approval-threshold', section: 'taxes', group: 'Audit & Compliance', label: 'Approval required above amount ($)', type: 'number', default: 50000, min: 0, max: 1000000, step: 1000 },
  { id: 'taxes-reconcile-before-file', section: 'taxes', group: 'Audit & Compliance', label: 'Require reconciliation before filing', type: 'toggle', default: true },

  // ===== Calendar & Deadlines (group) =====
  { id: 'taxes-calendar-default-view', section: 'taxes', group: 'Calendar & Deadlines', label: 'Default deadline calendar view', type: 'select', default: 'month', options: [{ value: 'month', label: 'Month' }, { value: 'quarter', label: 'Quarter' }, { value: 'year', label: 'Year' }, { value: 'list', label: 'List' }] },
  { id: 'taxes-calendar-week-start', section: 'taxes', group: 'Calendar & Deadlines', label: 'Calendar week starts on', type: 'select', default: 'sunday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },
  { id: 'taxes-calendar-show-weekends', section: 'taxes', group: 'Calendar & Deadlines', label: 'Show weekends on deadline calendar', type: 'toggle', default: true },
  { id: 'taxes-shift-weekend-deadlines', section: 'taxes', group: 'Calendar & Deadlines', label: 'Shift weekend deadlines to next business day', type: 'toggle', default: true },
  { id: 'taxes-observe-federal-holidays', section: 'taxes', group: 'Calendar & Deadlines', label: 'Observe federal holidays for due dates', type: 'toggle', default: true },
  { id: 'taxes-calendar-color-by-type', section: 'taxes', group: 'Calendar & Deadlines', label: 'Color-code deadlines by tax type', type: 'toggle', default: true },
  { id: 'taxes-calendar-export-ics', section: 'taxes', group: 'Calendar & Deadlines', label: 'Enable iCal (.ics) deadline export', type: 'toggle', default: false },
  { id: 'taxes-extension-tracking', section: 'taxes', group: 'Calendar & Deadlines', label: 'Track filing extensions', type: 'toggle', default: true },
  { id: 'taxes-show-grace-period', section: 'taxes', group: 'Calendar & Deadlines', label: 'Display payment grace periods', type: 'toggle', default: false },
  { id: 'taxes-deadline-countdown', section: 'taxes', group: 'Calendar & Deadlines', label: 'Show countdown to next deadline', type: 'toggle', default: true },
];
