import { CustomizationOption } from '../types';

export const customizations: CustomizationOption[] = [
  // ===== Display =====
  { id: 'tt-display-default-view', section: 'time-tracking', group: 'Display', label: 'Default view', description: 'Initial view when opening Time Tracking', type: 'select', default: 'timesheet', options: [{ value: 'timesheet', label: 'Timesheet grid' }, { value: 'list', label: 'Entry list' }, { value: 'calendar', label: 'Calendar' }, { value: 'kanban', label: 'Kanban' }] },
  { id: 'tt-display-show-running-timer', section: 'time-tracking', group: 'Display', label: 'Show running timer banner', description: 'Persistent banner for the active timer', type: 'toggle', default: true },
  { id: 'tt-display-timer-position', section: 'time-tracking', group: 'Display', label: 'Timer banner position', type: 'select', default: 'top', options: [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }, { value: 'floating', label: 'Floating' }] },
  { id: 'tt-display-compact-rows', section: 'time-tracking', group: 'Display', label: 'Compact row density', type: 'toggle', default: false },
  { id: 'tt-display-rows-per-page', section: 'time-tracking', group: 'Display', label: 'Entries per page', type: 'number', default: 50, min: 10, max: 500, step: 10 },
  { id: 'tt-display-show-avatars', section: 'time-tracking', group: 'Display', label: 'Show member avatars', type: 'toggle', default: true },
  { id: 'tt-display-show-project-color', section: 'time-tracking', group: 'Display', label: 'Show project color dot', type: 'toggle', default: true },
  { id: 'tt-display-show-billable-badge', section: 'time-tracking', group: 'Display', label: 'Show billable badge', type: 'toggle', default: true },
  { id: 'tt-display-zebra-stripes', section: 'time-tracking', group: 'Display', label: 'Zebra striped rows', type: 'toggle', default: true },
  { id: 'tt-display-sticky-header', section: 'time-tracking', group: 'Display', label: 'Sticky table header', type: 'toggle', default: true },
  { id: 'tt-display-group-by', section: 'time-tracking', group: 'Display', label: 'Group entries by', type: 'select', default: 'day', options: [{ value: 'none', label: 'None' }, { value: 'day', label: 'Day' }, { value: 'project', label: 'Project' }, { value: 'client', label: 'Client' }, { value: 'task', label: 'Task' }] },
  { id: 'tt-display-show-week-totals', section: 'time-tracking', group: 'Display', label: 'Show weekly totals row', type: 'toggle', default: true },
  { id: 'tt-display-show-daily-totals', section: 'time-tracking', group: 'Display', label: 'Show daily subtotals', type: 'toggle', default: true },
  { id: 'tt-display-empty-state-tip', section: 'time-tracking', group: 'Display', label: 'Show empty-state tips', type: 'toggle', default: true },
  { id: 'tt-display-timeline-zoom', section: 'time-tracking', group: 'Display', label: 'Calendar timeline zoom', type: 'select', default: 'week', options: [{ value: 'day', label: 'Day' }, { value: 'week', label: 'Week' }, { value: 'month', label: 'Month' }] },
  { id: 'tt-display-show-idle-warning', section: 'time-tracking', group: 'Display', label: 'Show idle time warning', type: 'toggle', default: true },
  { id: 'tt-display-duration-bar', section: 'time-tracking', group: 'Display', label: 'Show duration bar chart in rows', type: 'toggle', default: false },
  { id: 'tt-display-collapse-completed', section: 'time-tracking', group: 'Display', label: 'Auto-collapse completed days', type: 'toggle', default: false },

  // ===== Columns =====
  { id: 'tt-col-show-date', section: 'time-tracking', group: 'Columns', label: 'Show Date column', type: 'toggle', default: true },
  { id: 'tt-col-show-start-end', section: 'time-tracking', group: 'Columns', label: 'Show Start/End time columns', type: 'toggle', default: true },
  { id: 'tt-col-show-duration', section: 'time-tracking', group: 'Columns', label: 'Show Duration column', type: 'toggle', default: true },
  { id: 'tt-col-show-project', section: 'time-tracking', group: 'Columns', label: 'Show Project column', type: 'toggle', default: true },
  { id: 'tt-col-show-task', section: 'time-tracking', group: 'Columns', label: 'Show Task column', type: 'toggle', default: true },
  { id: 'tt-col-show-client', section: 'time-tracking', group: 'Columns', label: 'Show Client column', type: 'toggle', default: true },
  { id: 'tt-col-show-notes', section: 'time-tracking', group: 'Columns', label: 'Show Notes column', type: 'toggle', default: true },
  { id: 'tt-col-show-billable', section: 'time-tracking', group: 'Columns', label: 'Show Billable column', type: 'toggle', default: true },
  { id: 'tt-col-show-rate', section: 'time-tracking', group: 'Columns', label: 'Show Hourly Rate column', type: 'toggle', default: false },
  { id: 'tt-col-show-amount', section: 'time-tracking', group: 'Columns', label: 'Show Amount column', type: 'toggle', default: true },
  { id: 'tt-col-show-member', section: 'time-tracking', group: 'Columns', label: 'Show Team Member column', type: 'toggle', default: true },
  { id: 'tt-col-show-tags', section: 'time-tracking', group: 'Columns', label: 'Show Tags column', type: 'toggle', default: false },
  { id: 'tt-col-show-approval', section: 'time-tracking', group: 'Columns', label: 'Show Approval Status column', type: 'toggle', default: true },
  { id: 'tt-col-show-invoiced', section: 'time-tracking', group: 'Columns', label: 'Show Invoiced status column', type: 'toggle', default: true },
  { id: 'tt-col-show-source', section: 'time-tracking', group: 'Columns', label: 'Show Entry Source column', description: 'Timer, manual, or imported', type: 'toggle', default: false },
  { id: 'tt-col-notes-width', section: 'time-tracking', group: 'Columns', label: 'Notes column width (px)', type: 'number', default: 240, min: 80, max: 600, step: 10 },
  { id: 'tt-col-pin-duration', section: 'time-tracking', group: 'Columns', label: 'Pin Duration column', type: 'toggle', default: false },
  { id: 'tt-col-order', section: 'time-tracking', group: 'Columns', label: 'Column order preset', type: 'select', default: 'standard', options: [{ value: 'standard', label: 'Standard' }, { value: 'billing-first', label: 'Billing first' }, { value: 'minimal', label: 'Minimal' }] },

  // ===== Formatting =====
  { id: 'tt-fmt-duration-format', section: 'time-tracking', group: 'Formatting', label: 'Duration format', type: 'select', default: 'hh:mm', options: [{ value: 'hh:mm', label: '1:30' }, { value: 'decimal', label: '1.50' }, { value: 'hhmm-text', label: '1h 30m' }, { value: 'minutes', label: '90m' }] },
  { id: 'tt-fmt-time-format', section: 'time-tracking', group: 'Formatting', label: 'Time of day format', type: 'select', default: '12h', options: [{ value: '12h', label: '12-hour' }, { value: '24h', label: '24-hour' }] },
  { id: 'tt-fmt-date-format', section: 'time-tracking', group: 'Formatting', label: 'Date format', type: 'select', default: 'mm/dd/yyyy', options: [{ value: 'mm/dd/yyyy', label: 'MM/DD/YYYY' }, { value: 'dd/mm/yyyy', label: 'DD/MM/YYYY' }, { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' }] },
  { id: 'tt-fmt-decimal-places', section: 'time-tracking', group: 'Formatting', label: 'Decimal hours precision', type: 'number', default: 2, min: 0, max: 4, step: 1 },
  { id: 'tt-fmt-currency-symbol', section: 'time-tracking', group: 'Formatting', label: 'Currency symbol', type: 'text', default: '$' },
  { id: 'tt-fmt-currency-position', section: 'time-tracking', group: 'Formatting', label: 'Currency symbol position', type: 'select', default: 'before', options: [{ value: 'before', label: 'Before ($10)' }, { value: 'after', label: 'After (10$)' }] },
  { id: 'tt-fmt-week-start', section: 'time-tracking', group: 'Formatting', label: 'Week starts on', type: 'select', default: 'monday', options: [{ value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }, { value: 'saturday', label: 'Saturday' }] },
  { id: 'tt-fmt-rounding-display', section: 'time-tracking', group: 'Formatting', label: 'Round displayed durations', type: 'toggle', default: false },
  { id: 'tt-fmt-rounding-increment', section: 'time-tracking', group: 'Formatting', label: 'Display rounding increment (min)', type: 'number', default: 15, min: 1, max: 60, step: 1 },
  { id: 'tt-fmt-show-seconds', section: 'time-tracking', group: 'Formatting', label: 'Show seconds in timer', type: 'toggle', default: true },
  { id: 'tt-fmt-thousand-separator', section: 'time-tracking', group: 'Formatting', label: 'Thousands separator in amounts', type: 'toggle', default: true },
  { id: 'tt-fmt-relative-dates', section: 'time-tracking', group: 'Formatting', label: 'Use relative dates (Today, Yesterday)', type: 'toggle', default: true },
  { id: 'tt-fmt-negative-style', section: 'time-tracking', group: 'Formatting', label: 'Negative amount style', type: 'select', default: 'minus', options: [{ value: 'minus', label: '-$10' }, { value: 'parens', label: '($10)' }, { value: 'red', label: 'Red text' }] },
  { id: 'tt-fmt-empty-duration', section: 'time-tracking', group: 'Formatting', label: 'Empty duration placeholder', type: 'text', default: '—' },

  // ===== Defaults =====
  { id: 'tt-def-billable', section: 'time-tracking', group: 'Defaults', label: 'New entries billable by default', type: 'toggle', default: true },
  { id: 'tt-def-rounding-mode', section: 'time-tracking', group: 'Defaults', label: 'Time rounding mode', type: 'select', default: 'nearest', options: [{ value: 'none', label: 'No rounding' }, { value: 'nearest', label: 'Nearest' }, { value: 'up', label: 'Round up' }, { value: 'down', label: 'Round down' }] },
  { id: 'tt-def-rounding-increment', section: 'time-tracking', group: 'Defaults', label: 'Rounding increment (min)', type: 'number', default: 6, min: 1, max: 60, step: 1 },
  { id: 'tt-def-hourly-rate', section: 'time-tracking', group: 'Defaults', label: 'Default hourly rate', type: 'number', default: 75, min: 0, max: 10000, step: 5 },
  { id: 'tt-def-min-duration', section: 'time-tracking', group: 'Defaults', label: 'Minimum logged duration (min)', type: 'number', default: 1, min: 0, max: 120, step: 1 },
  { id: 'tt-def-project', section: 'time-tracking', group: 'Defaults', label: 'Default project name', type: 'text', default: '' },
  { id: 'tt-def-task', section: 'time-tracking', group: 'Defaults', label: 'Default task name', type: 'text', default: '' },
  { id: 'tt-def-note-template', section: 'time-tracking', group: 'Defaults', label: 'Default note template', type: 'text', default: '' },
  { id: 'tt-def-remember-last', section: 'time-tracking', group: 'Defaults', label: 'Remember last project/task', type: 'toggle', default: true },
  { id: 'tt-def-day-target-hours', section: 'time-tracking', group: 'Defaults', label: 'Daily target hours', type: 'number', default: 8, min: 0, max: 24, step: 0.5 },
  { id: 'tt-def-week-target-hours', section: 'time-tracking', group: 'Defaults', label: 'Weekly target hours', type: 'number', default: 40, min: 0, max: 168, step: 1 },
  { id: 'tt-def-overtime-threshold', section: 'time-tracking', group: 'Defaults', label: 'Daily overtime threshold (hrs)', type: 'number', default: 8, min: 0, max: 24, step: 0.5 },
  { id: 'tt-def-currency', section: 'time-tracking', group: 'Defaults', label: 'Default billing currency', type: 'select', default: 'USD', options: [{ value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' }] },
  { id: 'tt-def-tax-rate', section: 'time-tracking', group: 'Defaults', label: 'Default tax rate on time (%)', type: 'number', default: 0, min: 0, max: 50, step: 0.1 },
  { id: 'tt-def-start-on-open', section: 'time-tracking', group: 'Defaults', label: 'Pre-fill start time on new entry', type: 'toggle', default: true },

  // ===== Timer =====
  { id: 'tt-timer-mode', section: 'time-tracking', group: 'Timer', label: 'Timer mode', type: 'select', default: 'stopwatch', options: [{ value: 'stopwatch', label: 'Stopwatch' }, { value: 'pomodoro', label: 'Pomodoro' }, { value: 'manual', label: 'Manual only' }] },
  { id: 'tt-timer-single-active', section: 'time-tracking', group: 'Timer', label: 'Allow only one running timer', type: 'toggle', default: true },
  { id: 'tt-timer-idle-detection', section: 'time-tracking', group: 'Timer', label: 'Enable idle detection', type: 'toggle', default: true },
  { id: 'tt-timer-idle-threshold', section: 'time-tracking', group: 'Timer', label: 'Idle threshold (min)', type: 'number', default: 10, min: 1, max: 120, step: 1 },
  { id: 'tt-timer-idle-action', section: 'time-tracking', group: 'Timer', label: 'On idle detected', type: 'select', default: 'prompt', options: [{ value: 'prompt', label: 'Prompt me' }, { value: 'discard', label: 'Discard idle time' }, { value: 'keep', label: 'Keep idle time' }, { value: 'stop', label: 'Stop timer' }] },
  { id: 'tt-timer-auto-stop-shutdown', section: 'time-tracking', group: 'Timer', label: 'Auto-stop timer on app close', type: 'toggle', default: true },
  { id: 'tt-timer-resume-prompt', section: 'time-tracking', group: 'Timer', label: 'Prompt to resume timer on launch', type: 'toggle', default: true },
  { id: 'tt-timer-pomodoro-work', section: 'time-tracking', group: 'Timer', label: 'Pomodoro work length (min)', type: 'number', default: 25, min: 5, max: 90, step: 5 },
  { id: 'tt-timer-pomodoro-break', section: 'time-tracking', group: 'Timer', label: 'Pomodoro break length (min)', type: 'number', default: 5, min: 1, max: 30, step: 1 },
  { id: 'tt-timer-pomodoro-long-break', section: 'time-tracking', group: 'Timer', label: 'Pomodoro long break (min)', type: 'number', default: 15, min: 5, max: 60, step: 5 },
  { id: 'tt-timer-require-note-stop', section: 'time-tracking', group: 'Timer', label: 'Require note when stopping timer', type: 'toggle', default: false },
  { id: 'tt-timer-require-project-start', section: 'time-tracking', group: 'Timer', label: 'Require project before starting timer', type: 'toggle', default: false },
  { id: 'tt-timer-confirm-discard', section: 'time-tracking', group: 'Timer', label: 'Confirm before discarding timer', type: 'toggle', default: true },
  { id: 'tt-timer-max-duration', section: 'time-tracking', group: 'Timer', label: 'Max timer duration before warning (hrs)', type: 'number', default: 12, min: 1, max: 24, step: 1 },
  { id: 'tt-timer-show-tray', section: 'time-tracking', group: 'Timer', label: 'Show timer in system tray', type: 'toggle', default: true },
  { id: 'tt-timer-tray-format', section: 'time-tracking', group: 'Timer', label: 'Tray timer label', type: 'select', default: 'elapsed', options: [{ value: 'elapsed', label: 'Elapsed time' }, { value: 'project', label: 'Project name' }, { value: 'both', label: 'Both' }] },
  { id: 'tt-timer-tick-sound', section: 'time-tracking', group: 'Timer', label: 'Play tick sound', type: 'toggle', default: false },

  // ===== Behavior =====
  { id: 'tt-beh-autosave', section: 'time-tracking', group: 'Behavior', label: 'Auto-save entry drafts', type: 'toggle', default: true },
  { id: 'tt-beh-autosave-interval', section: 'time-tracking', group: 'Behavior', label: 'Auto-save interval (sec)', type: 'number', default: 30, min: 5, max: 300, step: 5 },
  { id: 'tt-beh-inline-edit', section: 'time-tracking', group: 'Behavior', label: 'Enable inline cell editing', type: 'toggle', default: true },
  { id: 'tt-beh-duplicate-on-enter', section: 'time-tracking', group: 'Behavior', label: 'Quick-duplicate previous entry', type: 'toggle', default: true },
  { id: 'tt-beh-confirm-delete', section: 'time-tracking', group: 'Behavior', label: 'Confirm before deleting entries', type: 'toggle', default: true },
  { id: 'tt-beh-overlap-warning', section: 'time-tracking', group: 'Behavior', label: 'Warn on overlapping time entries', type: 'toggle', default: true },
  { id: 'tt-beh-future-warning', section: 'time-tracking', group: 'Behavior', label: 'Warn on future-dated entries', type: 'toggle', default: true },
  { id: 'tt-beh-lock-after-approval', section: 'time-tracking', group: 'Behavior', label: 'Lock entries after approval', type: 'toggle', default: true },
  { id: 'tt-beh-lock-after-invoice', section: 'time-tracking', group: 'Behavior', label: 'Lock entries after invoicing', type: 'toggle', default: true },
  { id: 'tt-beh-lock-period-days', section: 'time-tracking', group: 'Behavior', label: 'Lock entries older than (days)', type: 'number', default: 0, min: 0, max: 365, step: 1 },
  { id: 'tt-beh-auto-categorize', section: 'time-tracking', group: 'Behavior', label: 'Auto-suggest task from note', type: 'toggle', default: false },
  { id: 'tt-beh-continue-yesterday', section: 'time-tracking', group: 'Behavior', label: 'Offer to continue yesterday\'s work', type: 'toggle', default: true },
  { id: 'tt-beh-merge-short-gaps', section: 'time-tracking', group: 'Behavior', label: 'Merge entries with short gaps', type: 'toggle', default: false },
  { id: 'tt-beh-merge-gap-min', section: 'time-tracking', group: 'Behavior', label: 'Merge gap threshold (min)', type: 'number', default: 5, min: 1, max: 60, step: 1 },
  { id: 'tt-beh-keep-screen-awake', section: 'time-tracking', group: 'Behavior', label: 'Keep screen awake while tracking', type: 'toggle', default: false },
  { id: 'tt-beh-quick-add-bar', section: 'time-tracking', group: 'Behavior', label: 'Show quick-add entry bar', type: 'toggle', default: true },
  { id: 'tt-beh-default-add-position', section: 'time-tracking', group: 'Behavior', label: 'Add new entries at', type: 'select', default: 'top', options: [{ value: 'top', label: 'Top of list' }, { value: 'bottom', label: 'Bottom of list' }] },

  // ===== Sorting & Filtering =====
  { id: 'tt-sort-default-field', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Default sort field', type: 'select', default: 'date', options: [{ value: 'date', label: 'Date' }, { value: 'duration', label: 'Duration' }, { value: 'project', label: 'Project' }, { value: 'amount', label: 'Amount' }] },
  { id: 'tt-sort-default-dir', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Default sort direction', type: 'select', default: 'desc', options: [{ value: 'asc', label: 'Ascending' }, { value: 'desc', label: 'Descending' }] },
  { id: 'tt-filter-default-range', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Default date range', type: 'select', default: 'this-week', options: [{ value: 'today', label: 'Today' }, { value: 'this-week', label: 'This week' }, { value: 'this-month', label: 'This month' }, { value: 'custom', label: 'Custom' }] },
  { id: 'tt-filter-default-member', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Default member filter', type: 'select', default: 'me', options: [{ value: 'me', label: 'Just me' }, { value: 'all', label: 'All members' }, { value: 'team', label: 'My team' }] },
  { id: 'tt-filter-show-billable-only', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Default to billable only', type: 'toggle', default: false },
  { id: 'tt-filter-hide-invoiced', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Hide invoiced entries by default', type: 'toggle', default: false },
  { id: 'tt-filter-hide-approved', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Hide approved entries by default', type: 'toggle', default: false },
  { id: 'tt-filter-remember', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Remember last used filters', type: 'toggle', default: true },
  { id: 'tt-filter-saved-views', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Enable saved filter views', type: 'toggle', default: true },
  { id: 'tt-filter-search-scope', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Search scope', type: 'select', default: 'all', options: [{ value: 'notes', label: 'Notes only' }, { value: 'all', label: 'All fields' }, { value: 'tags', label: 'Tags only' }] },
  { id: 'tt-filter-min-duration-hide', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Hide entries shorter than (min)', type: 'number', default: 0, min: 0, max: 120, step: 1 },
  { id: 'tt-sort-secondary-field', section: 'time-tracking', group: 'Sorting & Filtering', label: 'Secondary sort field', type: 'select', default: 'project', options: [{ value: 'none', label: 'None' }, { value: 'project', label: 'Project' }, { value: 'client', label: 'Client' }, { value: 'member', label: 'Member' }] },

  // ===== Notifications =====
  { id: 'tt-notif-timer-running-reminder', section: 'time-tracking', group: 'Notifications', label: 'Remind me a timer is running', type: 'toggle', default: true },
  { id: 'tt-notif-running-interval', section: 'time-tracking', group: 'Notifications', label: 'Running-timer reminder interval (min)', type: 'number', default: 30, min: 5, max: 240, step: 5 },
  { id: 'tt-notif-no-time-logged', section: 'time-tracking', group: 'Notifications', label: 'Remind me if no time logged today', type: 'toggle', default: true },
  { id: 'tt-notif-no-time-hour', section: 'time-tracking', group: 'Notifications', label: 'No-time reminder hour (24h)', type: 'number', default: 16, min: 0, max: 23, step: 1 },
  { id: 'tt-notif-daily-target-met', section: 'time-tracking', group: 'Notifications', label: 'Notify when daily target met', type: 'toggle', default: false },
  { id: 'tt-notif-overtime', section: 'time-tracking', group: 'Notifications', label: 'Notify on overtime', type: 'toggle', default: true },
  { id: 'tt-notif-weekly-summary', section: 'time-tracking', group: 'Notifications', label: 'Send weekly summary', type: 'toggle', default: true },
  { id: 'tt-notif-weekly-summary-day', section: 'time-tracking', group: 'Notifications', label: 'Weekly summary day', type: 'select', default: 'friday', options: [{ value: 'friday', label: 'Friday' }, { value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },
  { id: 'tt-notif-approval-needed', section: 'time-tracking', group: 'Notifications', label: 'Notify approver of pending timesheets', type: 'toggle', default: true },
  { id: 'tt-notif-approval-result', section: 'time-tracking', group: 'Notifications', label: 'Notify me of approval/rejection', type: 'toggle', default: true },
  { id: 'tt-notif-pomodoro-sound', section: 'time-tracking', group: 'Notifications', label: 'Play sound on Pomodoro end', type: 'toggle', default: true },
  { id: 'tt-notif-sound', section: 'time-tracking', group: 'Notifications', label: 'Notification sound', type: 'select', default: 'chime', options: [{ value: 'none', label: 'Silent' }, { value: 'chime', label: 'Chime' }, { value: 'bell', label: 'Bell' }, { value: 'ping', label: 'Ping' }] },
  { id: 'tt-notif-desktop', section: 'time-tracking', group: 'Notifications', label: 'Show desktop notifications', type: 'toggle', default: true },
  { id: 'tt-notif-submit-reminder', section: 'time-tracking', group: 'Notifications', label: 'Remind me to submit timesheet', type: 'toggle', default: true },
  { id: 'tt-notif-submit-reminder-day', section: 'time-tracking', group: 'Notifications', label: 'Submit reminder day', type: 'select', default: 'friday', options: [{ value: 'friday', label: 'Friday' }, { value: 'saturday', label: 'Saturday' }, { value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },

  // ===== Approval & Timesheets =====
  { id: 'tt-appr-require-approval', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Require timesheet approval', type: 'toggle', default: true },
  { id: 'tt-appr-period', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Timesheet period', type: 'select', default: 'weekly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'semimonthly', label: 'Semi-monthly' }, { value: 'monthly', label: 'Monthly' }] },
  { id: 'tt-appr-self-approve', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Allow self-approval', type: 'toggle', default: false },
  { id: 'tt-appr-auto-submit', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Auto-submit at period end', type: 'toggle', default: false },
  { id: 'tt-appr-require-note-reject', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Require note on rejection', type: 'toggle', default: true },
  { id: 'tt-appr-allow-edit-submitted', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Allow editing submitted entries', type: 'toggle', default: false },
  { id: 'tt-appr-approvers', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Default approver email', type: 'text', default: '' },
  { id: 'tt-appr-escalate-days', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Escalate unapproved after (days)', type: 'number', default: 3, min: 0, max: 30, step: 1 },
  { id: 'tt-appr-warn-incomplete', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Warn if below target before submit', type: 'toggle', default: true },
  { id: 'tt-appr-show-history', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Show approval history', type: 'toggle', default: true },
  { id: 'tt-appr-cutoff-day', section: 'time-tracking', group: 'Approval & Timesheets', label: 'Submission cutoff day of week', type: 'select', default: 'sunday', options: [{ value: 'friday', label: 'Friday' }, { value: 'saturday', label: 'Saturday' }, { value: 'sunday', label: 'Sunday' }, { value: 'monday', label: 'Monday' }] },

  // ===== Billing & Rates =====
  { id: 'tt-bill-rate-source', section: 'time-tracking', group: 'Billing & Rates', label: 'Rate source priority', type: 'select', default: 'task', options: [{ value: 'member', label: 'Member rate' }, { value: 'project', label: 'Project rate' }, { value: 'task', label: 'Task rate' }, { value: 'client', label: 'Client rate' }] },
  { id: 'tt-bill-round-to-invoice', section: 'time-tracking', group: 'Billing & Rates', label: 'Round time when invoicing', type: 'toggle', default: true },
  { id: 'tt-bill-invoice-increment', section: 'time-tracking', group: 'Billing & Rates', label: 'Invoice rounding increment (min)', type: 'number', default: 15, min: 1, max: 60, step: 1 },
  { id: 'tt-bill-min-billable', section: 'time-tracking', group: 'Billing & Rates', label: 'Minimum billable block (min)', type: 'number', default: 0, min: 0, max: 120, step: 5 },
  { id: 'tt-bill-overtime-multiplier', section: 'time-tracking', group: 'Billing & Rates', label: 'Overtime rate multiplier', type: 'number', default: 1.5, min: 1, max: 3, step: 0.1 },
  { id: 'tt-bill-show-cost-vs-bill', section: 'time-tracking', group: 'Billing & Rates', label: 'Show cost vs billable rate', type: 'toggle', default: false },
  { id: 'tt-bill-default-cost-rate', section: 'time-tracking', group: 'Billing & Rates', label: 'Default internal cost rate', type: 'number', default: 40, min: 0, max: 10000, step: 5 },
  { id: 'tt-bill-currency-per-client', section: 'time-tracking', group: 'Billing & Rates', label: 'Allow per-client currency', type: 'toggle', default: false },
  { id: 'tt-bill-mark-billed-on-invoice', section: 'time-tracking', group: 'Billing & Rates', label: 'Mark entries billed when invoiced', type: 'toggle', default: true },
  { id: 'tt-bill-group-invoice-by', section: 'time-tracking', group: 'Billing & Rates', label: 'Group invoice lines by', type: 'select', default: 'task', options: [{ value: 'entry', label: 'Each entry' }, { value: 'task', label: 'Task' }, { value: 'project', label: 'Project' }, { value: 'day', label: 'Day' }] },
  { id: 'tt-bill-include-notes-invoice', section: 'time-tracking', group: 'Billing & Rates', label: 'Include notes on invoice lines', type: 'toggle', default: true },
  { id: 'tt-bill-nonbillable-on-invoice', section: 'time-tracking', group: 'Billing & Rates', label: 'Show non-billable time on invoice', type: 'toggle', default: false },

  // ===== Export =====
  { id: 'tt-exp-default-format', section: 'time-tracking', group: 'Export', label: 'Default export format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'pdf', label: 'PDF' }, { value: 'json', label: 'JSON' }] },
  { id: 'tt-exp-include-headers', section: 'time-tracking', group: 'Export', label: 'Include column headers', type: 'toggle', default: true },
  { id: 'tt-exp-duration-as-decimal', section: 'time-tracking', group: 'Export', label: 'Export durations as decimal', type: 'toggle', default: true },
  { id: 'tt-exp-include-amounts', section: 'time-tracking', group: 'Export', label: 'Include billing amounts', type: 'toggle', default: true },
  { id: 'tt-exp-include-notes', section: 'time-tracking', group: 'Export', label: 'Include notes', type: 'toggle', default: true },
  { id: 'tt-exp-include-nonbillable', section: 'time-tracking', group: 'Export', label: 'Include non-billable entries', type: 'toggle', default: true },
  { id: 'tt-exp-csv-delimiter', section: 'time-tracking', group: 'Export', label: 'CSV delimiter', type: 'select', default: 'comma', options: [{ value: 'comma', label: 'Comma' }, { value: 'semicolon', label: 'Semicolon' }, { value: 'tab', label: 'Tab' }] },
  { id: 'tt-exp-filename-template', section: 'time-tracking', group: 'Export', label: 'Export filename template', type: 'text', default: 'timesheet_{period}' },
  { id: 'tt-exp-group-by', section: 'time-tracking', group: 'Export', label: 'Group export by', type: 'select', default: 'none', options: [{ value: 'none', label: 'None' }, { value: 'project', label: 'Project' }, { value: 'member', label: 'Member' }, { value: 'client', label: 'Client' }] },
  { id: 'tt-exp-pdf-logo', section: 'time-tracking', group: 'Export', label: 'Include company logo on PDF', type: 'toggle', default: true },
  { id: 'tt-exp-pdf-signature', section: 'time-tracking', group: 'Export', label: 'Include signature line on PDF', type: 'toggle', default: false },
  { id: 'tt-exp-summary-page', section: 'time-tracking', group: 'Export', label: 'Add summary page to export', type: 'toggle', default: true },
  { id: 'tt-exp-date-range-in-name', section: 'time-tracking', group: 'Export', label: 'Append date range to filename', type: 'toggle', default: true },
  { id: 'tt-exp-utf8-bom', section: 'time-tracking', group: 'Export', label: 'Add UTF-8 BOM to CSV', type: 'toggle', default: false },

  // ===== Colors & Theme =====
  { id: 'tt-color-billable', section: 'time-tracking', group: 'Colors & Theme', label: 'Billable accent color', type: 'color', default: '#22c55e' },
  { id: 'tt-color-nonbillable', section: 'time-tracking', group: 'Colors & Theme', label: 'Non-billable accent color', type: 'color', default: '#94a3b8' },
  { id: 'tt-color-running-timer', section: 'time-tracking', group: 'Colors & Theme', label: 'Running timer color', type: 'color', default: '#3b82f6' },
  { id: 'tt-color-overtime', section: 'time-tracking', group: 'Colors & Theme', label: 'Overtime highlight color', type: 'color', default: '#f59e0b' },
  { id: 'tt-color-approved', section: 'time-tracking', group: 'Colors & Theme', label: 'Approved status color', type: 'color', default: '#16a34a' },
  { id: 'tt-color-pending', section: 'time-tracking', group: 'Colors & Theme', label: 'Pending status color', type: 'color', default: '#eab308' },
  { id: 'tt-color-rejected', section: 'time-tracking', group: 'Colors & Theme', label: 'Rejected status color', type: 'color', default: '#ef4444' },
  { id: 'tt-color-invoiced', section: 'time-tracking', group: 'Colors & Theme', label: 'Invoiced status color', type: 'color', default: '#8b5cf6' },
  { id: 'tt-color-target-met', section: 'time-tracking', group: 'Colors & Theme', label: 'Target-met bar color', type: 'color', default: '#10b981' },
  { id: 'tt-color-idle', section: 'time-tracking', group: 'Colors & Theme', label: 'Idle time color', type: 'color', default: '#f97316' },
  { id: 'tt-color-today-highlight', section: 'time-tracking', group: 'Colors & Theme', label: 'Today highlight color', type: 'color', default: '#0ea5e9' },
  { id: 'tt-color-weekend', section: 'time-tracking', group: 'Colors & Theme', label: 'Weekend column tint', type: 'color', default: '#1e293b' },
  { id: 'tt-color-use-project-colors', section: 'time-tracking', group: 'Colors & Theme', label: 'Use per-project colors', type: 'toggle', default: true },
  { id: 'tt-color-heatmap', section: 'time-tracking', group: 'Colors & Theme', label: 'Activity heatmap color', type: 'color', default: '#6366f1' },

  // ===== Accessibility =====
  { id: 'tt-a11y-high-contrast', section: 'time-tracking', group: 'Accessibility', label: 'High contrast mode', type: 'toggle', default: false },
  { id: 'tt-a11y-font-size', section: 'time-tracking', group: 'Accessibility', label: 'Base font size (px)', type: 'number', default: 14, min: 10, max: 24, step: 1 },
  { id: 'tt-a11y-reduce-motion', section: 'time-tracking', group: 'Accessibility', label: 'Reduce timer animations', type: 'toggle', default: false },
  { id: 'tt-a11y-status-icons', section: 'time-tracking', group: 'Accessibility', label: 'Use icons alongside status colors', type: 'toggle', default: true },
  { id: 'tt-a11y-screen-reader-times', section: 'time-tracking', group: 'Accessibility', label: 'Verbose durations for screen readers', type: 'toggle', default: true },
  { id: 'tt-a11y-focus-outline', section: 'time-tracking', group: 'Accessibility', label: 'Show strong focus outline', type: 'toggle', default: true },
  { id: 'tt-a11y-keyboard-nav', section: 'time-tracking', group: 'Accessibility', label: 'Enable full keyboard grid navigation', type: 'toggle', default: true },
  { id: 'tt-a11y-colorblind-mode', section: 'time-tracking', group: 'Accessibility', label: 'Colorblind-safe palette', type: 'select', default: 'off', options: [{ value: 'off', label: 'Off' }, { value: 'deuteranopia', label: 'Deuteranopia' }, { value: 'protanopia', label: 'Protanopia' }, { value: 'tritanopia', label: 'Tritanopia' }] },
  { id: 'tt-a11y-announce-timer', section: 'time-tracking', group: 'Accessibility', label: 'Announce timer start/stop', type: 'toggle', default: false },
  { id: 'tt-a11y-line-height', section: 'time-tracking', group: 'Accessibility', label: 'Row line height multiplier', type: 'number', default: 1.4, min: 1, max: 2.5, step: 0.1 },

  // ===== Shortcuts =====
  { id: 'tt-key-start-stop', section: 'time-tracking', group: 'Shortcuts', label: 'Start/stop timer shortcut', type: 'text', default: 'Cmd+Shift+T' },
  { id: 'tt-key-new-entry', section: 'time-tracking', group: 'Shortcuts', label: 'New manual entry shortcut', type: 'text', default: 'Cmd+N' },
  { id: 'tt-key-duplicate', section: 'time-tracking', group: 'Shortcuts', label: 'Duplicate entry shortcut', type: 'text', default: 'Cmd+D' },
  { id: 'tt-key-delete', section: 'time-tracking', group: 'Shortcuts', label: 'Delete entry shortcut', type: 'text', default: 'Cmd+Backspace' },
  { id: 'tt-key-submit', section: 'time-tracking', group: 'Shortcuts', label: 'Submit timesheet shortcut', type: 'text', default: 'Cmd+Enter' },
  { id: 'tt-key-search', section: 'time-tracking', group: 'Shortcuts', label: 'Focus search shortcut', type: 'text', default: 'Cmd+F' },
  { id: 'tt-key-next-day', section: 'time-tracking', group: 'Shortcuts', label: 'Next day shortcut', type: 'text', default: 'Cmd+Right' },
  { id: 'tt-key-prev-day', section: 'time-tracking', group: 'Shortcuts', label: 'Previous day shortcut', type: 'text', default: 'Cmd+Left' },
  { id: 'tt-key-enabled', section: 'time-tracking', group: 'Shortcuts', label: 'Enable keyboard shortcuts', type: 'toggle', default: true },
  { id: 'tt-key-global-timer', section: 'time-tracking', group: 'Shortcuts', label: 'Enable global (system-wide) timer hotkey', type: 'toggle', default: false },
  { id: 'tt-key-toggle-billable', section: 'time-tracking', group: 'Shortcuts', label: 'Toggle billable shortcut', type: 'text', default: 'Cmd+B' },
  { id: 'tt-key-jump-today', section: 'time-tracking', group: 'Shortcuts', label: 'Jump to today shortcut', type: 'text', default: 'Cmd+T' },

  // ===== Privacy =====
  { id: 'tt-priv-track-activity', section: 'time-tracking', group: 'Privacy', label: 'Track app/window activity', type: 'toggle', default: false },
  { id: 'tt-priv-screenshots', section: 'time-tracking', group: 'Privacy', label: 'Capture periodic screenshots', type: 'toggle', default: false },
  { id: 'tt-priv-screenshot-interval', section: 'time-tracking', group: 'Privacy', label: 'Screenshot interval (min)', type: 'number', default: 10, min: 1, max: 60, step: 1 },
  { id: 'tt-priv-blur-screenshots', section: 'time-tracking', group: 'Privacy', label: 'Blur captured screenshots', type: 'toggle', default: true },
  { id: 'tt-priv-hide-rates-others', section: 'time-tracking', group: 'Privacy', label: 'Hide my rates from teammates', type: 'toggle', default: true },
  { id: 'tt-priv-hide-notes-others', section: 'time-tracking', group: 'Privacy', label: 'Hide my notes from teammates', type: 'toggle', default: false },
  { id: 'tt-priv-share-with-manager', section: 'time-tracking', group: 'Privacy', label: 'Share entries with manager', type: 'toggle', default: true },
  { id: 'tt-priv-anonymize-export', section: 'time-tracking', group: 'Privacy', label: 'Anonymize member names in export', type: 'toggle', default: false },
  { id: 'tt-priv-retention-days', section: 'time-tracking', group: 'Privacy', label: 'Activity data retention (days)', type: 'number', default: 90, min: 0, max: 730, step: 30 },
  { id: 'tt-priv-pause-during-break', section: 'time-tracking', group: 'Privacy', label: 'Pause tracking during breaks', type: 'toggle', default: true },
  { id: 'tt-priv-audit-log', section: 'time-tracking', group: 'Privacy', label: 'Keep entry edit audit log', type: 'toggle', default: true },

  // ===== Reports & Analytics =====
  { id: 'tt-rep-default-report', section: 'time-tracking', group: 'Reports & Analytics', label: 'Default report', type: 'select', default: 'summary', options: [{ value: 'summary', label: 'Summary' }, { value: 'detailed', label: 'Detailed' }, { value: 'by-project', label: 'By project' }, { value: 'by-member', label: 'By member' }, { value: 'utilization', label: 'Utilization' }] },
  { id: 'tt-rep-utilization-target', section: 'time-tracking', group: 'Reports & Analytics', label: 'Utilization target (%)', type: 'number', default: 80, min: 0, max: 100, step: 5 },
  { id: 'tt-rep-chart-type', section: 'time-tracking', group: 'Reports & Analytics', label: 'Report chart type', type: 'select', default: 'bar', options: [{ value: 'bar', label: 'Bar' }, { value: 'pie', label: 'Pie' }, { value: 'line', label: 'Line' }, { value: 'stacked', label: 'Stacked bar' }] },
  { id: 'tt-rep-show-billable-pct', section: 'time-tracking', group: 'Reports & Analytics', label: 'Show billable percentage', type: 'toggle', default: true },
  { id: 'tt-rep-include-weekends', section: 'time-tracking', group: 'Reports & Analytics', label: 'Include weekends in averages', type: 'toggle', default: false },
  { id: 'tt-rep-compare-prior', section: 'time-tracking', group: 'Reports & Analytics', label: 'Compare to prior period', type: 'toggle', default: true },
  { id: 'tt-rep-top-projects-count', section: 'time-tracking', group: 'Reports & Analytics', label: 'Top projects to show', type: 'number', default: 5, min: 1, max: 25, step: 1 },
  { id: 'tt-rep-show-trends', section: 'time-tracking', group: 'Reports & Analytics', label: 'Show trend indicators', type: 'toggle', default: true },
  { id: 'tt-rep-round-in-reports', section: 'time-tracking', group: 'Reports & Analytics', label: 'Apply rounding in reports', type: 'toggle', default: false },
  { id: 'tt-rep-heatmap', section: 'time-tracking', group: 'Reports & Analytics', label: 'Show activity heatmap', type: 'toggle', default: true },
  { id: 'tt-rep-cost-analysis', section: 'time-tracking', group: 'Reports & Analytics', label: 'Show cost vs revenue analysis', type: 'toggle', default: false },

  // ===== Integrations & Sync =====
  { id: 'tt-int-calendar-sync', section: 'time-tracking', group: 'Integrations & Sync', label: 'Sync from calendar events', type: 'toggle', default: false },
  { id: 'tt-int-calendar-source', section: 'time-tracking', group: 'Integrations & Sync', label: 'Calendar source', type: 'select', default: 'google', options: [{ value: 'google', label: 'Google Calendar' }, { value: 'outlook', label: 'Outlook' }, { value: 'ical', label: 'iCal' }] },
  { id: 'tt-int-create-from-events', section: 'time-tracking', group: 'Integrations & Sync', label: 'Auto-create entries from events', type: 'toggle', default: false },
  { id: 'tt-int-min-event-len', section: 'time-tracking', group: 'Integrations & Sync', label: 'Min event length to import (min)', type: 'number', default: 15, min: 1, max: 240, step: 5 },
  { id: 'tt-int-push-to-payroll', section: 'time-tracking', group: 'Integrations & Sync', label: 'Push approved hours to payroll', type: 'toggle', default: true },
  { id: 'tt-int-push-to-projects', section: 'time-tracking', group: 'Integrations & Sync', label: 'Update project budgets from time', type: 'toggle', default: true },
  { id: 'tt-int-auto-backup', section: 'time-tracking', group: 'Integrations & Sync', label: 'Include time data in auto-backup', type: 'toggle', default: true },
  { id: 'tt-int-sync-conflict', section: 'time-tracking', group: 'Integrations & Sync', label: 'Sync conflict resolution', type: 'select', default: 'newest', options: [{ value: 'newest', label: 'Keep newest' }, { value: 'local', label: 'Keep local' }, { value: 'remote', label: 'Keep remote' }, { value: 'prompt', label: 'Prompt me' }] },
  { id: 'tt-int-mobile-sync', section: 'time-tracking', group: 'Integrations & Sync', label: 'Sync with mobile timer', type: 'toggle', default: true },
  { id: 'tt-int-webhook-url', section: 'time-tracking', group: 'Integrations & Sync', label: 'Entry webhook URL', type: 'text', default: '' },

  // ===== Tags & Categorization =====
  { id: 'tt-tag-enable', section: 'time-tracking', group: 'Tags & Categorization', label: 'Enable tags', type: 'toggle', default: true },
  { id: 'tt-tag-require', section: 'time-tracking', group: 'Tags & Categorization', label: 'Require at least one tag', type: 'toggle', default: false },
  { id: 'tt-tag-max', section: 'time-tracking', group: 'Tags & Categorization', label: 'Max tags per entry', type: 'number', default: 5, min: 1, max: 20, step: 1 },
  { id: 'tt-tag-color', section: 'time-tracking', group: 'Tags & Categorization', label: 'Default tag color', type: 'color', default: '#64748b' },
  { id: 'tt-tag-suggest', section: 'time-tracking', group: 'Tags & Categorization', label: 'Suggest recent tags', type: 'toggle', default: true },
  { id: 'tt-tag-allow-new', section: 'time-tracking', group: 'Tags & Categorization', label: 'Allow creating new tags inline', type: 'toggle', default: true },
  { id: 'tt-tag-default-activity', section: 'time-tracking', group: 'Tags & Categorization', label: 'Default activity type', type: 'select', default: 'general', options: [{ value: 'general', label: 'General' }, { value: 'meeting', label: 'Meeting' }, { value: 'development', label: 'Development' }, { value: 'admin', label: 'Admin' }, { value: 'support', label: 'Support' }] },
  { id: 'tt-tag-show-in-list', section: 'time-tracking', group: 'Tags & Categorization', label: 'Show tag chips in entry list', type: 'toggle', default: true },

  // ===== Mobile & Offline =====
  { id: 'tt-mob-offline-mode', section: 'time-tracking', group: 'Mobile & Offline', label: 'Allow offline tracking', type: 'toggle', default: true },
  { id: 'tt-mob-gps-tag', section: 'time-tracking', group: 'Mobile & Offline', label: 'Tag entries with location', type: 'toggle', default: false },
  { id: 'tt-mob-geofence', section: 'time-tracking', group: 'Mobile & Offline', label: 'Auto start/stop with geofence', type: 'toggle', default: false },
  { id: 'tt-mob-haptic', section: 'time-tracking', group: 'Mobile & Offline', label: 'Haptic feedback on timer toggle', type: 'toggle', default: true },
  { id: 'tt-mob-sync-on-wifi', section: 'time-tracking', group: 'Mobile & Offline', label: 'Sync only on Wi-Fi', type: 'toggle', default: false },
  { id: 'tt-mob-widget', section: 'time-tracking', group: 'Mobile & Offline', label: 'Show home-screen widget', type: 'toggle', default: true },
  { id: 'tt-mob-quick-actions', section: 'time-tracking', group: 'Mobile & Offline', label: 'Enable lock-screen quick actions', type: 'toggle', default: true },
];
