#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Business Accounting Pro — VPS Initial Setup Script
#
# Run ONCE on a fresh Ubuntu 22.04 / 24.04 LTS VPS as root:
#   bash setup-vps.sh
#
# What this does:
#   1. Updates system packages
#   2. Installs Nginx
#   3. Installs Certbot (Let's Encrypt SSL)
#   4. Creates the deploy user with SSH key
#   5. Sets up directory structure
#   6. Configures Nginx for accounting.rmpgutah.us
#   7. Obtains SSL certificate
#   8. Enables the site and sets permissions
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

DOMAIN="accounting.rmpgutah.us"
DEPLOY_USER="deploy"
WEB_ROOT="/var/www/${DOMAIN}"
RELEASES_ROOT="/var/www/${DOMAIN}/releases"
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
ADMIN_EMAIL="admin@rmpgutah.us"   # ← change to your email for cert expiry notices

# ── Colors ──────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}▶ $*${NC}"; }
warning() { echo -e "${YELLOW}⚠ $*${NC}"; }
error()   { echo -e "${RED}✗ $*${NC}" >&2; exit 1; }

# ── Must run as root ─────────────────────────────────────
[[ $EUID -eq 0 ]] || error "Run this script as root: sudo bash setup-vps.sh"

# ─────────────────────────────────────────────────────────
info "1/8 — Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ─────────────────────────────────────────────────────────
info "2/8 — Installing Nginx, Certbot, rsync, curl..."
apt-get install -y -qq nginx certbot python3-certbot-nginx rsync curl ufw

# ─────────────────────────────────────────────────────────
info "3/8 — Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable
ufw status

# ─────────────────────────────────────────────────────────
info "4/8 — Creating deploy user '${DEPLOY_USER}'..."
if id "${DEPLOY_USER}" &>/dev/null; then
  warning "User '${DEPLOY_USER}' already exists — skipping creation."
else
  useradd -m -s /bin/bash "${DEPLOY_USER}"
  info "  Created user '${DEPLOY_USER}'"
fi

# Add deploy user to www-data group so it can write web files
usermod -aG www-data "${DEPLOY_USER}"

# Create .ssh directory for deploy user
DEPLOY_HOME=$(eval echo "~${DEPLOY_USER}")
mkdir -p "${DEPLOY_HOME}/.ssh"
touch "${DEPLOY_HOME}/.ssh/authorized_keys"
chmod 700 "${DEPLOY_HOME}/.ssh"
chmod 600 "${DEPLOY_HOME}/.ssh/authorized_keys"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${DEPLOY_HOME}/.ssh"

warning "  ACTION REQUIRED: Add your GitHub Actions public key to:"
warning "  ${DEPLOY_HOME}/.ssh/authorized_keys"
warning "  (See README in deploy/ directory for instructions)"

# ─────────────────────────────────────────────────────────
info "5/8 — Setting up web root directory structure..."
mkdir -p "${WEB_ROOT}"
mkdir -p "${RELEASES_ROOT}"
# Create a placeholder index.html until first real deployment
cat > "${WEB_ROOT}/index.html" <<'PLACEHOLDER'
<!DOCTYPE html><html><head><title>Coming Soon</title></head>
<body><p>Business Accounting Pro — deployment in progress.</p></body></html>
PLACEHOLDER

chown -R "${DEPLOY_USER}:www-data" "${WEB_ROOT}"
chmod -R 755 "${WEB_ROOT}"

# ─────────────────────────────────────────────────────────
info "6/8 — Writing Nginx configuration for ${DOMAIN}..."
cat > "${NGINX_CONF}" <<NGINX_EOF
# Business Accounting Pro — ${DOMAIN}
# Auto-generated by setup-vps.sh
# Managed by: certbot (SSL auto-renewal)

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    # Certbot ACME challenge path
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP → HTTPS
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${DOMAIN} www.${DOMAIN};

    # ── SSL (filled in by certbot) ─────────────────────
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # ── Security headers ───────────────────────────────
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options    "nosniff"                             always;
    add_header X-Frame-Options           "SAMEORIGIN"                          always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin"     always;

    root  ${WEB_ROOT};
    index index.html;

    # ── Landing page (static HTML) ─────────────────────
    location / {
        try_files \$uri \$uri/ /index.html;
        expires 1h;
        add_header Cache-Control "public, must-revalidate";
    }

    # ── Release/update files (served for electron-updater) ──
    location /releases/ {
        alias ${RELEASES_ROOT}/;
        autoindex off;

        # Allow CORS for electron-updater version checks
        add_header Access-Control-Allow-Origin "*";
        add_header Cache-Control "no-store, no-cache";

        # Force correct MIME types for update manifest files
        types {
            application/octet-stream dmg exe AppImage deb blockmap zip;
            text/yaml                yml yaml;
        }
    }

    # ── Static asset caching ───────────────────────────
    location ~* \.(svg|ico|png|jpg|jpeg|gif|webp|woff2|woff|ttf|css|js)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # ── Deny dotfiles ──────────────────────────────────
    location ~ /\. {
        deny all;
        return 404;
    }

    # ── Gzip compression ───────────────────────────────
    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml application/xml+rss text/javascript
               image/svg+xml;
    gzip_min_length 1000;
    gzip_proxied    any;
    gzip_vary       on;
}
NGINX_EOF

# Enable site
ln -sf "${NGINX_CONF}" "/etc/nginx/sites-enabled/${DOMAIN}"

# Remove default Nginx site if present
rm -f /etc/nginx/sites-enabled/default

# Test Nginx config before reload
nginx -t || error "Nginx configuration test failed — check ${NGINX_CONF}"

# ─────────────────────────────────────────────────────────
info "7/8 — Obtaining SSL certificate from Let's Encrypt..."
# Temporarily allow HTTP for certbot challenge
cat > "${NGINX_CONF}.http-only" <<HTTP_CONF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};
    root /var/www/certbot;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 200 'OK'; }
}
HTTP_CONF

mkdir -p /var/www/certbot
cp "${NGINX_CONF}.http-only" "/etc/nginx/sites-enabled/${DOMAIN}"
nginx -s reload 2>/dev/null || systemctl start nginx

certbot certonly \
  --webroot \
  --webroot-path=/var/www/certbot \
  --email "${ADMIN_EMAIL}" \
  --agree-tos \
  --no-eff-email \
  --domains "${DOMAIN},www.${DOMAIN}" \
  --non-interactive

# Restore full SSL config
cp "${NGINX_CONF}" "/etc/nginx/sites-enabled/${DOMAIN}"
nginx -t && nginx -s reload

rm -f "${NGINX_CONF}.http-only"

# Set up auto-renewal cron job
echo "0 3 * * * root certbot renew --quiet --post-hook 'nginx -s reload'" \
  > /etc/cron.d/certbot-renew
info "  Certbot auto-renewal cron installed."

# ─────────────────────────────────────────────────────────
info "7b/8 — Node.js 20 LTS and PM2 setup..."

# Install Node.js 20 LTS if not present
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
  info "  Node.js $(node --version) installed."
else
  info "  Node.js already installed: $(node --version)"
fi

# Install PM2 globally
npm install -g pm2 --quiet
pm2 startup systemd -u "${DEPLOY_USER}" --hp "/home/${DEPLOY_USER}" | tail -1 | bash || true

# Create server directory
mkdir -p /opt/bap-server
chown "${DEPLOY_USER}:${DEPLOY_USER}" /opt/bap-server
info "  PM2 and /opt/bap-server ready."

# ─────────────────────────────────────────────────────────
info "8/8 — Final permissions and Nginx restart..."
chown -R "${DEPLOY_USER}:www-data" "${WEB_ROOT}"
chmod -R 755 "${WEB_ROOT}"
systemctl enable nginx
systemctl restart nginx

echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  VPS setup complete!${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo ""
echo "  Domain:       https://${DOMAIN}"
echo "  Web root:     ${WEB_ROOT}"
echo "  Releases dir: ${RELEASES_ROOT}"
echo "  Deploy user:  ${DEPLOY_USER}"
echo ""
echo -e "${YELLOW}  NEXT STEPS:${NC}"
echo "  1. Add GitHub Actions SSH public key to:"
echo "     ${DEPLOY_HOME}/.ssh/authorized_keys"
echo "  2. Add these secrets in GitHub repo → Settings → Secrets:"
echo "     VPS_HOST        = <your VPS IP or hostname>"
echo "     VPS_USER        = ${DEPLOY_USER}"
echo "     VPS_SSH_KEY     = <your GitHub Actions private SSH key>"
echo "  3. Push to main — the deploy workflow fires automatically."
echo "  4. Create /opt/bap-server/.env with:"
echo "     PORT=3001"
echo "     SYNC_SECRET=\$(openssl rand -hex 32)"
echo "     STRIPE_SECRET_KEY=sk_live_..."
echo "     STRIPE_WEBHOOK_SECRET=whsec_..."
echo "     DESKTOP_WS_TOKEN=\$(openssl rand -hex 16)"
echo ""
