// ─── Single source of truth for table exemption sets ───
// These sets are used by db.create(), db.update(), db.queryAll(), and db.remove().
// ALL callers must import from here — DO NOT redefine locally in IPC or database files.
//
// Maintenance rule: keep each set deduplicated and alphabetized. The schema
// validator catches duplicates and stale entries (tables that now have a
// company_id column but are still on the exemption list).

// Tables that do NOT have a `company_id` column.
// db.create() injects company_id automatically unless the table is in this set.
//
// Categories (one entry per table, kept alphabetical within category):
//   1. Global reference / cross-tenant tables
//   2. User-scoped tables (no company_id)
//   3. Child / junction tables (company_id lives on parent)
//   4. Append-only log / audit tables without company scoping
export const TABLES_WITHOUT_COMPANY_ID = new Set([
  // ── 1. Global reference / cross-tenant ──────────────────────────
  'companies',
  'exchange_rates',
  'federal_payroll_constants',
  'federal_tax_brackets',
  'federal_tax_tables',
  'mileage_rates',
  'schema_meta',
  'schema_migrations',
  'state_tax_brackets',
  'state_tax_rates',
  'state_tax_tables',
  'users',

  // ── 2. User-scoped tables (no company_id) ───────────────────────
  'command_history',
  'custom_shortcuts',
  'macros',
  'user_2fa',

  // ── 3. Child / junction tables (company_id on parent) ───────────
  // Account-related child tables
  'account_aliases',
  'account_balance_history',
  'account_classify_rules',
  'account_comments',
  'account_group_members',
  'account_permissions',
  'account_renumber_log',
  'account_reconciliation_items',
  'account_reconciliations',
  'account_watches',
  // ACH (treasury) child tables
  'ach_batch_items',
  // API request log + webhook child tables
  'api_request_log',
  // Approval child tables
  'approval_instances',
  'audit_walkthroughs',
  // Bank child tables
  'bank_reconciliation_matches',
  'bank_match_attempts',
  // Bill child tables
  'bill_line_items',
  'bill_payments',
  // Budget child tables
  'budget_approvals',
  'budget_lines',
  // Cash-flow child / supporting tables
  'cc_statement_lines',
  // Classification settings
  'classification_settings',
  // Closed periods
  'closed_periods',
  // Client child tables
  'client_contacts',
  // Compliance child tables
  'compliance_documents',
  // Contract child tables
  'contract_modifications',
  'performance_obligations',
  'revenue_milestones',
  'variable_consideration_adjustments',
  // Credit-card / cost child tables
  'credit_note_items',
  // Debt child tables
  'debt_audit_log',
  'debt_automation_rules',
  'debt_campaigns',
  'debt_communications',
  'debt_compliance_log',
  'debt_contacts',
  'debt_disputes',
  'debt_evidence',
  'debt_legal_actions',
  'debt_notes',
  'debt_payment_matches',
  'debt_payment_plans',
  'debt_payments',
  'debt_pipeline_stages',
  'debt_plan_installments',
  'debt_promises',
  'debt_settlements',
  'debt_skip_traces',
  'debt_templates',
  // Document child tables
  'document_versions',
  // Email / template child tables
  'email_template_history',
  // Employee child tables
  'employee_equipment',
  // E-sign child tables
  'esign_audit_log',
  'esign_permissions',
  'esign_signatures',
  // Expense child tables
  'expense_approval_steps',
  'expense_comments',
  'expense_line_items',
  'expense_reimbursement_items',
  'expense_splits',
  // FX (held cross-tenant by design)
  'fx_rates',
  // Inter-company tables (company_id on parent_company_id / counterparty)
  'inter_company_je_pairs',
  'inter_company_transfers',
  // Inventory child tables
  'inventory_adjustment_items',
  'inventory_transfer_items',
  // Invoice child tables
  'invoice_debt_links',
  'invoice_line_items',
  'invoice_payment_schedule',
  'invoice_reminder_schedules',
  'invoice_reminders',
  // JE child / log tables (company_id on parent journal_entries row)
  'je_approvals',
  'je_attachments',
  'je_comments',
  'je_history',
  'journal_entry_lines',
  // Lead form submissions
  'lead_form_submissions',
  // Loan child tables
  'loan_events',
  'loan_payment_schedule',
  'loan_payments',
  // Lockbox child tables
  'lockbox_items',
  // Pay child tables
  'pay_stubs',
  // Period / SOX child tables
  'period_close_checklist',
  'period_close_log',
  'period_locks',
  'sox_control_tests',
  'sox_controls',
  // Portal integration
  'portal_integration_settings',
  // PTO child tables
  'pto_balances',
  'pto_policies',
  'pto_transactions',
  // PO child tables
  'po_line_items',
  // Prepaid / deferred-revenue child recognition tables
  'deferred_revenue_recognitions',
  'prepaid_recognitions',
  // Promo
  'promo_code_redemptions',
  // Quote child tables
  'quote_activity_log',
  'quote_line_items',
  'quote_signatures',
  'quote_template_lines',
  'quote_templates',
  // Recon
  'recon_imports',
  'recon_schedule',
  'reimbursement_batches',
  // Rolling forecast lines
  'rolling_forecast_lines',
  // Status / workflow child tables
  'custom_statuses',
  'entity_status_history',
  'status_transitions',
  // Stripe cache tables
  'stripe_cache',
  'stripe_offline_queue',
  'stripe_sync_state',
  'stripe_transactions',
  // Tag system child tables
  'entity_tags',
  'tag_groups',
  'tag_rules',
  'tags',
  // Tax filing
  'tax_filing_periods',
  'utah_withholding_config',
  // TB working/elimination
  'tb_elimination_entries',
  'tb_working_adjustments',
  // Stock-take child tables
  'stock_take_counts',
  // Timesheet child tables
  'timesheet_approvals',
  // Webhooks
  'webhook_deliveries',
  'webhook_secret_rotations',
  'webhook_subscriptions',
  // Workflow child tables
  'workflow_executions',
  'workflow_runs',
  // Asset depreciation
  'asset_depreciation_entries',

  // Dynamic Wave (F261-F350) — user-scoped or junction
  'workspace_layouts',
  'pinned_entities',
  'recently_viewed_entities',
  'search_history',
  'notification_preferences',
  'entity_locks',
  'user_presence',
  'report_schedules',
  'report_executions',
  'webhook_queue',
  'command_registry',

  // Feature Expansion Wave 3 (F351-F440) — global, junction, or other-scoped
  'state_withholding_tables',
  'state_reciprocity',
  'sales_tax_jurisdictions',
  'sales_tax_holidays',
  'entity_hierarchy',
  'currency_translations',
  'minority_interests',
  'goodwill_tracking',
  'equity_method_investments',
  'portal_users',
  'vendor_po_responses',
  'gmail_sync',
  'calendar_integrations',
  'calendar_event_sync',

  // Expense Advanced Wave (F541-F640) — child tables w/o company_id
  'trip_itinerary',
  'trip_per_diem_settings',
  'mileage_irs_rates',
  'mileage_state_rates',
  'mileage_route_stops',
  'expense_custom_field_values',
  'expense_voice_memos',

  // Finance Wave (F441-F540) — child / log tables (parent has company_id)
  'invoice_approval_steps',
  'invoice_email_log',
  'invoice_attachments',
  'progress_billing_releases',
  'retainer_drawdowns',
  'invoice_payment_plan_installments',
  'reminder_cadences',
  'payment_retry_attempts',
  'customer_credit_transactions',
  'refunds',
  'chargebacks',
  'customer_payment_methods',
  'check_print_jobs',
  'crypto_payments',
  'subscription_proration_events',
  'pricing_tiers',
  'usage_records',
  'customer_statements',
  'dunning_events',
  'bad_debt_writeoffs',
  'allowance_for_doubtful_accounts',
  'collection_agency_handoffs',
  'cohort_analysis',
  'analytics_snapshots',
  'withholding_tracking',
  'section_179_elections',
  'vendor_w9_records',
  'vendor_insurance_policies',
  'vendor_disputes',

  // ── 4. Append-only log / audit tables (no scoping by design) ────
  'anomaly_log',
  'automation_rules',
  'automation_run_log',
  'approval_queue',
  'custom_field_definitions',
  'custom_field_values',
  'documents',
  'email_log',
  'email_schedules',
  'email_templates',
  'entity_relations',
  'financial_anomalies',
  'inventory_movements',
  'invoice_tokens',
  'line_item_snippets',
  'notifications',
  'number_sequences',
  'pattern_cache',
  'payroll_runs',
  'predictions',
  'rule_logs',
  'rules',
  'sync_queue',
  'workflow_definitions',
]);

// Tables that do NOT have an `updated_at` column.
// db.update() appends ", updated_at = datetime('now')" unless the table is in this set.
//
// Anything that is append-only by design (logs, audit trails, history) belongs here,
// plus child/junction tables that don't track row-level update timestamps.
export const TABLES_WITHOUT_UPDATED_AT = new Set([
  // ── Append-only logs / audit trails ─────────────────────────────
  'anomaly_log',
  'anonymization_log',
  'api_request_log',
  'audit_log',
  'audit_samples',
  'audit_walkthroughs',
  'auditor_inquiries',
  'automation_run_log',
  'backup_verification_log',
  'bank_match_attempts',
  'budget_approvals',
  'bulk_operations_log',
  'cash_forecast_lines',
  'cash_position_snapshots',
  'command_history',
  'control_deficiencies',
  'cost_variance_analyses',
  'data_classifications',
  'data_subject_requests',
  'debt_audit_log',
  'debt_payment_matches',
  'deferred_revenue_recognitions',
  'direct_cash_forecasts',
  'email_log',
  'email_schedules',
  'email_template_history',
  'encryption_verification_log',
  'entity_audit_history',
  'entity_relations',
  'entity_status_history',
  'expense_activity_log',
  'forecast_accuracy',
  'fx_rates',
  'fx_revaluation_runs',
  'headcount_budgets',
  'invoice_activity_log',
  'je_approvals',
  'je_comments',
  'je_history',
  'je_import_sessions',
  'je_narratives',
  'loyalty_transactions',
  'materiality_calcs',
  'opening_balances',
  'period_close_checklist',
  'period_close_log',
  'period_locks',
  'pending_deposits',
  'petty_cash_log',
  'positive_pay_files',
  'predictions',
  'promo_code_redemptions',
  'quote_activity_log',
  'quote_conversion_log',
  'quote_signatures',
  'rebate_accruals',
  'recon_imports',
  'recon_schedule',
  'returns_reserves',
  'rolling_forecast_lines',
  'rule_logs',
  'rules',
  'sales_performance_snapshots',
  'sales_targets',
  'saved_searches',
  'schema_meta',
  'schema_migrations',
  'sod_user_assignments',
  'stock_take_counts',
  'stock_take_sessions',
  'stripe_offline_queue',
  'stripe_sync_state',
  'sync_queue',
  'triggered_actions_log',
  'tb_comparison_snapshots',
  'user_2fa',
  'user_session_log',
  'variance_explanations',
  'webhook_deliveries',
  'webhook_secret_rotations',
  'workflow_event_log',
  'workflow_executions',
  'workflow_runs',
  'work_in_process',
  'year_end_close_runs',

  // ── Append-only financial record tables ────────────────────────
  'asset_depreciation_entries',
  'asset_disposals',
  'asset_impairments',
  'asset_retirement_obligations',
  'asset_revaluations',
  'asset_transfers',
  'asset_warranties',
  'bank_transactions',
  'bill_line_items',
  'bill_payments',
  'billable_time_summary',
  'closed_periods',
  'commission_calculations',
  'compliance_documents',
  'deal_activities',
  'financial_anomalies',
  'inventory_adjustment_items',
  'inventory_adjustments',
  'inventory_lots',
  'inventory_serial_numbers',
  'inventory_transfer_items',
  'inventory_value_history',
  'invoice_debt_links',
  'invoice_payment_schedule',
  'invoice_reminder_schedules',
  'invoice_reminders',
  'invoice_tokens',
  'lockbox_items',
  'lockbox_imports',
  'loyalty_tiers',
  'low_stock_alerts',
  'pay_stubs',
  'payments',
  'payroll_runs',
  'pto_balances',
  'pto_transactions',
  'reimbursement_batches',
  'state_tax_brackets',
  'state_tax_rates',
  'stripe_cache',
  'stripe_transactions',
  'tax_categories',
  'tax_filing_periods',
  'tax_payments',
  'timesheet_periods',
  'timesheet_approvals',
  'win_loss_analysis',

  // ── Stripe references and integration child tables ──────────────
  'portal_integration_settings',
  'utah_withholding_config',

  // ── Junction / child tables without updated_at ─────────────────
  'account_aliases',
  'account_balance_history',
  'account_classify_rules',
  'account_comments',
  'account_group_members',
  'account_permissions',
  'account_reconciliation_items',
  'account_reconciliations',
  'account_renumber_log',
  'account_watches',
  'ach_batches',
  'ach_batch_items',
  'auto_categorize_learnings',
  'bank_reconciliation_matches',
  'budget_consolidations',
  'budget_drivers',
  'budget_lines',
  'capex_plans',
  'cc_statement_lines',
  'client_contacts',
  'cost_allocation_rules',
  'credit_card_statements',
  'credit_note_items',
  'custom_field_definitions',
  'custom_field_values',
  'data_masking_rules',
  'debt_automation_rules',
  'debt_campaigns',
  'debt_communications',
  'debt_compliance_log',
  'debt_contacts',
  'debt_disputes',
  'debt_evidence',
  'debt_legal_actions',
  'debt_notes',
  'debt_payments',
  'debt_payment_plans',
  'debt_pipeline_stages',
  'debt_plan_installments',
  'debt_promises',
  'debt_settlements',
  'debt_skip_traces',
  'debt_templates',
  'documents',
  'esign_audit_log',
  'esign_permissions',
  'esign_signatures',
  'expense_approval_steps',
  'expense_comments',
  'expense_line_items',
  'expense_reimbursement_items',
  'expense_splits',
  'inter_company_je_pairs',
  'inter_company_transfers',
  'inventory_locations',
  'inventory_movements',
  'ip_access_whitelist',
  'je_attachments',
  'journal_entry_lines',
  'lead_form_submissions',
  'letters_of_credit',
  'line_item_snippets',
  'loan_covenants',
  'loan_events',
  'loan_payment_schedule',
  'loan_payments',
  'macros',
  'custom_shortcuts',
  'mileage_rates',
  'federal_payroll_constants',
  'federal_tax_brackets',
  'exchange_rates',
  'notifications',
  'performance_obligations',
  'po_line_items',
  'prepaid_recognitions',
  'project_profitability',
  'pto_policies',
  'quick_actions',
  'quote_line_items',
  'quote_template_lines',
  'rcsa_assessments',
  'rfp_tracking',
  'revenue_milestones',
  'sales_pipeline_stages',
  'sla_definitions',
  'sox_control_tests',
  'sox_controls',
  'standalone_selling_prices',
  'standard_costs',
  'stop_payments',
  'status_transitions',
  'sub_processors',
  'sweep_rules',
  'tag_groups',
  'tag_rules',
  'tags',
  'tb_elimination_entries',
  'tb_working_adjustments',
  'treasury_investments',
  'user_companies',
  'vulnerabilities',
  'wire_transfers',
  'workflow_definitions',
  'workflows',
  // Dynamic Wave (F261-F350) log/append-only tables
  'search_history',
  'recently_viewed_entities',
  'pinned_entities',
  'bulk_undo_snapshots',
  'smart_detections',
  'vendor_canonicalizations',
  'recommendations',
  'report_executions',
  'webhook_queue',
  'activity_feed',
  'entity_locks',
  'user_presence',
  'notification_preferences',

  // Wave 3 (F351-F440) log/append-only and child tables
  'state_withholding_tables',
  'state_reciprocity',
  'sales_tax_jurisdictions',
  'sales_tax_holidays',
  'sales_tax_liability',
  'use_tax_accruals',
  'w2_year_end_runs',
  'direct_deposit_batches',
  'consolidated_statements',
  'currency_translations',
  'minority_interests',
  'portal_payments',
  'portal_documents',
  'vendor_po_responses',
  'vendor_invoice_submissions',
  'vendor_ach_updates',
  'vendor_1099_downloads',
  'vendor_compliance_attestations',
  'time_timers',
  'calendar_event_sync',
  'document_classifications',
  'document_extracted_fields',
  'bank_statement_imports',
  'contract_clauses',
  'user_mentions',
  'comment_reactions',
  'shared_drafts',
  'chat_messages',
  'plaid_synced_transactions',
  'quickbooks_exports',
  'gmail_sync',
  'cloud_storage_files',
  'goodwill_tracking',
  'workers_comp_classes',
  'employee_state_allocations',
  'section_125_plans',
  'tax_exemption_certificates',
  'sales_tax_nexus',
  'sales_tax_filing_schedule',

  // Finance Wave (F441-F540) log/append-only and child tables
  'invoice_approval_steps',
  'invoice_email_log',
  'invoice_attachments',
  'progress_billing_releases',
  'retainer_drawdowns',
  'invoice_payment_plan_installments',
  'payment_retry_attempts',
  'customer_credit_transactions',
  'refunds',
  'chargebacks',
  'check_print_jobs',
  'crypto_payments',
  'subscription_proration_events',
  'usage_records',
  'customer_statements',
  'dunning_events',
  'bad_debt_writeoffs',
  'allowance_for_doubtful_accounts',
  'collection_agency_handoffs',
  'mrr_arr_snapshots',
  'analytics_snapshots',
  'cohort_analysis',
  'form_1099_runs',
  'withholding_tracking',
  'quarterly_tax_estimates',
  'tax_provision',
  'rd_tax_credits',
  'section_179_elections',
  'vendor_w9_records',
  'vendor_insurance_policies',
  'vendor_disputes',
  'pricing_tiers',
  'per_diem_rates',
  'vehicles',
  'vendor_1099_thresholds',
  'expense_category_budgets',
  'expense_pre_approvals',
  'reminder_cadences',
  'customer_payment_methods',
  'late_fee_policies',
  'payment_terms',
  'dunning_sequences',
  'recurring_invoice_templates',

  // Expense Advanced Wave (F541-F640) log/append-only and child tables
  'expense_policies',
  'expense_policy_violations',
  'travel_policy_caps',
  'expense_templates_v2',
  'subscription_detections',
  'auto_tag_rules',
  'card_transactions',
  'card_dispute_records',
  'card_spend_rules',
  'trips',
  'trip_itinerary',
  'trip_per_diem_settings',
  'mileage_irs_rates',
  'mileage_state_rates',
  'mileage_routes',
  'mileage_route_stops',
  'vehicle_depreciation',
  'vehicle_maintenance',
  'expense_custom_field_defs',
  'expense_custom_field_values',
  'expense_tag_hierarchy',
  'spend_benchmarks',
  'cost_save_recommendations',
  'approval_workflow_defs',
  'workflow_delegations',
  'workflow_audit_log',
  'expense_capture_queue',
  'expense_voice_memos',
  'expense_report_templates_v2',
  'expense_year_end_rollups',
  'corporate_cards',
  // Payroll Wave (F641-F740) — snapshot/audit tables
  'withholding_records',
  'workers_comp_premium_calcs',
  'compensation_history',
  'gross_to_net_snapshots',
  'payroll_journal_links',
  'federal_tax_tables',
  'state_tax_tables',
  // Reporting Wave (F741-F840) — snapshot/audit/log tables
  'report_runs',
  'scheduled_report_history',
  'kpi_snapshots',
  'variance_analyses',
  'report_drill_audit',
  'period_comparisons',
  'dashboard_versions',
  'report_pin_cache',
  'report_favorites',
  'report_audit_log',
  'report_alert_events',
]);

// Tables with a `deleted_at` column for soft-delete support.
// queryAll() auto-filters these to exclude soft-deleted rows.
export const TABLES_WITH_DELETED_AT = new Set([
  'accounts',
  'bills',
  'clients',
  'custom_field_definitions',
  'employees',
  'expenses',
  'fixed_assets',
  'inventory_items',
  'invoices',
  'journal_entries',
  'loans',
  'projects',
  'quotes',
  'tags',
  'vendors',
]);

// Tables that support soft-delete via remove().
// remove() sets deleted_at instead of physically deleting.
export const SOFT_DELETE_TABLES = new Set([
  'bills',
  'clients',
  'employees',
  'expenses',
  'fixed_assets',
  'invoices',
  'journal_entries',
  'loans',
  'projects',
  'quotes',
  'vendors',
]);
